import {revalidatePath} from "next/cache";
import {requireWorkspaceUser} from "@/lib/auth";

export const dynamic="force-dynamic";

type WorkflowVersion={id:string;organisation_id?:string|null;workflow_code:string;name:string;version:number;status:string;trigger_type:string;max_criticality:string;definition:any;simulation_result:any;content_hash:string;created_by?:string|null;approved_by?:string|null;published_at?:string|null};
function parseJson(value:FormDataEntryValue|null){const raw=String(value||"").trim();if(!raw) throw new Error("Workflow definition JSON is required.");try{return JSON.parse(raw);}catch{throw new Error("Workflow definition must be valid JSON.");}}

async function createWorkflow(formData:FormData){
 "use server";const {supabase,memberships}=await requireWorkspaceUser();const scope=String(formData.get("scope")||"organisation");const org=scope==="platform"?null:(memberships[0]?.organisation_id||null);const {error}=await supabase.rpc("create_workflow_version",{target_organisation_id:org,input_payload:{code:String(formData.get("code")||""),name:String(formData.get("name")||""),trigger_type:String(formData.get("trigger_type")||"manual"),max_criticality:String(formData.get("max_criticality")||"C2"),definition:parseJson(formData.get("definition"))}});if(error) throw new Error(error.message);revalidatePath("/app/admin/workflows");
}
async function simulateWorkflow(formData:FormData){
 "use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("record_workflow_simulation",{target_workflow_id:String(formData.get("workflow_id")||""),target_reason:String(formData.get("reason")||"Pre-publication simulator run")});if(error) throw new Error(error.message);revalidatePath("/app/admin/workflows");
}
async function transitionWorkflow(formData:FormData){
 "use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("transition_workflow_version",{target_workflow_id:String(formData.get("workflow_id")||""),target_status:String(formData.get("target_status")||""),target_reason:String(formData.get("reason")||"")});if(error) throw new Error(error.message);revalidatePath("/app/admin/workflows");
}

export default async function WorkflowAdmin(){
 const {supabase,memberships}=await requireWorkspaceUser();const org=memberships[0]?.organisation_id||null;const isPlatformAdmin=memberships.some(m=>m.role_code==="super_admin"&&m.status==="active");
 const requests:Promise<any>[]=[];if(org)requests.push(Promise.resolve(supabase.rpc("list_workflow_definition_workspace",{target_organisation_id:org})));if(isPlatformAdmin)requests.push(Promise.resolve(supabase.rpc("list_workflow_definition_workspace",{target_organisation_id:null})));
 const results=await Promise.all(requests);for(const r of results){if(r.error) throw new Error(r.error.message);}const versions=results.flatMap(r=>(r.data?.versions||[]) as WorkflowVersion[]);
 const published=versions.filter(v=>v.status==="published").length;const review=versions.filter(v=>v.status==="review").length;const failed=versions.filter(v=>v.simulation_result&&v.simulation_result.passed===false).length;const c34=versions.filter(v=>["C3","C4"].includes(v.max_criticality)&&v.status==="published").length;
 const sample='{"start":"draft","states":[{"code":"draft","terminal":false},{"code":"review","terminal":false},{"code":"complete","terminal":true}],"transitions":[{"from":"draft","to":"review"},{"from":"review","to":"complete"}]}';
 return <>
  <div className="topbar"><div><div className="demo">Super Admin / Live Workflow Governance</div><h1>Workflow Definitions</h1><div className="subtle">Versioned state machines with graph simulation, maker-checker publication and immutable running-version provenance.</div></div></div>
  <div className="kpis">{[["Versions",String(versions.length)],["Published",String(published)],["In Review",String(review)],["Simulation Blocks",String(failed)],["Published C3/C4",String(c34)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid">
   <section className="panel"><h3>Create Workflow Version</h3><form action={createWorkflow}><div className="field-grid"><div className="field"><label>Scope</label><select name="scope"><option value="organisation">Organisation</option>{isPlatformAdmin&&<option value="platform">Platform default</option>}</select></div><div className="field"><label>Code</label><input name="code" required placeholder="WF-RELEASE"/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Trigger Type</label><input name="trigger_type" defaultValue="manual" required/></div><div className="field"><label>Max Criticality</label><select name="max_criticality"><option>C0</option><option>C1</option><option defaultValue="C2">C2</option><option>C3</option><option>C4</option></select></div></div><div className="field"><label>Workflow Graph JSON</label><textarea name="definition" rows={10} defaultValue={sample} required/></div><button className="btn">Create Draft Version</button></form></section>
   <section className="panel"><h3>Simulator Contract</h3><p className="subtle">The simulator validates start state, unique state codes, transition references, terminal-state presence, full reachability and reachable non-terminal dead ends. A failed simulation blocks publication.</p><div className="note"><b>Maker-checker.</b> The author cannot publish their own workflow version. A new published version retires the prior definition without rewriting its content or historical references.</div></section>
  </div>
  <section className="panel" style={{marginTop:16}}><h3>Workflow Registry</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Workflow</th><th>Version</th><th>Status</th><th>Trigger</th><th>Criticality</th><th>Simulation</th><th>Hash</th><th>Controlled Actions</th></tr></thead><tbody>{versions.map(v=>{const sim=v.simulation_result||{};const errors=Array.isArray(sim.errors)?sim.errors:[];return <tr key={v.id}><td><b>{v.workflow_code}</b><div className="subtle">{v.name} · {v.organisation_id?`Org ${v.organisation_id.slice(0,8)}`:"Platform default"}</div></td><td>v{v.version}</td><td><span className="badge">{v.status}</span></td><td>{v.trigger_type}</td><td>{v.max_criticality}</td><td>{typeof sim.passed==="boolean"?<><span className="badge">{sim.passed?"pass":"blocked"}</span>{errors.length>0&&<div className="subtle">{errors.join(", ")}</div>}{Array.isArray(sim.unreachable_states)&&sim.unreachable_states.length>0&&<div className="subtle">Unreachable: {sim.unreachable_states.join(", ")}</div>}{Array.isArray(sim.dead_end_states)&&sim.dead_end_states.length>0&&<div className="subtle">Dead ends: {sim.dead_end_states.join(", ")}</div>}</>:<span className="subtle">Not yet run</span>}</td><td><code>{v.content_hash.slice(0,12)}…</code></td><td><div style={{display:"grid",gap:6,minWidth:190}}>{["draft","review"].includes(v.status)&&<form action={simulateWorkflow}><input type="hidden" name="workflow_id" value={v.id}/><input type="hidden" name="reason" value="Pre-publication graph simulation"/><button className="btn ghost" style={{padding:8}}>Run Simulator</button></form>}{v.status==="draft"&&<form action={transitionWorkflow}><input type="hidden" name="workflow_id" value={v.id}/><input type="hidden" name="target_status" value="review"/><input name="reason" required placeholder="Review reason"/><button className="btn ghost" style={{padding:8}}>Submit Review</button></form>}{v.status==="review"&&<form action={transitionWorkflow}><input type="hidden" name="workflow_id" value={v.id}/><input type="hidden" name="target_status" value="published"/><input name="reason" required placeholder="Publication reason"/><button className="btn ghost" style={{padding:8}}>Publish if Simulator Passes</button></form>}{v.status==="published"&&<form action={transitionWorkflow}><input type="hidden" name="workflow_id" value={v.id}/><input type="hidden" name="target_status" value="retired"/><input name="reason" required placeholder="Retirement reason"/><button className="btn ghost" style={{padding:8}}>Retire</button></form>}</div></td></tr>})}{versions.length===0&&<tr><td colSpan={8} className="subtle">No workflow definitions exist yet. Create a version and run the graph simulator before publication.</td></tr>}</tbody></table></div></section>
 </>;
}
