import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import {ClimateWorkspaceClient} from "@/components/PlanningIntelligenceClients";
import {emptyClimateWorkspace,type ClimateWorkspaceState,type DesignProject} from "@/components/design-domain-runtime-types";

export const dynamic="force-dynamic";
export default async function ClimatePage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as DesignProject[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state:ClimateWorkspaceState=emptyClimateWorkspace;
 if(project){const {data,error}=await supabase.rpc("list_climate_workspace",{target_project_id:project.id});if(error)throw new Error(error.message);state=(data||emptyClimateWorkspace) as ClimateWorkspaceState;}
 return <><div className="topbar"><div><div className="demo">Climate / Environmental Evidence</div><h1>Climate & Environment</h1><div className="subtle">Engine-identified environmental studies with immutable inputs, result hashes, evidence, confidence and independent review.</div></div></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/climate?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{!project&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<ClimateWorkspaceClient projectId={project.id} state={state}/>}<div className="note"><b>Evidence before claim.</b> No daylight, energy, wind, water, flood or carbon claim is displayed as verified without a named method/engine, exact input/output hashes, evidence references and review state.</div></>;
}