export type CompilerInput={project:Record<string,unknown>;objective:string;truth:Array<Record<string,unknown>>;requirements:Array<Record<string,unknown>>;geometry?:Record<string,unknown>|null;regula?:Record<string,unknown>|null;engineering_engines:Array<Record<string,unknown>>;discipline_state:Record<string,unknown>;design_intent?:Record<string,unknown>|null;seed?:string;metric_set_version?:string};
export type StageState={stage:string;status:'completed'|'blocked'|'awaiting_review';criticality:string;engine_refs:string[];agent_run_refs:string[];evidence_refs:string[];assumptions:string[];validation_finding_refs:string[];details:Record<string,unknown>};
export type CompilerCandidate={option_id:string;objective_metrics:Record<string,unknown>;dominated:boolean;constraint_violations:string[];compliance_state:'pass'|'conditional'|'fail'|'not_verified'};
type HardConstraint={metric:string;min?:number;max?:number;equals?:number};
const DEFAULT_METRIC_SET='feasibility-envelope-metrics@1.0.0';
function valueNumber(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'){const normalized=value.trim().replaceAll(',','').replace(/%$/,'').trim();if(normalized&&Number.isFinite(Number(normalized)))return Number(normalized);}if(value&&typeof value==='object'&&!Array.isArray(value)){const x=(value as Record<string,unknown>).value;return valueNumber(x);}return undefined;}
function planningInput(input:CompilerInput,keys:string[],declaredKey:string){
 const matching=input.truth.filter(x=>keys.some(key=>String(x.record_key||'').toLowerCase()===key.toLowerCase()));
 const direct=matching.find(x=>x.status==='verified')||matching[0];
 if(direct)return{fact:direct,value:valueNumber(direct.value),verified:direct.status==='verified'};
 const declaration=input.truth.find(x=>String(x.record_key||'').toLowerCase()==='regulation.client_declared');const payload=declaration?.value;
 const declaredValue=payload&&typeof payload==='object'&&!Array.isArray(payload)?(payload as Record<string,unknown>)[declaredKey]:undefined;
 return{fact:declaration,value:valueNumber(declaredValue),verified:false};
}
function evidenceOf(f?:Record<string,unknown>){if(!f)return[];return [String(f.source_reference||`truth:${String(f.id||f.record_key||'unknown')}`)];}
function criticality(input:CompilerInput){const c=String(input.project.criticality||'C1');return ['C0','C1','C2','C3','C4'].includes(c)?c:'C1';}
function stage(stage:string,status:StageState['status'],input:CompilerInput,details:Record<string,unknown>,evidence:string[]=[],assumptions:string[]=[],engines:string[]=[]):StageState{return{stage,status,criticality:criticality(input),engine_refs:engines,agent_run_refs:[],evidence_refs:evidence,assumptions,validation_finding_refs:[],details};}
function approvedEngines(input:CompilerInput,disciplinePatterns:string[]){return (input.engineering_engines||[]).filter(e=>e.enabled===true&&['approved','conditionally_approved'].includes(String(e.certification_status))&&disciplinePatterns.some(p=>String(e.discipline||'').toLowerCase().includes(p))).map(e=>`${String(e.code)}@${String(e.version)}`);}
function hash32(text:string,seed:number){let h=(2166136261^seed)>>>0;for(let i=0;i<text.length;i++){h=Math.imul(h^text.charCodeAt(i),16777619)>>>0;h^=h>>>13;}return (h>>>0).toString(16).padStart(8,'0');}
function deterministicUuid(text:string){const hex=[hash32(text,0x9e3779b9),hash32(text,0x85ebca6b),hash32(text,0xc2b2ae35),hash32(text,0x27d4eb2f)].join('');const chars=hex.split('');chars[12]='5';chars[16]=['8','9','a','b'][parseInt(chars[16],16)%4];const h=chars.join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20,32)}`;}
function parseHardConstraints(input:CompilerInput){const intent=input.design_intent||{};const raw=Array.isArray(intent.mandatory_requirements)?intent.mandatory_requirements:[];const constraints:HardConstraint[]=[];const errors:string[]=[];for(const item of raw){if(!item||typeof item!=='object'||Array.isArray(item))continue;const x=item as Record<string,unknown>;const metric=String(x.metric||'').trim();if(!metric)continue;const min=valueNumber(x.min),max=valueNumber(x.max),equals=valueNumber(x.equals);if(min===undefined&&max===undefined&&equals===undefined){errors.push(`Hard constraint ${metric} has no numeric min/max/equals.`);continue;}if(min!==undefined&&max!==undefined&&min>max){errors.push(`Hard constraint ${metric} is infeasible because min ${min} exceeds max ${max}.`);continue;}if(equals!==undefined&&min!==undefined&&equals<min){errors.push(`Hard constraint ${metric} is infeasible because equals ${equals} is below min ${min}.`);continue;}if(equals!==undefined&&max!==undefined&&equals>max){errors.push(`Hard constraint ${metric} is infeasible because equals ${equals} exceeds max ${max}.`);continue;}constraints.push({metric,min,max,equals});}return{constraints,errors};}
function evaluateHardConstraints(metrics:Record<string,unknown>,constraints:HardConstraint[]){const violations:string[]=[];for(const c of constraints){const observed=valueNumber(metrics[c.metric]);if(observed===undefined){violations.push(`Hard constraint metric ${c.metric} is unavailable in metric set ${String(metrics.metric_set_version||'unknown')}.`);continue;}if(c.equals!==undefined&&Math.abs(observed-c.equals)>1e-9)violations.push(`${c.metric} ${observed} must equal ${c.equals}.`);if(c.min!==undefined&&observed<c.min)violations.push(`${c.metric} ${observed} is below minimum ${c.min}.`);if(c.max!==undefined&&observed>c.max)violations.push(`${c.metric} ${observed} exceeds maximum ${c.max}.`);}return violations;}
export function compileProject(input:CompilerInput){
 const stages:StageState[]=[];const blocked:string[]=[];const candidates:CompilerCandidate[]=[];const rejectedCandidates:Array<{profile:string;reasons:string[]}>=[];const c=criticality(input);const intent=input.design_intent||{};const seed=String(input.seed||intent.seed||'benchmark-v1');const metricSetVersion=String(input.metric_set_version||intent.metric_set_version||DEFAULT_METRIC_SET);const hard=parseHardConstraints(input);if(hard.errors.length)blocked.push(...hard.errors);
 const truth=input.truth||[];const criticalUnknowns=truth.filter(f=>f.status!=='verified'&&['C3','C4'].includes(String(f.criticality))).length;const truthStatus=truth.length===0?'blocked':criticalUnknowns>0?'blocked':'completed';stages.push(stage('project_truth',truthStatus,input,{records:truth.length,critical_unknowns:criticalUnknowns},truth.filter(f=>f.status==='verified').map(f=>String(f.source_reference||`truth:${f.id}`))));if(truthStatus==='blocked')blocked.push(truth.length===0?'Project Truth is empty.':`${criticalUnknowns} C3/C4 Project Truth record(s) remain unverified.`);
 const regula=input.regula as {run?:Record<string,unknown>;findings?:Array<Record<string,unknown>>}|null|undefined;const findings=regula?.findings||[];const hasRegula=!!regula?.run;const regulaFails=findings.filter(f=>f.status==='fail').length;const regulaHuman=findings.filter(f=>f.status==='requires_interpretation'||f.status==='not_verified').length;const regulaStatus:StageState['status']=!hasRegula?'blocked':regulaFails>0?'blocked':regulaHuman>0?'awaiting_review':'completed';stages.push(stage('regulatory_context',regulaStatus,input,{evaluation_run_id:regula?.run?.id||null,findings:findings.length,failures:regulaFails,human_or_unknown:regulaHuman},findings.map(f=>`regula:${String(f.rule_id||'finding')}`)));if(regulaStatus==='blocked')blocked.push(!hasRegula?'No completed REGULA evaluation is bound to this project.':`${regulaFails} deterministic regulatory failure(s) block compilation.`);
 const requirements=input.requirements||[];const openCritical=requirements.filter(r=>r.status==='open'&&['C3','C4'].includes(String(r.criticality))).length;const programmeStatus:StageState['status']=requirements.length===0?'blocked':openCritical>0?'awaiting_review':'completed';stages.push(stage('programme',programmeStatus,input,{requirements:requirements.length,open_critical:openCritical},requirements.map(r=>`requirement:${String(r.id||r.code)}`)));if(programmeStatus==='blocked')blocked.push('No governed programme requirements are available.');
 const geometry=input.geometry||null;const geometryValid=geometry?.engine_valid===true;const geometryVerified=String(geometry?.verification||'unverified')==='professionally_verified'||String(geometry?.verification||'')==='authority_verified';const area=valueNumber(geometry?.area);const feasibilityStatus:StageState['status']=geometryValid&&area&&area>0?geometryVerified?'completed':'awaiting_review':'blocked';stages.push(stage('feasibility',feasibilityStatus,input,{plot_area_m2:area||null,geometry_valid:geometryValid,geometry_verification:geometry?.verification||'not_available'},geometry?.content_hash?[`geometry:${String(geometry.content_hash)}`]:[],geometryValid&&!geometryVerified?['Deterministic geometry is valid but not professionally verified; feasibility remains preliminary.']:[]));if(feasibilityStatus==='blocked')blocked.push('A valid deterministic parcel geometry is required for feasibility.');
 const farInput=planningInput(input,['planning.far','planning.fsi','regulation.far','regulation.fsi','site.far','site.fsi'],'far');const coverageInput=planningInput(input,['planning.ground_coverage','regulation.ground_coverage','site.ground_coverage'],'groundCoverage');const far=farInput.value;let coverage=coverageInput.value;const coverageUnit=String(coverageInput.fact?.unit||'').toLowerCase();if(coverage!==undefined&&coverage<=1&&(coverageUnit==='ratio'||coverageUnit==='fraction'))coverage*=100;else if(coverage!==undefined&&coverage<=1&&coverageUnit!=="%"&&coverageUnit!=="percent")coverage=undefined;const planningInputsVerified=farInput.verified&&coverageInput.verified;const numericReady=!!area&&area>0&&far!==undefined&&far>0&&coverage!==undefined&&coverage>0&&coverage<=100;
 if(numericReady&&hard.errors.length===0){const maxGfa=area!*far!;const maxFootprint=area!*coverage!/100;const profiles=[['Regulatory Margin',.82],['Balanced',.92],['Yield',1]] as const;for(const [name,u] of profiles){const gfa=maxGfa*u,footprint=Math.min(maxFootprint,gfa),storeys=footprint>0?Math.ceil(gfa/footprint):0;const metrics:Record<string,unknown>={name,metric_set_version:metricSetVersion,seed,plot_area_m2:round(area!),input_far:far,input_ground_coverage_percent:coverage,planning_inputs_verified:planningInputsVerified,max_permitted_gfa_m2:round(maxGfa),scenario_gfa_m2:round(gfa),scenario_footprint_m2:round(footprint),approx_storeys_from_envelope:storeys,yield_score:round(u,3),regulatory_margin_score:round(1-u,3),open_space_percent:round(100-(footprint/area!)*100,2)};const violations=evaluateHardConstraints(metrics,hard.constraints);if(violations.length){rejectedCandidates.push({profile:name,reasons:violations});continue;}const idBasis=stableStringify({seed,metric_set_version:metricSetVersion,profile:name,metrics});candidates.push({option_id:deterministicUuid(idBasis),objective_metrics:metrics,dominated:false,constraint_violations:[],compliance_state:regulaFails>0?'fail':planningInputsVerified&&hasRegula?(regulaHuman>0?'conditional':'pass'):'not_verified'});}}
 const missing=[] as string[];if(!area)missing.push('valid plot area');if(!far)missing.push('FAR/FSI');if(coverage===undefined)missing.push('unambiguous ground coverage');const hardInfeasible=numericReady&&hard.errors.length===0&&hard.constraints.length>0&&candidates.length===0;const optionStatus:StageState['status']=numericReady&&hard.errors.length===0&&!hardInfeasible?regulaFails>0?'blocked':planningInputsVerified&&hasRegula&&regulaHuman===0?'completed':'awaiting_review':'blocked';stages.push(stage('option_generation',optionStatus,input,{candidates:candidates.length,rejected_candidates:rejectedCandidates,max_permitted_gfa_m2:numericReady?round(area!*far!):null,planning_inputs_verified:planningInputsVerified,missing_inputs:missing,hard_constraint_errors:hard.errors,hard_constraints:hard.constraints,seed,metric_set_version:metricSetVersion},[...evidenceOf(farInput.fact),...evidenceOf(coverageInput.fact),...(geometry?.content_hash?[`geometry:${String(geometry.content_hash)}`]:[])],planningInputsVerified?[]:['Client-declared FAR/FSI or ground coverage was used only for preliminary envelope options.'],['conceptspaces-feasibility-envelope@1.1.0']));if(optionStatus==='blocked'&&regulaFails===0){if(hard.errors.length){}else if(hardInfeasible)blocked.push(`Hard constraint set is infeasible for all generated candidates: ${rejectedCandidates.flatMap(x=>x.reasons).join(' | ')}`);else blocked.push(`Option generation requires ${missing.join(', ')}.`);}else if(numericReady&&!planningInputsVerified)blocked.push('Preliminary envelope options use client-declared planning values; source verification is required before design release.');
 const archEngines=approvedEngines(input,['arch']);const structuralEngines=approvedEngines(input,['struct']);const mepEngines=approvedEngines(input,['mep','mechanical','electrical','plumbing','fire']);
 stages.push(stage('architecture','awaiting_review',input,{certified_engine_refs:archEngines,reason:'Spatial design package requires governed architecture execution and professional review.'},[],[],archEngines));stages.push(stage('structure','awaiting_review',input,{certified_engine_refs:structuralEngines,reason:'Structural calculation geometry cannot be authored solely by an LLM.'},[],[],structuralEngines));stages.push(stage('mepf','awaiting_review',input,{certified_engine_refs:mepEngines,reason:'MEPF sizing requires discipline engines, standards, units and professional review.'},[],[],mepEngines));stages.push(stage('interiors','awaiting_review',input,{existing_design_dna:Array.isArray((input.discipline_state||{}).interiors)?((input.discipline_state||{}).interiors as unknown[]).length:0},[],[]));stages.push(stage('quantity_cost','awaiting_review',input,{reason:'QTO/BOQ must bind to measured model/document revisions before release.'},[],[]));stages.push(stage('coordination','awaiting_review',input,{reason:'Cross-discipline coordination requires model/object dependency evidence.'},[],[]));stages.push(stage('assurance','blocked',input,{reason:'Proof Before Publish cannot complete until all critical discipline stages and professional approvals pass.'},[],[]));blocked.push('Assurance remains blocked until architecture, engineering, cost and coordination evidence is reviewed.');
 const overall:'blocked'|'awaiting_review'|'completed'=blocked.some(x=>!x.startsWith('Assurance'))?'blocked':'awaiting_review';return{engine:'conceptspaces-building-compiler',engine_version:'1.1.0',status:overall,stages,candidates,blocked_reasons:blocked,summary:{criticality:c,objective:input.objective,seed,metric_set_version:metricSetVersion,design_intent_id:intent.id||null,design_intent_hash:intent.content_hash||null,candidates:candidates.length,rejected_candidates:rejectedCandidates.length,completed_stages:stages.filter(s=>s.status==='completed').length,blocked_stages:stages.filter(s=>s.status==='blocked').length,review_stages:stages.filter(s=>s.status==='awaiting_review').length}};
}
function round(n:number,p=2){return Number(n.toFixed(p));}
export function stableStringify(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stableStringify).join(',')}]`;const obj=value as Record<string,unknown>;return `{${Object.keys(obj).sort().map(k=>`${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(',')}}`;}
