export type CompilerInput={project:Record<string,unknown>;objective:string;truth:Array<Record<string,unknown>>;requirements:Array<Record<string,unknown>>;geometry?:Record<string,unknown>|null;regula?:Record<string,unknown>|null;engineering_engines:Array<Record<string,unknown>>;discipline_state:Record<string,unknown>};
export type StageState={stage:string;status:'completed'|'blocked'|'awaiting_review';criticality:string;engine_refs:string[];agent_run_refs:string[];evidence_refs:string[];assumptions:string[];validation_finding_refs:string[];details:Record<string,unknown>};
export type CompilerCandidate={option_id:string;objective_metrics:Record<string,unknown>;dominated:boolean;constraint_violations:string[];compliance_state:'pass'|'conditional'|'fail'|'not_verified'};
const STAGES=['project_truth','regulatory_context','programme','feasibility','option_generation','architecture','structure','mepf','interiors','quantity_cost','coordination','assurance'] as const;
function valueNumber(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'&&value.trim()&&Number.isFinite(Number(value)))return Number(value);if(value&&typeof value==='object'&&!Array.isArray(value)){const x=(value as Record<string,unknown>).value;return valueNumber(x);}return undefined;}
function verifiedFact(input:CompilerInput,keys:string[]){for(const key of keys){const f=input.truth.find(x=>String(x.record_key||'').toLowerCase()===key.toLowerCase()&&x.status==='verified');if(f)return f;}return undefined;}
function evidenceOf(f?:Record<string,unknown>){if(!f)return[];return [String(f.source_reference||`truth:${String(f.id||f.record_key||'unknown')}`)];}
function criticality(input:CompilerInput){const c=String(input.project.criticality||'C1');return ['C0','C1','C2','C3','C4'].includes(c)?c:'C1';}
function stage(stage:string,status:StageState['status'],input:CompilerInput,details:Record<string,unknown>,evidence:string[]=[],assumptions:string[]=[],engines:string[]=[]):StageState{return{stage,status,criticality:criticality(input),engine_refs:engines,agent_run_refs:[],evidence_refs:evidence,assumptions,validation_finding_refs:[],details};}
function approvedEngines(input:CompilerInput,disciplinePatterns:string[]){return (input.engineering_engines||[]).filter(e=>e.enabled===true&&['approved','conditionally_approved'].includes(String(e.certification_status))&&disciplinePatterns.some(p=>String(e.discipline||'').toLowerCase().includes(p))).map(e=>`${String(e.code)}@${String(e.version)}`);}
export function compileProject(input:CompilerInput){
 const stages:StageState[]=[];const blocked:string[]=[];const candidates:CompilerCandidate[]=[];const c=criticality(input);
 const truth=input.truth||[];const criticalUnknowns=truth.filter(f=>f.status!=='verified'&&['C3','C4'].includes(String(f.criticality))).length;const truthStatus=truth.length===0?'blocked':criticalUnknowns>0?'blocked':'completed';stages.push(stage('project_truth',truthStatus,input,{records:truth.length,critical_unknowns:criticalUnknowns},truth.filter(f=>f.status==='verified').map(f=>String(f.source_reference||`truth:${f.id}`))));if(truthStatus==='blocked')blocked.push(truth.length===0?'Project Truth is empty.':`${criticalUnknowns} C3/C4 Project Truth record(s) remain unverified.`);
 const regula=input.regula as {run?:Record<string,unknown>;findings?:Array<Record<string,unknown>>}|null|undefined;const findings=regula?.findings||[];const hasRegula=!!regula?.run;const regulaFails=findings.filter(f=>f.status==='fail').length;const regulaHuman=findings.filter(f=>f.status==='requires_interpretation'||f.status==='not_verified').length;let regulaStatus:StageState['status']=!hasRegula?'blocked':regulaFails>0?'blocked':regulaHuman>0?'awaiting_review':'completed';stages.push(stage('regulatory_context',regulaStatus,input,{evaluation_run_id:regula?.run?.id||null,findings:findings.length,failures:regulaFails,human_or_unknown:regulaHuman},findings.map(f=>`regula:${String(f.rule_id||'finding')}`)));if(regulaStatus==='blocked')blocked.push(!hasRegula?'No completed REGULA evaluation is bound to this project.':`${regulaFails} deterministic regulatory failure(s) block compilation.`);
 const requirements=input.requirements||[];const openCritical=requirements.filter(r=>r.status==='open'&&['C3','C4'].includes(String(r.criticality))).length;const programmeStatus:StageState['status']=requirements.length===0?'blocked':openCritical>0?'awaiting_review':'completed';stages.push(stage('programme',programmeStatus,input,{requirements:requirements.length,open_critical:openCritical},requirements.map(r=>`requirement:${String(r.id||r.code)}`)));if(programmeStatus==='blocked')blocked.push('No governed programme requirements are available.');
 const geometry=input.geometry||null;const geometryValid=geometry?.engine_valid===true;const geometryVerified=String(geometry?.verification||'unverified')==='professionally_verified'||String(geometry?.verification||'')==='authority_verified';const area=valueNumber(geometry?.area);const feasibilityStatus:StageState['status']=geometryValid&&area&&area>0?geometryVerified?'completed':'awaiting_review':'blocked';stages.push(stage('feasibility',feasibilityStatus,input,{plot_area_m2:area||null,geometry_valid:geometryValid,geometry_verification:geometry?.verification||'not_available'},geometry?.content_hash?[`geometry:${String(geometry.content_hash)}`]:[],geometryValid&&!geometryVerified?['Deterministic geometry is valid but not professionally verified; feasibility remains preliminary.']:[]));if(feasibilityStatus==='blocked')blocked.push('A valid deterministic parcel geometry is required for feasibility.');
 const farFact=verifiedFact(input,['planning.far','planning.fsi','regulation.far','regulation.fsi','site.far','site.fsi']);const coverageFact=verifiedFact(input,['planning.ground_coverage','regulation.ground_coverage','site.ground_coverage']);const far=valueNumber(farFact?.value);let coverage=valueNumber(coverageFact?.value);const coverageUnit=String(coverageFact?.unit||'').toLowerCase();if(coverage!==undefined&&coverage<=1&&(coverageUnit==='ratio'||coverageUnit==='fraction'))coverage*=100;else if(coverage!==undefined&&coverage<=1&&coverageUnit!=="%"&&coverageUnit!=="percent")coverage=undefined;const numericReady=!!area&&area>0&&far!==undefined&&far>0&&coverage!==undefined&&coverage>0&&coverage<=100;
 if(numericReady){const maxGfa=area!*far!;const maxFootprint=area!*coverage!/100;const profiles=[['Regulatory Margin',.82],['Balanced',.92],['Yield',1]] as const;for(const [name,u] of profiles){const gfa=maxGfa*u,footprint=Math.min(maxFootprint,gfa),storeys=footprint>0?Math.ceil(gfa/footprint):0;candidates.push({option_id:crypto.randomUUID(),objective_metrics:{name,plot_area_m2:round(area!),verified_far:far,verified_ground_coverage_percent:coverage,max_permitted_gfa_m2:round(maxGfa),scenario_gfa_m2:round(gfa),scenario_footprint_m2:round(footprint),approx_storeys_from_envelope:storeys,yield_score:round(u,3),regulatory_margin_score:round(1-u,3),open_space_percent:round(100-(footprint/area!)*100,2)},dominated:false,constraint_violations:[],compliance_state:regulaFails>0?'fail':regulaHuman>0?'conditional':hasRegula?'pass':'not_verified'});}}
 const optionStatus:StageState['status']=numericReady?regulaFails>0?'blocked':'completed':'blocked';const missing=[] as string[];if(!area)missing.push('valid plot area');if(!far)missing.push('verified FAR/FSI');if(coverage===undefined)missing.push('verified unambiguous ground coverage');stages.push(stage('option_generation',optionStatus,input,{candidates:candidates.length,max_permitted_gfa_m2:numericReady?round(area!*far!):null,missing_inputs:missing},[...evidenceOf(farFact),...evidenceOf(coverageFact),...(geometry?.content_hash?[`geometry:${String(geometry.content_hash)}`]:[])],[],['conceptspaces-feasibility-envelope@1.0.0']));if(optionStatus==='blocked'&&regulaFails===0)blocked.push(`Option generation requires ${missing.join(', ')}.`);
 const archEngines=approvedEngines(input,['arch']);const structuralEngines=approvedEngines(input,['struct']);const mepEngines=approvedEngines(input,['mep','mechanical','electrical','plumbing','fire']);
 stages.push(stage('architecture','awaiting_review',input,{certified_engine_refs:archEngines,reason:'Spatial design package requires governed architecture execution and professional review.'},[],[],archEngines));
 stages.push(stage('structure','awaiting_review',input,{certified_engine_refs:structuralEngines,reason:'Structural calculation geometry cannot be authored solely by an LLM.'},[],[],structuralEngines));
 stages.push(stage('mepf','awaiting_review',input,{certified_engine_refs:mepEngines,reason:'MEPF sizing requires discipline engines, standards, units and professional review.'},[],[],mepEngines));
 stages.push(stage('interiors','awaiting_review',input,{existing_design_dna:Array.isArray((input.discipline_state||{}).interiors)?((input.discipline_state||{}).interiors as unknown[]).length:0},[],[]));
 stages.push(stage('quantity_cost','awaiting_review',input,{reason:'QTO/BOQ must bind to measured model/document revisions before release.'},[],[]));
 stages.push(stage('coordination','awaiting_review',input,{reason:'Cross-discipline coordination requires model/object dependency evidence.'},[],[]));
 stages.push(stage('assurance','blocked',input,{reason:'Proof Before Publish cannot complete until all critical discipline stages and professional approvals pass.'},[],[]));blocked.push('Assurance remains blocked until architecture, engineering, cost and coordination evidence is reviewed.');
 const overall: 'blocked'|'awaiting_review'|'completed'=blocked.some(x=>!x.startsWith('Assurance'))?'blocked':'awaiting_review';return {engine:'conceptspaces-building-compiler',engine_version:'1.0.0',status:overall,stages,candidates,blocked_reasons:blocked,summary:{criticality:c,objective:input.objective,candidates:candidates.length,completed_stages:stages.filter(s=>s.status==='completed').length,blocked_stages:stages.filter(s=>s.status==='blocked').length,review_stages:stages.filter(s=>s.status==='awaiting_review').length}};
}
function round(n:number,p=2){return Number(n.toFixed(p));}
export function stableStringify(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stableStringify).join(',')}]`;const obj=value as Record<string,unknown>;return `{${Object.keys(obj).sort().map(k=>`${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(',')}}`;}
