import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import {ArchitectureWorkspaceClient} from "@/components/ArchitectureStructureWorkspaceClients";
import {emptyArchitectureWorkspace,type ArchitectureWorkspaceState,type DesignProject} from "@/components/design-domain-runtime-types";

type Credential={id:string;credential_type:string;issuing_body:string;registration_number:string;discipline?:string|null;valid_until?:string|null;verification_status:string};
type ValidationState={credentials?:Credential[]};
export const dynamic="force-dynamic";
export default async function ArchitecturePage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as DesignProject[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state:ArchitectureWorkspaceState=emptyArchitectureWorkspace;let credentials:Credential[]=[];
 if(project){const [workspace,validation]=await Promise.all([supabase.rpc("list_architecture_workspace",{target_project_id:project.id}),supabase.rpc("list_engineering_validation_workspace")]);if(workspace.error)throw new Error(workspace.error.message);if(validation.error)throw new Error(validation.error.message);state=(workspace.data||emptyArchitectureWorkspace) as ArchitectureWorkspaceState;credentials=((validation.data||{}) as ValidationState).credentials||[];}
 return <><div className="topbar"><div><div className="demo">Architecture / Building Compiler™ / Professional Release</div><h1>Architecture</h1><div className="subtle">Approved programme basis, design-option trace, versioned packages, requirement coverage, professional maker-checker approval and immutable issue evidence.</div></div></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/architecture?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{!project&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<ArchitectureWorkspaceClient projectId={project.id} state={state} credentials={credentials}/>}<div className="note"><b>Release authority.</b> Architecture is not issued because drawings appear complete. Approval requires an independent, current professional credential against the exact package hash; issue creates a final hash and the issued record becomes immutable.</div></>;
}