import {revalidatePath} from "next/cache";
import {requireWorkspaceUser} from "@/lib/auth";

export const dynamic="force-dynamic";

type ConfigVersion={id:string;organisation_id?:string|null;namespace:string;config_key:string;version:number;status:string;value:any;schema_definition:any;effective_from:string;effective_until?:string|null;rollback_of_id?:string|null;created_by?:string|null;published_by?:string|null;content_hash:string;change_reason?:string|null};

function parseJson(value:FormDataEntryValue|null,label:string){const raw=String(value||"").trim();if(!raw) return {};try{return JSON.parse(raw);}catch{throw new Error(`${label} must be valid JSON.`);}}

async function createConfig(formData:FormData){
 "use server";
 const {supabase,memberships}=await requireWorkspaceUser();
 const scope=String(formData.get("scope")||"organisation");
 const org=scope==="platform"?null:(memberships[0]?.organisation_id||null);
 const {error}=await supabase.rpc("create_config_version",{target_organisation_id:org,input_payload:{namespace:String(formData.get("namespace")||""),key:String(formData.get("config_key")||""),value:parseJson(formData.get("value"),"Value"),schema_definition:parseJson(formData.get("schema_definition"),"Schema"),effective_from:String(formData.get("effective_from")||""),effective_until:String(formData.get("effective_until")||""),reason:String(formData.get("reason")||"")}});
 if(error) throw new Error(error.message);revalidatePath("/app/admin/system-config");
}
async function transitionConfig(formData:FormData){
 "use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("transition_config_version",{target_config_id:String(formData.get("config_id")||""),target_status:String(formData.get("target_status")||""),target_reason:String(formData.get("reason")||"")});if(error) throw new Error(error.message);revalidatePath("/app/admin/system-config");
}
async function rollbackConfig(formData:FormData){
 "use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("rollback_config_version",{source_config_id:String(formData.get("config_id")||""),target_effective_from:String(formData.get("effective_from")||"")||null,target_reason:String(formData.get("reason")||"")});if(error) throw new Error(error.message);revalidatePath("/app/admin/system-config");
}

export default async function SystemConfig(){
 const {supabase,memberships}=await requireWorkspaceUser();const org=memberships[0]?.organisation_id||null;const isPlatformAdmin=memberships.some(m=>m.role_code==="super_admin"&&m.status==="active");
 const requests:Promise<any>[]=[];if(org)requests.push(Promise.resolve(supabase.rpc("list_system_config_workspace",{target_organisation_id:org})));if(isPlatformAdmin)requests.push(Promise.resolve(supabase.rpc("list_system_config_workspace",{target_organisation_id:null})));
 const results=await Promise.all(requests);for(const result of results){if(result.error) throw new Error(result.error.message);}const versions=results.flatMap(r=>(r.data?.versions||[]) as ConfigVersion[]);
 const published=versions.filter(v=>v.status==="published").length;const inReview=versions.filter(v=>v.status==="review").length;const future=versions.filter(v=>v.status==="published"&&new Date(v.effective_from)>new Date()).length;const rollbacks=versions.filter(v=>Boolean(v.rollback_of_id)).length;
 return <>
  <div className="topbar"><div><div className="demo">Super Admin / Live Configuration Governance</div><h1>Platform Configuration</h1><div className="subtle">Effective-dated, versioned business configuration with maker-checker publication, immutable history and controlled rollback.</div></div></div>
  <div className="kpis">{[["Versions",String(versions.length)],["Published",String(published)],["In Review",String(inReview)],["Future Effective",String(future)],["Rollbacks",String(rollbacks)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid">
   <section className="panel"><h3>Create Configuration Version</h3><form action={createConfig}><div className="field-grid"><div className="field"><label>Scope</label><select name="scope"><option value="organisation">Organisation</option>{isPlatformAdmin&&<option value="platform">Platform default</option>}</select></div><div className="field"><label>Namespace</label><input name="namespace" required placeholder="notifications"/></div><div className="field"><label>Key</label><input name="config_key" required placeholder="reminder_interval_hours"/></div><div className="field"><label>Effective From</label><input name="effective_from" type="datetime-local" required/></div><div className="field"><label>Effective Until</label><input name="effective_until" type="datetime-local"/></div><div className="field"><label>Change Reason</label><input name="reason" required/></div></div><div className="field"><label>Value JSON</label><textarea name="value" rows={5} required placeholder='{"value":24,"unit":"hours"}'/></div><div className="field"><label>Optional Schema JSON</label><textarea name="schema_definition" rows={3} placeholder='{"type":"object"}'/></div><button className="btn">Create Draft Version</button></form><div className="note"><b>No secrets in config.</b> Secret/password/token/API-key fields are rejected. Credentials remain in the secrets boundary.</div></section>
   <section className="panel"><h3>Control Model</h3><p className="subtle">A maker creates a version and submits it to review. A different authorised administrator publishes it. Resolution uses the configured effective time, so future changes require no deployment. Rollback publishes a new version copied from previously approved content; history is never rewritten.</p><div className="note"><b>Effective-date guard.</b> Overlapping published windows for the same scope/namespace/key are rejected.</div></section>
  </div>
  <section className="panel" style={{marginTop:16}}><h3>Configuration History</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Scope / Key</th><th>Version</th><th>Status</th><th>Effective Window</th><th>Value</th><th>Hash</th><th>Controlled Actions</th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td><b>{v.namespace}.{v.config_key}</b><div className="subtle">{v.organisation_id?`Org ${v.organisation_id.slice(0,8)}`:"Platform default"}{v.rollback_of_id?` · rollback of ${v.rollback_of_id.slice(0,8)}`:""}</div></td><td>v{v.version}</td><td><span className="badge">{v.status}</span></td><td>{new Date(v.effective_from).toLocaleString("en-IN")}<div className="subtle">to {v.effective_until?new Date(v.effective_until).toLocaleString("en-IN"):"open-ended"}</div></td><td><code style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(v.value)}</code></td><td><code>{v.content_hash.slice(0,12)}…</code></td><td><div style={{display:"grid",gap:6,minWidth:190}}>{v.status==="draft"&&<form action={transitionConfig}><input type="hidden" name="config_id" value={v.id}/><input type="hidden" name="target_status" value="review"/><input name="reason" required placeholder="Review reason"/><button className="btn ghost" style={{padding:8}}>Submit Review</button></form>}{v.status==="review"&&<form action={transitionConfig}><input type="hidden" name="config_id" value={v.id}/><input type="hidden" name="target_status" value="published"/><input name="reason" required placeholder="Publication reason"/><button className="btn ghost" style={{padding:8}}>Publish</button></form>}{v.status==="published"&&<form action={transitionConfig}><input type="hidden" name="config_id" value={v.id}/><input type="hidden" name="target_status" value="retired"/><input name="reason" required placeholder="Retirement reason"/><button className="btn ghost" style={{padding:8}}>Retire</button></form>}{["published","retired"].includes(v.status)&&<form action={rollbackConfig}><input type="hidden" name="config_id" value={v.id}/><input type="datetime-local" name="effective_from"/><input name="reason" required placeholder="Rollback reason"/><button className="btn ghost" style={{padding:8}}>Rollback to This Value</button></form>}</div></td></tr>)}{versions.length===0&&<tr><td colSpan={7} className="subtle">No configuration versions exist yet. Ordinary business rules can now be introduced without a code deployment.</td></tr>}</tbody></table></div></section>
 </>;
}