import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";

export const dynamic="force-dynamic";
type Org={id:string;name:string;role_code:string};
type Workspace={summary:{active_projects:number;truth_issues:number;pending_decisions:number;blocked_release_gates:number;critical_exceptions:number};projects:any[];recent_decisions:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";

export default async function Dashboard({searchParams}:{searchParams:Promise<{org?:string}>}){
 const {supabase}=await requireWorkspaceUser();
 const {data:orgData,error:orgError}=await supabase.rpc("list_user_organisations");if(orgError)throw new Error(orgError.message);
 const orgs=(orgData||[]) as Org[];const params=await searchParams;const organisation=orgs.find(o=>o.id===params.org)||orgs[0];
 let workspace:Workspace={summary:{active_projects:0,truth_issues:0,pending_decisions:0,blocked_release_gates:0,critical_exceptions:0},projects:[],recent_decisions:[]};
 if(organisation){const {data,error}=await supabase.rpc("list_command_centre_workspace",{target_organisation_id:organisation.id});if(error)throw new Error(error.message);workspace=(data||workspace) as Workspace;}
 const s=workspace.summary||{} as Workspace["summary"];
 return <>
  <div className="topbar"><div><div className="demo">Live Portfolio Command Centre</div><h1>Platform Command Centre</h1><div className="subtle">Derived directly from Project Truth, approvals, release assurance and risk records. No dashboard facts are stored separately.</div></div><Link className="btn" href="/app/projects/new">New Project</Link></div>
  <section className="panel"><h3>Organisation</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{orgs.map(o=><Link key={o.id} href={`/app?org=${o.id}`} className={organisation?.id===o.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{o.name} · {o.role_code}</Link>)}</div>{!orgs.length&&<div className="note">No active organisation membership is available.</div>}</section>
  <div className="kpis" style={{marginTop:16}}>{[["Active Projects",String(s.active_projects||0)],["Project Truth Issues",String(s.truth_issues||0)],["Pending Decisions",String(s.pending_decisions||0)],["Blocked Releases",String(s.blocked_release_gates||0)],["Critical Exceptions",String(s.critical_exceptions||0)]].map(([label,value])=><div className="kpi" key={label}><div className="label">{label}</div><div className="value">{value}</div><div className="subtle">Live source-domain state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Project Portfolio</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Project</th><th>Stage</th><th>Criticality</th><th>Truth issues</th><th>Pending approvals</th><th>Blocked releases</th><th>Critical risks</th></tr></thead><tbody>{(workspace.projects||[]).map(p=><tr key={p.id}><td><Link href={`/app/projects/${p.id}`}><b>{p.code}</b></Link><div className="subtle">{p.name} · {p.typology}</div></td><td><span className="badge">{pretty(p.stage)}</span></td><td>{p.criticality}</td><td>{p.truth_issues}</td><td>{p.pending_approvals}</td><td>{p.blocked_releases}</td><td>{p.critical_risks}</td></tr>)}{!(workspace.projects||[]).length&&<tr><td colSpan={7} className="subtle">No accessible projects exist for this organisation.</td></tr>}</tbody></table></div></section><section className="panel"><h3>Proof Before Publish</h3><p className="subtle">The command centre does not manufacture readiness. Release state remains owned by the release-assurance domain; unresolved Project Truth, professional authority, engineering evidence and critical exceptions are surfaced from their source records.</p><div className="note"><b>Continuous project graph.</b> Dashboard metrics are projections only. They cannot override approvals, releases, risk acceptance or underlying project records.</div></section></div>
  <section className="panel"><h3>Recent Approval Decisions</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Requested</th><th>Resource</th><th>Criticality</th><th>Decision</th><th>Pinned revision hash</th></tr></thead><tbody>{(workspace.recent_decisions||[]).map(a=><tr key={a.id}><td>{a.requested_at?new Date(a.requested_at).toLocaleString():"—"}</td><td>{pretty(a.resource_type)}</td><td>{a.criticality}</td><td><span className="badge">{pretty(a.decision)}</span></td><td><code>{a.requested_resource_hash?`${String(a.requested_resource_hash).slice(0,14)}…`:"—"}</code></td></tr>)}{!(workspace.recent_decisions||[]).length&&<tr><td colSpan={5} className="subtle">No approval requests have been recorded.</td></tr>}</tbody></table></div></section>
 </>;
}
