import { revalidatePath } from "next/cache";
import { requireWorkspaceUser } from "@/lib/auth";

export const dynamic="force-dynamic";
type Project={id:string;code:string;name:string};
type Issue={id:string;project_id?:string;issue_number:string;issue_type:string;title:string;description:string;status:string;priority:string;criticality:string;assignee_id?:string|null;due_at?:string|null;created_by?:string|null;created_at:string;updated_at:string};

async function createIssue(formData:FormData){
  "use server";const {supabase}=await requireWorkspaceUser();
  const payload={project_id:String(formData.get("project_id")||""),issue_type:String(formData.get("issue_type")||"coordination"),title:String(formData.get("title")||""),description:String(formData.get("description")||""),priority:String(formData.get("priority")||"medium"),criticality:String(formData.get("criticality")||"C1"),due_at:String(formData.get("due_at")||""),location_ref:String(formData.get("location_ref")||""),bcf_topic_ref:String(formData.get("bcf_topic_ref")||"")};
  const {error}=await supabase.rpc("create_coordination_issue",{input_payload:payload});if(error) throw new Error(error.message);revalidatePath("/app/issues");
}
async function addComment(formData:FormData){"use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("add_issue_comment",{target_issue_id:String(formData.get("issue_id")||""),comment_body:String(formData.get("comment_body")||""),evidence_refs:[]});if(error) throw new Error(error.message);revalidatePath("/app/issues");}
async function transitionIssue(formData:FormData){"use server";const {supabase}=await requireWorkspaceUser();const {error}=await supabase.rpc("transition_coordination_issue",{target_issue_id:String(formData.get("issue_id")||""),new_status:String(formData.get("status")||""),resolution_note:String(formData.get("resolution_note")||"")});if(error) throw new Error(error.message);revalidatePath("/app/issues");}

export default async function IssuesPage(){
  const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError) throw new Error(projectError.message);
  const projects=(projectData||[]) as Project[];const projectMap=new Map(projects.map(p=>[p.id,`${p.code} · ${p.name}`]));
  const batches=await Promise.all(projects.map(async p=>{const {data,error}=await supabase.rpc("list_project_issues",{target_project_id:p.id});if(error) throw new Error(error.message);return (data||[]).map((i:Issue)=>({...i,project_id:p.id}));}));
  const issues=batches.flat() as Issue[];const open=issues.filter(i=>!["resolved","closed"].includes(i.status)).length;const critical=issues.filter(i=>!["closed"].includes(i.status)&&["C3","C4"].includes(i.criticality)).length;const overdue=issues.filter(i=>!["resolved","closed"].includes(i.status)&&Boolean(i.due_at&&new Date(i.due_at)<new Date())).length;const awaiting=issues.filter(i=>i.status==="open").length;const closed=issues.filter(i=>i.status==="closed").length;
  return <>
    <div className="topbar"><div><div className="demo">Live BCF / RFI / Coordination</div><h1>Issues & RFIs</h1><div className="subtle">Project-linked coordination, technical queries, evidence, comments and controlled closure</div></div></div>
    <div className="kpis">{[["Open",String(open)],["Open C3/C4",String(critical)],["Overdue",String(overdue)],["Awaiting Action",String(awaiting)],["Closed",String(closed)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live workspace state</div></div>)}</div>
    <div className="panel-grid"><section className="panel"><h3>Create Issue / RFI</h3><form action={createIssue}><div className="field-grid"><div className="field"><label>Project</label><select name="project_id" required><option value="">Select</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Type</label><select name="issue_type" defaultValue="coordination"><option value="coordination">Coordination</option><option value="design">Design</option><option value="rfi">RFI</option><option value="quality">Quality</option><option value="regulatory">Regulatory</option><option value="commercial">Commercial</option><option value="site">Site</option></select></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Criticality</label><select name="criticality" defaultValue="C1">{["C0","C1","C2","C3","C4"].map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Priority</label><select name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><div className="field"><label>Due</label><input type="datetime-local" name="due_at"/></div><div className="field"><label>Location / Object Ref</label><input name="location_ref"/></div><div className="field"><label>BCF Topic Ref</label><input name="bcf_topic_ref"/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Description</label><textarea name="description" rows={3} required/></div></div><button className="btn" style={{marginTop:16}}>Create Issue</button></form></section><section className="panel"><h3>Closure Control</h3><p className="subtle">Issue status changes are audited. Closing an issue requires an explicit closure note, which is preserved as an issue comment and in the audit chain.</p><div className="note"><b>Project authority.</b> Issue creation, comments and transitions require access to the underlying project.</div></section></div>
    <section className="panel" style={{marginTop:16}}><h3>Coordination Queue</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Issue</th><th>Project</th><th>Type</th><th>Criticality</th><th>Status</th><th>Due</th><th>Comment / Transition</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td><b>{i.issue_number}</b><div>{i.title}</div><div className="subtle">{i.description}</div></td><td>{i.project_id?projectMap.get(i.project_id)||i.project_id.slice(0,8):"—"}</td><td>{i.issue_type}</td><td>{i.criticality}</td><td><span className="badge">{i.status}</span></td><td>{i.due_at?new Date(i.due_at).toLocaleString("en-IN"):"—"}</td><td><div style={{display:"grid",gap:6,minWidth:220}}><form action={addComment} style={{display:"grid",gap:5}}><input type="hidden" name="issue_id" value={i.id}/><input name="comment_body" placeholder="Add evidence-backed comment" required/><button className="btn ghost" style={{padding:7,fontSize:9}}>Add Comment</button></form>{i.status!=="closed"&&<form action={transitionIssue} style={{display:"grid",gap:5}}><input type="hidden" name="issue_id" value={i.id}/><select name="status" defaultValue={i.status==="open"?"in_progress":i.status==="in_progress"?"answered":i.status==="answered"?"resolved":"closed"}><option value="open">Open</option><option value="in_progress">In Progress</option><option value="answered">Answered</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><input name="resolution_note" placeholder="Required when closing"/><button className="btn ghost" style={{padding:7,fontSize:9}}>Transition</button></form>}</div></td></tr>)}{issues.length===0&&<tr><td colSpan={7} className="subtle">No issues yet.</td></tr>}</tbody></table></div></section>
  </>;
}
