import {revalidatePath} from "next/cache";
import {requireWorkspaceUser} from "@/lib/auth";

export const dynamic="force-dynamic";
const list=(v:FormDataEntryValue|null)=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);
async function createPack(formData:FormData){"use server";const {supabase}=await requireWorkspaceUser();const payload={code:String(formData.get("code")||"").trim().toUpperCase(),name:String(formData.get("name")||"").trim(),typology:String(formData.get("typology")||"").trim().toLowerCase(),version:1,programme_categories:list(formData.get("programme")),planning_principles:list(formData.get("planning")),operational_principles:list(formData.get("operations")),engineering_considerations:list(formData.get("engineering")),sustainability_considerations:list(formData.get("sustainability")),commercial_drivers:list(formData.get("commercial")),benchmark_sources:[],questionnaire:[],state:"draft"};const {error}=await supabase.schema("feasibility").from("typology_packs").insert(payload);if(error)throw new Error(error.message);revalidatePath("/app/admin/typologies");}
export default async function TypologiesAdmin(){const {supabase}=await requireWorkspaceUser();const {data,error}=await supabase.schema("feasibility").from("typology_packs").select("*").order("typology");if(error)throw new Error(error.message);const packs=data||[];return <>
 <div className="topbar"><div><div className="demo">Super Admin / Live Knowledge Governance</div><h1>Typology Knowledge Packs</h1><div className="subtle">Persisted, versioned planning knowledge. Every seeded pack remains draft until professional review.</div></div></div>
 <div className="panel-grid"><section className="panel"><h3>Create Pack</h3><form action={createPack}><div className="field-grid"><div className="field"><label>Code</label><input name="code" required placeholder="TYP-OFFICE"/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Typology</label><input name="typology" required/></div><div className="field"><label>Programme categories</label><input name="programme" placeholder="workspace, amenities, parking"/></div><div className="field"><label>Planning principles</label><input name="planning"/></div><div className="field"><label>Operational principles</label><input name="operations"/></div><div className="field"><label>Engineering considerations</label><input name="engineering"/></div><div className="field"><label>Sustainability considerations</label><input name="sustainability"/></div><div className="field"><label>Commercial drivers</label><input name="commercial"/></div></div><button className="btn">Create Draft Pack</button></form></section><section className="panel"><h3>Knowledge Pack Registry</h3><table className="table"><thead><tr><th>Code</th><th>Typology</th><th>Version</th><th>State</th><th>Focus</th></tr></thead><tbody>{packs.map(p=><tr key={p.id}><td><b>{p.code}</b><div className="subtle">{p.name}</div></td><td>{p.typology}</td><td>{p.version}</td><td><span className="badge">{p.state}</span></td><td>{[...(p.programme_categories||[]),...(p.planning_principles||[])].slice(0,4).join(", ")||"Awaiting definition"}</td></tr>)}</tbody></table><div className="note"><b>Promotion safeguard.</b> Draft knowledge is not used as regulatory truth until source, professional and maker-checker review is complete.</div></section></div>
 </>}
