import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import {EconomicsWorkspaceClient} from "@/components/PlanningIntelligenceClients";
import {emptyEconomicsWorkspace,type EconomicsWorkspaceState,type DesignProject} from "@/components/design-domain-runtime-types";

export const dynamic="force-dynamic";
export default async function EconomicsPage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as DesignProject[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state:EconomicsWorkspaceState=emptyEconomicsWorkspace;
 if(project){const {data,error}=await supabase.rpc("list_economics_workspace",{target_project_id:project.id});if(error)throw new Error(error.message);state=(data||emptyEconomicsWorkspace) as EconomicsWorkspaceState;}
 return <><div className="topbar"><div><div className="demo">Development Economics / Decision Intelligence</div><h1>Development Economics</h1><div className="subtle">Versioned commercial scenarios with disclosed assumptions, sources, calculation/model versions, sensitivity and maker-checker selection.</div></div></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/economics?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{!project&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<EconomicsWorkspaceClient projectId={project.id} state={state}/>}<div className="note"><b>Decision discipline.</b> IRR, NPV, value, cost or absorption figures are scenario outputs, never platform facts. Every selected scenario retains its exact assumptions, source map, model version and output hash.</div></>;
}