import { revalidatePath } from "next/cache";
import { requireWorkspaceUser } from "@/lib/auth";

export const dynamic="force-dynamic";
type Project={id:string;code:string;name:string};
type Approval={id:string;project_id?:string;resource_type:string;resource_id:string;requested_resource_hash?:string|null;requested_from?:string|null;role_required?:string|null;criticality:string;decision:string;comments?:string|null;requested_by?:string|null;requested_at:string;decided_at?:string|null;decision_evidence_hash?:string|null;decided_by?:string|null};
type ApprovalWorkspace={approvals:Approval[]};
const shortHash=(value?:string|null)=>value?`${value.slice(0,12)}…`:"—";

async function requestApproval(formData:FormData){
  "use server";const {supabase}=await requireWorkspaceUser();
  const payload={project_id:String(formData.get("project_id")||""),resource_type:String(formData.get("resource_type")||"document"),resource_id:String(formData.get("resource_id")||""),requested_from:String(formData.get("requested_from")||""),role_required:String(formData.get("role_required")||""),criticality:String(formData.get("criticality")||"C1"),comments:String(formData.get("comments")||"")};
  const {error}=await supabase.rpc("request_governed_approval",{input_payload:payload});if(error) throw new Error(error.message);revalidatePath("/app/approvals");
}
async function decideApproval(formData:FormData){
  "use server";const {supabase}=await requireWorkspaceUser();
  const {error}=await supabase.rpc("decide_governed_approval",{target_approval_id:String(formData.get("approval_id")||""),new_decision:String(formData.get("decision")||""),decision_comments:String(formData.get("decision_comments")||""),reviewed_resource_hash:String(formData.get("reviewed_resource_hash")||"")});
  if(error) throw new Error(error.message);revalidatePath("/app/approvals");
}

export default async function ApprovalsPage(){
  const {supabase,user}=await requireWorkspaceUser();
  const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError) throw new Error(projectError.message);
  const projects=(projectData||[]) as Project[];const projectMap=new Map(projects.map(p=>[p.id,`${p.code} · ${p.name}`]));
  const approvalBatches=await Promise.all(projects.map(async p=>{const {data,error}=await supabase.rpc("list_project_approval_workspace",{target_project_id:p.id});if(error) throw new Error(error.message);const state=(data||{approvals:[]}) as ApprovalWorkspace;return (state.approvals||[]).map((a:Approval)=>({...a,project_id:p.id}));}));
  const approvals=approvalBatches.flat() as Approval[];
  const pending=approvals.filter(a=>a.decision==="pending").length;const critical=approvals.filter(a=>a.decision==="pending"&&["C3","C4"].includes(a.criticality)).length;const assigned=approvals.filter(a=>a.decision==="pending"&&a.requested_from===user.id).length;const approved=approvals.filter(a=>["approved","approved_with_comments"].includes(a.decision)).length;const rejected=approvals.filter(a=>a.decision==="rejected").length;const legacy=approvals.filter(a=>a.decision==="pending"&&!a.requested_resource_hash).length;
  return <>
    <div className="topbar"><div><div className="demo">Live Maker-Checker / Authority</div><h1>Approvals</h1><div className="subtle">Role, scope, criticality and professional-eligibility-aware decisions pinned to the exact submitted resource revision.</div></div></div>
    <div className="kpis">{[["Pending",String(pending)],["Pending C3/C4",String(critical)],["Assigned To Me",String(assigned)],["Approved",String(approved)],["Legacy Re-request",String(legacy)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live workspace state</div></div>)}</div>
    <div className="panel-grid">
      <section className="panel"><h3>Request Approval</h3><form action={requestApproval}><div className="field-grid"><div className="field"><label>Project</label><select name="project_id" required><option value="">Select</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Resource Type</label><select name="resource_type" defaultValue="document"><option value="document">Document</option><option value="model">Model</option><option value="design_option">Design Option</option><option value="release">Release</option><option value="commercial">Commercial</option><option value="change">Change</option></select></div><div className="field"><label>Resource UUID</label><input name="resource_id" required placeholder="Current governed resource UUID"/></div><div className="field"><label>Criticality</label><select name="criticality" defaultValue="C1">{["C0","C1","C2","C3","C4"].map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Required Role</label><select name="role_required" defaultValue="lead_architect"><option value="lead_architect">Lead Architect</option><option value="architect">Architect</option><option value="structural_engineer">Structural Engineer</option><option value="mep_engineer">MEP Engineer</option><option value="quantity_surveyor">Quantity Surveyor</option><option value="regulatory_reviewer">Regulatory Reviewer</option><option value="client">Client</option><option value="client_approver">Client Approver</option><option value="project_manager">Project Manager</option><option value="finance">Finance</option></select></div><div className="field"><label>Specific Approver UUID</label><input name="requested_from" placeholder="Optional"/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Request Note</label><textarea name="comments" rows={3}/></div></div><button className="btn" style={{marginTop:16}}>Request Approval</button></form></section>
      <section className="panel"><h3>Authority Boundary</h3><p className="subtle">The request resolves and stores the domain-authoritative revision hash. At decision time the server resolves the resource again. A changed document, model, design option, release, contract, change analysis or coordination basis fails closed as <b>APPROVAL_VERSION_STALE</b>.</p><div className="note"><b>C3/C4:</b> exact professional role plus a currently verified professional credential remains mandatory. Administrative privilege cannot substitute for professional eligibility.</div></section>
    </div>
    <section className="panel" style={{marginTop:16}}><h3>Approval Queue</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Project</th><th>Resource</th><th>Pinned Submission</th><th>Criticality</th><th>Authority</th><th>Decision</th><th>Action</th></tr></thead><tbody>{approvals.map(a=><tr key={a.id}><td>{a.project_id?projectMap.get(a.project_id)||a.project_id.slice(0,8):"—"}</td><td>{a.resource_type}<div className="subtle">{a.resource_id.slice(0,8)}</div></td><td><code>{shortHash(a.requested_resource_hash)}</code>{!a.requested_resource_hash&&<div className="subtle">Legacy approval must be re-requested.</div>}</td><td>{a.criticality}</td><td>{a.role_required||"Unspecified"}{a.requested_from&&<div className="subtle">Assigned {a.requested_from.slice(0,8)}</div>}</td><td><span className="badge">{a.decision}</span>{a.decision_evidence_hash&&<div className="subtle">Decision {shortHash(a.decision_evidence_hash)}</div>}</td><td>{a.decision==="pending"&&a.requested_resource_hash?<form action={decideApproval} style={{display:"grid",gap:6,minWidth:220}}><input type="hidden" name="approval_id" value={a.id}/><input type="hidden" name="reviewed_resource_hash" value={a.requested_resource_hash}/><select name="decision" defaultValue="approved"><option value="approved">Approve exact revision</option><option value="approved_with_comments">Approve exact revision with comments</option><option value="rejected">Reject</option></select><input name="decision_comments" placeholder="Decision comments"/><button className="btn ghost" style={{padding:8}}>Record Decision</button>{a.requested_by===user.id&&["C2","C3","C4"].includes(a.criticality)&&<div className="subtle">Maker cannot approve own controlled action.</div>}</form>:a.decision==="pending"?<div className="subtle">Re-request against a pinned current revision.</div>:<div className="subtle">{a.comments||"Decided"}</div>}</td></tr>)}{approvals.length===0&&<tr><td colSpan={7} className="subtle">No approvals yet.</td></tr>}</tbody></table></div></section>
    {rejected>0&&<div className="note" style={{marginTop:16}}>Rejected decisions remain in the immutable audit trail and do not silently disappear from project history.</div>}
  </>;
}
