import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import {StructureWorkspaceClient} from "@/components/ArchitectureStructureWorkspaceClients";
import StructuralInvalidationEvidenceClient from "@/components/StructuralInvalidationEvidenceClient";
import {emptyStructureWorkspace,type StructureWorkspaceState,type DesignProject} from "@/components/design-domain-runtime-types";

type Credential={id:string;credential_type:string;issuing_body:string;registration_number:string;discipline?:string|null;valid_until?:string|null;verification_status:string};
type ValidationState={credentials?:Credential[]};
type Invalidation={id:string;structural_scheme_id:string;prior_architecture_package_id?:string|null;invalidating_architecture_package_id:string;prior_architecture_hash?:string|null;invalidating_architecture_hash:string;reason:string;affected_calculation_run_ids:unknown[];invalidation_hash:string;detected_at:string};
export const dynamic="force-dynamic";
export default async function StructurePage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as DesignProject[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state:StructureWorkspaceState=emptyStructureWorkspace;let credentials:Credential[]=[];let invalidations:Invalidation[]=[];
 if(project){const [workspace,validation]=await Promise.all([supabase.rpc("list_structure_workspace",{target_project_id:project.id}),supabase.rpc("list_engineering_validation_workspace")]);if(workspace.error)throw new Error(workspace.error.message);if(validation.error)throw new Error(validation.error.message);const raw=(workspace.data||emptyStructureWorkspace) as StructureWorkspaceState&{invalidations?:Invalidation[]};state=raw;invalidations=raw.invalidations||[];credentials=((validation.data||{}) as ValidationState).credentials||[];}
 return <><div className="topbar"><div><div className="demo">Structural Engineering / Certified Computation / Professional Release</div><h1>Structural Intelligence</h1><div className="subtle">Architecture-bound structural schemes, explicit geotechnical basis, certified solver evidence, exact calculation reviews, convergence and C3/C4 professional authority.</div></div><Link className="btn" href="/app/engineering">Engineering Verification</Link></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/structure?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{!project&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<><StructureWorkspaceClient projectId={project.id} state={state} credentials={credentials}/><StructuralInvalidationEvidenceClient invalidations={invalidations}/></>}<div className="note"><b>No LLM-only engineering authority.</b> Structural C3/C4 release remains blocked unless exact solver/version evidence is certified for the project criticality, analysis converges, calculation output hashes have current professional reviews, Architecture is current and the scheme receives credential-bound approval. A newly approved Architecture package automatically invalidates dependent structural analyses while preserving historical evidence.</div></>;
}