import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import InteriorsWorkspaceClient from "@/components/InteriorsWorkspaceClient";
import InteriorRenderEvidenceClient from "@/components/InteriorRenderEvidenceClient";
import {emptyInteriorsWorkspace,type InteriorsWorkspaceState,type DesignProject} from "@/components/design-domain-runtime-types";

export const dynamic="force-dynamic";
export default async function InteriorsPage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as DesignProject[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state:InteriorsWorkspaceState=emptyInteriorsWorkspace;
 if(project){const {data,error}=await supabase.rpc("list_interiors_workspace",{target_project_id:project.id});if(error)throw new Error(error.message);state=(data||emptyInteriorsWorkspace) as InteriorsWorkspaceState;}
 return <><div className="topbar"><div><div className="demo">Interior Design DNA / Room / Material / Shop Drawing Control</div><h1>Interiors</h1><div className="subtle">Versioned design language, exact-revision room packages, performance-aware material decisions and coordinated execution drawings.</div></div></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/interiors?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{!project&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<><InteriorsWorkspaceClient projectId={project.id} state={state}/><InteriorRenderEvidenceClient projectId={project.id} rooms={state.rooms} renders={state.renders}/></>}<div className="note"><b>Execution integrity.</b> Approved DNA is immutable/versioned; room packages pin model revision hashes; material substitutions expose cost/performance/lead-time delta; unresolved critical coordination checks block room/shop-drawing approval and issue; every registered render records the exact design/model revision and rendering engine used.</div></>;
}