"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {ActivationRow,ActivationState,ProjectStageRow,ProjectTeamMember,ProjectTeamState} from "@/components/commercial-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ");
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseArray(raw:string,label:string){try{const value=JSON.parse(raw||"[]");if(!Array.isArray(value))throw new Error();return value;}catch{throw new Error(`${label} must be a JSON array.`);}}
function parseObject(raw:string,label:string){try{const value=JSON.parse(raw||"{}");if(!value||Array.isArray(value)||typeof value!=="object")throw new Error();return value;}catch{throw new Error(`${label} must be a JSON object.`);}}

export default function ActivationStageClient({state,team}:{state:ActivationState;team:ProjectTeamState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const projects=state.projects||[];const activations=state.activations||[];const stages=state.stages||[];const contracts=state.contracts||[];
 const candidateOptions=Array.from(new Map((team.members||[]).map(m=>[m.user_id,m])).values());
 const activeTeam=(team.project_members||[]).filter(m=>m.status==="active");
 const projectName=(id?:string|null)=>projects.find(p=>p.id===id)?.name||id?.slice(0,8)||"—";
 const contractName=(id:string)=>{const c=contracts.find(x=>x.id===id);return c?`${c.contract_type||"Contract"} v${c.version}`:id.slice(0,8)};
 const memberLabel=(m:ProjectTeamMember)=>`${m.email||m.user_id.slice(0,8)} · ${pretty(m.role_code)}`;
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}

 async function assignMember(form:FormData){const {error}=await supabase.rpc("assign_project_member",{target_project_id:String(form.get("project_id")||""),target_user_id:String(form.get("user_id")||""),target_role_code:String(form.get("role_code")||""),target_discipline:String(form.get("discipline")||"")||null,target_reason:String(form.get("reason")||"Project team assignment")});if(error){setMessage(error.message);return;}refresh("Project team assignment saved and audited.");}
 async function removeMember(m:ProjectTeamMember){const reason=window.prompt(`Reason to remove ${memberLabel(m)}:`)||"";if(!reason)return;const {error}=await supabase.rpc("remove_project_member",{target_project_member_id:m.id,target_reason:reason});if(error){setMessage(error.message);return;}refresh("Project member deactivated without deleting assignment history.");}
 async function classify(form:FormData){const {error}=await supabase.rpc("set_project_data_classification",{target_project_id:String(form.get("project_id")||""),target_classification:String(form.get("classification")||"internal"),target_reason:String(form.get("reason")||"Data classification confirmed for activation")});if(error){setMessage(error.message);return;}refresh("Project data classification updated and audited.");}
 async function prepare(form:FormData){const payment=form.get("initial_payment_satisfied")==="on";const kyc=form.get("required_kyc_satisfied")==="on";const {error}=await supabase.rpc("prepare_project_activation",{target_contract_id:String(form.get("contract_id")||""),target_project_id:String(form.get("project_id")||""),input_payload:{initial_payment_satisfied:payment,required_kyc_satisfied:kyc,mobilisation_payment_evidence_ref:String(form.get("mobilisation_payment_evidence_ref")||"")||undefined,kyc_evidence_ref:String(form.get("kyc_evidence_ref")||"")||undefined}});if(error){setMessage(error.message);return;}refresh("Activation readiness recalculated from executed contract, payment/KYC evidence, project team, client users, site information and classification.");}
 async function activate(a:ActivationRow){const reason=window.prompt(`Activation reason for ${projectName(a.project_id)}:`)||"";if(!reason)return;const {data,error}=await supabase.rpc("activate_project",{target_activation_id:a.id,target_reason:reason});if(error){setMessage(error.message);return;}refresh(data==="blocked"?"Activation remains blocked; unresolved prerequisites are displayed below.":"Project activated. The contracted stage plan has been initialised.");}
 async function transitionStage(s:ProjectStageRow,target:string){let reason=window.prompt(`Reason for ${s.stage_code} → ${pretty(target)}:`)||"";if(!reason&&!["ready","in_progress"].includes(target))return;let evidence:unknown[]=[];if(["internal_review","client_review","approved","frozen"].includes(target)){const raw=window.prompt("Evidence refs JSON:","[]")||"";if(!raw)return;try{evidence=parseArray(raw,"Stage evidence");}catch(e){setMessage(e instanceof Error?e.message:String(e));return;}if(evidence.length===0){setMessage("This stage transition requires at least one evidence reference.");return;}}const {error}=await supabase.rpc("transition_project_stage",{target_project_stage_id:s.id,target_state:target,input_payload:{reason:reason||`${s.stage_code} ${target}`,evidence_refs:evidence}});if(error){setMessage(error.message);return;}refresh(`${s.stage_code} moved to ${pretty(target)}.`);}
 async function replan(form:FormData){try{const stageDates=parseObject(String(form.get("stage_dates")||"{}"),"Stage dates");const {error}=await supabase.rpc("replan_future_project_stages",{target_project_id:String(form.get("project_id")||""),target_contract_id:String(form.get("contract_id")||""),input_payload:{reason:String(form.get("reason")||""),stage_dates:stageDates}});if(error)throw error;refresh("Future stage plan rebaselined. Frozen/in-progress/review history was preserved rather than rewritten.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}

 const gateRows=(a:ActivationRow)=>[
  ["Accepted proposal",a.proposal_accepted],["Executed contract",a.contract_executed],["Initial payment",a.initial_payment_satisfied],["Required KYC",a.required_kyc_satisfied],
  ["Project team / Lead Architect",a.project_team_ready],["Client users",a.client_users_ready],["Site information",a.site_info_ready],["Data classification",a.data_classification_ready]
 ] as Array<[string,boolean]>;
 const nextActions=(s:ProjectStageRow)=>s.state==="not_started"?["ready"]:s.state==="ready"?["in_progress"]:s.state==="in_progress"?["internal_review"]:s.state==="internal_review"?["client_review","approved"]:s.state==="client_review"?["approved"]:s.state==="approved"?["frozen"]:[];
 const currentStages=projects.flatMap(p=>{const rows=stages.filter(s=>s.project_id===p.id);const max=rows.reduce((m,s)=>Math.max(m,s.baseline_version||0),0);return rows.filter(s=>s.baseline_version===max&&s.state!=="superseded");});

 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Activation runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Projects",String(projects.length).padStart(2,"0")],["Activation Pending",String(projects.filter(p=>p.lifecycle_state==="activation_pending").length).padStart(2,"0")],["Active",String(projects.filter(p=>p.lifecycle_state==="active").length).padStart(2,"0")],["Blocked",String(activations.filter(a=>a.state==="blocked").length).padStart(2,"0")],["Open Stages",String(currentStages.filter(s=>!["frozen","superseded"].includes(s.state)).length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live</div></div>)}</div>

  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Project Team & Client Users</h3><form action={assignMember}><div className="field-grid"><div className="field"><label>Project</label><select name="project_id" required>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Organisation user</label><select name="user_id" required>{candidateOptions.map(m=><option key={m.user_id} value={m.user_id}>{m.email||m.user_id} · {pretty(m.membership_role)}</option>)}</select></div><div className="field"><label>Project role</label><select name="role_code" defaultValue="project_manager"><option value="lead_architect">Lead Architect</option><option value="project_manager">Project / PMC Manager</option><option value="design_architect">Design Architect</option><option value="project_architect">Project Architect</option><option value="bim_manager">BIM Manager</option><option value="interior_designer">Interior Designer</option><option value="structural_engineer">Structural Engineer</option><option value="mep_lead">MEP Lead</option><option value="qs_cost_manager">QS / Cost Manager</option><option value="procurement_manager">Procurement Manager</option><option value="site_engineer">Site Engineer</option><option value="quality_manager">Quality Manager</option><option value="client_user">Client User</option><option value="client_reviewer">Client Reviewer</option><option value="client_approver">Client Approver</option><option value="client_admin">Client Admin</option><option value="auditor">Auditor</option></select></div><div className="field"><label>Discipline</label><input name="discipline"/></div></div><div className="field"><label>Assignment reason</label><input name="reason" defaultValue="Project activation team assignment"/></div><button className="btn">Assign Member</button></form>{candidateOptions.length===0&&<div className="note" style={{marginTop:8}}>No active organisation members are available for project assignment.</div>}{activeTeam.slice(0,24).map(m=><div className="note" key={m.id} style={{marginTop:7}}><b>{projectName(m.project_id)}</b> · {memberLabel(m)}{m.discipline&&<div className="subtle">{m.discipline}</div>}<button className="btn ghost" type="button" onClick={()=>removeMember(m)} style={{marginTop:5}}>Deactivate</button></div>)}</section>
   <section className="panel"><h3>Data Classification</h3><form action={classify}><div className="field"><label>Project</label><select name="project_id" required>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} · {p.data_classification||"internal"}</option>)}</select></div><div className="field"><label>Classification</label><select name="classification"><option>internal</option><option>confidential</option><option>restricted</option><option>public</option></select></div><div className="field"><label>Reason</label><input name="reason" required defaultValue="Classification confirmed before activation"/></div><button className="btn ghost">Apply Classification</button></form><div className="note" style={{marginTop:10}}><b>Fail closed.</b> Team, client access, site information and classification are server-evaluated. Payment and KYC can only be marked satisfied when evidence references are recorded.</div></section>
  </div>

  <section className="panel"><h3>Prepare Activation</h3><form action={prepare}><div className="field-grid"><div className="field"><label>Executed contract</label><select name="contract_id" required>{contracts.filter(c=>c.status==="active"&&c.execution_hash).map(c=><option key={c.id} value={c.id}>{contractName(c.id)} · {shortHash(c.execution_hash)}</option>)}</select></div><div className="field"><label>Project</label><select name="project_id" required>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} · {pretty(p.lifecycle_state||"pre_contract")}</option>)}</select></div></div><div style={{display:"flex",gap:18,flexWrap:"wrap",margin:"12px 0"}}><label><input type="checkbox" name="initial_payment_satisfied"/> Initial payment satisfied</label><label><input type="checkbox" name="required_kyc_satisfied"/> Required KYC satisfied</label></div><div className="field-grid"><div className="field"><label>Payment evidence reference</label><input name="mobilisation_payment_evidence_ref" placeholder="Receipt / bank / gateway / finance evidence"/></div><div className="field"><label>KYC evidence reference</label><input name="kyc_evidence_ref" placeholder="Verified KYC record / document reference"/></div></div><button className="btn">Recalculate Activation Readiness</button></form>{contracts.filter(c=>c.status==="active"&&c.execution_hash).length===0&&<div className="note" style={{marginTop:8}}>No executed active contract is available. Activation cannot be prepared until legal execution is complete.</div>}</section>

  <section className="panel"><h3>Activation Gate Ledger</h3>{activations.map(a=><div className="note" key={a.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b>{projectName(a.project_id)}</b> · <span className="badge">{pretty(a.state)}</span><div className="subtle">Activation hash <code>{shortHash(a.activation_hash)}</code>{a.blocked_reason?` · ${a.blocked_reason}`:""}</div></div>{a.state!=="activated"&&<button className="btn" type="button" onClick={()=>activate(a)}>Attempt Activation</button>}</div><div className="grid-3" style={{marginTop:10}}>{gateRows(a).map(([label,ok])=><div className="card" key={label}><div className="eyebrow">{label}</div><h3>{ok?"Ready":"Blocked"}</h3></div>)}</div></div>)}{activations.length===0&&<div className="subtle">No activation assessment exists yet.</div>}</section>

  <section className="panel"><h3>Current Stage Plan</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Project</th><th>Stage</th><th>Baseline</th><th>State</th><th>Dependencies</th><th>Plan / Actual</th><th>Action</th></tr></thead><tbody>{currentStages.sort((a,b)=>a.project_id.localeCompare(b.project_id)||a.sequence-b.sequence).map(s=><tr key={s.id}><td>{projectName(s.project_id)}</td><td><b>{s.stage_code}</b><div className="subtle">{s.title}</div></td><td>v{s.baseline_version}<div className="subtle"><code>{shortHash(s.source_scope_hash)}</code></div></td><td><span className="badge">{pretty(s.state)}</span></td><td>{s.dependencies.length?s.dependencies.join(" → "):"—"}</td><td>{s.planned_start||"—"} → {s.planned_finish||"—"}<div className="subtle">Actual {s.actual_start||"—"} → {s.actual_finish||"—"}</div></td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{nextActions(s).map(next=><button className={next==="frozen"?"btn":"btn ghost"} type="button" key={next} onClick={()=>transitionStage(s,next)}>{pretty(next)}</button>)}</div></td></tr>)}{currentStages.length===0&&<tr><td colSpan={7} className="subtle">No active stage plan yet. It is created atomically when activation succeeds.</td></tr>}</tbody></table></div></section>

  <section className="panel"><h3>Change-order Future Replan</h3><p className="subtle">Only future, untouched stages are superseded into a new baseline. In-progress, review, approved and frozen history is preserved.</p><form action={replan}><div className="field-grid"><div className="field"><label>Project</label><select name="project_id" required>{projects.filter(p=>p.lifecycle_state==="active").map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Active change-order contract</label><select name="contract_id" required>{contracts.filter(c=>c.status==="active"&&c.execution_hash).map(c=><option key={c.id} value={c.id}>{contractName(c.id)}</option>)}</select></div></div><div className="field"><label>Replan reason</label><input name="reason" required/></div><div className="field"><label>Stage dates JSON</label><textarea name="stage_dates" rows={4} defaultValue={'{"S04":{"planned_start":"","planned_finish":""}}'}/></div><button className="btn ghost">Create Future Baseline</button></form></section>
 </>;
}
