"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type AIWorkspace={agents:any[];models:any[];prompts:any[];evaluation_cases:any[];evaluation_results:any[];learning_candidates:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const parseArray=(v:FormDataEntryValue|null)=>{const s=String(v||"").trim();if(!s)return [];const x=JSON.parse(s);if(!Array.isArray(x))throw new Error("Expected a JSON array");return x;};
const parseObject=(v:FormDataEntryValue|null)=>{const s=String(v||"").trim();if(!s)return {};const x=JSON.parse(s);if(!x||Array.isArray(x)||typeof x!=="object")throw new Error("Expected a JSON object");return x;};

export default function AIControlGovernanceClient({workspace}:{workspace:AIWorkspace}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const agents=workspace.agents||[];const models=workspace.models||[];const prompts=workspace.prompts||[];const cases=workspace.evaluation_cases||[];const results=workspace.evaluation_results||[];const learning=workspace.learning_candidates||[];
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function createAgent(form:FormData){try{const {error}=await supabase.rpc("create_ai_agent",{input_payload:{code:String(form.get("code")||""),name:String(form.get("name")||""),purpose:String(form.get("purpose")||""),max_criticality:String(form.get("max_criticality")||"C1"),allowed_autonomy:String(form.get("allowed_autonomy")||"ai_advisory"),allowed_tools:parseArray(form.get("allowed_tools")),prohibited_actions:parseArray(form.get("prohibited_actions")),no_hallucination_zones:parseArray(form.get("no_hallucination_zones")),requires_human_approval_for:parseArray(form.get("requires_human_approval_for")),requires_grounding:form.get("requires_grounding")==="on"}});if(error)return setMessage(error.message);refresh("AI agent definition created disabled. Evaluation and runtime gates still apply.");}catch(e){fail(e);}}
 async function createModel(form:FormData){try{const {error}=await supabase.rpc("create_ai_model_profile",{input_payload:{provider:String(form.get("provider")||""),model:String(form.get("model")||""),purpose:String(form.get("purpose")||""),max_criticality:String(form.get("max_criticality")||"C1"),secret_ref:String(form.get("secret_ref")||""),supports_structured_output:form.get("supports_structured_output")==="on",supports_vision:form.get("supports_vision")==="on",supports_tool_use:form.get("supports_tool_use")==="on",data_residency:String(form.get("data_residency")||""),latency_target_ms:String(form.get("latency_target_ms")||""),evaluation_threshold:String(form.get("evaluation_threshold")||"0"),cost_policy:parseObject(form.get("cost_policy"))}});if(error)return setMessage(error.message);refresh("Model profile created disabled. Its secret reference is never returned to this UI.");}catch(e){fail(e);}}
 async function createPrompt(form:FormData){const {error}=await supabase.rpc("create_ai_prompt_version",{input_payload:{agent_code:String(form.get("agent_code")||""),template:String(form.get("template")||""),output_schema_ref:String(form.get("output_schema_ref")||""),system_policy_ref:String(form.get("system_policy_ref")||"")}});if(error)return setMessage(error.message);refresh("Prompt version drafted with an immutable prompt hash.");}
 async function createCase(form:FormData){try{const {error}=await supabase.rpc("create_ai_evaluation_case",{input_payload:{suite_code:String(form.get("suite_code")||""),name:String(form.get("name")||""),criticality:String(form.get("criticality")||"C1"),input:parseObject(form.get("input")),expected_assertions:parseArray(form.get("expected_assertions"))}});if(error)return setMessage(error.message);refresh("Evaluation case registered.");}catch(e){fail(e);}}
 async function recordResult(form:FormData){try{const {error}=await supabase.rpc("record_ai_evaluation_result",{target_case_id:String(form.get("case_id")||""),target_model_profile_id:String(form.get("model_profile_id")||""),target_prompt_version_id:String(form.get("prompt_version_id")||""),target_score:Number(form.get("score")||0),target_passed:form.get("passed")==="on",target_findings:parseArray(form.get("findings"))});if(error)return setMessage(error.message);refresh("Evaluation result recorded as immutable benchmark evidence.");}catch(e){fail(e);}}
 async function activatePrompt(id:string){const reason=window.prompt("Independent prompt activation reason");if(!reason?.trim())return;const {error}=await supabase.rpc("activate_ai_prompt_version",{target_prompt_id:id,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh("Prompt activated after evaluation gate.");}
 async function modelState(id:string,enabled:boolean){const reason=window.prompt(`${enabled?"Enable":"Disable"} model reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("set_ai_model_enabled",{target_model_id:id,target_enabled:enabled,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Model ${enabled?"enabled":"disabled"}.`);}
 async function agentState(a:any,enabled:boolean){const autonomy=window.prompt("Allowed autonomy",a.allowed_autonomy||"ai_advisory");if(!autonomy?.trim())return;const reason=window.prompt(`${enabled?"Enable":"Disable"} agent reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("set_ai_agent_state",{target_agent_code:String(a.code),target_enabled:enabled,target_autonomy:autonomy.trim(),target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Agent ${enabled?"enabled":"disabled"} under governed autonomy.`);}
 const passed=results.filter(r=>r.passed).length;const c34Autonomous=agents.filter(a=>a.enabled&&["C3","C4"].includes(a.max_criticality)&&a.allowed_autonomy==="bounded_autonomous").length;
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>AI governance:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Enabled Agents",String(agents.filter(a=>a.enabled).length)],["Enabled Models",String(models.filter(m=>m.enabled).length)],["Evaluation Passes",`${passed}/${results.length}`],["C3/C4 Autonomous",String(c34Autonomous)],["Learning Candidates",String(learning.length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>8?20:30}}>{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Create Agent Definition</h3><form action={createAgent}><div className="field-grid"><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Max criticality</label><select name="max_criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div><div className="field"><label>Autonomy</label><select name="allowed_autonomy"><option>human_only</option><option>ai_advisory</option><option>ai_draft</option><option>execute_after_approval</option><option>bounded_autonomous</option></select></div></div><div className="field"><label>Purpose</label><textarea name="purpose" rows={2} required/></div><div className="field-grid"><div className="field"><label>Allowed tools JSON</label><textarea name="allowed_tools" rows={3} defaultValue="[]"/></div><div className="field"><label>Prohibited actions JSON</label><textarea name="prohibited_actions" rows={3} defaultValue="[]"/></div><div className="field"><label>No-hallucination zones JSON</label><textarea name="no_hallucination_zones" rows={3} defaultValue="[]"/></div><div className="field"><label>Human approval actions JSON</label><textarea name="requires_human_approval_for" rows={3} defaultValue="[]"/></div></div><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" name="requires_grounding" defaultChecked/> Requires grounding</label><button className="btn" style={{marginTop:10}}>Create Disabled Agent</button></form></section>
   <section className="panel"><h3>Create Model Profile</h3><form action={createModel}><div className="field-grid"><div className="field"><label>Provider</label><input name="provider" required/></div><div className="field"><label>Model</label><input name="model" required/></div><div className="field"><label>Purpose</label><input name="purpose" required/></div><div className="field"><label>Max criticality</label><select name="max_criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div><div className="field"><label>Vault / secret reference</label><input name="secret_ref" required/></div><div className="field"><label>Evaluation threshold (0–1)</label><input name="evaluation_threshold" type="number" min="0" max="1" step="0.01" defaultValue="0"/></div><div className="field"><label>Latency target ms</label><input name="latency_target_ms" type="number" min="1"/></div><div className="field"><label>Data residency</label><input name="data_residency"/></div></div><div className="field"><label>Cost policy JSON</label><textarea name="cost_policy" rows={3} defaultValue="{}"/></div><div style={{display:"flex",gap:14,flexWrap:"wrap"}}><label><input type="checkbox" name="supports_structured_output"/> Structured output</label><label><input type="checkbox" name="supports_vision"/> Vision</label><label><input type="checkbox" name="supports_tool_use"/> Tool use</label></div><button className="btn" style={{marginTop:10}}>Create Disabled Model</button></form></section>
  </div>
  <section className="panel"><h3>Agent Authority Registry</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Agent</th><th>Criticality</th><th>Autonomy</th><th>Grounding</th><th>Status</th><th>Hash</th><th>Action</th></tr></thead><tbody>{agents.map(a=><tr key={String(a.code)}><td><b>{a.name}</b><div className="subtle">{String(a.code)}</div></td><td>{a.max_criticality}</td><td>{pretty(a.allowed_autonomy)}</td><td>{a.requires_grounding?"Required":"Not required"}</td><td><span className="badge">{a.enabled?"enabled":"disabled"}</span></td><td><code>{short(a.definition_hash)}</code></td><td><button className="btn ghost" style={{padding:6}} onClick={()=>agentState(a,!a.enabled)}>{a.enabled?"Disable":"Enable"}</button></td></tr>)}{agents.length===0&&<tr><td colSpan={7} className="subtle">No AI agents are configured. The platform will not invent agent availability.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Model Profiles</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Model</th><th>Purpose</th><th>Criticality</th><th>Capabilities</th><th>Status</th><th>Threshold</th><th>Action</th></tr></thead><tbody>{models.map(m=><tr key={m.id}><td><b>{m.provider} / {m.model}</b><div className="subtle"><code>{short(m.profile_hash)}</code></div></td><td>{m.purpose}</td><td>{m.max_criticality}</td><td>{[m.supports_structured_output&&"structured",m.supports_vision&&"vision",m.supports_tool_use&&"tools"].filter(Boolean).join(", ")||"basic"}</td><td><span className="badge">{m.enabled?"enabled":"disabled"}</span></td><td>{m.evaluation_threshold??"—"}</td><td><button className="btn ghost" style={{padding:6}} onClick={()=>modelState(m.id,!m.enabled)}>{m.enabled?"Disable":"Enable"}</button></td></tr>)}{models.length===0&&<tr><td colSpan={7} className="subtle">No model profiles exist. Secret references are never rendered here.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid">
   <section className="panel"><h3>Draft Prompt Version</h3><form action={createPrompt}><div className="field"><label>Agent</label><select name="agent_code" required>{agents.map(a=><option key={String(a.code)} value={String(a.code)}>{String(a.code)} · {a.name}</option>)}</select></div><div className="field"><label>Prompt template</label><textarea name="template" rows={8} required/></div><div className="field-grid"><div className="field"><label>Output schema ref</label><input name="output_schema_ref"/></div><div className="field"><label>System policy ref</label><input name="system_policy_ref"/></div></div><button className="btn" disabled={!agents.length}>Draft Prompt</button></form></section>
   <section className="panel"><h3>Create Evaluation Case</h3><form action={createCase}><div className="field"><label>Suite / agent code</label><select name="suite_code" required>{agents.map(a=><option key={String(a.code)} value={String(a.code)}>{String(a.code)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Criticality</label><select name="criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div></div><div className="field"><label>Input JSON</label><textarea name="input" rows={4} defaultValue="{}"/></div><div className="field"><label>Expected assertions JSON</label><textarea name="expected_assertions" rows={4} defaultValue="[]"/></div><button className="btn ghost" disabled={!agents.length}>Create Case</button></form></section>
  </div>
  <section className="panel"><h3>Prompt Versions & Evaluation Gate</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Agent</th><th>Version</th><th>Status</th><th>Hash</th><th>Evaluation</th><th>Action</th></tr></thead><tbody>{prompts.map(p=>{const pr=results.filter(r=>r.prompt_version_id===p.id);return <tr key={p.id}><td>{String(p.agent_code)}</td><td>{p.version}</td><td><span className="badge">{pretty(p.status)}</span></td><td><code>{short(p.prompt_hash)}</code></td><td>{pr.filter(r=>r.passed).length}/{pr.length} passing results</td><td>{p.status!=="active"&&p.status!=="retired"&&<button className="btn ghost" style={{padding:6}} onClick={()=>activatePrompt(p.id)}>Activate</button>}</td></tr>})}{prompts.length===0&&<tr><td colSpan={6} className="subtle">No prompt versions exist.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Record Evaluation Evidence</h3><form action={recordResult}><div className="field-grid"><div className="field"><label>Case</label><select name="case_id" required>{cases.map(c=><option key={c.id} value={c.id}>{c.suite_code} · {c.name}</option>)}</select></div><div className="field"><label>Model</label><select name="model_profile_id" required>{models.map(m=><option key={m.id} value={m.id}>{m.provider} / {m.model}</option>)}</select></div><div className="field"><label>Prompt</label><select name="prompt_version_id" required>{prompts.map(p=><option key={p.id} value={p.id}>{String(p.agent_code)} v{p.version}</option>)}</select></div><div className="field"><label>Score (0–1)</label><input name="score" type="number" min="0" max="1" step="0.001" required/></div></div><div className="field"><label>Findings JSON</label><textarea name="findings" rows={3} defaultValue="[]"/></div><label><input type="checkbox" name="passed"/> Passed</label><div><button className="btn" style={{marginTop:10}} disabled={!cases.length||!models.length||!prompts.length}>Record Result</button></div></form></section>
  <div className="note"><b>Critical AI authority:</b> C3/C4 bounded autonomy is rejected by the database. Agent enablement requires an active evaluated prompt and an enabled model rated for the agent criticality. Missing evidence fails closed.</div>
 </>;
}
