"use client";

import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type RuntimeProject={id:string;organisation_id:string;code:string;name:string;criticality:string;status:string};
type RuntimeAgent={code:string;name:string;enabled:boolean;max_criticality:string;allowed_autonomy:string;requires_grounding:boolean;definition_hash?:string|null};
type RuntimeModel={id:string;provider:string;model:string;enabled:boolean;max_criticality:string;evaluation_threshold?:number|null;profile_hash?:string|null};
type RuntimeRun={id:string;project_id?:string|null;agent_code:string;model_profile_id:string;status:string;criticality:string;input_ref?:string|null;output_ref?:string|null;output_status?:string|null;output_hash?:string|null;grounding_status?:string|null;evidence_refs:unknown[];correlation_id:string;started_at?:string|null;finished_at?:string|null;created_at:string};
type LearningCandidate={id:string;source_project_id?:string|null;source_type:string;source_ref:string;stage:string;privacy_state:string;evidence_quality:string;benchmark_delta?:number|null;expert_reviewers:unknown[];rollback_ref?:string|null;promotion_scope?:string|null;candidate_hash?:string|null;updated_at:string};
export type AIRuntimeWorkspace={projects:RuntimeProject[];agents:RuntimeAgent[];models:RuntimeModel[];runs:RuntimeRun[];learning_candidates:LearningCandidate[]};
export const emptyAIRuntimeWorkspace:AIRuntimeWorkspace={projects:[],agents:[],models:[],runs:[],learning_candidates:[]};

const pretty=(v?:string|null)=>v?v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function arr(value:FormDataEntryValue|null){const s=String(value||"").trim();if(!s)return [];const x=JSON.parse(s);if(!Array.isArray(x))throw new Error("Expected a JSON array");return x;}
function obj(value:FormDataEntryValue|null){const s=String(value||"").trim();if(!s)return {};const x=JSON.parse(s);if(!x||Array.isArray(x)||typeof x!=="object")throw new Error("Expected a JSON object");return x;}

export default function AIRuntimeLearningClient({workspace}:{workspace:AIRuntimeWorkspace}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const enabledAgents=workspace.agents.filter(a=>a.enabled);const enabledModels=workspace.models.filter(m=>m.enabled);const openRuns=workspace.runs.filter(r=>["queued","running","awaiting_approval"].includes(r.status));
 const projectMap=useMemo(()=>new Map(workspace.projects.map(p=>[p.id,p])),[workspace.projects]);
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function startRun(form:FormData){try{const project=projectMap.get(String(form.get("project_id")||""));if(!project)return setMessage("Select a valid project.");const {data,error}=await supabase.rpc("start_ai_agent_run",{target_organisation_id:project.organisation_id,target_project_id:project.id,target_agent_code:String(form.get("agent_code")||""),target_model_profile_id:String(form.get("model_profile_id")||""),target_criticality:String(form.get("criticality")||project.criticality),target_input_ref:String(form.get("input_ref")||""),target_evidence_refs:arr(form.get("evidence_refs"))});if(error)return setMessage(error.message);refresh(`Governed AI run ${String(data).slice(0,8)} started with agent, prompt, model and criticality pinned.`);}catch(e){fail(e);}}
 async function completeRun(form:FormData){try{const hash=String(form.get("output_hash")||"").trim();const {data,error}=await supabase.rpc("complete_ai_agent_run",{target_run_id:String(form.get("run_id")||""),target_succeeded:form.get("succeeded")==="on",target_output_ref:String(form.get("output_ref")||""),target_output_payload:obj(form.get("output_payload")),target_authoritative:form.get("authoritative")==="on",target_output_hash:hash||undefined});if(error)return setMessage(error.message);const out=(data||{}) as Record<string,unknown>;refresh(`Run completed as ${pretty(String(out.output_status||out.status||"complete"))}. Missing required grounding is recorded as Not Verified.`);}catch(e){fail(e);}}
 async function proposeLearning(form:FormData){const projectId=String(form.get("source_project_id")||"")||undefined;const {data,error}=await supabase.rpc("propose_ai_learning_candidate",{target_source_project_id:projectId,target_source_type:String(form.get("source_type")||""),target_source_ref:String(form.get("source_ref")||""),target_evidence_quality:String(form.get("evidence_quality")||"medium")});if(error)return setMessage(error.message);refresh(`Learning candidate ${String(data).slice(0,8)} proposed. It cannot enter production without privacy, expert and benchmark gates.`);}
 async function transitionLearning(form:FormData){try{const payload:{privacy_state?:string;expert_reviewers?:unknown[];benchmark_delta?:number;rollback_ref?:string;promotion_scope?:string}={};const privacy=String(form.get("privacy_state")||"");if(privacy)payload.privacy_state=privacy;const experts=String(form.get("expert_reviewers")||"").trim();if(experts)payload.expert_reviewers=arr(form.get("expert_reviewers"));const benchmark=String(form.get("benchmark_delta")||"").trim();if(benchmark)payload.benchmark_delta=Number(benchmark);const rollback=String(form.get("rollback_ref")||"").trim();if(rollback)payload.rollback_ref=rollback;const scope=String(form.get("promotion_scope")||"").trim();if(scope)payload.promotion_scope=scope;const {data,error}=await supabase.rpc("transition_ai_learning_candidate",{target_candidate_id:String(form.get("candidate_id")||""),target_stage:String(form.get("stage")||""),input_payload:payload,target_reason:String(form.get("reason")||"")});if(error)return setMessage(error.message);refresh(`Learning candidate advanced to ${pretty(String(data))}.`);}catch(e){fail(e);}}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>AI runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Governed Runs",workspace.runs.length],["Open Runs",openRuns.length],["Enabled Agents",enabledAgents.length],["Enabled Models",enabledModels.length],["Learning Candidates",workspace.learning_candidates.length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{String(v).padStart(2,"0")}</div><div className="subtle">Live authority state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Start Governed AI Run</h3><form action={startRun}><div className="field"><label>Project</label><select name="project_id" required>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} · {p.criticality}</option>)}</select></div><div className="field-grid"><div className="field"><label>Enabled agent</label><select name="agent_code" required>{enabledAgents.map(a=><option key={a.code} value={a.code}>{a.code} · max {a.max_criticality}</option>)}</select></div><div className="field"><label>Enabled model</label><select name="model_profile_id" required>{enabledModels.map(m=><option key={m.id} value={m.id}>{m.provider}/{m.model} · max {m.max_criticality}</option>)}</select></div><div className="field"><label>Run criticality</label><select name="criticality" defaultValue="C1">{["C0","C1","C2","C3","C4"].map(v=><option key={v}>{v}</option>)}</select></div></div><div className="field"><label>Input reference</label><input name="input_ref" placeholder="project://controlled-input"/></div><div className="field"><label>Grounding / evidence refs JSON</label><textarea name="evidence_refs" rows={4} defaultValue="[]"/></div><button className="btn" disabled={!workspace.projects.length||!enabledAgents.length||!enabledModels.length}>Start Pinned Run</button></form><div className="note" style={{marginTop:12}}>Execution rechecks the actual agent and model criticality. A C4 run cannot start on a model or agent rated below C4.</div></section>
   <section className="panel"><h3>Complete Governed Run</h3><form action={completeRun}><div className="field"><label>Open run</label><select name="run_id" required>{openRuns.map(r=><option key={r.id} value={r.id}>{r.agent_code} · {r.criticality} · {r.id.slice(0,8)}</option>)}</select></div><div style={{display:"flex",gap:14,flexWrap:"wrap"}}><label><input type="checkbox" name="succeeded" defaultChecked/> Execution succeeded</label><label><input type="checkbox" name="authoritative"/> Authoritative output</label></div><div className="field"><label>Output reference</label><input name="output_ref" placeholder="artifact://result"/></div><div className="field"><label>Output SHA-256</label><input name="output_hash" minLength={64} maxLength={64}/></div><div className="field"><label>Completion payload JSON</label><textarea name="output_payload" rows={5} defaultValue="{}"/></div><button className="btn ghost" disabled={!openRuns.length}>Complete With Evidence State</button></form><div className="note" style={{marginTop:12}}>Authoritative or grounding-required output without evidence is not promoted as fact. It resolves to <b>Not Verified</b>.</div></section>
  </div>
  <section className="panel"><h3>AI Run Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Run</th><th>Project</th><th>Agent / Model</th><th>Criticality</th><th>Runtime</th><th>Grounding</th><th>Output</th><th>Hash</th></tr></thead><tbody>{workspace.runs.map(r=>{const p=projectMap.get(r.project_id||"");const m=workspace.models.find(x=>x.id===r.model_profile_id);return <tr key={r.id}><td><code>{r.id.slice(0,8)}</code></td><td>{p?`${p.code} · ${p.name}`:"Organisation"}</td><td>{r.agent_code}<div className="subtle">{m?`${m.provider}/${m.model}`:short(r.model_profile_id)}</div></td><td>{r.criticality}</td><td><span className="badge">{pretty(r.status)}</span></td><td>{pretty(r.grounding_status)}</td><td>{pretty(r.output_status)}</td><td><code>{short(r.output_hash)}</code></td></tr>})}{!workspace.runs.length&&<tr><td colSpan={8} className="subtle">No governed AI runs have been recorded yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid">
   <section className="panel"><h3>Propose Learning Candidate</h3><form action={proposeLearning}><div className="field"><label>Source project</label><select name="source_project_id"><option value="">Cross-project / organisation source</option>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field-grid"><div className="field"><label>Source type</label><input name="source_type" required placeholder="outcome_signal / benchmark / review"/></div><div className="field"><label>Evidence quality</label><select name="evidence_quality" defaultValue="medium"><option>low</option><option>medium</option><option>high</option></select></div></div><div className="field"><label>Controlled source reference</label><input name="source_ref" required/></div><button className="btn">Propose Candidate</button></form></section>
   <section className="panel"><h3>Advance Learning Gate</h3><form action={transitionLearning}><div className="field"><label>Candidate</label><select name="candidate_id" required>{workspace.learning_candidates.filter(c=>c.stage!=="retired").map(c=><option key={c.id} value={c.id}>{c.source_type} · {c.id.slice(0,8)} · {pretty(c.stage)}</option>)}</select></div><div className="field"><label>Target stage</label><select name="stage"><option value="privacy_review">Privacy Review</option><option value="expert_review">Expert Review</option><option value="benchmark">Benchmark</option><option value="shadow">Shadow</option><option value="controlled_production">Controlled Production</option><option value="retired">Retire</option></select></div><div className="field-grid"><div className="field"><label>Privacy decision</label><select name="privacy_state"><option value="">Keep current</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><div className="field"><label>Promotion scope</label><select name="promotion_scope"><option value="project">Project</option><option value="organisation">Organisation</option><option value="global">Global</option></select></div><div className="field"><label>Benchmark delta</label><input name="benchmark_delta" type="number" step="0.001"/></div></div><div className="field"><label>Expert reviewer refs JSON</label><textarea name="expert_reviewers" rows={3} placeholder='["credential://reviewer"]'/></div><div className="field"><label>Rollback reference</label><input name="rollback_ref" placeholder="release://prior-governed-version"/></div><div className="field"><label>Decision reason</label><textarea name="reason" rows={3} required/></div><button className="btn ghost" disabled={!workspace.learning_candidates.length}>Apply Learning Gate</button></form></section>
  </div>
  <section className="panel"><h3>Learning Promotion Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Candidate</th><th>Stage</th><th>Privacy</th><th>Evidence</th><th>Experts</th><th>Benchmark Δ</th><th>Scope</th><th>Rollback</th></tr></thead><tbody>{workspace.learning_candidates.map(c=><tr key={c.id}><td>{c.source_type}<div className="subtle"><code>{short(c.candidate_hash)}</code></div></td><td><span className="badge">{pretty(c.stage)}</span></td><td>{pretty(c.privacy_state)}</td><td>{pretty(c.evidence_quality)}</td><td>{Array.isArray(c.expert_reviewers)?c.expert_reviewers.length:0}</td><td>{c.benchmark_delta??"—"}</td><td>{pretty(c.promotion_scope)}</td><td><code>{c.rollback_ref||"—"}</code></td></tr>)}{!workspace.learning_candidates.length&&<tr><td colSpan={8} className="subtle">No learning candidates exist.</td></tr>}</tbody></table></div></section>
 </>;
}
