"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {AnalyticsWorkspaceState,LatestKPI} from "@/components/analytics-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ");
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function signal(x:LatestKPI){const v=Number(x.value);const target=x.target===null||x.target===undefined?null:Number(x.target);const w=x.warning_threshold===null||x.warning_threshold===undefined?null:Number(x.warning_threshold);const c=x.critical_threshold===null||x.critical_threshold===undefined?null:Number(x.critical_threshold);if(x.direction==="higher_is_better"){if(c!==null&&v<c)return "critical";if(w!==null&&v<w)return "warning";return "on_track";}if(x.direction==="lower_is_better"){if(c!==null&&v>c)return "critical";if(w!==null&&v>w)return "warning";return "on_track";}if(target!==null){const d=Math.abs(v-target);if(c!==null&&d>c)return "critical";if(w!==null&&d>w)return "warning";}return "on_track";}

export default function AnalyticsWorkspaceClient({organisationId,state}:{organisationId:string;state:AnalyticsWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const definitions=state.definitions||[];const active=definitions.filter(d=>d.active);const latest=state.latest||[];const critical=latest.filter(x=>signal(x)==="critical").length;const warning=latest.filter(x=>signal(x)==="warning").length;
 const projectName=(id?:string|null)=>state.projects.find(p=>p.id===id)?.name||"Organisation";
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 async function createDefinition(form:FormData){const {error}=await supabase.rpc("create_kpi_definition",{target_organisation_id:organisationId,input_payload:{code:String(form.get("code")||""),name:String(form.get("name")||""),domain:String(form.get("domain")||""),unit:String(form.get("unit")||""),direction:String(form.get("direction")||"higher_is_better"),target:String(form.get("target")||"")||undefined,warning_threshold:String(form.get("warning_threshold")||"")||undefined,critical_threshold:String(form.get("critical_threshold")||"")||undefined,calculation_ref:String(form.get("calculation_ref")||""),refresh_cadence:String(form.get("refresh_cadence")||"manual")}});if(error){setMessage(error.message);return;}refresh("KPI definition version created; any prior active version was superseded without rewriting history.");}
 async function observe(form:FormData){const projectId=String(form.get("project_id")||"")||null;const {error}=await supabase.rpc("record_kpi_observation",{target_kpi_id:String(form.get("kpi_id")||""),target_project_id:projectId,input_payload:{value:String(form.get("value")||""),observed_at:String(form.get("observed_at")||"")||undefined,source_ref:String(form.get("source_ref")||""),confidence:String(form.get("confidence")||"C")}});if(error){setMessage(error.message);return;}refresh("Immutable KPI observation recorded with definition/calculation provenance.");}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Analytics runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Active KPI Definitions",String(active.length).padStart(2,"0")],["Latest Observations",String(latest.length).padStart(2,"0")],["Critical Signals",String(critical).padStart(2,"0")],["Warning Signals",String(warning).padStart(2,"0")],["D-Confidence Latest",String(latest.filter(x=>x.confidence==="D").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live evidence state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Versioned KPI Definition</h3><form action={createDefinition}><div className="field-grid"><div className="field"><label>Code</label><input name="code" required placeholder="KPI-COST"/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Domain</label><input name="domain" required placeholder="cost / quality / cash / programme"/></div><div className="field"><label>Unit</label><input name="unit" required placeholder="% / days / count / INR"/></div><div className="field"><label>Direction</label><select name="direction"><option value="higher_is_better">Higher is better</option><option value="lower_is_better">Lower is better</option><option value="target_band">Target band</option></select></div><div className="field"><label>Target</label><input name="target" type="number" step="0.0001"/></div><div className="field"><label>Warning threshold</label><input name="warning_threshold" type="number" step="0.0001"/></div><div className="field"><label>Critical threshold</label><input name="critical_threshold" type="number" step="0.0001"/></div><div className="field"><label>Refresh cadence</label><input name="refresh_cadence" defaultValue="manual"/></div></div><div className="field"><label>Calculation reference</label><input name="calculation_ref" required placeholder="metric-spec://... or governed formula/report reference"/></div><button className="btn">Create Definition Version</button></form></section>
   <section className="panel"><h3>Record Observation</h3><form action={observe}><div className="field"><label>KPI</label><select name="kpi_id" required>{active.map(d=><option key={d.id} value={d.id}>{d.code} v{d.version} · {d.name}</option>)}</select></div><div className="field-grid"><div className="field"><label>Project</label><select name="project_id"><option value="">Organisation level</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Value</label><input name="value" type="number" step="0.0001" required/></div><div className="field"><label>Observed at</label><input name="observed_at" type="datetime-local"/></div><div className="field"><label>Confidence</label><select name="confidence" defaultValue="C"><option>A</option><option>B</option><option>C</option><option>D</option></select></div></div><div className="field"><label>Source reference</label><input name="source_ref" required placeholder="report / query / approved document / ledger snapshot"/></div><button className="btn ghost" disabled={active.length===0}>Record Observation</button></form>{active.length===0&&<div className="note" style={{marginTop:8}}>No active KPI definition exists. The dashboard remains empty rather than inventing values.</div>}</section>
  </div>
  <section className="panel"><h3>Latest Decision Metrics</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>KPI</th><th>Scope</th><th>Value</th><th>Target / Thresholds</th><th>Signal</th><th>Confidence</th><th>Source / Calculation</th><th>Observed</th></tr></thead><tbody>{latest.map(x=><tr key={`${x.kpi_id}-${x.project_id||"org"}`}><td><b>{x.code}</b><div className="subtle">{x.name} · v{x.definition_version}</div></td><td>{projectName(x.project_id)}</td><td>{Number(x.value).toLocaleString("en-IN")} {x.unit}</td><td>{x.target??"—"}<div className="subtle">W {x.warning_threshold??"—"} · C {x.critical_threshold??"—"}</div></td><td><span className="badge">{pretty(signal(x))}</span></td><td><span className="badge">{x.confidence}</span></td><td>{x.source_ref}<div className="subtle">{x.calculation_ref} · <code>{shortHash(x.observation_hash)}</code></div></td><td>{new Date(x.observed_at).toLocaleString("en-IN")}</td></tr>)}{latest.length===0&&<tr><td colSpan={8} className="subtle">No KPI observations exist yet.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Definition Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Domain</th><th>Version</th><th>Direction</th><th>Calculation</th><th>State</th></tr></thead><tbody>{definitions.map(d=><tr key={d.id}><td>{d.code}</td><td>{d.name}</td><td>{d.domain}</td><td>v{d.version}</td><td>{pretty(d.direction)}</td><td>{d.calculation_ref}<div className="subtle"><code>{shortHash(d.configuration_hash)}</code></div></td><td><span className="badge">{d.active?"active":"superseded"}</span></td></tr>)}{definitions.length===0&&<tr><td colSpan={7} className="subtle">No KPI definitions exist yet.</td></tr>}</tbody></table></div></section>
 </>;
}
