"use client";
import {useRouter} from "next/navigation";
import {useState,useTransition} from "react";
import {createClient} from "@/lib/supabase";

type ApiCredential={id:string;name:string;key_prefix:string;scopes:string[];project_restrictions:string[];allowed_ip_cidrs:string[];expires_at?:string|null;revoked_at?:string|null;created_at:string;last_used_at?:string|null;rate_limit_per_minute:number;rotated_from_id?:string|null};
type ProviderInstance={id:string;provider_key:string;environment:string;status:string;enabled:boolean;verified_at?:string|null;last_health_check_at?:string|null;last_health_status?:string|null;circuit_open_until?:string|null;failure_threshold?:number|null};
type Subscription={id:string;subscriber_key:string;event_pattern:string;endpoint_ref?:string|null;enabled:boolean;max_attempts:number;allowed_criticalities:string[];filter:Record<string,unknown>;subscription_hash?:string|null;created_at:string};
type Delivery={id:string;event_id:string;subscription_id:string;status:string;attempt_count:number;idempotency_key:string;next_attempt_at?:string|null;delivered_at?:string|null;response_code?:number|null;error_code?:string|null;created_at:string};
type Webhook={id:string;provider_key:string;environment:string;provider_event_id?:string|null;event_type?:string|null;signature_valid:boolean;payload_hash:string;processing_status:string;error?:unknown;correlation_id:string;received_at:string;processed_at?:string|null};
type EventDef={id:string;event_type:string;latest_version:number;owner_domain:string;description:string;pii_classification:string;default_criticality:string;retention_days:number;replayable:boolean;enabled:boolean};
type ContractVersion={id:string;major_version:number;minor_version:number;compatibility_mode:string;breaking_change:boolean;status:string;schema_hash:string;created_by:string;published_at?:string|null};
type DataContract={id:string;contract_key:string;producer:string;description:string;status:string;versions:ContractVersion[]};
export type ApiIntegrationState={credentials:ApiCredential[];instances:ProviderInstance[];subscriptions:Subscription[];deliveries:Delivery[];webhooks:Webhook[];event_definitions:EventDef[];data_contracts:DataContract[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
export default function ApiIntegrationGovernanceClient({organisationId,state,view}:{organisationId:string;state:ApiIntegrationState;view:"api"|"events"|"monitor"}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [oneTimeSecret,setOneTimeSecret]=useState<{secret:string;key_prefix:string;credential_id:string}|null>(null);const [busy,startTransition]=useTransition();
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 async function rpc(name:string,args:Record<string,unknown>,ok:string){const {data,error}=await supabase.rpc(name,args);if(error){setMessage(error.message);return null;}refresh(ok);return data;}
 async function issue(fd:FormData){const data=await rpc("issue_api_credential",{target_organisation_id:organisationId,input_payload:{name:String(fd.get("name")||""),scopes:String(fd.get("scopes")||"").split(",").map(v=>v.trim()).filter(Boolean),project_restrictions:String(fd.get("projects")||"").split(",").map(v=>v.trim()).filter(Boolean),allowed_ip_cidrs:String(fd.get("ips")||"").split(",").map(v=>v.trim()).filter(Boolean),expires_at:fd.get("expires_at")?new Date(String(fd.get("expires_at"))).toISOString():null,rate_limit_per_minute:String(fd.get("rate")||"60")}},"API credential issued. The raw secret is shown once only.");if(data){const d=data as {secret:string;key_prefix:string;credential_id:string};setOneTimeSecret(d);}}
 async function revoke(fd:FormData){await rpc("revoke_api_credential",{target_credential_id:String(fd.get("credential_id")),target_reason:String(fd.get("reason")||"")},"API credential revoked immediately.");}
 async function rotate(fd:FormData){const data=await rpc("rotate_api_credential",{target_credential_id:String(fd.get("credential_id")),target_reason:String(fd.get("reason")||"")},"API credential rotated; prior credential is revoked.");if(data){const d=data as {secret:string;key_prefix:string;credential_id:string};setOneTimeSecret(d);}}
 async function subscribe(fd:FormData){let filter:Record<string,unknown>={};try{filter=JSON.parse(String(fd.get("filter")||"{}"));}catch{setMessage("Subscription filter must be valid JSON.");return;}await rpc("create_event_subscription",{target_organisation_id:organisationId,input_payload:{subscriber_key:String(fd.get("subscriber_key")||""),event_pattern:String(fd.get("event_pattern")||""),endpoint_ref:String(fd.get("endpoint_ref")||""),secret_ref:String(fd.get("secret_ref")||""),filter,allowed_criticalities:String(fd.get("criticalities")||"C0,C1,C2").split(",").map(v=>v.trim()).filter(Boolean),max_attempts:String(fd.get("max_attempts")||"8")}},"Event subscription created with secret reference only.");}
 async function toggle(fd:FormData){await rpc("set_event_subscription_enabled",{target_subscription_id:String(fd.get("subscription_id")),target_enabled:String(fd.get("enabled"))==="true",target_reason:String(fd.get("reason")||"")},"Subscription state updated.");}
 async function registerEvent(fd:FormData){await rpc("register_event_definition",{input_payload:{event_type:String(fd.get("event_type")||""),latest_version:String(fd.get("version")||"1"),owner_domain:String(fd.get("owner_domain")||""),description:String(fd.get("description")||""),pii_classification:String(fd.get("pii")||"none"),default_criticality:String(fd.get("criticality")||"C1"),retention_days:String(fd.get("retention")||"2555"),replayable:fd.get("replayable")==="on"}},"Domain event registered.");}
 async function createContract(fd:FormData){let schema:Record<string,unknown>;try{schema=JSON.parse(String(fd.get("schema")||"{}"));}catch{setMessage("Data contract schema must be valid JSON.");return;}await rpc("create_data_contract_version",{input_payload:{contract_key:String(fd.get("contract_key")||""),producer:String(fd.get("producer")||""),description:String(fd.get("description")||""),major_version:String(fd.get("major")||"1"),minor_version:String(fd.get("minor")||"0"),compatibility_mode:String(fd.get("compatibility")||"backward"),schema_definition:schema}},"Data contract draft created; compatibility evaluated against the latest published version.");}
 async function publishContract(fd:FormData){await rpc("publish_data_contract_version",{target_version_id:String(fd.get("version_id")),target_reason:String(fd.get("reason")||"")},"Data contract version published after compatibility gate.");}
 async function deprecateContract(fd:FormData){await rpc("deprecate_data_contract_version",{target_version_id:String(fd.get("version_id")),target_deprecation_at:new Date(String(fd.get("deprecation_at"))).toISOString(),target_reason:String(fd.get("reason")||"")},"Data contract version deprecated with an explicit future window.");}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Integration Governance:</b> {message}{busy?" Refreshing…":""}</div>}
  {oneTimeSecret&&<div className="note" style={{marginBottom:16,border:"2px solid currentColor"}}><b>One-time API secret</b><p className="subtle">Copy this value now. It is not stored in retrievable form and will not appear after refresh.</p><code style={{wordBreak:"break-all"}}>{oneTimeSecret.secret}</code><div className="subtle">Prefix {oneTimeSecret.key_prefix} · credential {oneTimeSecret.credential_id}</div><button className="btn ghost" style={{marginTop:8}} onClick={()=>setOneTimeSecret(null)}>I have stored it securely</button></div>}
  {view==="api"&&<>
   <div className="kpis">{[["Active Credentials",String(state.credentials.filter(c=>!c.revoked_at&&(!c.expires_at||new Date(c.expires_at)>new Date())).length)],["Revoked",String(state.credentials.filter(c=>c.revoked_at).length)],["Scoped Subscriptions",String(state.subscriptions.length)],["Provider Instances",String(state.instances.length)],["API Audit Boundary","Hash only"]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>10?18:30}}>{v}</div><div className="subtle">Live governed state</div></div>)}</div>
   <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Issue Scoped API Credential</h3><form action={issue} style={{display:"grid",gap:8}}><input name="name" required placeholder="Credential name"/><input name="scopes" required placeholder="Scopes, comma separated e.g. project:read,document:read"/><input name="projects" placeholder="Optional allowed project UUIDs"/><input name="ips" placeholder="Optional allowed IP CIDRs"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input name="expires_at" type="datetime-local"/><input name="rate" type="number" min="1" max="100000" defaultValue="60"/></div><button className="btn">Issue Credential</button></form></section><section className="panel"><h3>Credential Policy</h3><p className="subtle">Blanket scopes are rejected. Secrets are generated server-side, shown once, stored only as SHA-256, restricted by optional project/IP scope, expiry and rate limit, and become invalid immediately on revocation.</p></section></div>
   <section className="panel"><h3>API Credentials</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Name / Prefix</th><th>Scopes</th><th>Restrictions</th><th>Expiry / Last Used</th><th>State</th><th>Governance</th></tr></thead><tbody>{state.credentials.map(c=><tr key={c.id}><td><b>{c.name}</b><div className="subtle"><code>{c.key_prefix}</code></div></td><td>{c.scopes.join(", ")}</td><td>{c.project_restrictions.length?`${c.project_restrictions.length} project(s)`:"All authorised projects"}<div className="subtle">{c.rate_limit_per_minute}/min</div></td><td>{c.expires_at?new Date(c.expires_at).toLocaleString("en-IN"):"No expiry"}<div className="subtle">Last used {c.last_used_at?new Date(c.last_used_at).toLocaleString("en-IN"):"never"}</div></td><td><span className="badge">{c.revoked_at?"revoked":c.expires_at&&new Date(c.expires_at)<=new Date()?"expired":"active"}</span></td><td>{!c.revoked_at&&<div style={{display:"grid",gap:5,minWidth:210}}><form action={rotate} style={{display:"flex",gap:5}}><input type="hidden" name="credential_id" value={c.id}/><input name="reason" required placeholder="Rotation reason"/><button className="btn ghost">Rotate</button></form><form action={revoke} style={{display:"flex",gap:5}}><input type="hidden" name="credential_id" value={c.id}/><input name="reason" required placeholder="Revocation reason"/><button className="btn ghost">Revoke</button></form></div>}</td></tr>)}{state.credentials.length===0&&<tr><td colSpan={6} className="subtle">No API credentials are configured for this organisation.</td></tr>}</tbody></table></div></section>
  </>}
  {view==="events"&&<>
   <div className="panel-grid"><section className="panel"><h3>Register Domain Event</h3><form action={registerEvent} style={{display:"grid",gap:8}}><input name="event_type" required placeholder="event.type"/><input name="owner_domain" required placeholder="Owner domain"/><textarea name="description" required placeholder="Purpose and payload semantics"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input name="version" type="number" min="1" defaultValue="1"/><select name="criticality" defaultValue="C1">{["C0","C1","C2","C3","C4"].map(v=><option key={v}>{v}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><select name="pii"><option>none</option><option>limited</option><option>sensitive</option></select><input name="retention" type="number" min="1" defaultValue="2555"/></div><label><input type="checkbox" name="replayable" defaultChecked/> Replayable</label><button className="btn">Register Event</button></form></section><section className="panel"><h3>Create Event Subscription</h3><form action={subscribe} style={{display:"grid",gap:8}}><input name="subscriber_key" required placeholder="Subscriber key"/><input name="event_pattern" required placeholder="Event pattern"/><input name="endpoint_ref" required placeholder="Endpoint reference, not raw credential"/><input name="secret_ref" required placeholder="Secret-manager reference"/><input name="criticalities" defaultValue="C0,C1,C2"/><input name="max_attempts" type="number" min="1" defaultValue="8"/><textarea name="filter" defaultValue="{}"/><button className="btn">Create Subscription</button></form></section></div>
   <section className="panel"><h3>Domain Event Registry</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Event</th><th>Version</th><th>Owner</th><th>PII</th><th>Criticality</th><th>Retention</th><th>Replay</th></tr></thead><tbody>{state.event_definitions.map(e=><tr key={e.id}><td><b>{e.event_type}</b><div className="subtle">{e.description}</div></td><td>{e.latest_version}</td><td>{e.owner_domain}</td><td>{e.pii_classification}</td><td>{e.default_criticality}</td><td>{e.retention_days}d</td><td>{e.replayable?"yes":"no"}</td></tr>)}{state.event_definitions.length===0&&<tr><td colSpan={7} className="subtle">No registered events.</td></tr>}</tbody></table></div></section>
   <section className="panel"><h3>Event Subscriptions</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Subscriber</th><th>Pattern</th><th>Endpoint</th><th>Criticality</th><th>State</th><th>Action</th></tr></thead><tbody>{state.subscriptions.map(s=><tr key={s.id}><td><b>{s.subscriber_key}</b><div className="subtle"><code>{short(s.subscription_hash)}</code></div></td><td>{s.event_pattern}</td><td>{s.endpoint_ref||"—"}</td><td>{s.allowed_criticalities.join(", ")}</td><td><span className="badge">{s.enabled?"enabled":"paused"}</span></td><td><form action={toggle} style={{display:"flex",gap:5}}><input type="hidden" name="subscription_id" value={s.id}/><input type="hidden" name="enabled" value={String(!s.enabled)}/><input name="reason" required placeholder="Reason"/><button className="btn ghost">{s.enabled?"Pause":"Enable"}</button></form></td></tr>)}{state.subscriptions.length===0&&<tr><td colSpan={6} className="subtle">No event subscriptions configured.</td></tr>}</tbody></table></div></section>
   <div className="panel-grid"><section className="panel"><h3>Draft Data Contract Version</h3><form action={createContract} style={{display:"grid",gap:8}}><input name="contract_key" required placeholder="Contract key"/><input name="producer" required placeholder="Producer"/><input name="description" required placeholder="Description"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input name="major" type="number" min="1" defaultValue="1"/><input name="minor" type="number" min="0" defaultValue="0"/></div><select name="compatibility"><option>backward</option><option>none</option></select><textarea name="schema" rows={8} defaultValue={'{"type":"object","properties":{},"required":[]}'}/><button className="btn">Evaluate & Draft</button></form></section><section className="panel"><h3>Compatibility Gate</h3><p className="subtle">Removing a property, changing a property type, or adding a newly required field is classified as breaking. A breaking draft cannot publish unless its major version exceeds the latest published major version.</p></section></div>
   <section className="panel"><h3>Data Contract Registry</h3><div style={{display:"grid",gap:10}}>{state.data_contracts.map(c=><div className="note" key={c.id}><b>{c.contract_key}</b> · {c.producer} · <span className="badge">{pretty(c.status)}</span><div className="subtle">{c.description}</div><div style={{display:"grid",gap:7,marginTop:8}}>{c.versions.map(v=><div key={v.id} style={{borderTop:"1px solid var(--line)",paddingTop:7}}><b>v{v.major_version}.{v.minor_version}</b> · {pretty(v.status)} · {v.breaking_change?"BREAKING":"compatible"} · <code>{short(v.schema_hash)}</code>{v.status==="draft"&&<form action={publishContract} style={{display:"flex",gap:5,marginTop:5}}><input type="hidden" name="version_id" value={v.id}/><input name="reason" required placeholder="Independent publish reason"/><button className="btn ghost">Publish</button></form>}{v.status==="published"&&<form action={deprecateContract} style={{display:"flex",gap:5,marginTop:5,flexWrap:"wrap"}}><input type="hidden" name="version_id" value={v.id}/><input name="deprecation_at" type="datetime-local" required/><input name="reason" required placeholder="Deprecation reason"/><button className="btn ghost">Deprecate</button></form>}</div>)}</div></div>)}{state.data_contracts.length===0&&<div className="note">No data contracts registered.</div>}</div></section>
  </>}
  {view==="monitor"&&<>
   <div className="kpis">{[["Provider Instances",String(state.instances.length)],["Degraded Providers",String(state.instances.filter(i=>i.status==="degraded").length)],["Webhook Failures",String(state.webhooks.filter(w=>!w.signature_valid||w.processing_status==="failed").length)],["Delivery Failures",String(state.deliveries.filter(d=>d.status==="failed"||d.status==="dead_letter").length)],["Open Circuits",String(state.instances.filter(i=>i.circuit_open_until&&new Date(i.circuit_open_until)>new Date()).length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live provider state</div></div>)}</div>
   <section className="panel" style={{marginTop:16}}><h3>Provider Instances</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Provider</th><th>Environment</th><th>State</th><th>Health</th><th>Circuit</th><th>Verified</th></tr></thead><tbody>{state.instances.map(i=><tr key={i.id}><td><b>{i.provider_key}</b></td><td>{i.environment}</td><td><span className="badge">{pretty(i.status)}</span></td><td>{pretty(i.last_health_status)}<div className="subtle">{i.last_health_check_at?new Date(i.last_health_check_at).toLocaleString("en-IN"):"never checked"}</div></td><td>{i.circuit_open_until&&new Date(i.circuit_open_until)>new Date()?`OPEN until ${new Date(i.circuit_open_until).toLocaleString("en-IN")}`:"closed"}</td><td>{i.verified_at?new Date(i.verified_at).toLocaleString("en-IN"):"—"}</td></tr>)}{state.instances.length===0&&<tr><td colSpan={6} className="subtle">No provider instances configured.</td></tr>}</tbody></table></div></section>
   <div className="panel-grid"><section className="panel"><h3>Webhook Evidence</h3><div style={{display:"grid",gap:8}}>{state.webhooks.slice(0,30).map(w=><div className="note" key={w.id}><b>{w.provider_key} · {w.event_type||"event"}</b> <span className="badge">{pretty(w.processing_status)}</span><div className="subtle">Signature {w.signature_valid?"verified":"INVALID"} · hash <code>{short(w.payload_hash)}</code> · trace {w.correlation_id.slice(0,12)}…</div></div>)}{state.webhooks.length===0&&<div className="note">No webhook receipts recorded.</div>}</div></section><section className="panel"><h3>Event Delivery / DLQ</h3><div style={{display:"grid",gap:8}}>{state.deliveries.slice(0,30).map(d=><div className="note" key={d.id}><b>{pretty(d.status)}</b> · attempts {d.attempt_count}<div className="subtle">Idempotency <code>{d.idempotency_key}</code>{d.error_code?` · ${d.error_code}`:""}</div></div>)}{state.deliveries.length===0&&<div className="note">No event deliveries recorded.</div>}</div></section></div>
  </>}
 </>;
}
