"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type Pack={id:string;code:string;name:string;typology:string;version:number;questionnaire:Array<{code:string;question:string}>;pack_hash:string};
type Brief={id:string;version:number;source_type:string;raw_input:string;structured_draft:Record<string,unknown>;status:string;input_hash:string;confirmed_hash?:string|null;created_at:string};
type ProgrammeBrief={id:string;version:number;status:string;client_priorities:unknown;exclusions:unknown;target_efficiency?:number|null;target_built_up_area?:number|null;budget_band?:string|null;approved_at?:string|null};
type Requirement={id:string;code:string;statement:string;category:string;acceptance_criteria:unknown;criticality:string;version:number;approval_state:string;requirement_hash?:string|null;approved_at?:string|null};
type Trace={id:string;requirement_id:string;resource_type:string;resource_ref:string;evidence_hash?:string|null;created_at:string};
export type BriefRequirementWorkspace={typology_packs:Pack[];briefs:Brief[];programme_briefs:ProgrammeBrief[];requirements:Requirement[];revisions:unknown[];trace_links:Trace[]};

function parseJson(value:FormDataEntryValue|null,fallback:unknown){try{return JSON.parse(String(value||""));}catch{return fallback;}}
export default function BriefRequirementsClient({projectId,state}:{projectId:string;state:BriefRequirementWorkspace}){
 const router=useRouter();const supabase=createClient();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const refresh=()=>startTransition(()=>router.refresh());
 async function interpret(form:FormData){const structured=parseJson(form.get("structured_draft"),null);if(!structured||typeof structured!=="object"||Array.isArray(structured)){setMessage("Structured draft must be valid JSON object.");return;}setMessage("Recording draft interpretation…");const {error}=await supabase.rpc("interpret_project_brief",{target_project_id:projectId,input_payload:{source_type:String(form.get("source_type")||"text"),typology_pack_id:String(form.get("typology_pack_id")||""),raw_input:String(form.get("raw_input")||""),structured_draft:structured}});if(error){setMessage(error.message);return;}setMessage("Draft interpretation recorded. It has not become an approved brief until a human confirms it.");refresh();}
 async function confirm(id:string){const reason=window.prompt("Reason for human confirmation");if(!reason)return;setMessage("Confirming brief and creating approved programme brief…");const {error}=await supabase.rpc("confirm_project_brief",{target_brief_id:id,input_payload:{},target_reason:reason});if(error){setMessage(error.message);return;}setMessage("Brief confirmed and prior approved brief superseded with history retained.");refresh();}
 async function createRequirement(form:FormData){const criteria=parseJson(form.get("acceptance_criteria"),null);if(!Array.isArray(criteria)){setMessage("Acceptance criteria must be a JSON array.");return;}setMessage("Creating draft requirement…");const {error}=await supabase.rpc("create_project_requirement",{target_project_id:projectId,input_payload:{code:String(form.get("code")||""),statement:String(form.get("statement")||""),category:String(form.get("category")||""),acceptance_criteria:criteria,criticality:String(form.get("criticality")||"C1")}});if(error){setMessage(error.message);return;}setMessage("Draft requirement created.");refresh();}
 async function approveRequirement(id:string){const reason=window.prompt("Requirement approval reason");if(!reason)return;setMessage("Approving exact requirement revision…");const {error}=await supabase.rpc("approve_project_requirement",{target_requirement_id:id,target_reason:reason});if(error){setMessage(error.message);return;}setMessage("Requirement approved and dependent compiler runs invalidated for re-evaluation.");refresh();}
 async function reviseRequirement(form:FormData){const disciplines=String(form.get("affected_disciplines")||"").split(",").map(x=>x.trim()).filter(Boolean);if(!disciplines.length){setMessage("At least one affected discipline is required.");return;}const reason=String(form.get("reason")||"").trim();if(!reason){setMessage("Revision reason is required.");return;}setMessage("Creating requirement revision and running downstream change impact…");const {data,error}=await supabase.rpc("revise_project_requirement",{target_requirement_id:String(form.get("requirement_id")||""),input_payload:{statement:String(form.get("statement")||"")||undefined,affected_disciplines:disciplines},target_reason:reason});if(error){setMessage(error.message);return;}setMessage(`Revision created with governed downstream impact ${String((data as {change_impact_id?:string})?.change_impact_id||"").slice(0,8)}.`);refresh();}
 async function linkTrace(form:FormData){const hash=String(form.get("evidence_hash")||"").trim();setMessage("Linking requirement trace…");const {error}=await supabase.rpc("link_requirement_trace",{target_requirement_id:String(form.get("requirement_id")||""),target_resource_type:String(form.get("resource_type")||""),target_resource_ref:String(form.get("resource_ref")||""),target_evidence_hash:hash||null});if(error){setMessage(error.message);return;}setMessage("Requirement trace linked and audited.");refresh();}
 return <>
  {message&&<div className="note" role="status" style={{marginBottom:16}}><b>Brief & Requirements:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Typology Packs",state.typology_packs.length],["Brief Versions",state.briefs.length],["Approved Briefs",state.programme_briefs.filter(x=>x.status==="approved").length],["Requirements",state.requirements.length],["Trace Links",state.trace_links.length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:18}}><section className="panel"><h3>Interpret Brief</h3><form action={interpret}><div className="field"><label>Source type</label><select name="source_type"><option value="text">Text</option><option value="voice">Voice transcript</option><option value="document">Document extraction</option><option value="meeting">Meeting record</option></select></div><div className="field"><label>Typology pack</label><select name="typology_pack_id" required defaultValue=""><option value="" disabled>Select pack</option>{state.typology_packs.map(p=><option value={p.id} key={p.id}>{p.name} v{p.version}</option>)}</select></div><div className="field"><label>Raw brief evidence</label><textarea name="raw_input" rows={7} required/></div><div className="field"><label>Structured draft JSON</label><textarea name="structured_draft" rows={8} defaultValue={'{"priorities":[],"exclusions":[]}'}/></div><button className="btn">Record Draft</button></form></section><section className="panel"><h3>Typology Questionnaires</h3>{state.typology_packs.map(p=><div key={p.id} className="note" style={{marginBottom:12}}><b>{p.name}</b><div className="subtle">Pack hash {p.pack_hash?.slice(0,12)}…</div><ol>{(p.questionnaire||[]).map(q=><li key={q.code}>{q.question}</li>)}</ol></div>)}</section></div>
  <section className="panel" style={{marginTop:18}}><h3>Brief Interpretation History</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Version</th><th>Source</th><th>Status</th><th>Input hash</th><th>Confirmation</th></tr></thead><tbody>{state.briefs.map(b=><tr key={b.id}><td>v{b.version}</td><td>{b.source_type}</td><td><span className="badge">{b.status}</span></td><td><code>{b.input_hash.slice(0,12)}…</code></td><td>{b.status==="draft"?<button className="btn ghost" onClick={()=>confirm(b.id)}>Human Confirm</button>:b.confirmed_hash?<code>{b.confirmed_hash.slice(0,12)}…</code>:"—"}</td></tr>)}{!state.briefs.length&&<tr><td colSpan={5} className="subtle">No brief interpretation has been recorded.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid" style={{marginTop:18}}><section className="panel"><h3>Create Requirement</h3><form action={createRequirement}><div className="field"><label>Code</label><input name="code" required placeholder="REQ-001"/></div><div className="field"><label>Statement</label><textarea name="statement" rows={4} required/></div><div className="field-grid"><div className="field"><label>Category</label><input name="category" required/></div><div className="field"><label>Criticality</label><select name="criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div></div><div className="field"><label>Acceptance criteria JSON array</label><textarea name="acceptance_criteria" rows={5} defaultValue="[]"/></div><button className="btn">Create Draft</button></form></section><section className="panel"><h3>Revise Approved Requirement</h3><form action={reviseRequirement}><div className="field"><label>Requirement</label><select name="requirement_id" required defaultValue=""><option value="" disabled>Select approved requirement</option>{state.requirements.filter(r=>r.approval_state==="approved").map(r=><option value={r.id} key={r.id}>{r.code} · v{r.version}</option>)}</select></div><div className="field"><label>Revised statement</label><textarea name="statement" rows={4}/></div><div className="field"><label>Affected disciplines</label><input name="affected_disciplines" required placeholder="architecture, structure, mepf"/></div><div className="field"><label>Reason</label><textarea name="reason" rows={3} required/></div><button className="btn">Revise + Analyse Impact</button></form></section></div>
  <section className="panel" style={{marginTop:18}}><h3>Requirements Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Requirement</th><th>Category</th><th>Criticality</th><th>Version</th><th>Approval</th><th>Hash</th><th></th></tr></thead><tbody>{state.requirements.map(r=><tr key={r.id}><td><b>{r.code}</b><br/><span className="subtle">{r.statement}</span></td><td>{r.category}</td><td>{r.criticality}</td><td>v{r.version}</td><td><span className="badge">{r.approval_state}</span></td><td>{r.requirement_hash?<code>{r.requirement_hash.slice(0,12)}…</code>:"—"}</td><td>{r.approval_state==="draft"&&<button className="btn ghost" onClick={()=>approveRequirement(r.id)}>Approve</button>}</td></tr>)}{!state.requirements.length&&<tr><td colSpan={7} className="subtle">No requirements recorded.</td></tr>}</tbody></table></div></section>
  <section className="panel" style={{marginTop:18}}><h3>Requirement Traceability</h3><form action={linkTrace}><div className="field-grid"><div className="field"><label>Requirement</label><select name="requirement_id" required defaultValue=""><option value="" disabled>Select</option>{state.requirements.map(r=><option value={r.id} key={r.id}>{r.code}</option>)}</select></div><div className="field"><label>Resource type</label><select name="resource_type"><option value="model_object">Model object</option><option value="drawing">Drawing</option><option value="test">Test</option><option value="document">Document</option><option value="model">Model</option><option value="calculation">Calculation</option><option value="boq">BOQ</option><option value="task">Task</option><option value="release">Release</option></select></div><div className="field"><label>Resource reference</label><input name="resource_ref" required/></div><div className="field"><label>Evidence SHA-256 (optional)</label><input name="evidence_hash" pattern="[0-9a-fA-F]{64}"/></div></div><button className="btn">Link Trace</button></form><div style={{overflowX:"auto",marginTop:16}}><table className="table"><thead><tr><th>Requirement</th><th>Type</th><th>Reference</th><th>Evidence</th></tr></thead><tbody>{state.trace_links.map(l=><tr key={l.id}><td>{state.requirements.find(r=>r.id===l.requirement_id)?.code||l.requirement_id.slice(0,8)}</td><td>{l.resource_type}</td><td>{l.resource_ref}</td><td>{l.evidence_hash?<code>{l.evidence_hash.slice(0,12)}…</code>:"—"}</td></tr>)}{!state.trace_links.length&&<tr><td colSpan={4} className="subtle">No requirement trace links recorded.</td></tr>}</tbody></table></div></section>
 </>;
}
