"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useState,useTransition} from "react";
import {createClient} from "@/lib/supabase";

type PermissionSet={view_documents?:boolean;download_documents?:boolean;approve?:boolean;view_commercial?:boolean;pay?:boolean;message?:boolean;ask_project?:boolean};
export type ClientPortalProject={id:string;code:string;name:string;typology:string;stage:string;status:string;jurisdiction_city?:string|null;jurisdiction_state?:string|null;jurisdiction_country?:string|null;access_id?:string|null;access_role:string;permissions:PermissionSet;access_mode:"client"|"internal"};
export type ClientPortalInvitation={access_id:string;project_id:string;project_code:string;project_name:string;role:string;status:string;invited_at:string;access_hash?:string|null};
type Stage={id:string;stage_code:string;title:string;sequence:number;state:string;planned_start?:string|null;planned_finish?:string|null;actual_start?:string|null;actual_finish?:string|null};
type Approval={id:string;resource_type:string;resource_id:string;requested_resource_hash?:string|null;role_required?:string|null;criticality:string;decision:string;comments?:string|null;requested_at:string;decided_at?:string|null;decision_evidence_hash?:string|null};
type DocumentRow={id:string;document_number:string;title:string;discipline:string;document_type:string;status:string;revision:string;checksum:string;share_rights?:Record<string,unknown>};
type InvoiceRow={id:string;invoice_number:string;status:string;currency:string;issue_date:string;due_date:string;subtotal:number;tax:number;total:number;amount_paid:number;outstanding:number};
type PaymentRow={id:string;reference:string;amount_minor:number;currency:string;status:string;created_at:string};
type RiskRow={id:string;code:string;title:string;category:string;description:string;inherent_level:string;residual_level?:string|null;status:string;review_due_at?:string|null};
type ReleaseRow={id:string;package_type:string;package_reference:string;content_hash:string;state:string;issued_at?:string|null};
type ContractRow={id?:string;version?:number;status?:string;contract_type?:string|null;jurisdiction?:string|null;effective_at?:string|null;expires_at?:string|null;execution_hash?:string|null};
export type ClientPortalWorkspace={project:{id:string;code:string;name:string;typology:string;stage:string;status:string;city?:string|null;state?:string|null;country?:string|null};access:{mode:"client"|"internal";access_id?:string|null;role:string;permissions:PermissionSet};stages:Stage[];approvals:Approval[];documents:DocumentRow[];contract:ContractRow;invoices:InvoiceRow[];payments:PaymentRow[];risks:RiskRow[];releases:ReleaseRow[]};

const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const money=(amount:number,currency="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:0}).format(Number(amount||0));

export default function ClientPortalWorkspaceClient({projects,invitations,projectId,state,basePath}:{projects:ClientPortalProject[];invitations:ClientPortalInvitation[];projectId?:string;state?:ClientPortalWorkspace|null;basePath:string}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [payment,setPayment]=useState<{invoice_number:string;currency:string;amount_minor:number;receipt:string;idempotency_key:string}|null>(null);const [busy,startTransition]=useTransition();
 const permissions=state?.access.permissions||{};const approvals=state?.approvals||[];const invoices=state?.invoices||[];const risks=state?.risks||[];const releases=state?.releases||[];
 const pending=approvals.filter(a=>a.decision==="pending").length;const due=invoices.filter(i=>["issued","part_paid","overdue"].includes(i.status)&&Number(i.outstanding)>0).length;const critical=risks.filter(r=>["critical","high"].includes(r.inherent_level)&&r.status!=="closed").length;
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function activate(accessId:string){const {error}=await supabase.rpc("activate_client_portal_access",{target_access_id:accessId});if(error){setMessage(error.message);return;}refresh("Client access activated against your authenticated email identity.");}
 async function decide(form:FormData){const {error}=await supabase.rpc("decide_client_project_approval",{target_approval_id:String(form.get("approval_id")||""),target_decision:String(form.get("decision")||""),target_comments:String(form.get("comments")||"")});if(error){setMessage(error.message);return;}refresh("Decision recorded against the exact pinned submission revision.");}
 async function preparePayment(invoice:InvoiceRow){const {data,error}=await supabase.rpc("prepare_client_invoice_payment",{target_invoice_id:invoice.id});if(error){setMessage(error.message);return;}setPayment(data as {invoice_number:string;currency:string;amount_minor:number;receipt:string;idempotency_key:string});setMessage("Payment handoff prepared and audited. No funds are captured until the configured payment provider completes the transaction.");}
 return <>
  {invitations.length>0&&<section className="panel"><h3>Pending Client Invitations</h3><div style={{display:"grid",gap:10}}>{invitations.map(inv=><div className="note" key={inv.access_id} style={{display:"flex",gap:12,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><div><b>{inv.project_code} · {inv.project_name}</b><div className="subtle">Role: {pretty(inv.role)} · invited {new Date(inv.invited_at).toLocaleString("en-IN")}</div></div><button className="btn" disabled={busy} onClick={()=>activate(inv.access_id)}>Activate Access</button></div>)}</div></section>}
  {message&&<div className="note" style={{marginBottom:16}}><b>Client Portal:</b> {message}{busy?" Refreshing…":""}</div>}
  <section className="panel"><h3>Projects</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`${basePath}?project=${p.id}`} className={projectId===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{projects.length===0&&invitations.length===0&&<div className="note">No active client project access is linked to this identity.</div>}</section>
  {state&&<>
   <div className="topbar" style={{marginTop:16}}><div><div className="demo">Client Portal / Controlled Project View</div><h1>{state.project.name}</h1><div className="subtle">{state.project.code} · {state.project.typology} · {pretty(state.project.stage)} · access: {pretty(state.access.role)}</div></div>{permissions.ask_project&&<Link className="btn ghost" href={`${basePath}/ask?project=${state.project.id}`}>Ask Your Project</Link>}</div>
   <div className="kpis">{[["Project Stage",pretty(state.project.stage)],["Open Decisions",String(pending).padStart(2,"0")],["Invoices Due",String(due).padStart(2,"0")],["Client Risks",String(critical).padStart(2,"0")],["Issued Releases",String(releases.length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>12?18:30}}>{v}</div><div className="subtle">Live authorised state</div></div>)}</div>
   <div className="panel-grid" style={{marginTop:16}}>
    <section className="panel"><h3>Project Journey</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Stage</th><th>State</th><th>Planned</th><th>Actual</th></tr></thead><tbody>{state.stages.map(s=><tr key={s.id}><td><b>{s.title}</b><div className="subtle">{s.stage_code}</div></td><td><span className="badge">{pretty(s.state)}</span></td><td>{s.planned_start||"—"} → {s.planned_finish||"—"}</td><td>{s.actual_start||"—"} → {s.actual_finish||"—"}</td></tr>)}{state.stages.length===0&&<tr><td colSpan={4} className="subtle">No governed project stages have been activated yet.</td></tr>}</tbody></table></div></section>
    <section className="panel"><h3>Client Authority</h3><p className="subtle">Only client-targeted decisions appear here. Internal WIP, internal notes and unissued documents are not returned by this workspace.</p><div className="note"><b>Revision safety:</b> every approval is pinned to the exact submitted resource hash and is revalidated at decision time.</div></section>
   </div>
   <section className="panel"><h3>Approvals & Decisions</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Resource</th><th>Criticality</th><th>Authority</th><th>Pinned Revision</th><th>Status</th><th>Action</th></tr></thead><tbody>{approvals.map(a=><tr key={a.id}><td>{pretty(a.resource_type)}<div className="subtle">{a.resource_id.slice(0,8)}</div></td><td>{a.criticality}</td><td>{pretty(a.role_required)}</td><td><code>{shortHash(a.requested_resource_hash)}</code></td><td><span className="badge">{pretty(a.decision)}</span></td><td>{a.decision==="pending"&&state.access.mode==="client"&&permissions.approve&&a.requested_resource_hash?<form action={decide} style={{display:"grid",gap:6,minWidth:220}}><input type="hidden" name="approval_id" value={a.id}/><select name="decision" defaultValue="approved"><option value="approved">Approve exact revision</option><option value="approved_with_comments">Approve with comments</option><option value="rejected">Reject</option></select><input name="comments" placeholder="Decision comments"/><button className="btn ghost" style={{padding:8}}>Record Decision</button></form>:a.decision==="pending"?<div className="subtle">{state.access.mode==="internal"?"Use internal Approvals workspace for staff action.":"No approval authority for this access role."}</div>:<div className="subtle">{a.comments||`Decided ${a.decided_at?new Date(a.decided_at).toLocaleString("en-IN"):""}`}</div>}</td></tr>)}{approvals.length===0&&<tr><td colSpan={6} className="subtle">No client decisions are currently requested.</td></tr>}</tbody></table></div></section>
   {permissions.view_documents&&<section className="panel"><h3>Published Documents</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Document</th><th>Discipline</th><th>Type</th><th>Revision</th><th>Status</th><th>Checksum</th></tr></thead><tbody>{state.documents.map(d=><tr key={d.id}><td><b>{d.document_number}</b><div className="subtle">{d.title}</div></td><td>{d.discipline}</td><td>{pretty(d.document_type)}</td><td>{d.revision}</td><td><span className="badge">{d.status}</span></td><td><code>{shortHash(d.checksum)}</code></td></tr>)}{state.documents.length===0&&<tr><td colSpan={6} className="subtle">No published approved/issued documents are currently available.</td></tr>}</tbody></table></div></section>}
   {permissions.view_commercial&&<div className="panel-grid"><section className="panel"><h3>Commercial Status</h3>{state.contract?.id?<><div><b>Contract v{state.contract.version}</b> · <span className="badge">{pretty(state.contract.status)}</span></div><div className="subtle" style={{marginTop:8}}>Effective {state.contract.effective_at?new Date(state.contract.effective_at).toLocaleDateString("en-IN"):"—"} · Expires {state.contract.expires_at?new Date(state.contract.expires_at).toLocaleDateString("en-IN"):"—"}</div><div className="subtle">Execution hash <code>{shortHash(state.contract.execution_hash)}</code></div></>:<div className="subtle">No client-visible current contract is available.</div>}</section><section className="panel"><h3>Payment Boundary</h3><p className="subtle">The portal prepares an idempotent invoice payment handoff and records the action immediately. Provider order creation/capture remains a separate configured integration step.</p>{payment&&<div className="note"><b>{payment.invoice_number}</b> · {money(payment.amount_minor/100,payment.currency)}<div className="subtle">Receipt {payment.receipt} · {payment.idempotency_key}</div></div>}</section></div>}
   {permissions.view_commercial&&<section className="panel"><h3>Invoices</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Invoice</th><th>Issue / Due</th><th>Total</th><th>Paid</th><th>Outstanding</th><th>Status / Action</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><b>{i.invoice_number}</b></td><td>{i.issue_date}<div className="subtle">Due {i.due_date}</div></td><td>{money(i.total,i.currency)}</td><td>{money(i.amount_paid,i.currency)}</td><td>{money(i.outstanding,i.currency)}</td><td><span className="badge">{pretty(i.status)}</span>{state.access.mode==="client"&&permissions.pay&&["issued","part_paid","overdue"].includes(i.status)&&i.outstanding>0&&<div style={{marginTop:6}}><button className="btn ghost" style={{padding:8}} onClick={()=>preparePayment(i)}>Prepare Secure Payment</button></div>}</td></tr>)}{invoices.length===0&&<tr><td colSpan={6} className="subtle">No issued client invoices are currently available.</td></tr>}</tbody></table></div></section>}
   {risks.length>0&&<section className="panel"><h3>Client-Visible Risks</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Risk</th><th>Category</th><th>Level</th><th>Status</th><th>Review</th></tr></thead><tbody>{risks.map(r=><tr key={r.id}><td><b>{r.code} · {r.title}</b><div className="subtle">{r.description}</div></td><td>{r.category}</td><td><span className="badge">{r.inherent_level}</span></td><td>{pretty(r.status)}</td><td>{r.review_due_at?new Date(r.review_due_at).toLocaleDateString("en-IN"):"—"}</td></tr>)}</tbody></table></div></section>}
   <section className="panel"><h3>Issued Releases</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Package</th><th>Reference</th><th>Issued</th><th>Content Hash</th></tr></thead><tbody>{releases.map(r=><tr key={r.id}><td>{pretty(r.package_type)}</td><td>{r.package_reference}</td><td>{r.issued_at?new Date(r.issued_at).toLocaleString("en-IN"):"—"}</td><td><code>{shortHash(r.content_hash)}</code></td></tr>)}{releases.length===0&&<tr><td colSpan={4} className="subtle">No issued release package is currently available.</td></tr>}</tbody></table></div></section>
  </>}
 </>;
}
