export type ScopeCatalogueItem={id:string;code:string;name:string;category:string;description?:string|null;dependencies:string[];pricing_models:string[];default_state:string;active:boolean;version:number};
export type CommercialOpportunity={id:string;organisation_id:string;lead_id?:string|null;contact_id?:string|null;project_name:string;stage:string;probability:number;expected_fee?:number|null;currency:string;scope_modules?:string[]|null;decision_due_at?:string|null;created_at:string;updated_at:string};
export type CommercialIntake={id:string;organisation_id:string;opportunity_id?:string|null;project_id?:string|null;current_step:string;status:string;source_channel?:string|null;created_by?:string|null;created_at:string;updated_at:string};
export type ScopeSelection={id:string;intake_session_id:string;module_code:string;state:"included"|"optional"|"excluded";pricing_model?:string|null;quoted_amount?:number|null;currency:string;notes?:string|null;created_at:string;updated_at:string};
export type ScopeOverride={id:string;intake_session_id:string;module_code:string;dependency_code:string;reason:string;evidence_refs:unknown[];status:"requested"|"approved"|"rejected"|"withdrawn";requested_by?:string|null;decided_by?:string|null;decided_at?:string|null;created_at:string};
export type CommercialProposal={id:string;organisation_id:string;opportunity_id:string;version:number;status:string;currency:string;subtotal:number;tax:number;total:number;valid_until?:string|null;commercial_notes:unknown[];client_counter_offer?:number|null;approved_by?:string|null;approved_at?:string|null;created_by?:string|null;submitted_at?:string|null;created_at:string;updated_at:string;scope_intake_session_id?:string|null;scope_snapshot:Record<string,unknown>;scope_hash?:string|null;accepted_scope_hash?:string|null;source_proposal_id?:string|null};
export type ProposalLine={id:string;proposal_id:string;title:string;scope_code:string;pricing_model:string;quantity:number;rate:number;tax_code?:string|null;amount:number;optional:boolean;sort_order:number};
export type NegotiationEvent={id:string;proposal_id:string;version:number;party:string;event_type:string;amount?:number|null;currency?:string|null;scope_delta:unknown;note?:string|null;actor_user_id?:string|null;created_at:string};
export type CommercialProject={id:string;code:string;name:string;stage:string;status:string;typology?:string;lead_architect_user_id?:string|null;lifecycle_state?:string;data_classification?:string;opportunity_id?:string|null;contract_id?:string|null;organisation_id?:string};
export type ScopeCommercialState={catalogue:ScopeCatalogueItem[];opportunities:CommercialOpportunity[];intake_sessions:CommercialIntake[];selections:ScopeSelection[];overrides:ScopeOverride[];proposals:CommercialProposal[];proposal_lines:ProposalLine[];negotiation_events:NegotiationEvent[];projects:CommercialProject[]};
export const emptyScopeCommercialState:ScopeCommercialState={catalogue:[],opportunities:[],intake_sessions:[],selections:[],overrides:[],proposals:[],proposal_lines:[],negotiation_events:[],projects:[]};

export type LegalClause={id:string;organisation_id:string;code:string;category:string;jurisdiction:string;contract_type:string;risk:string;owner_role:string;active:boolean;created_by?:string|null;created_at:string;updated_at:string};
export type ClauseVersion={id:string;clause_id:string;version:number;approved_text:string;alternative_positions:unknown[];effective_from:string;effective_until?:string|null;status:string;content_hash:string;created_by?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string};
export type ContractRow={id:string;organisation_id:string;proposal_id:string;project_id?:string|null;version:number;status:string;effective_at?:string|null;expires_at?:string|null;signature_provider?:string|null;signature_envelope_id?:string|null;contract_snapshot:Record<string,unknown>;created_by?:string|null;created_at:string;updated_at:string;parent_contract_id?:string|null;contract_type?:string|null;jurisdiction?:string|null;draft_hash?:string|null;execution_hash?:string|null;executed_by?:string|null;executed_at?:string|null;amendment_reason?:string|null};
export type ContractBinding={id:string;contract_id:string;clause_version_id:string;clause_code:string;clause_hash:string;sort_order:number;created_at:string};
export type ContractRedline={id:string;contract_id:string;clause_version_id?:string|null;party:string;proposed_text:string;note?:string|null;evidence_refs:unknown[];status:string;created_by?:string|null;decided_by?:string|null;decided_at?:string|null;decision_note?:string|null;created_at:string};
export type SignatureEnvelope={id:string;contract_id:string;provider:string;provider_envelope_id?:string|null;signatories:unknown[];signing_order:unknown[];status:string;final_document_hash?:string|null;evidence_refs:unknown[];created_by?:string|null;sent_at?:string|null;completed_at?:string|null;updated_at:string;created_at:string};
export type ContractObligation={id:string;contract_id:string;party:string;obligation:string;due_at?:string|null;evidence_required?:string|null;status:string;completed_at?:string|null;clause_ref?:string|null;trigger_ref?:string|null;owner_ref?:string|null;source_hash?:string|null;waiver_reason?:string|null;waived_by?:string|null;waived_at?:string|null};
export type ContractStateEvent={id:string;contract_id:string;from_status?:string|null;to_status:string;evidence_reference?:string|null;actor_id?:string|null;created_at:string};
export type ContractLegalState={clauses:LegalClause[];clause_versions:ClauseVersion[];contracts:ContractRow[];bindings:ContractBinding[];redlines:ContractRedline[];signatures:SignatureEnvelope[];obligations:ContractObligation[];state_events:ContractStateEvent[]};
export const emptyContractLegalState:ContractLegalState={clauses:[],clause_versions:[],contracts:[],bindings:[],redlines:[],signatures:[],obligations:[],state_events:[]};

export type ActivationRow={id:string;opportunity_id:string;proposal_id:string;contract_id:string;project_id?:string|null;proposal_accepted:boolean;contract_executed:boolean;initial_payment_satisfied:boolean;required_kyc_satisfied:boolean;state:string;blocked_reason?:string|null;mobilisation_payment_evidence_ref?:string|null;kyc_evidence_ref?:string|null;project_team_ready:boolean;client_users_ready:boolean;site_info_ready:boolean;data_classification_ready:boolean;activation_hash?:string|null;checked_by?:string|null;checked_at?:string|null;activated_by?:string|null;activated_at?:string|null;created_at:string;updated_at:string};
export type ProjectStageRow={id:string;project_id:string;stage_code:string;title:string;sequence:number;baseline_version:number;state:string;contracted_modules:string[];dependencies:string[];deliverables:unknown[];approval_chain:unknown[];planned_start?:string|null;planned_finish?:string|null;actual_start?:string|null;actual_finish?:string|null;source_contract_id:string;source_scope_hash:string;created_at:string;updated_at:string};
export type ProjectStageEvent={id:string;project_stage_id:string;project_id:string;from_state?:string|null;to_state:string;reason?:string|null;evidence_refs:unknown[];actor_id?:string|null;created_at:string};
export type ActivationState={projects:CommercialProject[];activations:ActivationRow[];stages:ProjectStageRow[];stage_events:ProjectStageEvent[];contracts:ContractRow[]};
export const emptyActivationState:ActivationState={projects:[],activations:[],stages:[],stage_events:[],contracts:[]};
