"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

export type CommunicationMeetingState={communications:any[];meetings:any[];transcripts:any[];minutes:any[];decisions:any[];actions:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const jsonArray=(v:FormDataEntryValue|null)=>{const s=String(v||"").trim();if(!s)return [];const p=JSON.parse(s);if(!Array.isArray(p))throw new Error("Expected a JSON array");return p;};

export default function CommunicationMeetingClient({projectId,state}:{projectId:string;state:CommunicationMeetingState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const communications=state.communications||[];const meetings=state.meetings||[];const transcripts=state.transcripts||[];const minutes=state.minutes||[];
 function ok(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function draftCommunication(form:FormData){const {error}=await supabase.rpc("create_project_communication",{target_project_id:projectId,input_payload:{channel:String(form.get("channel")||"email"),recipient:String(form.get("recipient")||""),subject:String(form.get("subject")||""),body:String(form.get("body")||""),policy_class:String(form.get("policy_class")||"routine"),consent_basis:String(form.get("consent_basis")||"")}});if(error)return setMessage(error.message);ok("Communication drafted. Sensitive/legal/critical classes remain blocked until independent approval.");}
 async function decideCommunication(id:string,decision:string){const reason=window.prompt(`${decision} reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("approve_project_communication",{target_communication_id:id,target_decision:decision,target_reason:reason.trim()});if(error)return setMessage(error.message);ok(`Communication ${decision}.`);}
 async function queueCommunication(id:string){const {error}=await supabase.rpc("queue_project_communication",{target_communication_id:id});if(error)return setMessage(error.message);ok("Communication passed policy/consent checks and was queued to the transactional delivery layer.");}
 async function createMeeting(form:FormData){try{const {error}=await supabase.rpc("create_project_meeting",{target_project_id:projectId,input_payload:{title:String(form.get("title")||""),scheduled_at:String(form.get("scheduled_at")||""),participants:jsonArray(form.get("participants")),agenda:jsonArray(form.get("agenda")),recording_ref:String(form.get("recording_ref")||"")}});if(error)return setMessage(error.message);ok("Meeting created with governed agenda/participant context.");}catch(e){fail(e);}}
 async function transcript(form:FormData){const {error}=await supabase.rpc("record_meeting_transcript",{target_meeting_id:String(form.get("meeting_id")||""),input_payload:{source_ref:String(form.get("source_ref")||""),transcript_text:String(form.get("transcript_text")||""),confidence:String(form.get("confidence")||"0"),recording_ref:String(form.get("recording_ref")||"")}});if(error)return setMessage(error.message);ok("Transcript retained with source hash and confidence.");}
 async function draftMinutes(form:FormData){try{const {error}=await supabase.rpc("create_meeting_minutes_draft",{target_meeting_id:String(form.get("meeting_id")||""),input_payload:{transcript_id:String(form.get("transcript_id")||""),extraction_mode:String(form.get("extraction_mode")||"human"),decisions:jsonArray(form.get("decisions")),actions:jsonArray(form.get("actions"))}});if(error)return setMessage(error.message);ok("Minutes draft created. Extracted decisions/actions are still drafts and have no project authority yet.");}catch(e){fail(e);}}
 async function reviewMinutes(id:string){const reason=window.prompt("Minutes review note")||"Human review completed";const {error}=await supabase.rpc("review_meeting_minutes",{target_minutes_id:id,target_reason:reason});if(error)return setMessage(error.message);ok("Minutes marked human-reviewed; publication remains a separate authority step.");}
 async function publishMinutes(id:string){const reason=window.prompt("Publication reason / confirmation");if(!reason?.trim())return;const {error}=await supabase.rpc("publish_meeting_minutes",{target_minutes_id:id,target_reason:reason.trim()});if(error)return setMessage(error.message);ok("Minutes published. Durable decision IDs and linked action task IDs were created atomically.");}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Communication / Meeting Intelligence:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="panel-grid">
   <section className="panel"><h3>Draft Project Communication</h3><form action={draftCommunication}><div className="field-grid"><div className="field"><label>Channel</label><select name="channel"><option>email</option><option>whatsapp</option><option>sms</option><option>in_app</option></select></div><div className="field"><label>Policy class</label><select name="policy_class"><option value="routine">Routine</option><option value="sensitive">Sensitive</option><option value="legal">Legal</option><option value="critical">Critical</option></select></div><div className="field"><label>Recipient</label><input name="recipient" required/></div><div className="field"><label>Subject</label><input name="subject"/></div></div><div className="field"><label>Body</label><textarea name="body" rows={5} required/></div><div className="field"><label>Consent / legal basis if recipient consent is not recorded</label><input name="consent_basis" placeholder="Optional where explicit channel consent exists"/></div><button className="btn">Create Governed Draft</button></form></section>
   <section className="panel"><h3>Create Meeting</h3><form action={createMeeting}><div className="field-grid"><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Scheduled</label><input name="scheduled_at" type="datetime-local"/></div></div><div className="field"><label>Participants JSON array</label><textarea name="participants" rows={3} placeholder='[{"name":"...","role":"..."}]'/></div><div className="field"><label>Agenda JSON array</label><textarea name="agenda" rows={3} placeholder='["Item 1","Item 2"]'/></div><div className="field"><label>Recording reference</label><input name="recording_ref"/></div><button className="btn ghost">Create Meeting</button></form></section>
  </div>
  <section className="panel"><h3>Communication Centre</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Channel / Recipient</th><th>Class</th><th>Approval</th><th>Status</th><th>Hash</th><th>Actions</th></tr></thead><tbody>{communications.map(c=><tr key={c.id}><td><b>{c.channel}</b> · {c.recipient}<div className="subtle">{c.subject||"No subject"}</div></td><td><span className="badge">{pretty(c.policy_class)}</span></td><td>{pretty(c.approval_state)}</td><td>{pretty(c.status)}</td><td><code>{short(c.body_hash)}</code></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{c.approval_state==="pending"&&<><button className="btn ghost" onClick={()=>decideCommunication(c.id,"approved")}>Approve</button><button className="btn ghost" onClick={()=>decideCommunication(c.id,"rejected")}>Reject</button></>}{["draft","approved"].includes(c.status)&&c.approval_state!=="rejected"&&<button className="btn ghost" onClick={()=>queueCommunication(c.id)}>Policy-check & Queue</button>}</div></td></tr>)}{communications.length===0&&<tr><td colSpan={6} className="subtle">No project communications yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid">
   <section className="panel"><h3>Retain Transcript</h3><form action={transcript}><div className="field"><label>Meeting</label><select name="meeting_id" required>{meetings.map(m=><option key={m.id} value={m.id}>{m.title} · {pretty(m.status)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Source reference</label><input name="source_ref" required placeholder="recording:// or approved transcript source"/></div><div className="field"><label>Confidence 0–1</label><input name="confidence" type="number" min="0" max="1" step="0.01" defaultValue="1"/></div></div><div className="field"><label>Transcript</label><textarea name="transcript_text" rows={7} required/></div><button className="btn ghost" disabled={meetings.length===0}>Record Immutable Transcript</button></form></section>
   <section className="panel"><h3>Draft Minutes / AI Extraction Boundary</h3><form action={draftMinutes}><div className="field"><label>Meeting</label><select name="meeting_id" required>{meetings.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div><div className="field"><label>Transcript</label><select name="transcript_id"><option value="">Manual source</option>{transcripts.map(t=><option key={t.id} value={t.id}>{t.source_ref} · {short(t.transcript_hash)}</option>)}</select></div><div className="field"><label>Extraction mode</label><select name="extraction_mode"><option value="human">Human</option><option value="ai">AI draft</option></select></div><div className="field"><label>Decision drafts JSON</label><textarea name="decisions" rows={4} placeholder='[{"text":"Decision","type":"design_instruction","impact":"..."}]'/></div><div className="field"><label>Action drafts JSON</label><textarea name="actions" rows={4} placeholder='[{"title":"Action","priority":"high","due_at":"2026-09-01T12:00:00+05:30"}]'/></div><button className="btn" disabled={meetings.length===0}>Create Minutes Draft</button></form></section>
  </div>
  <section className="panel"><h3>Meeting / Minutes Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Meeting</th><th>Status</th><th>Latest draft</th><th>Source / Draft hash</th><th>Authority</th></tr></thead><tbody>{meetings.map(m=>{const d=minutes.find(x=>x.meeting_id===m.id&&x.status!=="superseded");return <tr key={m.id}><td><b>{m.title}</b><div className="subtle">{m.scheduled_at?new Date(m.scheduled_at).toLocaleString("en-IN"):"Unscheduled"}</div></td><td><span className="badge">{pretty(m.status)}</span></td><td>{d?`${pretty(d.extraction_mode)} · ${pretty(d.status)}`:"—"}</td><td>{d?<><code>{short(d.source_hash)}</code><div className="subtle"><code>{short(d.draft_hash)}</code></div></>:"—"}</td><td>{d?.status==="draft"?<button className="btn ghost" onClick={()=>reviewMinutes(d.id)}>Human Review</button>:d?.status==="reviewed"?<button className="btn" onClick={()=>publishMinutes(d.id)}>Publish Minutes</button>:d?.status==="published"?<span className="badge">Published</span>:"—"}</td></tr>})}{meetings.length===0&&<tr><td colSpan={5} className="subtle">No meetings yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Confirmed Decisions</h3>{(state.decisions||[]).map(d=><div className="note" key={d.id}><b>{pretty(d.decision_type)}</b> · {d.decision_text}<div className="subtle">Hash <code>{short(d.decision_hash)}</code> · source <code>{short(d.source_hash)}</code></div></div>)}{(state.decisions||[]).length===0&&<div className="subtle">No published decisions.</div>}</section><section className="panel"><h3>Linked Action Tasks</h3>{(state.actions||[]).map(a=><div className="note" key={a.link_id}><b>{a.title}</b> · <span className="badge">{pretty(a.state)}</span><div className="subtle">Priority {a.priority} · Task {a.task_id.slice(0,8)} · source <code>{short(a.source_hash)}</code></div></div>)}{(state.actions||[]).length===0&&<div className="subtle">No published meeting actions.</div>}</section></div>
 </>;
}
