"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Run={id:string;objective:string;status:string;input_hash:string;output_hash:string;blocked_reasons:string[];created_at:string;completed_at?:string|null}|null;
type Stage={id:string;stage:string;status:string;criticality:string;engine_refs:string[];input_hash:string;output_hash?:string|null;evidence_refs:string[];assumptions:string[]};
type Candidate={id:string;objective_metrics:Record<string,unknown>;compliance_state:string;human_shortlisted:boolean;constraint_violations:string[]};
export type CompilerState={run:Run;stages:Stage[];candidates:Candidate[];branches:Array<Record<string,unknown>>};
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function CompilerRuntimeClient({projectId,state}:{projectId:string;state:CompilerState}){
 const router=useRouter();const supabase=createClient();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 async function compile(form:FormData){setMessage("Freezing project state and running governed compiler stages…");const objective=String(form.get("objective")||"balanced");const {data,error}=await supabase.functions.invoke("compiler-run",{body:{project_id:projectId,objective}});if(error){setMessage(error.message);return;}const result=data as {error?:string;compilation_run_id?:string;status?:string;summary?:Record<string,unknown>;blocked_reasons?:string[]};if(result.error){setMessage(result.error);return;}setMessage(`Compiler run ${result.compilation_run_id?.slice(0,8)} recorded as ${result.status}. ${(result.blocked_reasons||[]).slice(0,2).join(" ")}`);startTransition(()=>router.refresh());}
 async function shortlist(id:string){const {error}=await supabase.rpc("shortlist_compiler_candidate",{target_candidate_id:id});if(error){setMessage(error.message);return;}setMessage("Candidate shortlisted by a human decision. No automatic selection was made.");startTransition(()=>router.refresh());}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Building Compiler:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="panel-grid"><section className="panel"><h3>Compile Current Project State</h3><form action={compile}><div className="field"><label>Optimisation objective</label><select name="objective" defaultValue={state.run?.objective||"balanced"}><option value="balanced">Balanced</option><option value="commercial_yield">Commercial yield</option><option value="environmental">Environmental</option><option value="architecture">Architecture</option><option value="capex">Capex</option></select></div><button className="btn" style={{marginTop:14}}>Run Building Compiler™</button></form><p className="subtle" style={{marginTop:14}}>The run freezes its own input hashes. Re-running after Project Truth, regulations or design state changes creates a new evidence state rather than rewriting history.</p></section><section className="panel"><h3>Current Run</h3>{state.run?<><div className="metric-grid"><div><b>{label(state.run.status)}</b><span>Status</span></div><div><b>{state.stages.filter(s=>s.status==="completed").length}/{state.stages.length}</b><span>Completed stages</span></div><div><b>{state.candidates.length}</b><span>Feasibility options</span></div></div><div className="subtle" style={{marginTop:14}}>Input {state.run.input_hash?.slice(0,12)}…<br/>Output {state.run.output_hash?.slice(0,12)}…</div>{state.run.blocked_reasons?.length>0&&<div className="note" style={{marginTop:14}}>{state.run.blocked_reasons.map((r,i)=><div key={i}>• {r}</div>)}</div>}</>:<div className="subtle">No live compilation has been executed yet.</div>}</section></div>
  <section className="panel" style={{marginTop:18}}><h3>Compilation Stages</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Stage</th><th>Status</th><th>Criticality</th><th>Engines</th><th>Evidence</th><th>Output hash</th></tr></thead><tbody>{state.stages.map(s=><tr key={s.id}><td><b>{label(s.stage)}</b></td><td><span className="badge">{label(s.status)}</span></td><td>{s.criticality}</td><td>{s.engine_refs?.length?s.engine_refs.join(", "):"Human / not executed"}</td><td>{s.evidence_refs?.length?s.evidence_refs.length:"0"}</td><td><code>{s.output_hash?.slice(0,10)||"—"}</code></td></tr>)}{state.stages.length===0&&<tr><td colSpan={6} className="subtle">Run the compiler to create a governed stage ledger.</td></tr>}</tbody></table></div></section>
  <section className="panel" style={{marginTop:18}}><h3>Pareto / Feasibility Candidates</h3><div className="grid-3">{state.candidates.map(c=>{const m=c.objective_metrics||{};return <div className="card" key={c.id}><div className="eyebrow">{String(m.name||"Candidate")}</div><h3>{Number(m.scenario_gfa_m2||0).toLocaleString("en-IN")} m²</h3><p>GFA scenario<br/>Footprint {Number(m.scenario_footprint_m2||0).toLocaleString("en-IN")} m²<br/>Approx. envelope storeys {String(m.approx_storeys_from_envelope||"—")}<br/>Open space {String(m.open_space_percent||"—")}%</p><span className="badge">{c.compliance_state}</span><div style={{marginTop:12}}>{c.human_shortlisted?<b>Human shortlisted</b>:<button className="btn ghost" onClick={()=>shortlist(c.id)}>Shortlist</button>}</div></div>})}{state.candidates.length===0&&<div className="note">No numeric feasibility option can be generated until valid geometry plus verified FAR/FSI and unambiguous ground coverage exist.</div>}</div></section>
  <div className="note" style={{marginTop:18}}><b>Compiler rule.</b> A stage is never complete because AI produced text. Architecture, structure, MEPF, cost, coordination and assurance remain review-gated until deterministic engines, model evidence and the applicable professional approvals are bound to the run.</div>
 </>;
}
