"use client";

import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {ChangeImpact,ConfigurationProject,ConfigurationWorkspace,ProjectChangeRequest} from "@/components/configuration-runtime-types";

const human=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const short=(v?:string|null)=>v?`${v.slice(0,14)}…`:"—";
const when=(v?:string|null)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const money=(v?:number|null)=>v==null?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const refs=(v:string)=>v.split(/[\n,]/).map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf(":");return i>0?{type:x.slice(0,i).trim(),id:x.slice(i+1).trim()}:{reference:x};});
const disciplines=(v:string)=>v.split(/[\n,]/).map(x=>x.trim().toLowerCase()).filter(Boolean);

export default function ConfigurationControlClient({projects,state,section}:{projects:ConfigurationProject[];state:ConfigurationWorkspace;section:"branches"|"changes"}){
 const supabase=createClient(),router=useRouter();const [message,setMessage]=useState(""),[busy,startTransition]=useTransition();const [projectId,setProjectId]=useState(projects[0]?.id||"");
 const refresh=(text:string)=>{setMessage(text);startTransition(()=>router.refresh());};
 const branches=useMemo(()=>state.branches.filter(b=>b.project_id===projectId),[state,projectId]);
 const changes=useMemo(()=>state.changes.filter(c=>c.project_id===projectId),[state,projectId]);
 const impacts=useMemo(()=>state.impacts.filter(i=>i.project_id===projectId),[state,projectId]);
 const commits=useMemo(()=>state.commits.filter(c=>c.project_id===projectId),[state,projectId]);
 const projectLabel=(id:string)=>{const p=projects.find(x=>x.id===id);return p?`${p.code} · ${p.name}`:id.slice(0,8);};
 async function call(name:string,args:Record<string,unknown>,success:string){const {error}=await supabase.rpc(name,args);if(error){setMessage(error.message);return false;}refresh(success);return true;}
 async function bootstrap(){await call("bootstrap_project_main_branch",{target_project_id:projectId},"Main configuration branch bootstrapped from the current governed project snapshot.");}
 async function createBranch(f:FormData){await call("create_project_configuration_branch",{input_payload:{project_id:String(f.get("project_id")||""),name:String(f.get("name")||""),purpose:String(f.get("purpose")||""),parent_branch_id:String(f.get("parent_branch_id")||"")}},"Configuration branch created from the selected exact head.");}
 async function branchState(id:string,status:string){const reason=window.prompt(`Reason for ${status}?`);if(!reason)return;await call("transition_project_configuration_branch",{target_branch_id:id,target_status:status,target_reason:reason},`Branch moved to ${human(status)}.`);}
 async function propose(f:FormData){await call("propose_project_change",{input_payload:{project_id:String(f.get("project_id")||""),branch_id:String(f.get("branch_id")||""),change_ref:String(f.get("change_ref")||""),title:String(f.get("title")||""),description:String(f.get("description")||""),source_object_refs:refs(String(f.get("source_refs")||"")),proposed_disciplines:disciplines(String(f.get("disciplines")||""))}},"Project change registered on the selected branch.");}
 async function analyze(id:string,f:FormData){await call("analyze_project_change",{target_change_request_id:id,input_payload:{criticality:String(f.get("criticality")||"C2"),confidence:String(f.get("confidence")||"C"),estimated_cost_delta:String(f.get("cost")||""),estimated_schedule_delta_days:String(f.get("days")||""),decision_reversal_cost:String(f.get("reversal")||"")}},"Blast-radius analysis completed and exact analysis hash frozen.");}
 async function requestApproval(id:string,f:FormData){await call("request_project_change_approval",{target_change_request_id:id,target_role_required:String(f.get("role")||"lead_architect")},"Exact-hash maker-checker approval requested.");}
 async function syncApproval(id:string){await call("sync_project_change_approval",{target_change_request_id:id},"Approval state synchronized against the exact analysis hash.");}
 async function applyChange(id:string){const note=window.prompt("Commit message (optional)")||"";await call("apply_project_change",{target_change_request_id:id,target_message:note},"Approved change committed to the branch with immutable lineage.");}
 async function cancelChange(id:string){const reason=window.prompt("Cancellation reason");if(!reason)return;await call("cancel_project_change",{target_change_request_id:id,target_reason:reason},"Change request cancelled with audit evidence.");}
 async function mergeBranch(sourceId:string,f:FormData){await call("merge_project_configuration_branch",{source_branch_id:sourceId,target_branch_id:String(f.get("target")||""),target_change_request_id:String(f.get("change")||""),target_reason:String(f.get("reason")||"")},"Branch merged through governed exact-hash change control.");}
 const latestImpact=(c:ProjectChangeRequest):ChangeImpact|undefined=>impacts.find(i=>i.id===c.latest_impact_id);
 const openChanges=changes.filter(c=>!["applied","cancelled","rejected"].includes(c.status)).length,pending=changes.filter(c=>c.status==="approval_pending").length,activeBranches=branches.filter(b=>b.status==="active").length;
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Configuration Control:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="field" style={{maxWidth:520,marginBottom:18}}><label>Project workspace</label><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div>
  <div className="kpis">{[["Active Branches",activeBranches],["Open Changes",openChanges],["Approval Pending",pending],["Commits",commits.length],["Analyses",impacts.length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{String(v).padStart(2,"0")}</div><div className="subtle">{projectId?projectLabel(projectId):"Workspace"}</div></div>)}</div>

  {section==="branches"?<>
   <div className="panel-grid"><section className="panel"><h3>Building Git Bootstrap / Branch</h3>{!branches.some(b=>b.name==="main")&&<button className="btn" type="button" onClick={bootstrap}>Bootstrap Main from Current Project</button>}<form action={createBranch} style={{marginTop:12}}><input type="hidden" name="project_id" value={projectId}/><div className="field"><label>Branch name</label><input name="name" required placeholder="client-option-b"/></div><div className="field"><label>Purpose</label><textarea name="purpose" required rows={2}/></div><div className="field"><label>Parent branch</label><select name="parent_branch_id"><option value="">Main</option>{branches.filter(b=>["active","frozen"].includes(b.status)).map(b=><option key={b.id} value={b.id}>{b.name} · {short(b.head_commit_hash)}</option>)}</select></div><button className="btn">Create Exact-Head Branch</button></form></section><section className="panel"><h3>Merge Invariant</h3><p className="subtle">A branch cannot be merged merely because it exists. It must carry an applied change whose blast-radius analysis was approved against the exact analysis hash. The merge commit records both parent heads.</p><div className="note"><b>No silent divergence.</b> Frozen, abandoned and merged branches cannot receive new change commits.</div></section></div>
   <section style={{marginTop:18}}><div className="grid-3">{branches.map(b=>{const branchChanges=changes.filter(c=>c.branch_id===b.id&&c.status==="applied");return <div className="card" key={b.id}><div className="eyebrow">{b.name} · {human(b.status)}</div><h3>{b.purpose}</h3><div className="subtle">Head <code>{short(b.head_commit_hash)}</code><br/>Parent <code>{short(b.parent_commit_hash)}</code><br/>Created {when(b.created_at)}</div>{b.name!=="main"&&!["merged","abandoned"].includes(b.status)&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:10}}><button className="btn ghost" type="button" onClick={()=>branchState(b.id,b.status==="frozen"?"active":"frozen")}>{b.status==="frozen"?"Unfreeze":"Freeze"}</button><button className="btn ghost" type="button" onClick={()=>branchState(b.id,"abandoned")}>Abandon</button></div>}{b.name!=="main"&&b.status==="active"&&branchChanges.length>0&&<form action={f=>mergeBranch(b.id,f)} style={{marginTop:12}}><div className="field"><label>Target branch</label><select name="target" required>{branches.filter(x=>x.id!==b.id&&x.status==="active").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Applied change</label><select name="change" required>{branchChanges.map(c=><option key={c.id} value={c.id}>{c.change_ref} · {c.title}</option>)}</select></div><div className="field"><label>Merge rationale</label><textarea name="reason" required rows={2}/></div><button className="btn">Governed Merge</button></form>}</div>})}{branches.length===0&&<div className="note">No project branches yet. Bootstrap `main` from the current governed configuration.</div>}</div></section>
   <section className="panel" style={{marginTop:18}}><h3>Immutable Commit Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Time</th><th>Branch</th><th>Commit</th><th>Parents</th><th>Message</th></tr></thead><tbody>{commits.map(c=><tr key={c.id}><td>{when(c.created_at)}</td><td>{branches.find(b=>b.id===c.branch_id)?.name||c.branch_id.slice(0,8)}</td><td><code>{short(c.content_hash)}</code></td><td>{(c.parent_commit_hashes||[]).map(short).join(", ")||"Genesis"}</td><td>{c.message}</td></tr>)}{commits.length===0&&<tr><td colSpan={5}>No commits yet.</td></tr>}</tbody></table></div></section>
  </>:<>
   <div className="panel-grid"><section className="panel"><h3>Propose Project Change</h3><form action={propose}><input type="hidden" name="project_id" value={projectId}/><div className="field"><label>Branch</label><select name="branch_id" required><option value="">Select active branch</option>{branches.filter(b=>b.status==="active").map(b=><option key={b.id} value={b.id}>{b.name} · {short(b.head_commit_hash)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Change reference</label><input name="change_ref" placeholder="Auto if blank"/></div><div className="field"><label>Title</label><input name="title" required/></div></div><div className="field"><label>Description</label><textarea name="description" required rows={3}/></div><div className="field"><label>Affected disciplines</label><input name="disciplines" required placeholder="architecture, structure, mechanical"/></div><div className="field"><label>Source object references</label><textarea name="source_refs" rows={2} placeholder="document:uuid or model:uuid, one per line"/></div><button className="btn" disabled={!branches.some(b=>b.status==="active")}>Register Change</button></form>{!branches.some(b=>b.status==="active")&&<div className="note" style={{marginTop:10}}>Bootstrap the project main branch in Building Git before proposing a change.</div>}</section><section className="panel"><h3>Impact Contract</h3><p className="subtle">Analysis freezes an exact baseline hash plus the affected regulatory, requirements, CDE, engineering, coordination, BOQ, contract, programme and release inventory. Any project configuration mutation after analysis forces re-analysis before approval or commit.</p><div className="note"><b>Maker-checker.</b> C3/C4 approvals inherit the verified professional eligibility controls from the governed approval runtime.</div></section></div>
   <section style={{marginTop:18}}><div className="grid-3">{changes.map(c=>{const impact=latestImpact(c);const approval=state.approvals.find(a=>a.id===c.approval_request_id);return <div className="card" key={c.id}><div className="eyebrow">{c.change_ref} · {human(c.status)}</div><h3>{c.title}</h3><p>{c.description}</p><div className="subtle">Branch {branches.find(b=>b.id===c.branch_id)?.name||c.branch_id.slice(0,8)}<br/>Disciplines {(c.proposed_disciplines||[]).map(human).join(", ")}<br/>Updated {when(c.updated_at)}</div>{impact&&<div className="note" style={{marginTop:10}}><b>Analysis v{impact.analysis_version}</b> · {impact.criticality} · Confidence {impact.confidence}<br/>Hash <code>{short(impact.analysis_hash)}</code><br/>Baseline <code>{short(impact.baseline_hash)}</code><br/>Docs {impact.affected_documents?.length||0} · Models {impact.affected_model_objects?.length||0} · Coordination {impact.affected_coordination?.length||0} · Releases {impact.affected_releases?.length||0}<br/>BOQ {impact.affected_boq_lines?.length||0} · Contracts {impact.affected_contracts?.length||0} · Tasks {impact.affected_programme_tasks?.length||0}<br/>Cost Δ {money(impact.estimated_cost_delta)} · Schedule Δ {impact.estimated_schedule_delta_days??"—"} days · Reversal {money(impact.decision_reversal_cost)}</div>}
     {["draft","rejected","analyzed"].includes(c.status)&&<form action={f=>analyze(c.id,f)} style={{marginTop:10}}><div className="field-grid"><div className="field"><label>Criticality</label><select name="criticality" defaultValue={impact?.criticality||"C2"}>{["C0","C1","C2","C3","C4"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Confidence</label><select name="confidence" defaultValue={impact?.confidence||"C"}>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="field-grid"><div className="field"><label>Estimated cost delta ₹</label><input name="cost" type="number" step="0.01"/></div><div className="field"><label>Schedule delta days</label><input name="days" type="number"/></div></div><div className="field"><label>Decision reversal cost ₹</label><input name="reversal" type="number" step="0.01"/></div><button className="btn">{impact?"Re-analyse & Supersede":"Analyse Blast Radius"}</button></form>}
     {c.status==="analyzed"&&<form action={f=>requestApproval(c.id,f)} style={{marginTop:10}}><div className="field"><label>Required reviewer role</label><select name="role" defaultValue="lead_architect"><option value="lead_architect">Lead Architect</option><option value="architect">Architect</option><option value="structural_engineer">Structural Engineer</option><option value="mep_engineer">MEP Engineer</option><option value="quantity_surveyor">Quantity Surveyor</option><option value="regulatory_reviewer">Regulatory Reviewer</option></select></div><button className="btn ghost">Request Exact-Hash Approval</button></form>}
     {c.status==="approval_pending"&&<div className="note" style={{marginTop:10}}>Approval {approval?.decision||"pending"}. Reviewer must decide against <code>{short(impact?.analysis_hash)}</code>.<div style={{display:"flex",gap:6,marginTop:8}}><button className="btn ghost" type="button" onClick={()=>syncApproval(c.id)}>Sync Approval</button><Link className="btn ghost" href="/app/approvals">Open Approvals</Link></div></div>}
     {c.status==="approved"&&<button className="btn" style={{marginTop:10}} type="button" onClick={()=>applyChange(c.id)}>Commit Approved Change</button>}
     {!['applied','cancelled'].includes(c.status)&&<button className="btn ghost" style={{marginTop:8}} type="button" onClick={()=>cancelChange(c.id)}>Cancel</button>}
     {c.status==="applied"&&<div className="note" style={{marginTop:10}}><b>Committed.</b> Applied {when(c.applied_at)}. If this is an option branch, complete the governed merge in Building Git.</div>}
    </div>})}{changes.length===0&&<div className="note">No governed project changes yet.</div>}</div></section>
  </>}
 </>;
}
