"use client";

import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {CoordinationItem,CoordinationProject,CoordinationResource,CoordinationWorkspaceState} from "@/components/coordination-runtime-types";

const disciplines=["architecture","structure","mechanical","electrical","plumbing","fire","elv","bms","vertical_transport","interiors","landscape","facade","civil"];
const resourceTypes=["model","document","requirement","truth_record","release"];
const human=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const refs=(value:string)=>value.split(/[\n,]/).map(v=>v.trim()).filter(Boolean);
const when=(value?:string|null)=>value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const shortHash=(value?:string|null)=>value?`${value.slice(0,16)}…`:"—";

export default function CoordinationMatrixClient({projects,state}:{projects:CoordinationProject[];state:CoordinationWorkspaceState}){
 const router=useRouter(),supabase=createClient();
 const [message,setMessage]=useState(""),[busy,startTransition]=useTransition();
 const [projectId,setProjectId]=useState(projects[0]?.id||"");
 const [sourceType,setSourceType]=useState("model"),[targetType,setTargetType]=useState("model");
 const refresh=(text:string)=>{setMessage(text);startTransition(()=>router.refresh());};

 const resources=(type:string):CoordinationResource[]=>type==="model"?state.models:type==="document"?state.documents:type==="requirement"?state.requirements:type==="truth_record"?state.truth_records:state.releases;
 const sourceOptions=useMemo(()=>resources(sourceType).filter(r=>r.project_id===projectId),[sourceType,projectId,state]);
 const targetOptions=useMemo(()=>resources(targetType).filter(r=>r.project_id===projectId),[targetType,projectId,state]);

 async function raise(form:FormData){
  const payload={project_id:String(form.get("project_id")||""),source_discipline:String(form.get("source_discipline")||""),target_discipline:String(form.get("target_discipline")||""),subject:String(form.get("subject")||""),description:String(form.get("description")||""),criticality:String(form.get("criticality")||"C1"),priority:String(form.get("priority")||"medium"),due_at:String(form.get("due_at")||""),location_ref:String(form.get("location_ref")||""),bcf_topic_ref:String(form.get("bcf_topic_ref")||""),requirement_ref:String(form.get("requirement_ref")||""),source_resource_type:String(form.get("source_resource_type")||""),source_resource_id:String(form.get("source_resource_id")||""),target_resource_type:String(form.get("target_resource_type")||""),target_resource_id:String(form.get("target_resource_id")||""),reason:"Cross-discipline coordination item raised from the governed matrix workspace"};
  const {data,error}=await supabase.rpc("raise_coordination_matrix_item",{input_payload:payload});if(error){setMessage(error.message);return;}refresh(`Coordination item ${String(data).slice(0,8)} raised with linked issue and resource hashes.`);
 }
 async function transition(item:CoordinationItem,stateValue:string,reason:string,evidence:string[]=[]){const {error}=await supabase.rpc("transition_coordination_matrix_item",{target_item_id:item.id,target_state:stateValue,target_reason:reason,target_evidence_refs:evidence});if(error){setMessage(error.message);return;}refresh(`${item.issue_number} moved to ${human(stateValue)}.`);}
 async function resolve(item:CoordinationItem,form:FormData){const evidence=refs(String(form.get("evidence")||""));await transition(item,"resolved",String(form.get("reason")||""),evidence);}
 async function requestDeviation(item:CoordinationItem,form:FormData){const {data,error}=await supabase.rpc("request_coordination_deviation_approval",{target_item_id:item.id,target_role_required:String(form.get("role")||"lead_architect"),target_reason:String(form.get("reason")||"")});if(error){setMessage(error.message);return;}refresh(`Deviation approval ${String(data).slice(0,8)} requested for exact coordination hash.`);}
 async function assign(item:CoordinationItem,form:FormData){const {error}=await supabase.rpc("assign_coordination_matrix_owner",{target_item_id:item.id,target_owner_user_id:String(form.get("owner")||""),target_reason:"Coordination ownership reassigned by project management"});if(error){setMessage(error.message);return;}refresh(`${item.issue_number} owner updated.`);}
 async function rebaseline(item:CoordinationItem,form:FormData){const reason=String(form.get("reason")||"");const {error}=await supabase.rpc("refresh_coordination_matrix_resources",{target_item_id:item.id,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`${item.issue_number} re-baselined to current linked resources and reopened for coordination.`);}

 const open=state.items.filter(i=>i.state==="open").length,coordinating=state.items.filter(i=>i.state==="coordinating").length,critical=state.items.filter(i=>["open","coordinating"].includes(i.state)&&["C3","C4"].includes(i.criticality)).length,resolved=state.items.filter(i=>i.state==="resolved").length,deviations=state.items.filter(i=>i.state==="accepted_deviation").length,stale=state.items.filter(i=>!i.resources_current).length;
 return <>
  {message&&<div className="note" style={{marginBottom:18}}><b>Coordination:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Open",open],["Coordinating",coordinating],["Open C3/C4",critical],["Resolved",resolved],["Accepted Deviations",deviations],["Stale Baselines",stale]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{String(v).padStart(2,"0")}</div><div className="subtle">Live matrix</div></div>)}</div>

  <div className="panel-grid"><section className="panel"><h3>Raise Cross-Discipline Item</h3><form action={raise}>
   <div className="field"><label>Project</label><select name="project_id" required value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div>
   <div className="field-grid"><div className="field"><label>Source discipline</label><select name="source_discipline" defaultValue="architecture">{disciplines.map(d=><option key={d} value={d}>{human(d)}</option>)}</select></div><div className="field"><label>Target discipline</label><select name="target_discipline" defaultValue="structure">{disciplines.map(d=><option key={d} value={d}>{human(d)}</option>)}</select></div></div>
   <div className="field"><label>Subject</label><input name="subject" required placeholder="Beam / duct conflict at Level 03"/></div><div className="field"><label>Description</label><textarea name="description" rows={3} required/></div>
   <div className="field-grid"><div className="field"><label>Criticality</label><select name="criticality" defaultValue="C2">{["C0","C1","C2","C3","C4"].map(v=><option key={v}>{v}</option>)}</select></div><div className="field"><label>Priority</label><select name="priority" defaultValue="high"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div><div className="field"><label>Due</label><input type="datetime-local" name="due_at"/></div><div className="field"><label>Location / object ref</label><input name="location_ref"/></div></div>
   <div className="field-grid"><div className="field"><label>Source resource type</label><select name="source_resource_type" value={sourceType} onChange={e=>setSourceType(e.target.value)}>{resourceTypes.map(v=><option key={v} value={v}>{human(v)}</option>)}</select></div><div className="field"><label>Source resource</label><select name="source_resource_id" required><option value="">Select current resource</option>{sourceOptions.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></div><div className="field"><label>Target resource type</label><select name="target_resource_type" value={targetType} onChange={e=>setTargetType(e.target.value)}>{resourceTypes.map(v=><option key={v} value={v}>{human(v)}</option>)}</select></div><div className="field"><label>Target resource</label><select name="target_resource_id" required><option value="">Select current resource</option>{targetOptions.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></div></div>
   <div className="field-grid"><div className="field"><label>Requirement reference</label><input name="requirement_ref"/></div><div className="field"><label>BCF topic reference</label><input name="bcf_topic_ref"/></div></div><button className="btn" disabled={!projects.length}>Raise + Hash-Bind Resources</button>
  </form></section>
  <section className="panel"><h3>Coordination Control</h3><p className="subtle">Every matrix item creates a linked coordination issue and captures the exact hash of the selected source and target resource. Resolution needs evidence. A deviation cannot be accepted until a governed approval has reviewed the exact coordination hash.</p><div className="note"><b>Release coupling.</b> Pack 28 treats any open or coordinating matrix item as a release blocker and now also rejects stale resource baselines.</div><div className="note" style={{marginTop:10}}><b>Freshness invariant.</b> If a linked resource changes after coordination, the item must be re-baselined and reopened. Previous resolution and deviation evidence is deliberately invalidated.</div></section></div>

  <section style={{marginTop:18}}><div className="topbar"><div><div className="demo">Federated Coordination / Hash-Bound Evidence</div><h2>Coordination Matrix</h2></div></div><div className="grid-3">{state.items.map(item=>{const approval=state.approvals.find(a=>a.resource_id===item.id&&["approved","approved_with_comments"].includes(a.decision)&&a.decision_evidence_hash===item.coordination_hash);const members=state.members.filter(m=>m.project_id===item.project_id);const current=item.resources_current!==false;return <div className="card" key={item.id}><div className="eyebrow">{item.issue_number} · {item.criticality} · {human(item.priority)}</div><h3>{human(item.source_discipline)} → {human(item.target_discipline)}</h3><p>{item.subject}</p><div className="subtle">State <span className="badge">{human(item.state)}</span><br/>Issue {human(item.issue_status)}<br/>Baseline <span className="badge">{current?"Current":"Stale"}</span><br/>Coordination hash <code>{shortHash(item.coordination_hash)}</code><br/>Updated {when(item.updated_at)}</div>
   <div className="note" style={{marginTop:10}}><b>Source:</b> {item.source_resource?.label||"—"}<br/>Captured <code>{shortHash(item.source_resource?.captured_hash)}</code><br/>Current <code>{shortHash(item.source_resource?.hash)}</code> · {item.source_resource?.fresh===false?"Changed":"Current"}<br/><b>Target:</b> {item.target_resource?.label||"—"}<br/>Captured <code>{shortHash(item.target_resource?.captured_hash)}</code><br/>Current <code>{shortHash(item.target_resource?.hash)}</code> · {item.target_resource?.fresh===false?"Changed":"Current"}</div>
   {!current&&<div className="note" style={{marginTop:10}}><b>Baseline changed.</b> Positive coordination actions are blocked until this item is re-baselined to the current linked resources. Re-baselining generates a new coordination hash and reopens the linked issue.<form action={f=>rebaseline(item,f)} style={{marginTop:10}}><div className="field"><label>Re-baseline reason</label><textarea name="reason" rows={2} required placeholder="Explain why the linked resource change requires renewed coordination"/></div><button className="btn">Re-baseline + Reopen</button></form></div>}
   {current&&item.state==="open"&&<button type="button" className="btn ghost" style={{marginTop:10}} onClick={()=>transition(item,"coordinating","Coordination work commenced against the hash-bound source and target resources")}>Start Coordinating</button>}
   {current&&["open","coordinating"].includes(item.state)&&<form action={f=>resolve(item,f)} style={{marginTop:10}}><div className="field"><label>Resolution rationale</label><textarea name="reason" required rows={2} placeholder="Explain how the coordination conflict was resolved"/></div><div className="field"><label>Resolution evidence references</label><textarea name="evidence" required rows={2} placeholder="CDE version/hash, BCF view, drawing/model reference; one per line"/></div><button className="btn">Resolve with Evidence</button></form>}
   {current&&["open","coordinating"].includes(item.state)&&!approval&&<form action={f=>requestDeviation(item,f)} style={{marginTop:10}}><div className="field"><label>Deviation reviewer role</label><select name="role" defaultValue="lead_architect"><option value="lead_architect">Lead Architect</option><option value="architect">Architect</option><option value="structural_engineer">Structural Engineer</option><option value="mep_engineer">MEP Engineer</option><option value="regulatory_reviewer">Regulatory Reviewer</option></select></div><div className="field"><label>Deviation rationale</label><textarea name="reason" required rows={2}/></div><button className="btn ghost">Request Exact-Hash Deviation Approval</button></form>}
   {current&&approval&&["open","coordinating"].includes(item.state)&&<div className="note" style={{marginTop:10}}><b>Deviation approved.</b> Approval {approval.id.slice(0,8)} reviewed this exact coordination hash.<br/><button type="button" className="btn" style={{marginTop:8}} onClick={()=>transition(item,"accepted_deviation","Accepted deviation implemented under governed approval",[approval.id])}>Accept Deviation</button></div>}
   {current&&["resolved","accepted_deviation"].includes(item.state)&&<button type="button" className="btn ghost" style={{marginTop:10}} onClick={()=>transition(item,"open","Coordination item reopened because the previous resolution/deviation no longer represents current design intent")}>Reopen</button>}
   {members.length>0&&<form action={f=>assign(item,f)} style={{marginTop:10}}><div className="field"><label>Owner</label><select name="owner" defaultValue={item.owner_user_id||""}>{members.map(m=><option value={m.user_id} key={`${m.user_id}-${m.role_code}`}>{m.role_code} · {m.discipline||"general"} · {m.user_id.slice(0,8)}</option>)}</select></div><button className="btn ghost">Reassign Owner</button></form>}
   {item.resolution_note&&<div className="note" style={{marginTop:10}}><b>Resolution:</b> {item.resolution_note}<br/>Evidence: {(item.resolution_evidence_refs||[]).join(", ")||"—"}</div>}
  </div>})}{!state.items.length&&<div className="note">No governed coordination matrix items yet. Raise the first item against current CDE/project resources above.</div>}</div></section>

  <section className="panel" style={{marginTop:18}}><div className="topbar"><div><h3>Governance Ledger</h3><div className="subtle">Append-only matrix events, resource re-baselines and deviation approvals</div></div><Link className="btn ghost" href="/app/approvals">Open Approvals</Link></div><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Time</th><th>Issue</th><th>Event</th><th>Reason</th><th>Evidence</th></tr></thead><tbody>{state.events.slice(0,60).map(e=>{const item=state.items.find(i=>i.id===e.coordination_item_id);return <tr key={e.id}><td>{when(e.created_at)}</td><td>{item?.issue_number||e.coordination_item_id.slice(0,8)}</td><td>{human(e.event_type)}</td><td>{e.reason}</td><td>{(e.evidence_refs||[]).join(", ")||"—"}</td></tr>})}{!state.events.length&&<tr><td colSpan={5} className="subtle">No coordination governance events yet.</td></tr>}</tbody></table></div></section>
 </>;
}
