"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import type {BOQLine,CostPlan,CostWorkspaceState,ProjectRow,QTORun,VEOption} from "@/components/lifecycle-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ");
const money=(n:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n||0));
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseJSON(raw:FormDataEntryValue|null,label:string){try{return JSON.parse(String(raw||"[]"));}catch{throw new Error(`${label} must be valid JSON.`);}}

export default function CostWorkspaceClient({projects,projectId,state}:{projects:ProjectRow[];projectId:string;state:CostWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const models=state.models||[];const qtos=state.qto_runs||[];const quantities=state.quantities||[];const plans=state.cost_plans||[];const lines=state.boq_lines||[];const ve=state.ve_options||[];
 const approved=plans.find(p=>p.status==="approved");const approvedQto=qtos.filter(q=>q.status==="approved");const draftPlans=plans.filter(p=>p.status==="draft");
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function startQto(form:FormData){try{setMessage("Starting exact-model QTO run…");const exclusions=parseJSON(form.get("exclusions"),"Exclusions");const tolerance=parseJSON(form.get("tolerance"),"Tolerance");const {error}=await supabase.rpc("start_qto_run",{target_project_id:projectId,input_payload:{model_id:String(form.get("model_id")||""),measurement_rule_set_ref:String(form.get("measurement_rule_set_ref")||""),classification_ref:String(form.get("classification_ref")||"")||undefined,exclusions,tolerance}});if(error)throw error;refresh("QTO run created against the selected approved model checksum.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function completeQto(form:FormData){try{setMessage("Recording deterministic QTO output…");const quantitiesPayload=parseJSON(form.get("quantities"),"Quantities");const errorCode=String(form.get("error_code")||"").trim();const payload=errorCode?{error_code:errorCode}:{output_hash:String(form.get("output_hash")||"").toLowerCase(),quantities:quantitiesPayload};const {error}=await supabase.rpc("complete_qto_run",{target_qto_run_id:String(form.get("qto_run_id")||""),input_payload:payload});if(error)throw error;refresh(errorCode?"QTO failure recorded without mutating approved quantities.":"QTO output recorded with object, rule and formula provenance.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function approveQto(q:QTORun){setMessage("Checking QTO source-model freshness…");const {error}=await supabase.rpc("approve_qto_run",{target_qto_run_id:q.id,target_reason:"QS approval from Cost workspace"});if(error){setMessage(error.message);return;}refresh("QTO approved against its immutable source model checksum.");}
 async function createPlan(form:FormData){setMessage("Creating cost plan against current Project Configuration…");const {error}=await supabase.rpc("create_cost_plan",{target_project_id:projectId,input_payload:{qto_run_id:String(form.get("qto_run_id")||"")||undefined,stage:String(form.get("stage")||"cost_plan"),currency:String(form.get("currency")||"INR"),confidence:String(form.get("confidence")||"C"),basis_date:String(form.get("basis_date")||""),contingencies:String(form.get("contingencies")||"0"),professional_fees:String(form.get("professional_fees")||"0"),taxes:String(form.get("taxes")||"0")}});if(error){setMessage(error.message);return;}refresh("Draft cost plan created and bound to the current configuration hash.");}
 async function addLine(form:FormData){setMessage("Adding traceable BOQ line…");const {error}=await supabase.rpc("add_boq_line",{target_cost_plan_id:String(form.get("cost_plan_id")||""),input_payload:{quantity_item_id:String(form.get("quantity_item_id")||"")||undefined,manual_item:String(form.get("manual_item"))==="true",code:String(form.get("code")||""),description:String(form.get("description")||""),unit:String(form.get("unit")||""),quantity:String(form.get("quantity")||"")||undefined,rate:String(form.get("rate")||"0"),currency:String(form.get("currency")||"INR"),rate_source:String(form.get("rate_source")||""),rate_date:String(form.get("rate_date")||""),confidence:String(form.get("confidence")||"C"),specification_ref:String(form.get("specification_ref")||"")||undefined,package_category:String(form.get("package_category")||"")||undefined,notes:String(form.get("notes")||"")||undefined}});if(error){setMessage(error.message);return;}refresh("BOQ line added with rate and quantity provenance.");}
 async function transitionPlan(p:CostPlan,status:string){const reason=window.prompt(`Reason for ${pretty(status)}:`)||"Cost workflow transition";const {error}=await supabase.rpc("transition_cost_plan",{target_cost_plan_id:p.id,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`Cost plan moved to ${pretty(status)}.`);}
 async function proposeVE(form:FormData){try{const lifecycle=parseJSON(form.get("lifecycle_impact"),"Lifecycle impact");const performance=parseJSON(form.get("performance_impact"),"Performance impact");const reqs=parseJSON(form.get("requirement_impact_refs"),"Requirement impacts");const {error}=await supabase.rpc("propose_value_engineering_option",{target_project_id:projectId,input_payload:{source_boq_line_id:String(form.get("source_boq_line_id")||"")||undefined,discipline:String(form.get("discipline")||"")||undefined,proposal:String(form.get("proposal")||""),reason:String(form.get("reason")||""),capex_impact:String(form.get("capex_impact")||"0"),opex_impact:String(form.get("opex_impact")||"")||undefined,programme_impact_days:String(form.get("programme_impact_days")||"")||undefined,quality_impact:String(form.get("quality_impact")||"neutral"),carbon_impact:String(form.get("carbon_impact")||"neutral"),alternative_ref:String(form.get("alternative_ref")||"")||undefined,lifecycle_impact:lifecycle,performance_impact:performance,lead_time_impact_days:String(form.get("lead_time_impact_days")||"")||undefined,approved_deviation_ref:String(form.get("approved_deviation_ref")||"")||undefined,requirement_impact_refs:reqs}});if(error)throw error;refresh("VE option proposed with commercial, lifecycle and performance impacts.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function decideVE(v:VEOption,decision:string){const reason=window.prompt(`Reason to ${decision} this VE option:`)||"";if(decision!=="review"&&!reason)return;const {error}=await supabase.rpc("decide_value_engineering_option",{target_option_id:v.id,target_decision:decision,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`VE option moved to ${decision}.`);}
 const planLines=(planId:string)=>lines.filter(l=>l.cost_plan_id===planId);
 return <>
  <section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/cost?project=${p.id}`} className={p.id===projectId?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div></section>
  {message&&<div className="note" style={{marginTop:16}}><b>Cost runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis" style={{marginTop:16}}>{[["Approved Estimate",approved?money(approved.total,approved.currency):"—"],["QTO Runs",String(qtos.length).padStart(2,"0")],["Approved QTO",String(approvedQto.length).padStart(2,"0")],["BOQ Lines",String(lines.length).padStart(2,"0")],["Open VE",String(ve.filter(v=>!["accepted","rejected"].includes(v.decision_state)).length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>10?18:30}}>{v}</div><div className="subtle">Live</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Start Object-based QTO</h3><form action={startQto}><div className="field"><label>Approved / issued model</label><select name="model_id" required>{models.map(m=><option key={m.id} value={m.id}>{m.model_name} · {m.status} · {shortHash(m.checksum)}</option>)}</select></div><div className="field"><label>Measurement rule set</label><input name="measurement_rule_set_ref" required placeholder="e.g. NRM2-2026 / project QS rules v3"/></div><div className="field"><label>Classification</label><input name="classification_ref" placeholder="Uniclass / OmniClass / project code"/></div><div className="field"><label>Exclusions JSON</label><textarea name="exclusions" rows={3} defaultValue="[]"/></div><div className="field"><label>Tolerance JSON</label><textarea name="tolerance" rows={3} defaultValue='{"quantity_percent":0.5}'/></div><button className="btn">Start QTO</button></form></section>
  <section className="panel"><h3>Complete QTO Engine Run</h3><form action={completeQto}><div className="field"><label>Queued / running QTO</label><select name="qto_run_id" required>{qtos.filter(q=>["queued","running"].includes(q.status)).map(q=><option key={q.id} value={q.id}>{q.id.slice(0,8)} · {q.measurement_rule_set_ref}</option>)}</select></div><div className="field"><label>Output SHA-256</label><input name="output_hash" minLength={64} maxLength={64}/></div><div className="field"><label>Quantities JSON</label><textarea name="quantities" rows={8} defaultValue={'[{"code":"Q-001","description":"Example measured item","discipline":"ARC","unit":"m2","quantity":0,"confidence":"B","source_object_refs":["IFC-GUID"],"measurement_rule_ref":"rule-001","formula":"net_area"}]'}/></div><div className="field"><label>Or record engine error code</label><input name="error_code" placeholder="Leave blank on success"/></div><button className="btn">Record QTO Result</button></form></section></div>
  <section className="panel" style={{marginTop:16}}><h3>QTO Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Run</th><th>Model hash</th><th>Rule set</th><th>Status</th><th>Output</th><th></th></tr></thead><tbody>{qtos.map(q=><tr key={q.id}><td>{q.id.slice(0,8)}</td><td><code>{shortHash(q.model_checksum)}</code></td><td>{q.measurement_rule_set_ref}</td><td><span className="badge">{pretty(q.status)}</span></td><td><code>{shortHash(q.output_hash)}</code>{q.error_code&&<div className="subtle">{q.error_code}</div>}</td><td>{q.status==="completed"&&<button className="btn ghost" type="button" onClick={()=>approveQto(q)}>Approve QTO</button>}</td></tr>)}{qtos.length===0&&<tr><td colSpan={6} className="subtle">No QTO runs yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Create Cost Plan</h3><form action={createPlan}><div className="field"><label>Approved QTO</label><select name="qto_run_id"><option value="">Manual / allowance-led plan</option>{approvedQto.map(q=><option key={q.id} value={q.id}>{q.id.slice(0,8)} · {q.measurement_rule_set_ref}</option>)}</select></div><div className="field-grid"><div className="field"><label>Stage</label><input name="stage" defaultValue="cost_plan"/></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div><div className="field"><label>Confidence</label><select name="confidence"><option>A</option><option>B</option><option selected={false}>C</option><option>D</option></select></div><div className="field"><label>Basis date</label><input name="basis_date" type="date"/></div><div className="field"><label>Contingencies</label><input name="contingencies" type="number" step="0.01" defaultValue="0"/></div><div className="field"><label>Professional fees</label><input name="professional_fees" type="number" step="0.01" defaultValue="0"/></div><div className="field"><label>Taxes</label><input name="taxes" type="number" step="0.01" defaultValue="0"/></div></div><button className="btn">Create Plan</button></form><div className="subtle" style={{marginTop:8}}>Current Project Configuration: <code>{shortHash(state.configuration_hash)}</code></div></section>
  <section className="panel"><h3>Add BOQ Line</h3><form action={addLine}><div className="field"><label>Draft plan</label><select name="cost_plan_id" required>{draftPlans.map(p=><option key={p.id} value={p.id}>v{p.version} · {p.stage}</option>)}</select></div><div className="field"><label>Quantity source</label><select name="quantity_item_id"><option value="">Manual item</option>{quantities.map(q=><option key={q.id} value={q.id}>{q.code} r{q.revision} · {q.quantity} {q.unit}</option>)}</select></div><input type="hidden" name="manual_item" value="false"/><div className="field-grid"><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Description</label><input name="description" required/></div><div className="field"><label>Unit</label><input name="unit"/></div><div className="field"><label>Quantity override</label><input name="quantity" type="number" step="0.0001"/></div><div className="field"><label>Rate</label><input name="rate" type="number" step="0.01" required/></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div><div className="field"><label>Rate source</label><input name="rate_source" required placeholder="Quote / tender / dataset ref"/></div><div className="field"><label>Rate date</label><input name="rate_date" type="date" required/></div><div className="field"><label>Confidence</label><select name="confidence" defaultValue="C"><option>A</option><option>B</option><option>C</option><option>D</option></select></div><div className="field"><label>Specification ref</label><input name="specification_ref"/></div><div className="field"><label>Package category</label><input name="package_category"/></div></div><div className="field"><label>Notes / manual basis</label><textarea name="notes" rows={2}/></div><button className="btn">Add BOQ Line</button></form></section></div>
  <section className="panel" style={{marginTop:16}}><h3>Cost Plans & BOQ</h3>{plans.map(p=><div key={p.id} className="note" style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><b>Plan v{p.version} · {p.stage}</b><div className="subtle">{pretty(p.status)} · {money(p.total,p.currency)} · confidence {p.confidence} · config <code>{shortHash(p.configuration_hash)}</code></div></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{p.status==="draft"&&<button className="btn ghost" type="button" onClick={()=>transitionPlan(p,"for_review")}>Send for Review</button>}{p.status==="for_review"&&<><button className="btn ghost" type="button" onClick={()=>transitionPlan(p,"draft")}>Return Draft</button><button className="btn" type="button" onClick={()=>transitionPlan(p,"approved")}>Approve</button></>}{p.status==="approved"&&<button className="btn ghost" type="button" onClick={()=>transitionPlan(p,"superseded")}>Supersede</button>}</div></div>{planLines(p.id).length>0&&<div style={{overflowX:"auto",marginTop:10}}><table className="table"><thead><tr><th>Code</th><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th><th>Source</th></tr></thead><tbody>{planLines(p.id).map((b:BOQLine)=><tr key={b.id}><td>{b.code}</td><td>{b.description}</td><td>{b.quantity} {b.unit}</td><td>{money(b.rate,b.currency)}</td><td>{money(b.total,b.currency)}</td><td>{b.manual_item?"Manual classified":`QTO ${b.quantity_item_id?.slice(0,8)}`}<div className="subtle">{b.rate_source} · {b.rate_date}</div></td></tr>)}</tbody></table></div>}</div>)}{plans.length===0&&<p className="subtle">No cost plans yet.</p>}</section>
  <div className="panel-grid"><section className="panel"><h3>Propose Value Engineering</h3><form action={proposeVE}><div className="field"><label>BOQ line</label><select name="source_boq_line_id"><option value="">System / design-level option</option>{lines.map(l=><option key={l.id} value={l.id}>{l.code} · {l.description}</option>)}</select></div><div className="field"><label>Proposal</label><input name="proposal" required/></div><div className="field"><label>Reason</label><textarea name="reason" rows={2} required/></div><div className="field-grid"><div className="field"><label>Discipline</label><input name="discipline"/></div><div className="field"><label>Alternative ref</label><input name="alternative_ref"/></div><div className="field"><label>Capex impact</label><input name="capex_impact" type="number" step="0.01" defaultValue="0"/></div><div className="field"><label>Opex impact</label><input name="opex_impact" type="number" step="0.01"/></div><div className="field"><label>Programme days</label><input name="programme_impact_days" type="number"/></div><div className="field"><label>Lead-time days</label><input name="lead_time_impact_days" type="number"/></div><div className="field"><label>Quality impact</label><select name="quality_impact"><option>positive</option><option>neutral</option><option>negative</option></select></div><div className="field"><label>Carbon impact</label><select name="carbon_impact"><option>positive</option><option>neutral</option><option>negative</option></select></div></div><div className="field"><label>Lifecycle impact JSON</label><textarea name="lifecycle_impact" rows={3} defaultValue="{}"/></div><div className="field"><label>Performance impact JSON</label><textarea name="performance_impact" rows={3} defaultValue='{"mandatory_performance":"unchanged"}'/></div><div className="field"><label>Requirement impact refs JSON</label><textarea name="requirement_impact_refs" rows={2} defaultValue="[]"/></div><div className="field"><label>Approved deviation ref, if mandatory performance changes</label><input name="approved_deviation_ref"/></div><button className="btn">Propose VE</button></form></section><section className="panel"><h3>VE Decision Ledger</h3>{ve.map(v=><div key={v.id} className="note" style={{marginBottom:8}}><b>{v.proposal}</b><div className="subtle">{pretty(v.decision_state)} · capex {money(v.capex_impact)} · programme {v.programme_impact_days??0}d · quality {v.quality_impact} · carbon {v.carbon_impact||"—"}</div>{!["accepted","rejected"].includes(v.decision_state)&&<div style={{display:"flex",gap:6,marginTop:6}}><button className="btn ghost" type="button" onClick={()=>decideVE(v,"review")}>Review</button><button className="btn" type="button" onClick={()=>decideVE(v,"accepted")}>Accept</button><button className="btn ghost" type="button" onClick={()=>decideVE(v,"rejected")}>Reject</button></div>}</div>)}{ve.length===0&&<p className="subtle">No VE options recorded.</p>}</section></div>
 </>;
}
