"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type Workspace={tokens:any[];components:any[];preferences:any;saved_views:any[];audits:any[];findings:any[];localisation:any[];glossary:any[];help_guides:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const parseJson=(v:FormDataEntryValue|null,fallback:any)=>{const s=String(v||"").trim();if(!s)return fallback;return JSON.parse(s);};

export default function DesignSystemGovernanceClient({organisationId,workspace}:{organisationId:string;workspace:Workspace}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const tokens=workspace.tokens||[],components=workspace.components||[],audits=workspace.audits||[],findings=workspace.findings||[];
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function prefs(form:FormData){try{const {error}=await supabase.rpc("upsert_user_preferences",{input_payload:{locale:String(form.get("locale")||"en-IN"),unit_system:String(form.get("unit_system")||"metric"),number_locale:String(form.get("number_locale")||"en-IN"),currency_code:String(form.get("currency_code")||"INR"),reduced_motion:form.get("reduced_motion")==="on",high_contrast:form.get("high_contrast")==="on",density:String(form.get("density")||"comfortable"),preferences:parseJson(form.get("preferences"),{})}});if(error)return setMessage(error.message);refresh("User preferences saved with explicit locale and unit policy.");}catch(e){fail(e);}}
 async function saveView(form:FormData){try{const projectId=String(form.get("project_id")||"").trim();const {error}=await supabase.rpc("save_user_view",{target_organisation_id:organisationId,target_project_id:projectId||null,input_payload:{name:String(form.get("name")||""),route:String(form.get("route")||""),filters:parseJson(form.get("filters"),{}),sort:parseJson(form.get("sort"),[]),layout:parseJson(form.get("layout"),{})}});if(error)return setMessage(error.message);refresh("Saved view updated for the authenticated user.");}catch(e){fail(e);}}
 async function token(form:FormData){try{const {error}=await supabase.rpc("create_design_token",{target_organisation_id:organisationId,input_payload:{token_key:String(form.get("token_key")||""),category:String(form.get("category")||""),value:parseJson(form.get("value"),{})}});if(error)return setMessage(error.message);refresh("Design token drafted with an immutable hash.");}catch(e){fail(e);}}
 async function tokenState(id:string,status:string){const reason=window.prompt(`${status} reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("transition_design_token",{target_id:id,target_status:status,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Design token moved to ${pretty(status)}.`);}
 async function component(form:FormData){try{const {error}=await supabase.rpc("create_ui_component_contract",{target_organisation_id:organisationId,input_payload:{component_key:String(form.get("component_key")||""),name:String(form.get("name")||""),semantics:parseJson(form.get("semantics"),{}),keyboard_contract:parseJson(form.get("keyboard_contract"),{}),error_contract:parseJson(form.get("error_contract"),{}),responsive_contract:parseJson(form.get("responsive_contract"),{})}});if(error)return setMessage(error.message);refresh("UI component contract drafted.");}catch(e){fail(e);}}
 async function componentState(id:string,status:string){const reason=window.prompt(`${status} reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("transition_ui_component_contract",{target_id:id,target_status:status,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`UI component contract moved to ${pretty(status)}.`);}
 async function audit(form:FormData){const {error}=await supabase.rpc("create_accessibility_audit",{target_organisation_id:organisationId,input_payload:{route:String(form.get("route")||""),commit_sha:String(form.get("commit_sha")||""),target_wcag:String(form.get("target_wcag")||"2.2 AA"),automated_report_ref:String(form.get("automated_report_ref")||"")}});if(error)return setMessage(error.message);refresh("Accessibility audit opened against an exact commit and route.");}
 async function finding(form:FormData){const {error}=await supabase.rpc("record_accessibility_finding",{target_audit_id:String(form.get("audit_id")||""),input_payload:{criterion:String(form.get("criterion")||""),severity:String(form.get("severity")||"medium"),issue:String(form.get("issue")||""),recovery_action:String(form.get("recovery_action")||""),evidence_ref:String(form.get("evidence_ref")||"")}});if(error)return setMessage(error.message);refresh("Accessibility finding recorded; high/critical open findings block a passing audit.");}
 async function finishAudit(id:string,status:string){const automated=window.prompt("Automated accessibility report reference");if(!automated?.trim())return;const keyboard=window.prompt("Manual keyboard evidence reference");if(!keyboard?.trim())return;const screen=window.prompt("Manual screen-reader evidence reference");if(!screen?.trim())return;const reason=window.prompt(`${status} review reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("complete_accessibility_audit",{target_audit_id:id,input_payload:{status,automated_report_ref:automated.trim(),keyboard_evidence_ref:keyboard.trim(),screen_reader_evidence_ref:screen.trim(),reason:reason.trim()}});if(error)return setMessage(error.message);refresh(`Accessibility audit ${status}.`);}
 async function registry(kind:string,form:FormData){try{const payload=kind==="localisation"?{locale:String(form.get("locale")||"en-IN"),key:String(form.get("key")||""),value:String(form.get("value")||"")} : kind==="glossary"?{locale:String(form.get("locale")||"en-IN"),term:String(form.get("term")||""),definition:String(form.get("definition")||"")} : {guide_key:String(form.get("guide_key")||""),title:String(form.get("title")||""),route:String(form.get("route")||""),content_ref:String(form.get("content_ref")||"")};const {error}=await supabase.rpc("create_ux_registry_entry",{target_organisation_id:organisationId,target_kind:kind,input_payload:payload});if(error)return setMessage(error.message);refresh(`${pretty(kind)} entry created.`);}catch(e){fail(e);}}
 const p=workspace.preferences||{};
 return <>
  {message&&<div className="note" data-live-message style={{marginBottom:16}}><b>Design system:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Published Tokens",String(tokens.filter(x=>x.status==="published").length)],["Published Components",String(components.filter(x=>x.status==="published").length)],["Accessibility Audits",String(audits.length)],["Open A11y Findings",String(findings.filter(x=>x.status==="open").length)],["Saved Views",String((workspace.saved_views||[]).length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>User Preference Centre</h3><form action={prefs}><div className="field-grid"><div className="field"><label>Locale</label><input name="locale" defaultValue={p.locale||"en-IN"}/></div><div className="field"><label>Unit system</label><select name="unit_system" defaultValue={p.unit_system||"metric"}><option>metric</option><option>imperial</option></select></div><div className="field"><label>Number locale</label><input name="number_locale" defaultValue={p.number_locale||"en-IN"}/></div><div className="field"><label>Currency</label><input name="currency_code" defaultValue={p.currency_code||"INR"}/></div><div className="field"><label>Density</label><select name="density" defaultValue={p.density||"comfortable"}><option>comfortable</option><option>compact</option></select></div></div><div style={{display:"flex",gap:16,margin:"12px 0"}}><label><input type="checkbox" name="reduced_motion" defaultChecked={!!p.reduced_motion}/> Reduced motion</label><label><input type="checkbox" name="high_contrast" defaultChecked={!!p.high_contrast}/> High contrast</label></div><div className="field"><label>Additional preferences JSON</label><textarea name="preferences" rows={3} defaultValue={JSON.stringify(p.preferences||{})}/></div><button className="btn">Save Preferences</button></form></section><section className="panel"><h3>Saved View</h3><form action={saveView}><div className="field-grid"><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Route</label><input name="route" required placeholder="/app/cost"/></div></div><div className="field"><label>Optional Project UUID</label><input name="project_id"/></div><div className="field-grid"><div className="field"><label>Filters JSON</label><textarea name="filters" rows={3} defaultValue="{}"/></div><div className="field"><label>Sort JSON</label><textarea name="sort" rows={3} defaultValue="[]"/></div></div><div className="field"><label>Layout JSON</label><textarea name="layout" rows={3} defaultValue="{}"/></div><button className="btn ghost">Save View</button></form></section></div>
  <div className="panel-grid"><section className="panel"><h3>Draft Design Token</h3><form action={token}><div className="field-grid"><div className="field"><label>Token key</label><input name="token_key" required/></div><div className="field"><label>Category</label><input name="category" required placeholder="colour / spacing / type / motion"/></div></div><div className="field"><label>Value JSON</label><textarea name="value" rows={4} required defaultValue="{}"/></div><button className="btn">Draft Token</button></form></section><section className="panel"><h3>Draft Component Contract</h3><form action={component}><div className="field-grid"><div className="field"><label>Component key</label><input name="component_key" required/></div><div className="field"><label>Name</label><input name="name" required/></div></div>{[["semantics","Semantic contract"],["keyboard_contract","Keyboard contract"],["error_contract","Error / recovery contract"],["responsive_contract","Responsive contract"]].map(([n,l])=><div className="field" key={n}><label>{l} JSON</label><textarea name={n} rows={3} defaultValue="{}"/></div>)}<button className="btn">Draft Component</button></form></section></div>
  <section className="panel"><h3>Design Tokens & Component Contracts</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Kind</th><th>Key</th><th>Version</th><th>Status</th><th>Hash</th><th>Action</th></tr></thead><tbody>{tokens.map(x=><tr key={`t-${x.id}`}><td>Token</td><td>{x.token_key}</td><td>{x.version}</td><td><span className="badge">{pretty(x.status)}</span></td><td><code>{short(x.token_hash)}</code></td><td>{x.status==="draft"?<button className="btn ghost" onClick={()=>tokenState(x.id,"review")}>Review</button>:x.status==="review"?<button className="btn" onClick={()=>tokenState(x.id,"published")}>Publish</button>:x.status==="published"?<button className="btn ghost" onClick={()=>tokenState(x.id,"retired")}>Retire</button>:null}</td></tr>)}{components.map(x=><tr key={`c-${x.id}`}><td>Component</td><td>{x.component_key}</td><td>{x.version}</td><td><span className="badge">{pretty(x.status)}</span></td><td><code>{short(x.component_hash)}</code></td><td>{x.status==="draft"?<button className="btn ghost" onClick={()=>componentState(x.id,"review")}>Review</button>:x.status==="review"?<button className="btn" onClick={()=>componentState(x.id,"published")}>Publish</button>:x.status==="published"?<button className="btn ghost" onClick={()=>componentState(x.id,"retired")}>Retire</button>:null}</td></tr>)}{!tokens.length&&!components.length&&<tr><td colSpan={6} className="subtle">No design tokens or component contracts exist.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Open Accessibility Audit</h3><form action={audit}><div className="field-grid"><div className="field"><label>Route</label><input name="route" required placeholder="/app/site"/></div><div className="field"><label>Exact Git commit SHA</label><input name="commit_sha" required minLength={7}/></div><div className="field"><label>WCAG target</label><input name="target_wcag" defaultValue="2.2 AA"/></div><div className="field"><label>Automated report reference</label><input name="automated_report_ref"/></div></div><button className="btn">Open Audit</button></form></section><section className="panel"><h3>Record Accessibility Finding</h3><form action={finding}><div className="field"><label>Audit</label><select name="audit_id" required>{audits.map(a=><option key={a.id} value={a.id}>{a.route} · {short(a.commit_sha)} · {a.status}</option>)}</select></div><div className="field-grid"><div className="field"><label>WCAG criterion</label><input name="criterion" required/></div><div className="field"><label>Severity</label><select name="severity"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div></div><div className="field"><label>Issue</label><textarea name="issue" rows={3} required/></div><div className="field"><label>Recovery action</label><textarea name="recovery_action" rows={3} required/></div><div className="field"><label>Evidence reference</label><input name="evidence_ref"/></div><button className="btn ghost" disabled={!audits.length}>Record Finding</button></form></section></div>
  <section className="panel"><h3>Accessibility Evidence Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Route / Commit</th><th>Target</th><th>Status</th><th>Automated</th><th>Keyboard</th><th>Screen Reader</th><th>Open High/Critical</th><th>Decision</th></tr></thead><tbody>{audits.map(a=>{const af=findings.filter(f=>f.audit_id===a.id);const blockers=af.filter(f=>f.status==="open"&&["high","critical"].includes(f.severity)).length;return <tr key={a.id}><td><b>{a.route}</b><div className="subtle"><code>{short(a.commit_sha)}</code></div></td><td>{a.target_wcag}</td><td><span className="badge">{a.status}</span></td><td>{a.automated_report_ref||"—"}</td><td>{a.keyboard_evidence_ref||"—"}</td><td>{a.screen_reader_evidence_ref||"—"}</td><td>{blockers}</td><td>{a.status==="draft"&&<div style={{display:"flex",gap:5}}><button className="btn" onClick={()=>finishAudit(a.id,"pass")}>Pass</button><button className="btn ghost" onClick={()=>finishAudit(a.id,"fail")}>Fail</button></div>}</td></tr>})}{!audits.length&&<tr><td colSpan={8} className="subtle">No accessibility evidence has been asserted. A pass cannot be created without automated, keyboard and screen-reader evidence.</td></tr>}</tbody></table></div></section>
  <div className="grid-3"><section className="panel"><h3>Localisation Entry</h3><form action={f=>registry("localisation",f)}><div className="field"><label>Locale</label><input name="locale" defaultValue="en-IN"/></div><div className="field"><label>Key</label><input name="key" required/></div><div className="field"><label>Value</label><textarea name="value" rows={3} required/></div><button className="btn ghost">Create Draft</button></form></section><section className="panel"><h3>Terminology Glossary</h3><form action={f=>registry("glossary",f)}><div className="field"><label>Locale</label><input name="locale" defaultValue="en-IN"/></div><div className="field"><label>Term</label><input name="term" required/></div><div className="field"><label>Definition</label><textarea name="definition" rows={3} required/></div><button className="btn ghost">Create Draft</button></form></section><section className="panel"><h3>Help / Guided Tour</h3><form action={f=>registry("help",f)}><div className="field"><label>Guide key</label><input name="guide_key" required/></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Route</label><input name="route"/></div><div className="field"><label>Content reference</label><input name="content_ref" required/></div><button className="btn ghost">Create Draft</button></form></section></div>
  <div className="note"><b>F31 pass rule.</b> A route cannot be marked accessible without an exact commit, automated report, manual keyboard evidence and manual screen-reader evidence; open high/critical findings block pass.</div>
 </>;
}
