"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type Intent={id:string;version:number;typology:string;optimisation_mode:string;mandatory_requirements:unknown;preferences:unknown;exclusions:unknown;seed:string;metric_set_version:string;status:string;content_hash?:string|null;approved_at?:string|null};
type Branch={id:string;name:string;parent_branch_id?:string|null;parent_commit_hash?:string|null;head_commit_hash:string;purpose:string;status:string;created_at:string};
type Instruction={id:string;branch_id:string;source_type:string;raw_input:string;structured_changes:unknown;status:string;input_hash:string;interpretation_hash:string;execution_hash?:string|null;created_at:string};
type ObjectRevision={id:string;branch_id:string;object_key:string;revision:number;state:string;geometry_hash?:string|null;properties:Record<string,unknown>;content_hash:string;created_at:string};
export type DesignReviewWorkspace={intents:Intent[];branches:Branch[];instructions:Instruction[];objects:ObjectRevision[]};
function json(value:FormDataEntryValue|null,fallback:unknown){try{return JSON.parse(String(value||""));}catch{return fallback;}}
export default function DesignReviewRuntimeClient({projectId,state}:{projectId:string;state:DesignReviewWorkspace}){
 const router=useRouter();const supabase=createClient();const [message,setMessage]=useState("");const [diff,setDiff]=useState<Array<Record<string,unknown>>>([]);const [busy,startTransition]=useTransition();const refresh=()=>startTransition(()=>router.refresh());const scenarioBranches=state.branches.filter(b=>b.name!=="main"&&b.status==="active");
 async function createIntent(form:FormData){const hard=json(form.get("mandatory_requirements"),null),preferences=json(form.get("preferences"),null),exclusions=json(form.get("exclusions"),null);if(!Array.isArray(hard)||!preferences||!Array.isArray(exclusions)){setMessage("Hard constraints and exclusions must be arrays; preferences must be valid JSON.");return;}setMessage("Creating design objective…");const {error}=await supabase.rpc("create_design_intent",{target_project_id:projectId,input_payload:{typology:String(form.get("typology")||""),optimisation_mode:String(form.get("optimisation_mode")||"balanced"),seed:String(form.get("seed")||"benchmark-v1"),metric_set_version:String(form.get("metric_set_version")||"feasibility-envelope-metrics@1.0.0"),mandatory_requirements:hard,preferences,exclusions,programme:{}}});if(error){setMessage(error.message);return;}setMessage("Design objective recorded as draft.");refresh();}
 async function approveIntent(id:string){const reason=window.prompt("Approval reason");if(!reason)return;const {error}=await supabase.rpc("approve_design_intent",{target_intent_id:id,target_reason:reason});if(error){setMessage(error.message);return;}setMessage("Design objective approved and prior dependent compiler results invalidated.");refresh();}
 async function createBranch(form:FormData){const main=state.branches.find(b=>b.name==="main");setMessage("Creating isolated design branch…");const {error}=await supabase.rpc("create_project_configuration_branch",{input_payload:{project_id:projectId,parent_branch_id:main?.id||null,name:String(form.get("name")||""),purpose:String(form.get("purpose")||"")}});if(error){setMessage(error.message);return;}setMessage("Isolated design branch created. Main remains unchanged.");refresh();}
 async function interpret(form:FormData){const changes=json(form.get("structured_changes"),null);if(!Array.isArray(changes)||!changes.length){setMessage("Structured changes must be a non-empty JSON array.");return;}const branch=String(form.get("branch_id")||"");if(!branch){setMessage("Choose a non-main branch.");return;}setMessage("Recording structured interpretation before execution…");const {error}=await supabase.rpc("interpret_design_change",{target_project_id:projectId,target_branch_id:branch,input_payload:{source_type:String(form.get("source_type")||"text"),raw_input:String(form.get("raw_input")||""),transcript:String(form.get("transcript")||"")||undefined,structured_changes:changes}});if(error){setMessage(error.message);return;}setMessage("Interpretation recorded as draft. No design object has changed.");refresh();}
 async function approveInstruction(id:string){const reason=window.prompt("Approval reason");if(!reason)return;const {error}=await supabase.rpc("approve_design_change_instruction",{target_instruction_id:id,target_reason:reason});if(error){setMessage(error.message);return;}setMessage("Instruction approved for controlled execution.");refresh();}
 async function executeInstruction(id:string){const reason=window.prompt("Execution reason");if(!reason)return;const {error}=await supabase.rpc("execute_design_change_instruction",{target_instruction_id:id,target_reason:reason});if(error){setMessage(error.message);return;}setMessage("Approved instruction executed on its isolated branch only.");refresh();}
 async function compare(form:FormData){const a=String(form.get("branch_a")||""),b=String(form.get("branch_b")||"");if(!a||!b){setMessage("Choose two branches.");return;}const {data,error}=await supabase.rpc("compare_object_revisions",{target_project_id:projectId,target_branch_a:a,target_branch_b:b});if(error){setMessage(error.message);return;}setDiff((data||[]) as Array<Record<string,unknown>>);setMessage("Object-level geometry/property diff calculated.");}
 async function runCompiler(){const approved=state.intents.find(i=>i.status==="approved");setMessage("Running deterministic compiler against approved design intent…");const {data,error}=await supabase.functions.invoke("compiler-run",{body:{project_id:projectId,objective:approved?.optimisation_mode||"balanced",seed:approved?.seed||"benchmark-v1"}});if(error){setMessage(error.message);return;}const r=data as {error?:string;input_hash?:string;output_hash?:string;candidates?:unknown[];blocked_reasons?:string[]};if(r.error){setMessage(r.error);return;}setMessage(`Compiler complete. Input ${r.input_hash?.slice(0,12)}… output ${r.output_hash?.slice(0,12)}… candidates ${r.candidates?.length||0}. ${r.blocked_reasons?.length?`Blocks: ${r.blocked_reasons.join(" | ")}`:""}`);refresh();}
 return <>
  {message&&<div className="note" role="status" style={{marginBottom:16}}><b>Design Review:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Design Intents",state.intents.length],["Active Branches",state.branches.filter(b=>b.status==="active").length],["Instructions",state.instructions.length],["Object Revisions",state.objects.length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:18}}><section className="panel"><h3>Design Objective</h3><form action={createIntent}><div className="field-grid"><div className="field"><label>Typology</label><input name="typology" required/></div><div className="field"><label>Optimisation mode</label><select name="optimisation_mode"><option value="balanced">Balanced</option><option value="commercial_yield">Commercial yield</option><option value="environmental">Environmental</option><option value="architecture">Architecture</option><option value="capex">CAPEX</option></select></div><div className="field"><label>Fixed seed</label><input name="seed" defaultValue="benchmark-v1" required/></div><div className="field"><label>Metric-set version</label><input name="metric_set_version" defaultValue="feasibility-envelope-metrics@1.0.0" required/></div></div><div className="field"><label>Hard constraints JSON</label><textarea name="mandatory_requirements" rows={6} defaultValue={'[{"metric":"open_space_percent","min":20}]'}/></div><div className="field"><label>Preferences JSON</label><textarea name="preferences" rows={4} defaultValue="{}"/></div><div className="field"><label>Exclusions JSON</label><textarea name="exclusions" rows={3} defaultValue="[]"/></div><button className="btn">Create Draft Objective</button></form><div style={{marginTop:16}}>{state.intents.map(i=><div className="note" key={i.id} style={{marginBottom:8}}><b>v{i.version} · {i.optimisation_mode}</b> · {i.status}<div className="subtle">Seed {i.seed} · Metrics {i.metric_set_version} · {i.content_hash?.slice(0,12)||"draft"}</div>{i.status==="draft"&&<button type="button" className="btn ghost" onClick={()=>approveIntent(i.id)} style={{marginTop:8}}>Approve Objective</button>}</div>)}</div><button className="btn" type="button" onClick={runCompiler}>Run Deterministic Compiler</button></section>
  <section className="panel"><h3>Scenario Branch</h3><form action={createBranch}><div className="field"><label>Name</label><input name="name" required placeholder="concept-option-a"/></div><div className="field"><label>Purpose</label><textarea name="purpose" rows={3} required/></div><button className="btn">Create Isolated Branch</button></form><div style={{marginTop:16}}>{state.branches.map(b=><div key={b.id} className="note" style={{marginBottom:8}}><b>{b.name}</b> · {b.status}<div className="subtle">Head {b.head_commit_hash.slice(0,12)}… · {b.purpose}</div></div>)}</div></section></div>
  <section className="panel" style={{marginTop:18}}><h3>Voice / Text Instruction Interpretation</h3><form action={interpret}><div className="field-grid"><div className="field"><label>Scenario branch</label><select name="branch_id" required defaultValue=""><option value="" disabled>Select non-main branch</option>{scenarioBranches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></div><div className="field"><label>Source type</label><select name="source_type"><option value="text">Text</option><option value="voice">Voice</option></select></div></div><div className="field"><label>Raw instruction</label><textarea name="raw_input" rows={4} required/></div><div className="field"><label>Transcript (voice only)</label><textarea name="transcript" rows={3}/></div><div className="field"><label>Structured changes JSON</label><textarea name="structured_changes" rows={8} defaultValue={'[{"action":"add","object_key":"room-001","properties":{"use":"guestroom"}}]'}/></div><button className="btn">Record Structured Interpretation</button></form><div style={{overflowX:"auto",marginTop:16}}><table className="table"><thead><tr><th>Instruction</th><th>Branch</th><th>Status</th><th>Hash</th><th>Authority</th></tr></thead><tbody>{state.instructions.map(i=><tr key={i.id}><td>{i.source_type}<br/><span className="subtle">{i.raw_input.slice(0,80)}</span></td><td>{state.branches.find(b=>b.id===i.branch_id)?.name||i.branch_id.slice(0,8)}</td><td><span className="badge">{i.status}</span></td><td><code>{i.interpretation_hash.slice(0,12)}…</code></td><td>{i.status==="draft"?<button className="btn ghost" onClick={()=>approveInstruction(i.id)}>Approve</button>:i.status==="approved"?<button className="btn" onClick={()=>executeInstruction(i.id)}>Execute on Branch</button>:i.execution_hash?<code>{i.execution_hash.slice(0,12)}…</code>:"—"}</td></tr>)}{!state.instructions.length&&<tr><td colSpan={5} className="subtle">No design instruction has been interpreted.</td></tr>}</tbody></table></div></section>
  <section className="panel" style={{marginTop:18}}><h3>Object-Level Revision Compare</h3><form action={compare}><div className="field-grid"><div className="field"><label>Revision branch A</label><select name="branch_a" required defaultValue=""><option value="" disabled>Select</option>{state.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></div><div className="field"><label>Revision branch B</label><select name="branch_b" required defaultValue=""><option value="" disabled>Select</option>{state.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></div></div><button className="btn">Compare Objects</button></form><div style={{overflowX:"auto",marginTop:16}}><table className="table"><thead><tr><th>Object</th><th>Change</th><th>Geometry</th><th>Properties</th><th>Revision A/B</th></tr></thead><tbody>{diff.map((d,idx)=><tr key={String(d.object_key||idx)}><td>{String(d.object_key||"")}</td><td><span className="badge">{String(d.change_type||"")}</span></td><td>{d.geometry_changed?"Changed":"Same"}</td><td>{d.properties_changed?"Changed":"Same"}</td><td>{String(d.revision_a??"—")} / {String(d.revision_b??"—")}</td></tr>)}{!diff.length&&<tr><td colSpan={5} className="subtle">Run a comparison to inspect expected object-level geometry/property changes.</td></tr>}</tbody></table></div></section>
 </>;
}
