export type DesignProject={id:string;code:string;name:string;typology?:string;stage?:string;status?:string};

export type ProgrammeBaseline={id:string;project_id:string;version:number;title:string;source_refs:unknown[];status:string;programme_hash:string;created_by?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string};
export type ProgrammeItem={id:string;programme_baseline_id:string;project_id:string;code:string;space_type:string;zone?:string|null;quantity:number;target_area_each?:number|null;area_unit:string;capacity?:number|null;adjacency:unknown[];operational_rules:Record<string,unknown>;priority:string;source_ref:string;confidence:string;notes?:string|null;item_hash:string};
export type RequirementRow={id:string;project_id:string;code:string;statement:string;category:string;status:string;criticality:string};
export type ProgrammeWorkspaceState={baselines:ProgrammeBaseline[];items:ProgrammeItem[];requirements:RequirementRow[]};
export const emptyProgrammeWorkspace:ProgrammeWorkspaceState={baselines:[],items:[],requirements:[]};

export type ClimateStudy={id:string;project_id:string;study_type:string;title:string;source_model_ref?:string|null;source_model_hash?:string|null;weather_source_ref?:string|null;engine_ref:string;engine_version:string;method_ref:string;input_snapshot:Record<string,unknown>;result_summary:Record<string,unknown>;evidence_refs:unknown[];input_hash:string;output_hash:string;confidence:string;status:string;created_by?:string|null;reviewed_by?:string|null;reviewed_at?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string};
export type ClimateWorkspaceState={studies:ClimateStudy[]};
export const emptyClimateWorkspace:ClimateWorkspaceState={studies:[]};

export type EconomicScenario={id:string;project_id:string;name:string;version:number;assumptions:Record<string,unknown>;assumption_sources:Record<string,unknown>;metrics:Record<string,unknown>;sensitivity:Record<string,unknown>;calculation_ref:string;model_version:string;input_hash:string;output_hash:string;confidence:string;status:string;created_by?:string|null;reviewed_by?:string|null;reviewed_at?:string|null;selected_by?:string|null;selected_at?:string|null;created_at:string};
export type EconomicsWorkspaceState={scenarios:EconomicScenario[]};
export const emptyEconomicsWorkspace:EconomicsWorkspaceState={scenarios:[]};

export type InteriorDNA={id:string;project_id:string;version:number;narrative:string;palette:unknown[];material_rules:unknown[];lighting_rules:unknown[];joinery_rules:unknown[];ffe_rules:unknown[];prohibited_elements:unknown[];source_refs:unknown[];confidence:string;status:string;dna_hash:string;created_by?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string};
export type InteriorRoom={id:string;project_id:string;dna_id:string;space_ref:string;version:number;design_revision_ref:string;model_revision_hash:string;layout_refs:unknown[];elevation_refs:unknown[];finishes:unknown[];lighting:unknown[];furniture:unknown[];visualisation_refs:unknown[];drawing_refs:unknown[];boq_refs:unknown[];coordination_checks:unknown[];status:string;package_hash:string;created_by?:string|null;created_at:string};
export type InteriorMaterial={id:string;project_id:string;dna_id:string;room_package_id?:string|null;base_selection_id?:string|null;material_code:string;product_ref?:string|null;source_ref:string;specification:Record<string,unknown>;cost_amount?:number|null;currency:string;lead_time_days?:number|null;performance:Record<string,unknown>;sustainability:Record<string,unknown>;substitution_delta:Record<string,unknown>;approved_deviation_ref?:string|null;status:string;selection_hash:string;created_by?:string|null;created_at:string};
export type InteriorShopDrawing={id:string;project_id:string;room_package_id:string;component_ref:string;version:number;dimensional_source_ref:string;dimensional_source_hash:string;drawing_refs:unknown[];detail_refs:unknown[];hardware_refs:unknown[];tolerances:Record<string,unknown>;boq_refs:unknown[];coordination_checks:unknown[];status:string;drawing_hash:string;created_by?:string|null;created_at:string};
export type InteriorRender={id:string;project_id:string;room_package_id:string;render_ref:string;design_revision_ref:string;model_revision_hash:string;dna_id:string;dna_hash:string;renderer:string;renderer_version:string;source_refs:unknown[];material_selection_refs:unknown[];geometry_source_ref?:string|null;conceptual:boolean;metadata_hash:string;created_by?:string|null;created_at:string};
export type InteriorsWorkspaceState={dna:InteriorDNA[];rooms:InteriorRoom[];materials:InteriorMaterial[];shop_drawings:InteriorShopDrawing[];renders:InteriorRender[]};
export const emptyInteriorsWorkspace:InteriorsWorkspaceState={dna:[],rooms:[],materials:[],shop_drawings:[],renders:[]};

export type ArchitecturePackage={id:string;project_id:string;stage:string;version:number;space_programme_ref:string;drawing_refs:unknown[];model_refs:unknown[];requirement_coverage_percent:number;design_option_id?:string|null;status:string;package_hash?:string|null;source_model_hash?:string|null;review_evidence_refs:unknown[];criticality:string;approval_credential_id?:string|null;approved_by?:string|null;approved_at?:string|null;issued_at?:string|null;issue_hash?:string|null;created_at:string};
export type DesignOption={id:string;project_id:string;name:string;status:string;generated_by:string;metrics:unknown;validation_summary:Record<string,unknown>;created_at:string};
export type ProfessionalReview={id:string;resource_type:string;resource_id:string;resource_hash:string;discipline:string;reviewer_user_id:string;credential_id:string;decision:string;comments?:string|null;reviewed_at?:string|null;created_at:string};
export type ArchitectureWorkspaceState={packages:ArchitecturePackage[];programme_baselines:ProgrammeBaseline[];design_options:DesignOption[];reviews:ProfessionalReview[]};
export const emptyArchitectureWorkspace:ArchitectureWorkspaceState={packages:[],programme_baselines:[],design_options:[],reviews:[]};

export type StructuralScheme={id:string;project_id:string;version:number;system:string;material_system:string;load_assumptions:Record<string,unknown>;design_standards:unknown[];analysis_model_ref?:string|null;calculation_run_ids:unknown[];model_refs:unknown[];drawing_refs:unknown[];status:string;source_architecture_package_id?:string|null;source_architecture_hash?:string|null;scheme_hash?:string|null;convergence_status:string;review_evidence_refs:unknown[];criticality:string;approval_credential_id?:string|null;approved_by?:string|null;approved_at?:string|null;issued_at?:string|null;issue_hash?:string|null;created_at:string};
export type CalculationRun={id:string;project_id:string;discipline:string;calculation_type:string;engine_id:string;engine_version:string;status:string;input_snapshot_ref:string;assumptions:unknown[];standard_references:unknown[];unit_system:string;output_ref?:string|null;result_summary?:Record<string,unknown>|null;evidence_refs:unknown[];input_hash:string;output_hash?:string|null;created_at:string};
export type EngineeringEngine={id:string;code:string;name:string;discipline:string;engine_type:string;version:string;certification_status:string;maximum_criticality:string;enabled:boolean};
export type StructureWorkspaceState={schemes:StructuralScheme[];architecture_packages:ArchitecturePackage[];calculation_runs:CalculationRun[];engines:EngineeringEngine[];reviews:ProfessionalReview[]};
export const emptyStructureWorkspace:StructureWorkspaceState={schemes:[],architecture_packages:[],calculation_runs:[],engines:[],reviews:[]};