"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {FinanceInvoice,FinanceJournal,FinanceWorkspaceState,FiscalPeriod} from "@/components/finance-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ");
const money=(n:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n||0));
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";

export default function FinanceWorkspaceClient({organisationId,state}:{organisationId:string;state:FinanceWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [paymentPayload,setPaymentPayload]=useState("");const [busy,startTransition]=useTransition();
 const accounts=state.accounts||[];const periods=state.periods||[];const journals=state.journals||[];const invoices=state.invoices||[];const projects=state.projects||[];const contracts=state.contracts||[];
 const accountName=(id:string)=>{const a=accounts.find(x=>x.id===id);return a?`${a.code} · ${a.name}`:id.slice(0,8)};
 const projectName=(id?:string|null)=>projects.find(x=>x.id===id)?.name||"—";
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}

 async function createAccount(form:FormData){const {error}=await supabase.rpc("create_finance_account",{target_organisation_id:organisationId,input_payload:{code:String(form.get("code")||""),name:String(form.get("name")||""),account_type:String(form.get("account_type")||"asset"),parent_id:String(form.get("parent_id")||"")||undefined,currency:String(form.get("currency")||"INR")}});if(error){setMessage(error.message);return;}refresh("Ledger account created under the governed chart of accounts.");}
 async function createPeriod(form:FormData){const {error}=await supabase.rpc("create_fiscal_period",{target_organisation_id:organisationId,input_payload:{period_code:String(form.get("period_code")||""),start_date:String(form.get("start_date")||""),end_date:String(form.get("end_date")||"")}});if(error){setMessage(error.message);return;}refresh("Open fiscal period created. Overlapping periods are rejected server-side.");}
 async function periodStatus(p:FiscalPeriod,status:string){const reason=window.prompt(`${status} reason for ${p.period_code}:`)||"";if(!reason)return;const {error}=await supabase.rpc("set_fiscal_period_status",{target_period_id:p.id,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`${p.period_code} moved to ${status}.`);}
 async function createJournal(form:FormData){const amount=Number(form.get("amount")||0);if(!(amount>0)){setMessage("Journal amount must be positive.");return;}const projectId=String(form.get("project_id")||"")||undefined;const costCode=String(form.get("cost_code")||"")||undefined;const memo=String(form.get("memo")||"")||undefined;const lines=[{account_id:String(form.get("debit_account_id")||""),project_id:projectId,cost_code:costCode,debit:amount,credit:0,currency:String(form.get("currency")||"INR"),memo},{account_id:String(form.get("credit_account_id")||""),project_id:projectId,cost_code:costCode,debit:0,credit:amount,currency:String(form.get("currency")||"INR"),memo}];const {error}=await supabase.rpc("create_finance_journal",{target_organisation_id:organisationId,input_payload:{posting_date:String(form.get("posting_date")||""),source_type:String(form.get("source_type")||"manual"),memo,lines}});if(error){setMessage(error.message);return;}refresh("Balanced draft journal created. A different authorised user must post it.");}
 async function postJournal(j:FinanceJournal){const reason=window.prompt(`Posting reason for ${j.journal_number}:`)||"";if(!reason)return;const {error}=await supabase.rpc("post_finance_journal",{target_journal_id:j.id,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`${j.journal_number} posted with an immutable hash.`);}
 async function reverseJournal(j:FinanceJournal){const reason=window.prompt(`Reversal reason for ${j.journal_number}:`)||"";if(!reason)return;const date=window.prompt("Reversal posting date (YYYY-MM-DD):",new Date().toISOString().slice(0,10))||"";if(!date)return;const {error}=await supabase.rpc("create_finance_reversal",{target_journal_id:j.id,target_posting_date:date,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`Draft reversal created for ${j.journal_number}; it requires independent posting.`);}
 async function createInvoice(form:FormData){const projectId=String(form.get("project_id")||"")||undefined;const contractId=String(form.get("contract_id")||"")||undefined;const {error}=await supabase.rpc("create_invoice_draft",{input_payload:{organisation_id:organisationId,project_id:projectId,contract_id:contractId,invoice_number:String(form.get("invoice_number")||""),currency:String(form.get("currency")||"INR"),issue_date:String(form.get("issue_date")||""),due_date:String(form.get("due_date")||""),metadata:{billing_basis:String(form.get("billing_basis")||"contract_milestone")},lines:[{description:String(form.get("description")||""),quantity:Number(form.get("quantity")||1),rate:Number(form.get("rate")||0),gst_rate:Number(form.get("gst_rate")||0),sort_order:1}]}});if(error){setMessage(error.message);return;}refresh("Invoice draft created against the selected project/contract. Issuance remains maker-checker controlled.");}
 async function issueInvoice(i:FinanceInvoice){const {error}=await supabase.rpc("issue_invoice",{target_invoice_id:i.id});if(error){setMessage(error.message);return;}refresh(`${i.invoice_number} issued by an independent finance checker.`);}
 async function preparePayment(i:FinanceInvoice){const {data,error}=await supabase.rpc("prepare_invoice_payment",{target_invoice_id:i.id});if(error){setMessage(error.message);return;}setPaymentPayload(JSON.stringify(data,null,2));setMessage(`Payment intent prepared for ${i.invoice_number}. Provider capture remains an external gateway action and is not fabricated.`);}
 const journalTotal=(id:string)=>state.journal_lines.filter(l=>l.journal_id===id).reduce((s,l)=>s+Number(l.debit||0),0);
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Finance runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Issued Invoices",money(state.summary.issued_invoice_total)],["Receivables",money(state.summary.receivables)],["TDS Receivable",money(state.summary.tds_receivable)],["Applied Cash",money(state.summary.cash_received)],["Posted Journals",String(state.summary.posted_journal_count).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>11?18:30}}>{v}</div><div className="subtle">Live ledger state</div></div>)}</div>

  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Chart of Accounts</h3><form action={createAccount}><div className="field-grid"><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Type</label><select name="account_type"><option>asset</option><option>liability</option><option>equity</option><option>income</option><option>expense</option></select></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div><div className="field"><label>Parent</label><select name="parent_id"><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></div></div><button className="btn">Create Account</button></form><div style={{marginTop:10,maxHeight:300,overflow:"auto"}}>{accounts.map(a=><div className="note" key={a.id} style={{marginBottom:6}}><b>{a.code}</b> · {a.name}<div className="subtle">{pretty(a.account_type)} · {a.currency||"multi-currency"}</div></div>)}{accounts.length===0&&<div className="subtle">No ledger accounts exist yet.</div>}</div></section>
   <section className="panel"><h3>Fiscal Period Control</h3><form action={createPeriod}><div className="field-grid"><div className="field"><label>Period code</label><input name="period_code" required placeholder="FY27-P01"/></div><div className="field"><label>Start</label><input name="start_date" type="date" required/></div><div className="field"><label>End</label><input name="end_date" type="date" required/></div></div><button className="btn">Create Period</button></form>{periods.map(p=><div className="note" key={p.id} style={{marginTop:7}}><b>{p.period_code}</b> · {p.start_date} → {p.end_date} · <span className="badge">{p.status}</span><div style={{marginTop:5}}>{p.status==="open"?<button className="btn ghost" type="button" onClick={()=>periodStatus(p,"closed")}>Close Period</button>:<button className="btn ghost" type="button" onClick={()=>periodStatus(p,"open")}>Admin Reopen</button>}</div></div>)}{periods.length===0&&<div className="note" style={{marginTop:8}}>Posting correctly fails closed until an open fiscal period covers the journal date.</div>}</section>
  </div>

  <section className="panel"><h3>Balanced Journal</h3><form action={createJournal}><div className="field-grid"><div className="field"><label>Posting date</label><input name="posting_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Source type</label><input name="source_type" required defaultValue="manual"/></div><div className="field"><label>Project</label><select name="project_id"><option value="">Organisation level</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Cost code</label><input name="cost_code"/></div><div className="field"><label>Debit account</label><select name="debit_account_id" required>{accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></div><div className="field"><label>Credit account</label><select name="credit_account_id" required>{accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></div><div className="field"><label>Amount</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR" required/></div></div><div className="field"><label>Memo</label><input name="memo"/></div><button className="btn" disabled={accounts.length<2}>Create Balanced Draft</button></form>{accounts.length<2&&<div className="note" style={{marginTop:8}}>At least two active ledger accounts are required.</div>}</section>

  <section className="panel"><h3>Journal Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Journal</th><th>Date</th><th>Source</th><th>Debit</th><th>Status</th><th>Hash / Reversal</th><th>Action</th></tr></thead><tbody>{journals.map(j=><tr key={j.id}><td><b>{j.journal_number}</b><div className="subtle">{j.memo||""}</div></td><td>{j.posting_date}</td><td>{pretty(j.source_type)}</td><td>{money(journalTotal(j.id))}</td><td><span className="badge">{j.status}</span></td><td><code>{shortHash(j.posted_hash)}</code>{j.reversal_of_id&&<div className="subtle">Reverses {j.reversal_of_id.slice(0,8)}</div>}</td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{j.status==="draft"&&<button className="btn ghost" type="button" onClick={()=>postJournal(j)}>Independent Post</button>}{j.status==="posted"&&!journals.some(x=>x.reversal_of_id===j.id&&["draft","posted"].includes(x.status))&&<button className="btn ghost" type="button" onClick={()=>reverseJournal(j)}>Create Reversal</button>}</div></td></tr>)}{journals.length===0&&<tr><td colSpan={7} className="subtle">No journals exist yet.</td></tr>}</tbody></table></div></section>

  <section className="panel"><h3>Contract-to-Cash Invoice</h3><form action={createInvoice}><div className="field-grid"><div className="field"><label>Invoice number</label><input name="invoice_number" required/></div><div className="field"><label>Project</label><select name="project_id"><option value="">Organisation level</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Active contract</label><select name="contract_id"><option value="">No contract</option>{contracts.filter(c=>c.status==="active"&&c.execution_hash).map(c=><option key={c.id} value={c.id}>{c.contract_type||"Contract"} · {projectName(c.project_id)}</option>)}</select></div><div className="field"><label>Issue date</label><input name="issue_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Due date</label><input name="due_date" type="date" required/></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div><div className="field"><label>Description</label><input name="description" required/></div><div className="field"><label>Quantity</label><input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" required/></div><div className="field"><label>Rate</label><input name="rate" type="number" min="0" step="0.01" required/></div><div className="field"><label>GST %</label><input name="gst_rate" type="number" min="0" step="0.01" defaultValue="0" required/></div></div><input type="hidden" name="billing_basis" value="contract_milestone"/><button className="btn">Create Invoice Draft</button></form><div className="note" style={{marginTop:8}}><b>Tax evidence boundary.</b> The draft stores the explicit rate used. Effective-dated tax-rule resolution and statutory provider issuance are governed separately; the platform does not claim IRN/QR or statutory filing success unless the corresponding integration confirms it.</div></section>

  <section className="panel"><h3>Invoice / Payment Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Invoice</th><th>Project</th><th>Total</th><th>Paid / TDS</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><b>{i.invoice_number}</b><div className="subtle">{i.issue_date} · due {i.due_date}</div></td><td>{projectName(i.project_id)}</td><td>{money(i.total,i.currency)}</td><td>{money(i.amount_paid,i.currency)}<div className="subtle">TDS {money(i.tds_receivable,i.currency)}</div></td><td><span className="badge">{pretty(i.status)}</span></td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{i.status==="draft"&&<button className="btn ghost" type="button" onClick={()=>issueInvoice(i)}>Independent Issue</button>}{["issued","part_paid","overdue"].includes(i.status)&&<button className="btn ghost" type="button" onClick={()=>preparePayment(i)}>Prepare Payment</button>}</div></td></tr>)}{invoices.length===0&&<tr><td colSpan={6} className="subtle">No invoices exist yet.</td></tr>}</tbody></table></div>{paymentPayload&&<div className="note" style={{marginTop:10}}><b>Prepared payment payload</b><pre style={{whiteSpace:"pre-wrap",fontSize:11,marginBottom:0}}>{paymentPayload}</pre></div>}</section>

  <section className="panel"><h3>Tax Determination Provenance</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Date</th><th>Source</th><th>Status</th><th>Rules</th><th>Components</th></tr></thead><tbody>{state.tax_determinations.map(t=><tr key={t.id}><td>{t.transaction_date}</td><td>{t.source_type}</td><td><span className="badge">{pretty(t.status)}</span></td><td>{Array.isArray(t.rule_ids)?t.rule_ids.length:0}</td><td>{Array.isArray(t.components)?t.components.length:0}</td></tr>)}{state.tax_determinations.length===0&&<tr><td colSpan={5} className="subtle">No governed tax determination has been recorded yet.</td></tr>}</tbody></table></div></section>
 </>;
}
