"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {InteriorRender,InteriorRoom} from "@/components/design-domain-runtime-types";

const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseArray(v:FormDataEntryValue|null){const raw=String(v||"").trim();if(!raw)return[];const parsed=JSON.parse(raw) as unknown;if(!Array.isArray(parsed))throw new Error("Expected a JSON array");return parsed;}
export default function InteriorRenderEvidenceClient({projectId,rooms,renders}:{projectId:string;rooms:InteriorRoom[];renders:InteriorRender[]}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const eligible=rooms.filter(r=>["approved","issued"].includes(r.status));
 async function register(form:FormData){try{const {error}=await supabase.rpc("register_interior_render",{target_project_id:projectId,input_payload:{room_package_id:String(form.get("room_package_id")||""),render_ref:String(form.get("render_ref")||""),renderer:String(form.get("renderer")||""),renderer_version:String(form.get("renderer_version")||""),source_refs:parseArray(form.get("source_refs")),material_selection_refs:parseArray(form.get("material_selection_refs")),geometry_source_ref:String(form.get("geometry_source_ref")||"")||undefined,conceptual:String(form.get("conceptual")||"true")==="true"}});if(error){setMessage(error.message);return;}setMessage("Render evidence registered against the exact approved room, DNA and model revision.");startTransition(()=>router.refresh());}catch(e){setMessage(e instanceof Error?e.message:"Invalid render evidence payload");}}
 return <section className="panel"><div className="topbar"><div><h3>Render Revision Evidence</h3><div className="subtle">Every registered render pins the room package, Design DNA hash, design revision and model revision SHA-256 used to produce it.</div></div></div>{message&&<div className="note" style={{marginBottom:14}}>{message}{busy?" Refreshing…":""}</div>}<div className="panel-grid"><div><form action={register}><div className="field"><label>Approved / issued room package</label><select name="room_package_id" required>{eligible.map(r=><option key={r.id} value={r.id}>{r.space_ref} v{r.version} · {short(r.model_revision_hash)}</option>)}</select></div><div className="field"><label>Render reference</label><input name="render_ref" required placeholder="render://artifact-or-file-reference"/></div><div className="field-grid"><div className="field"><label>Renderer</label><input name="renderer" required placeholder="renderer/provider"/></div><div className="field"><label>Renderer version</label><input name="renderer_version" required/></div></div><div className="field"><label>Source references JSON</label><textarea name="source_refs" rows={3} placeholder='["drawing://...","model://..."]'/></div><div className="field"><label>Material selection refs JSON</label><textarea name="material_selection_refs" rows={3} placeholder='["material-selection-uuid"]'/></div><div className="field"><label>Geometry source reference</label><input name="geometry_source_ref" placeholder="Required for non-conceptual render"/></div><div className="field"><label>Classification</label><select name="conceptual" defaultValue="true"><option value="true">Conceptual</option><option value="false">Source-linked / non-conceptual</option></select></div><button className="btn" disabled={eligible.length===0}>Register Render Evidence</button></form></div><div><h4>Evidence Register</h4><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Render</th><th>Revision</th><th>Renderer</th><th>Class</th><th>Evidence Hash</th></tr></thead><tbody>{renders.map(r=><tr key={r.id}><td>{r.render_ref}</td><td><div>{r.design_revision_ref}</div><code>{short(r.model_revision_hash)}</code></td><td>{r.renderer} · {r.renderer_version}</td><td><span className="badge">{r.conceptual?"Conceptual":"Source Linked"}</span></td><td><code>{short(r.metadata_hash)}</code></td></tr>)}{renders.length===0&&<tr><td colSpan={5} className="subtle">No render evidence has been registered yet.</td></tr>}</tbody></table></div></div></div></section>;
}