export type ProjectRow={id:string;code:string;name:string;typology:string;stage:string;criticality:string;status:string};

export type ModelRow={id:string;project_id:string;discipline:string;model_name:string;format:string;schema_version?:string|null;object_key:string;checksum:string;coordinate_system?:string|null;status:string;revision?:string|number|null;parent_model_id?:string|null;validation_summary?:Record<string,unknown>|null;validation_hash?:string|null;approved_by?:string|null;approved_at?:string|null;issued_by?:string|null;issued_at?:string|null;created_at:string;updated_at:string};
export type ModelValidationRun={id:string;project_id:string;model_id:string;validation_type:string;adapter_key?:string|null;adapter_version?:string|null;passed:boolean;result_hash:string;findings:unknown[];evidence_refs:unknown[];created_by?:string|null;created_at:string};
export type ModelIssue={id:string;issue_number:string;title:string;status:string;priority:string;criticality:string;updated_at:string};
export type ModelWorkspaceState={models:ModelRow[];validation_runs:ModelValidationRun[];issues:ModelIssue[]};
export const emptyModelWorkspace:ModelWorkspaceState={models:[],validation_runs:[],issues:[]};

export type QTORun={id:string;project_id:string;model_id:string;model_checksum:string;measurement_rule_set_ref:string;classification_ref?:string|null;exclusions:unknown[];tolerance:Record<string,unknown>;input_hash:string;output_hash?:string|null;status:string;error_code?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string;updated_at:string};
export type QuantityItem={id:string;project_id:string;code:string;description:string;discipline:string;unit:string;quantity:number;source:string;source_reference?:string|null;confidence:string;revision:number;qto_run_id?:string|null;source_object_refs:unknown[];measurement_rule_ref?:string|null;formula?:string|null;source_revision_hash?:string|null;quantity_hash?:string|null};
export type CostPlan={id:string;project_id:string;version:number;stage:string;currency:string;contingencies:number;professional_fees:number;taxes:number;total:number;confidence:string;basis_date:string;status:string;qto_run_id?:string|null;baseline_plan_id?:string|null;configuration_hash?:string|null;approved_hash?:string|null;approved_by?:string|null;approved_at?:string|null;created_at:string};
export type BOQLine={id:string;cost_plan_id:string;quantity_item_id?:string|null;code:string;description:string;unit:string;quantity:number;rate:number;currency:string;total:number;confidence:string;rate_source?:string|null;rate_date?:string|null;revision:string;notes?:string|null;manual_item:boolean;source_hash?:string|null};
export type VEOption={id:string;project_id:string;proposal:string;reason:string;capex_impact:number;opex_impact?:number|null;programme_impact_days?:number|null;quality_impact:string;carbon_impact?:string|null;decision_state:string;source_boq_line_id?:string|null;alternative_ref?:string|null;lifecycle_impact?:Record<string,unknown>;performance_impact?:Record<string,unknown>;lead_time_impact_days?:number|null;approved_deviation_ref?:string|null;created_at:string};
export type CostWorkspaceState={configuration_hash:string;models:ModelRow[];qto_runs:QTORun[];quantities:QuantityItem[];cost_plans:CostPlan[];boq_lines:BOQLine[];ve_options:VEOption[]};
export const emptyCostWorkspace:CostWorkspaceState={configuration_hash:"",models:[],qto_runs:[],quantities:[],cost_plans:[],boq_lines:[],ve_options:[]};

export type Vendor={id:string;organisation_id:string;legal_name:string;display_name?:string|null;gstin?:string|null;pan?:string|null;udyam_number?:string|null;categories?:unknown[];kyc_status:string;status:string;metadata?:Record<string,unknown>};
export type TenderPackage={id:string;project_id:string;package_code:string;title:string;status:string;bid_due_at?:string|null;opening_at?:string|null;opened_at?:string|null;opened_by?:string|null;selected_bid_id?:string|null;award_decision_hash?:string|null;award_reason?:string|null;created_at:string;updated_at:string};
export type BidCount={tender_package_id:string;submitted_count:number};
export type Bid={id:string;tender_package_id:string;vendor_id:string;status:string;currency:string;total:number;submitted_at?:string|null;created_at:string};
export type BidEvaluation={id:string;bid_id:string;evaluation_type:string;decision:string;score?:number|null;normalised_total?:number|null;evaluation_hash:string;reviewed_by?:string|null;created_at:string};
export type PurchaseOrder={id:string;project_id:string;tender_package_id:string;selected_bid_id:string;vendor_id:string;po_number:string;version:number;currency:string;total:number;approved_variation_total:number;decision_hash:string;status:string;created_at:string;updated_at:string};
export type GoodsReceipt={id:string;project_id:string;purchase_order_id:string;grn_number:string;status:string;received_at:string;created_at:string};
export type VendorInvoice={id:string;project_id:string;purchase_order_id:string;invoice_number:string;invoice_total:number;match_status:string;status:string;created_at:string};
export type ProcurementWorkspaceState={vendors:Vendor[];packages:TenderPackage[];bid_counts:BidCount[];bids:Bid[];evaluations:BidEvaluation[];purchase_orders:PurchaseOrder[];goods_receipts:GoodsReceipt[];vendor_invoices:VendorInvoice[];approved_boq_lines:BOQLine[]};
export const emptyProcurementWorkspace:ProcurementWorkspaceState={vendors:[],packages:[],bid_counts:[],bids:[],evaluations:[],purchase_orders:[],goods_receipts:[],vendor_invoices:[],approved_boq_lines:[]};

export type SiteActivity={id:string;project_id:string;wbs_code:string;name:string;state:string;progress_percent:number;planned_start?:string|null;planned_finish?:string|null;actual_start?:string|null;actual_finish?:string|null;updated_at:string};
export type SiteDiary={id:string;project_id:string;diary_date:string;status:string;weather:Record<string,unknown>;manpower:unknown[];equipment:unknown[];progress:unknown[];photos:unknown[];notes?:string|null;created_at:string};
export type SiteObservation={id:string;project_id:string;observation_number:string;observation_type:string;title:string;description:string;criticality:string;status:string;location_ref?:string|null;source_model_id?:string|null;source_revision_hash?:string|null;observed_at:string};
export type InspectionTestPlan={id:string;project_id:string;code:string;work_package:string;activity:string;status:string;acceptance_criteria:unknown[];responsible_party:string;created_at:string};
export type InspectionRecord={id:string;project_id:string;itp_id:string;result:string;location_ref?:string|null;evidence_refs:unknown[];non_conformance_id?:string|null;source_model_id?:string|null;source_revision_hash?:string|null;inspected_at:string};
export type NCR={id:string;project_id:string;number:string;title:string;criticality:string;status:string;disposition:string;location_ref?:string|null;created_at:string};
export type ProgressMeasurement={id:string;project_id:string;activity_id?:string|null;purchase_order_id?:string|null;boq_line_id?:string|null;location_ref?:string|null;measured_quantity:number;unit:string;evidence_refs:unknown[];status:string;created_at:string};
export type ProgressClaim={id:string;project_id:string;contractor_id:string;period_from:string;period_to:string;gross_claim:number;certified_payable:number;status:string;created_at:string};
export type SiteVariation={id:string;project_id:string;purchase_order_id?:string|null;variation_ref:string;description:string;amount:number;status:string;decision_hash?:string|null;created_at:string};
export type OfflinePackage={id:string;project_id:string;user_id:string;source_hash:string;downloaded_at:string;expires_at?:string|null;status:string};
export type SiteWorkspaceState={activities:SiteActivity[];diaries:SiteDiary[];observations:SiteObservation[];rfis:ModelIssue[];itps:InspectionTestPlan[];inspections:InspectionRecord[];ncrs:NCR[];measurements:ProgressMeasurement[];claims:ProgressClaim[];variations:SiteVariation[];offline_packages:OfflinePackage[]};
export const emptySiteWorkspace:SiteWorkspaceState={activities:[],diaries:[],observations:[],rfis:[],itps:[],inspections:[],ncrs:[],measurements:[],claims:[],variations:[],offline_packages:[]};

export type RealityCapture={id:string;project_id:string;capture_type:string;capture_ref:string;model_id?:string|null;model_checksum?:string|null;coordinate_system?:string|null;comparison_status:string;captured_at:string;registration_hash?:string|null;comparison_hash?:string|null;tolerance:Record<string,unknown>;capture_provenance:Record<string,unknown>};
export type RealityDeviation={id:string;comparison_id:string;project_id:string;model_object_ref?:string|null;location_ref?:string|null;deviation_type:string;measured_value?:number|null;permitted_tolerance?:number|null;unit?:string|null;severity:string;status:string;confidence?:number|null;evidence_refs:unknown[];review_note?:string|null;decision_hash?:string|null;linked_issue_id?:string|null;linked_ncr_id?:string|null;created_at:string};
export type RealityWorkspaceState={approved_models:ModelRow[];captures:RealityCapture[];deviations:RealityDeviation[];open_ncrs:NCR[]};
export const emptyRealityWorkspace:RealityWorkspaceState={approved_models:[],captures:[],deviations:[],open_ncrs:[]};

export type HandoverItem={id:string;project_id:string;item_code:string;category:string;title:string;mandatory:boolean;evidence_refs:unknown[];status:string;submitted_by?:string|null;accepted_by?:string|null;accepted_at?:string|null;created_at:string;updated_at:string};
export type HandoverException={id:string;project_id:string;handover_item_id:string;reason:string;evidence_refs:unknown[];status:string;requested_by?:string|null;decided_by?:string|null;decided_at?:string|null;created_at:string};
export type AssetPassport={id:string;project_id:string;asset_code:string;asset_type:string;system_code?:string|null;install_location?:string|null;manufacturer?:string|null;model?:string|null;serial_number?:string|null;warranty_from?:string|null;warranty_until?:string|null;document_refs:unknown[];commissioning_refs:unknown[];operational_status:string;verified_by?:string|null;verified_at?:string|null;source_building_passport_hash?:string|null};
export type MaterialPassport={id:string;project_id:string;material_code:string;name:string;manufacturer?:string|null;product_code?:string|null;batch_ref?:string|null;install_locations:unknown[];quantity?:number|null;unit?:string|null;warranty_until?:string|null;evidence_refs:unknown[];created_at:string};
export type CommissioningRecord={id:string;project_id:string;system_code:string;asset_code?:string|null;test_type:string;procedure_ref:string;test_date:string;result:string;evidence_refs:unknown[];accepted_by?:string|null;accepted_at?:string|null;created_at:string};
export type BuildingPassport={id:string;project_id:string;version:number;snapshot_hash:string;mandatory_gap_refs:unknown[];exception_refs:unknown[];status:string;compiled_by?:string|null;issued_by?:string|null;compiled_at:string;issued_at?:string|null};
export type MaintenanceWorkOrder={id:string;project_id:string;asset_passport_id?:string|null;title:string;type:string;priority:string;due_at?:string|null;assignee_ref?:string|null;status:string;evidence_refs:unknown[];closed_at?:string|null;created_at:string;updated_at:string};
export type TwinBinding={id:string;project_id:string;asset_passport_id:string;provider_key:string;external_asset_ref:string;telemetry_schema:Record<string,unknown>;status:string;last_seen_at?:string|null;created_at:string;updated_at:string};
export type HandoverWorkspaceState={items:HandoverItem[];exceptions:HandoverException[];assets:AssetPassport[];materials:MaterialPassport[];commissioning:CommissioningRecord[];passports:BuildingPassport[];work_orders:MaintenanceWorkOrder[];twin_bindings:TwinBinding[];models:Array<Pick<ModelRow,'id'|'model_name'|'discipline'|'revision'|'status'|'checksum'>>;documents:Array<{id:string;document_number:string;title:string;revision:string;status:string;cde_state:string}>};
export const emptyHandoverWorkspace:HandoverWorkspaceState={items:[],exceptions:[],assets:[],materials:[],commissioning:[],passports:[],work_orders:[],twin_bindings:[],models:[],documents:[]};
