"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type System={id:string;discipline:string;system_code:string;name:string;status:string};
type Model={id:string;name:string;discipline:string;revision:string;checksum:string;status:string};
type Calc={id:string;discipline:string;calculation_type:string;status:string;input_hash:string;output_hash?:string|null};
type Load={id:string;system_id:string;calculation_run_id:string;source_model_hash:string;status:string;load_hash:string};
type Route={id:string;system_id:string;route_code:string;route_geometry_ref?:string|null;status:string;infeasible_reasons:unknown[];route_hash:string};
type Equipment={id:string;system_id:string;equipment_code:string;required_capacity:number;selected_capacity:number;capacity_unit:string;reconciliation_status:string;status:string;reconciliation_hash:string};
type Package={id:string;discipline:string;version:number;criticality:string;status:string;package_hash:string;issue_hash?:string|null};
type Invalidation={id:string;prior_model_hash:string;new_model_hash:string;affected_load_ids:unknown[];affected_route_ids:unknown[];affected_equipment_ids:unknown[];affected_package_ids:unknown[];invalidation_hash:string;detected_at:string};
export type MepWorkspace={systems:System[];models:Model[];calculations:Calc[];loads:Load[];routes:Route[];equipment:Equipment[];packages:Package[];invalidations:Invalidation[]};
type Credential={id:string;discipline?:string|null;verification_status:string;valid_until?:string|null;registration_number:string};
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const array=(f:FormData,k:string)=>{const raw=String(f.get(k)||"").trim();if(!raw)return[];const v=JSON.parse(raw) as unknown;if(!Array.isArray(v))throw new Error(`${k} must be a JSON array`);return v;};
const obj=(f:FormData,k:string)=>{const raw=String(f.get(k)||"").trim();if(!raw)return{};const v=JSON.parse(raw) as unknown;if(!v||Array.isArray(v)||typeof v!=="object")throw new Error(`${k} must be a JSON object`);return v;};
export default function MepRuntimeClient({projectId,state,credentials}:{projectId:string;state:MepWorkspace;credentials:Credential[]}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const refresh=(m:string)=>{setMessage(m);startTransition(()=>router.refresh());};
 async function call(name:string,args:Record<string,unknown>,ok:string){const {data,error}=await supabase.rpc(name,args);if(error){setMessage(error.message);return null;}refresh(ok);return data;}
 async function system(f:FormData){try{await call("register_mep_system",{target_project_id:projectId,target_discipline:String(f.get("discipline")||""),target_system_code:String(f.get("code")||""),target_name:String(f.get("name")||""),target_design_criteria:obj(f,"criteria"),target_reason:String(f.get("reason")||"")},"MEP system registered with governed criteria.");}catch(e){setMessage(e instanceof Error?e.message:"Invalid payload");}}
 async function load(f:FormData){await call("record_mep_load",{target_project_id:projectId,input_payload:{system_id:String(f.get("system")||""),calculation_run_id:String(f.get("calc")||""),source_model_id:String(f.get("model")||"")}},"Load record pinned to the exact calculation and model revision.");}
 async function route(f:FormData){try{const result=await call("propose_mep_route",{target_project_id:projectId,input_payload:{system_id:String(f.get("system")||""),source_model_id:String(f.get("model")||""),calculation_run_id:String(f.get("calc")||"")||undefined,route_code:String(f.get("code")||""),route_geometry_ref:String(f.get("geometry")||"")||undefined,blocked_zone_intersections:array(f,"blocked"),constraint_failures:array(f,"failures")}},"Route evaluation recorded.");if(result&&typeof result==="object"&&"status" in result)setMessage(`Route ${(result as {status:string}).status}. ${JSON.stringify((result as {infeasible_reasons?:unknown}).infeasible_reasons||[])}`);}catch(e){setMessage(e instanceof Error?e.message:"Invalid route payload");}}
 async function equipment(f:FormData){try{await call("register_mep_equipment",{target_project_id:projectId,input_payload:{system_id:String(f.get("system")||""),source_model_id:String(f.get("model")||""),calculation_run_id:String(f.get("calc")||""),model_object_ref:String(f.get("object_ref")||""),equipment_code:String(f.get("code")||""),required_capacity:String(f.get("required")||""),selected_capacity:String(f.get("selected")||""),capacity_unit:String(f.get("unit")||""),tolerance_percent:String(f.get("tolerance")||"0"),schedule_data:obj(f,"schedule")}},"Equipment schedule reconciled against model and calculation evidence.");}catch(e){setMessage(e instanceof Error?e.message:"Invalid equipment payload");}}
 async function approveEquipment(f:FormData){await call("approve_mep_equipment",{target_equipment_id:String(f.get("equipment")||""),target_reason:String(f.get("reason")||"")},"Equipment selection independently approved.");}
 async function createPackage(f:FormData){try{await call("create_mep_package",{target_project_id:projectId,input_payload:{discipline:String(f.get("discipline")||""),criticality:String(f.get("criticality")||"C2"),source_model_id:String(f.get("model")||""),system_ids:array(f,"systems"),load_record_ids:array(f,"loads"),route_ids:array(f,"routes"),equipment_ids:array(f,"equipment"),drawing_refs:array(f,"drawings")}},"MEP release package created from current governed references.");}catch(e){setMessage(e instanceof Error?e.message:"Invalid package payload");}}
 async function transition(f:FormData){await call("transition_mep_package",{target_package_id:String(f.get("package")||""),target_status:String(f.get("status")||"for_review"),target_credential_id:String(f.get("credential")||"")||null,target_reason:String(f.get("reason")||"")},"MEP package transition recorded through the professional release gate.");}
 return <>{message&&<div className="note" aria-live="polite"><b>MEPF:</b> {message}{busy?" Refreshing…":""}</div>}
 <div className="kpis">{[["Systems",state.systems.length],["Loads",state.loads.length],["Routes",state.routes.length],["Equipment",state.equipment.length],["Packages",state.packages.length],["Invalidations",state.invalidations.length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed records</div></div>)}</div>
 <div className="panel-grid"><section className="panel"><h3>System + Load Evidence</h3><form action={system}><div className="field-grid"><div className="field"><label>Discipline</label><select name="discipline"><option>mechanical</option><option>electrical</option><option>plumbing</option><option>fire</option><option>elv</option><option>bms</option><option>vertical_transport</option></select></div><div className="field"><label>System code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div></div><div className="field"><label>Design criteria JSON</label><textarea name="criteria" rows={3} placeholder="{}"/></div><div className="field"><label>Reason</label><input name="reason" required/></div><button className="btn">Register System</button></form><hr/><form action={load}><div className="field"><label>System</label><select name="system" required>{state.systems.map(s=><option key={s.id} value={s.id}>{s.discipline} · {s.system_code}</option>)}</select></div><div className="field"><label>Completed calculation</label><select name="calc" required>{state.calculations.filter(c=>c.status==="completed").map(c=><option key={c.id} value={c.id}>{c.discipline} · {c.calculation_type} · {short(c.output_hash)}</option>)}</select></div><div className="field"><label>Approved / issued model</label><select name="model" required>{state.models.map(m=><option key={m.id} value={m.id}>{m.name} {m.revision} · {short(m.checksum)}</option>)}</select></div><button className="btn ghost">Bind Load Evidence</button></form></section>
 <section className="panel"><h3>Fail-Closed Routing</h3><form action={route}><div className="field"><label>System</label><select name="system" required>{state.systems.map(s=><option key={s.id} value={s.id}>{s.discipline} · {s.system_code}</option>)}</select></div><div className="field"><label>Model</label><select name="model" required>{state.models.map(m=><option key={m.id} value={m.id}>{m.name} {m.revision}</option>)}</select></div><div className="field"><label>Calculation (optional)</label><select name="calc"><option value="">None</option>{state.calculations.filter(c=>c.status==="completed").map(c=><option key={c.id} value={c.id}>{c.discipline} · {c.calculation_type}</option>)}</select></div><div className="field-grid"><div className="field"><label>Route code</label><input name="code" required/></div><div className="field"><label>Geometry ref</label><input name="geometry" placeholder="Omit when constraints fail"/></div></div><div className="field"><label>Blocked-zone intersections JSON</label><textarea name="blocked" rows={3} placeholder="[]"/></div><div className="field"><label>Constraint failures JSON</label><textarea name="failures" rows={3} placeholder="[]"/></div><button className="btn">Evaluate Route</button></form></section></div>
 <div className="panel-grid"><section className="panel"><h3>Equipment Reconciliation</h3><form action={equipment}><div className="field"><label>System</label><select name="system" required>{state.systems.map(s=><option key={s.id} value={s.id}>{s.discipline} · {s.system_code}</option>)}</select></div><div className="field"><label>Model</label><select name="model" required>{state.models.map(m=><option key={m.id} value={m.id}>{m.name} {m.revision}</option>)}</select></div><div className="field"><label>Calculation</label><select name="calc" required>{state.calculations.filter(c=>c.status==="completed").map(c=><option key={c.id} value={c.id}>{c.discipline} · {c.calculation_type}</option>)}</select></div><div className="field-grid"><div className="field"><label>Model object ref</label><input name="object_ref" required/></div><div className="field"><label>Equipment code</label><input name="code" required/></div><div className="field"><label>Required capacity</label><input name="required" type="number" step="any" required/></div><div className="field"><label>Selected capacity</label><input name="selected" type="number" step="any" required/></div><div className="field"><label>Unit</label><input name="unit" required/></div><div className="field"><label>Tolerance %</label><input name="tolerance" type="number" defaultValue="0" min="0" max="100"/></div></div><div className="field"><label>Schedule data JSON</label><textarea name="schedule" rows={3} placeholder="{}"/></div><button className="btn">Reconcile Equipment</button></form><form action={approveEquipment}><div className="field"><label>Reconciled proposal</label><select name="equipment">{state.equipment.filter(e=>e.status==="proposed"&&e.reconciliation_status==="reconciled").map(e=><option key={e.id} value={e.id}>{e.equipment_code}</option>)}</select></div><div className="field"><label>Independent approval reason</label><input name="reason" required/></div><button className="btn ghost">Approve Equipment</button></form></section>
 <section className="panel"><h3>MEP Release Package</h3><form action={createPackage}><div className="field-grid"><div className="field"><label>Discipline</label><select name="discipline"><option>mechanical</option><option>electrical</option><option>plumbing</option><option>fire</option><option>elv</option><option>bms</option><option>vertical_transport</option></select></div><div className="field"><label>Criticality</label><select name="criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div></div><div className="field"><label>Source model</label><select name="model" required>{state.models.map(m=><option key={m.id} value={m.id}>{m.name} {m.revision}</option>)}</select></div>{[["systems","System UUIDs"],["loads","Load UUIDs"],["routes","Route UUIDs"],["equipment","Equipment UUIDs"],["drawings","Drawing refs"]].map(([n,l])=><div className="field" key={n}><label>{l} JSON</label><textarea name={n} rows={2} required={n!=="drawings"} placeholder='["..."]'/></div>)}<button className="btn">Create Package</button></form><form action={transition}><div className="field"><label>Package</label><select name="package">{state.packages.filter(p=>!["issued","stale"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.discipline} v{p.version} · {p.criticality} · {p.status}</option>)}</select></div><div className="field"><label>Transition</label><select name="status"><option value="for_review">For Review</option><option value="approved">Approve</option><option value="issued">Issue</option></select></div><div className="field"><label>Professional credential</label><select name="credential"><option value="">Not required for lower criticality review step</option>{credentials.filter(c=>c.verification_status==="verified").map(c=><option key={c.id} value={c.id}>{c.discipline||"discipline"} · {c.registration_number}</option>)}</select></div><div className="field"><label>Reason</label><input name="reason" required/></div><button className="btn ghost">Transition Package</button></form></section></div>
 <section className="panel"><h3>MEP Evidence & Invalidation Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Resource</th><th>Status</th><th>Evidence</th><th>Detail</th></tr></thead><tbody>{state.routes.map(r=><tr key={`r-${r.id}`}><td>Route · {r.route_code}</td><td><span className="badge">{r.status}</span></td><td><code>{short(r.route_hash)}</code></td><td>{r.status==="infeasible"?JSON.stringify(r.infeasible_reasons):r.route_geometry_ref||"—"}</td></tr>)}{state.equipment.map(e=><tr key={`e-${e.id}`}><td>Equipment · {e.equipment_code}</td><td><span className="badge">{e.reconciliation_status}</span></td><td><code>{short(e.reconciliation_hash)}</code></td><td>{e.selected_capacity} / {e.required_capacity} {e.capacity_unit}</td></tr>)}{state.packages.map(p=><tr key={`p-${p.id}`}><td>Package · {p.discipline} v{p.version}</td><td><span className="badge">{p.status}</span></td><td><code>{short(p.issue_hash||p.package_hash)}</code></td><td>{p.criticality}</td></tr>)}{state.invalidations.map(i=><tr key={`i-${i.id}`}><td>Model invalidation</td><td><span className="badge">Recorded</span></td><td><code>{short(i.invalidation_hash)}</code></td><td>{new Date(i.detected_at).toLocaleString("en-IN")} · loads {i.affected_load_ids.length}, routes {i.affected_route_ids.length}, equipment {i.affected_equipment_ids.length}, packages {i.affected_package_ids.length}</td></tr>)}{state.routes.length+state.equipment.length+state.packages.length+state.invalidations.length===0&&<tr><td colSpan={4} className="subtle">No MEP execution evidence exists yet.</td></tr>}</tbody></table></div></section></>;
}