"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import type {ModelRow,ModelWorkspaceState,ProjectRow} from "@/components/lifecycle-runtime-types";

const shortHash=(value?:string|null)=>value?`${value.slice(0,12)}…`:"—";
const pretty=(value:string)=>value.replaceAll("_"," ");

export default function ModelWorkspaceClient({projects,projectId,state}:{projects:ProjectRow[];projectId:string;state:ModelWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const models=state.models||[];const validations=state.validation_runs||[];const issues=state.issues||[];
 const latestValidationByModel=new Map<string,typeof validations[number]>();for(const v of validations){if(!latestValidationByModel.has(v.model_id))latestValidationByModel.set(v.model_id,v);}
 const valid=models.filter(m=>latestValidationByModel.get(m.id)?.passed).length;const issued=models.filter(m=>m.status==="issued").length;const failed=validations.filter(v=>!v.passed).length;
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function register(form:FormData){setMessage("Registering immutable model revision…");const payload={project_id:projectId,model_name:String(form.get("model_name")||""),discipline:String(form.get("discipline")||"GEN"),format:String(form.get("format")||"ifc"),schema_version:String(form.get("schema_version")||"")||undefined,object_key:String(form.get("object_key")||""),checksum:String(form.get("checksum")||"").toLowerCase(),coordinate_system:String(form.get("coordinate_system")||"")||undefined};const {error}=await supabase.rpc("register_cde_model",{input_payload:payload});if(error){setMessage(error.message);return;}refresh("Model revision registered. Validation is required before approval or issue.");}
 async function validate(form:FormData){setMessage("Recording model validation evidence…");let findings:unknown[]=[];let evidence:unknown[]=[];try{findings=JSON.parse(String(form.get("findings")||"[]"));evidence=JSON.parse(String(form.get("evidence_refs")||"[]"));}catch{setMessage("Findings and evidence must be valid JSON arrays.");return;}const {error}=await supabase.rpc("record_cde_model_validation",{target_model_id:String(form.get("model_id")),input_payload:{validation_type:String(form.get("validation_type")||"ifc"),adapter_key:String(form.get("adapter_key")||"")||undefined,adapter_version:String(form.get("adapter_version")||"")||undefined,passed:String(form.get("passed"))==="true",result_hash:String(form.get("result_hash")||"").toLowerCase(),findings,evidence_refs:evidence,criticality:String(form.get("criticality")||"C2")}});if(error){setMessage(error.message);return;}refresh("Validation evidence recorded. Failed validation automatically creates a structured model-linked issue.");}
 async function transition(model:ModelRow,status:string){const reason=status==="superseded"||status==="withdrawn"?window.prompt(`Reason to ${status} this revision:`)||"":null;if((status==="superseded"||status==="withdrawn")&&!reason)return;setMessage(`Moving model to ${pretty(status)}…`);const {error}=await supabase.rpc("transition_cde_model",{target_model_id:model.id,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`Model moved to ${pretty(status)}.`);}
 function nextActions(model:ModelRow){if(model.status==="draft")return [["for_review","Send to review"]];if(model.status==="for_review")return [["for_approval","Send to approval"]];if(model.status==="for_approval")return [["approved","Approve"]];if(model.status==="approved")return [["issued","Issue"]];if(model.status==="issued")return [["superseded","Supersede"]];return [] as string[][];}
 return <>
  <section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/models?project=${p.id}`} className={p.id===projectId?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div></section>
  {message&&<div className="note" style={{marginTop:16}}><b>Model runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis" style={{marginTop:16}}>{[["Registered",String(models.length).padStart(2,"0")],["Validated",String(valid).padStart(2,"0")],["Issued",String(issued).padStart(2,"0")],["Failed Checks",String(failed).padStart(2,"0")],["Open Model Issues",String(issues.filter(i=>i.status!=="closed").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Register Model Revision</h3><form action={register}><div className="field-grid"><div className="field"><label>Model name</label><input name="model_name" required/></div><div className="field"><label>Discipline</label><input name="discipline" defaultValue="ARC" required/></div><div className="field"><label>Format</label><select name="format" defaultValue="ifc"><option>ifc</option><option>dwg</option><option>dxf</option><option>rvt</option><option>nwd</option><option>nwc</option><option>pdf</option><option>gbxml</option><option>json</option></select></div><div className="field"><label>Schema version</label><input name="schema_version" defaultValue="IFC4.3"/></div><div className="field"><label>Coordinate system</label><input name="coordinate_system" placeholder="Project / EPSG / survey grid"/></div><div className="field"><label>Storage object key</label><input name="object_key" defaultValue={`${projectId}/models/`} required/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>SHA-256 checksum</label><input name="checksum" minLength={64} maxLength={64} required placeholder="64 hexadecimal characters"/></div></div><button className="btn" style={{marginTop:12}}>Register Revision</button></form><p className="subtle">Register only after the binary exists in controlled storage. The checksum is the immutable content identity; published information is never overwritten.</p></section>
  <section className="panel"><h3>Record IFC / IDS Validation</h3><form action={validate}><div className="field"><label>Model</label><select name="model_id" required>{models.filter(m=>!["issued","superseded","withdrawn"].includes(m.status)).map(m=><option key={m.id} value={m.id}>{m.model_name} · {m.status}</option>)}</select></div><div className="field-grid"><div className="field"><label>Validation type</label><select name="validation_type"><option>ifc</option><option>ids</option><option>geometry</option><option>semantic</option><option>round_trip</option></select></div><div className="field"><label>Outcome</label><select name="passed"><option value="true">Pass</option><option value="false">Fail</option></select></div><div className="field"><label>Adapter</label><input name="adapter_key" placeholder="validator / adapter key"/></div><div className="field"><label>Adapter version</label><input name="adapter_version" placeholder="exact version"/></div><div className="field"><label>Criticality on failure</label><select name="criticality"><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div></div><div className="field"><label>Result SHA-256</label><input name="result_hash" minLength={64} maxLength={64} required/></div><div className="field"><label>Structured findings JSON</label><textarea name="findings" rows={4} defaultValue="[]"/></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={3} defaultValue="[]"/></div><button className="btn" style={{marginTop:12}}>Record Validation</button></form></section></div>
  <section className="panel" style={{marginTop:16}}><h3>Model Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Model</th><th>Discipline</th><th>Format / Schema</th><th>Revision</th><th>Status</th><th>Validation</th><th>Checksum</th><th>Authority</th></tr></thead><tbody>{models.map(m=>{const v=latestValidationByModel.get(m.id);return <tr key={m.id}><td><b>{m.model_name}</b><div className="subtle">{m.coordinate_system||"Coordinate system not declared"}</div></td><td>{m.discipline}</td><td>{m.format.toUpperCase()}<div className="subtle">{m.schema_version||"—"}</div></td><td>{String(m.revision??"P01")}</td><td><span className="badge">{pretty(m.status)}</span></td><td>{v?<><span className="badge">{v.passed?"Pass":"Fail"}</span><div className="subtle">{v.validation_type} · {new Date(v.created_at).toLocaleString("en-IN")}</div></>:"Not run"}</td><td><code>{shortHash(m.checksum)}</code></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{nextActions(m).map(([status,label])=><button key={status} type="button" className="btn ghost" onClick={()=>transition(m,status)}>{label}</button>)}</div></td></tr>})}{models.length===0&&<tr><td colSpan={8} className="subtle">No model revisions registered for this project.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Validation Ledger</h3>{validations.slice(0,12).map(v=><div key={v.id} className="note" style={{marginBottom:8}}><b>{v.validation_type.toUpperCase()} · {v.passed?"PASS":"FAIL"}</b><div className="subtle">Result {shortHash(v.result_hash)} · model {v.model_id.slice(0,8)} · {new Date(v.created_at).toLocaleString("en-IN")}</div></div>)}{validations.length===0&&<p className="subtle">No validation evidence yet.</p>}</section><section className="panel"><h3>Structured Model Issues</h3>{issues.slice(0,12).map(i=><div key={i.id} className="note" style={{marginBottom:8}}><b>{i.issue_number} · {i.title}</b><div className="subtle">{i.criticality} · {i.priority} · {pretty(i.status)}</div></div>)}{issues.length===0&&<p className="subtle">No model-linked validation issues.</p>}</section></div>
 </>;
}
