"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {ProgrammeWorkspaceState,ClimateWorkspaceState,EconomicsWorkspaceState} from "@/components/design-domain-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseJSON(value:FormDataEntryValue|null,fallback:unknown){const text=String(value||"").trim();if(!text)return fallback;return JSON.parse(text) as unknown;}
function useRuntime(){const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const refresh=(text:string)=>{setMessage(text);startTransition(()=>router.refresh());};return {supabase,message,setMessage,busy,refresh};}

export function ProgrammeWorkspaceClient({projectId,state}:{projectId:string;state:ProgrammeWorkspaceState}){
 const rt=useRuntime();const approved=state.baselines.find(b=>b.status==="approved");const activeItems=approved?state.items.filter(i=>i.programme_baseline_id===approved.id):[];
 async function create(form:FormData){try{const {error}=await rt.supabase.rpc("create_programme_baseline",{target_project_id:projectId,input_payload:{title:String(form.get("title")||""),source_refs:parseJSON(form.get("source_refs"),[]),items:parseJSON(form.get("items"),[])}});if(error){rt.setMessage(error.message);return;}rt.refresh("Programme draft created with immutable source/item hashes.");}catch(e){rt.setMessage(e instanceof Error?e.message:"Invalid JSON payload");}}
 async function approve(form:FormData){const {error}=await rt.supabase.rpc("approve_programme_baseline",{target_baseline_id:String(form.get("baseline_id")||""),target_reason:String(form.get("reason")||"")});if(error){rt.setMessage(error.message);return;}rt.refresh("Programme baseline approved. Prior approved baseline, if any, was superseded without rewriting history.");}
 const net=activeItems.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.target_area_each)||0),0);
 return <>{rt.message&&<div className="note"><b>Programme runtime:</b> {rt.message}{rt.busy?" Refreshing…":""}</div>}
 <div className="kpis">{[["Baselines",String(state.baselines.length).padStart(2,"0")],["Approved",approved?`v${approved.version}`:"None"],["Approved Items",String(activeItems.length).padStart(2,"0")],["Net Target Area",net?`${net.toLocaleString("en-IN")} sqm`:"—"],["D-Confidence",String(activeItems.filter(i=>i.confidence==="D").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>10?18:30}}>{v}</div><div className="subtle">Live project state</div></div>)}</div>
 <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Create Programme Baseline</h3><form action={create}><div className="field"><label>Baseline title</label><input name="title" required/></div><div className="field"><label>Source references JSON</label><textarea name="source_refs" rows={3} placeholder='["brief://...","meeting://..."]'/></div><div className="field"><label>Programme items JSON</label><textarea name="items" rows={9} required placeholder='[{"code":"...","space_type":"...","quantity":1,"target_area_each":0,"area_unit":"sqm","capacity":0,"adjacency":[],"operational_rules":{},"priority":"must","source_ref":"...","confidence":"C"}]'/></div><button className="btn">Create Draft Baseline</button></form></section>
 <section className="panel"><h3>Approve Draft Baseline</h3><form action={approve}><div className="field"><label>Draft</label><select name="baseline_id" required>{state.baselines.filter(b=>b.status==="draft").map(b=><option key={b.id} value={b.id}>v{b.version} · {b.title}</option>)}</select></div><div className="field"><label>Approval reason</label><textarea name="reason" rows={4} required/></div><button className="btn ghost" disabled={!state.baselines.some(b=>b.status==="draft")}>Approve Baseline</button></form><div className="note" style={{marginTop:12}}>Approval is role-gated. A new approved baseline supersedes the old baseline and downstream consumers must use the new hash.</div></section></div>
 <section className="panel"><h3>Programme Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Code</th><th>Space</th><th>Zone</th><th>Qty</th><th>Area Each</th><th>Capacity</th><th>Priority</th><th>Confidence</th><th>Source</th></tr></thead><tbody>{activeItems.map(i=><tr key={i.id}><td>{i.code}</td><td>{i.space_type}</td><td>{i.zone||"—"}</td><td>{i.quantity}</td><td>{i.target_area_each??"—"} {i.area_unit}</td><td>{i.capacity??"—"}</td><td>{pretty(i.priority)}</td><td><span className="badge">{i.confidence}</span></td><td>{i.source_ref}</td></tr>)}{activeItems.length===0&&<tr><td colSpan={9} className="subtle">No approved programme baseline exists yet.</td></tr>}</tbody></table></div></section>
 <section className="panel"><h3>Requirement Trace</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Code</th><th>Requirement</th><th>Category</th><th>Criticality</th><th>Status</th></tr></thead><tbody>{state.requirements.map(r=><tr key={r.id}><td>{r.code}</td><td>{r.statement}</td><td>{r.category}</td><td>{r.criticality}</td><td><span className="badge">{r.status}</span></td></tr>)}{state.requirements.length===0&&<tr><td colSpan={5} className="subtle">No structured requirements exist yet.</td></tr>}</tbody></table></div></section></>;
}

export function ClimateWorkspaceClient({projectId,state}:{projectId:string;state:ClimateWorkspaceState}){
 const rt=useRuntime();
 async function register(form:FormData){try{const {error}=await rt.supabase.rpc("register_climate_study",{target_project_id:projectId,input_payload:{study_type:String(form.get("study_type")||""),title:String(form.get("title")||""),source_model_ref:String(form.get("source_model_ref")||"")||undefined,source_model_hash:String(form.get("source_model_hash")||"")||undefined,weather_source_ref:String(form.get("weather_source_ref")||"")||undefined,engine_ref:String(form.get("engine_ref")||""),engine_version:String(form.get("engine_version")||""),method_ref:String(form.get("method_ref")||""),input_snapshot:parseJSON(form.get("input_snapshot"),{}),result_summary:parseJSON(form.get("result_summary"),{}),evidence_refs:parseJSON(form.get("evidence_refs"),[]),input_hash:String(form.get("input_hash")||""),output_hash:String(form.get("output_hash")||""),confidence:String(form.get("confidence")||"C")}});if(error){rt.setMessage(error.message);return;}rt.refresh("Climate study registered with exact engine/method/input/output provenance.");}catch(e){rt.setMessage(e instanceof Error?e.message:"Invalid JSON payload");}}
 async function review(form:FormData){const {error}=await rt.supabase.rpc("review_climate_study",{target_study_id:String(form.get("study_id")||""),target_decision:String(form.get("decision")||"reviewed"),target_reason:String(form.get("reason")||"")});if(error){rt.setMessage(error.message);return;}rt.refresh("Climate review decision recorded without rewriting the study result.");}
 return <>{rt.message&&<div className="note"><b>Climate runtime:</b> {rt.message}{rt.busy?" Refreshing…":""}</div>}<div className="kpis">{[["Studies",String(state.studies.length).padStart(2,"0")],["Approved",String(state.studies.filter(s=>s.status==="approved").length).padStart(2,"0")],["Awaiting Review",String(state.studies.filter(s=>["completed","reviewed"].includes(s.status)).length).padStart(2,"0")],["D-Confidence",String(state.studies.filter(s=>s.confidence==="D").length).padStart(2,"0")],["Rejected",String(state.studies.filter(s=>s.status==="rejected").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live evidence state</div></div>)}</div>
 <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Register Verified Study Result</h3><form action={register}><div className="field-grid"><div className="field"><label>Study type</label><select name="study_type"><option>solar</option><option>daylight</option><option>wind</option><option>energy</option><option>water</option><option>flood</option><option>embodied_carbon</option><option>other</option></select></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Engine / dataset</label><input name="engine_ref" required/></div><div className="field"><label>Engine version</label><input name="engine_version" required/></div><div className="field"><label>Method reference</label><input name="method_ref" required/></div><div className="field"><label>Confidence</label><select name="confidence"><option>A</option><option>B</option><option selected>C</option><option>D</option></select></div></div><div className="field"><label>Weather / environmental source</label><input name="weather_source_ref"/></div><div className="field"><label>Source model reference / hash</label><div className="field-grid"><input name="source_model_ref"/><input name="source_model_hash" minLength={64} maxLength={64}/></div></div><div className="field"><label>Input snapshot JSON</label><textarea name="input_snapshot" rows={4} placeholder="{}"/></div><div className="field"><label>Result summary JSON</label><textarea name="result_summary" rows={4} placeholder="{}"/></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={3} required placeholder='["artifact://..."]'/></div><div className="field-grid"><div className="field"><label>Input SHA-256</label><input name="input_hash" minLength={64} maxLength={64} required/></div><div className="field"><label>Output SHA-256</label><input name="output_hash" minLength={64} maxLength={64} required/></div></div><button className="btn">Register Result</button></form></section>
 <section className="panel"><h3>Human Review</h3><form action={review}><div className="field"><label>Study</label><select name="study_id" required>{state.studies.filter(s=>["completed","reviewed"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.title} · {pretty(s.status)}</option>)}</select></div><div className="field"><label>Decision</label><select name="decision"><option value="reviewed">Reviewed</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><div className="field"><label>Reason</label><textarea name="reason" rows={4} required/></div><button className="btn ghost" disabled={!state.studies.some(s=>["completed","reviewed"].includes(s.status))}>Record Review</button></form></section></div>
 <section className="panel"><h3>Environmental Study Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Study</th><th>Type</th><th>Engine</th><th>Status</th><th>Confidence</th><th>Evidence</th><th>Hashes</th></tr></thead><tbody>{state.studies.map(s=><tr key={s.id}><td>{s.title}</td><td>{pretty(s.study_type)}</td><td>{s.engine_ref} · {s.engine_version}<div className="subtle">{s.method_ref}</div></td><td><span className="badge">{pretty(s.status)}</span></td><td>{s.confidence}</td><td>{s.evidence_refs.length}</td><td><code>IN {shortHash(s.input_hash)}</code><br/><code>OUT {shortHash(s.output_hash)}</code></td></tr>)}{state.studies.length===0&&<tr><td colSpan={7} className="subtle">No climate study has been registered. No environmental claim is inferred.</td></tr>}</tbody></table></div></section></>;
}

export function EconomicsWorkspaceClient({projectId,state}:{projectId:string;state:EconomicsWorkspaceState}){
 const rt=useRuntime();
 async function create(form:FormData){try{const {error}=await rt.supabase.rpc("create_economic_scenario",{target_project_id:projectId,input_payload:{name:String(form.get("name")||""),assumptions:parseJSON(form.get("assumptions"),{}),assumption_sources:parseJSON(form.get("assumption_sources"),{}),metrics:parseJSON(form.get("metrics"),{}),sensitivity:parseJSON(form.get("sensitivity"),{}),calculation_ref:String(form.get("calculation_ref")||""),model_version:String(form.get("model_version")||""),input_hash:String(form.get("input_hash")||""),output_hash:String(form.get("output_hash")||""),confidence:String(form.get("confidence")||"C")}});if(error){rt.setMessage(error.message);return;}rt.refresh("Economic scenario version created with explicit assumptions, sources and deterministic output hashes.");}catch(e){rt.setMessage(e instanceof Error?e.message:"Invalid JSON payload");}}
 async function decide(form:FormData){const id=String(form.get("scenario_id")||"");const action=String(form.get("action")||"reviewed");const reason=String(form.get("reason")||"");const result=action==="selected"?await rt.supabase.rpc("select_economic_scenario",{target_scenario_id:id,target_reason:reason}):await rt.supabase.rpc("review_economic_scenario",{target_scenario_id:id,target_decision:action,target_reason:reason});if(result.error){rt.setMessage(result.error.message);return;}rt.refresh(`Economic scenario ${action} with immutable decision history.`);}
 const selected=state.scenarios.find(s=>s.status==="selected");
 return <>{rt.message&&<div className="note"><b>Economics runtime:</b> {rt.message}{rt.busy?" Refreshing…":""}</div>}<div className="kpis">{[["Scenarios",String(state.scenarios.length).padStart(2,"0")],["Selected",selected?selected.name:"None"],["Reviewed",String(state.scenarios.filter(s=>s.status==="reviewed").length).padStart(2,"0")],["D-Confidence",String(state.scenarios.filter(s=>s.confidence==="D").length).padStart(2,"0")],["Model Versions",String(new Set(state.scenarios.map(s=>s.model_version)).size).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>12?18:30}}>{v}</div><div className="subtle">Live scenario state</div></div>)}</div>
 <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Create Economic Scenario</h3><form action={create}><div className="field-grid"><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Model version</label><input name="model_version" required/></div><div className="field"><label>Calculation reference</label><input name="calculation_ref" required/></div><div className="field"><label>Confidence</label><select name="confidence"><option>A</option><option>B</option><option selected>C</option><option>D</option></select></div></div><div className="field"><label>Assumptions JSON</label><textarea name="assumptions" rows={4} required placeholder="{}"/></div><div className="field"><label>Assumption sources JSON</label><textarea name="assumption_sources" rows={4} required placeholder="{}"/></div><div className="field"><label>Metrics JSON</label><textarea name="metrics" rows={4} required placeholder='{"development_cost":0,"gross_value":0,"irr":0}'/></div><div className="field"><label>Sensitivity JSON</label><textarea name="sensitivity" rows={4} placeholder="{}"/></div><div className="field-grid"><div className="field"><label>Input SHA-256</label><input name="input_hash" minLength={64} maxLength={64} required/></div><div className="field"><label>Output SHA-256</label><input name="output_hash" minLength={64} maxLength={64} required/></div></div><button className="btn">Create Scenario Version</button></form></section>
 <section className="panel"><h3>Review / Select</h3><form action={decide}><div className="field"><label>Scenario</label><select name="scenario_id" required>{state.scenarios.filter(s=>["draft","reviewed"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.name} v{s.version} · {s.status}</option>)}</select></div><div className="field"><label>Action</label><select name="action"><option value="reviewed">Review</option><option value="rejected">Reject draft</option><option value="selected">Select reviewed scenario</option></select></div><div className="field"><label>Decision rationale</label><textarea name="reason" rows={5} required/></div><button className="btn ghost">Record Decision</button></form><div className="note" style={{marginTop:12}}>Review uses maker-checker separation. Selection is permitted only from Reviewed state.</div></section></div>
 <section className="panel"><h3>Scenario Comparison</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Scenario</th><th>Status</th><th>Confidence</th><th>Metrics</th><th>Calculation</th><th>Hash</th></tr></thead><tbody>{state.scenarios.map(s=><tr key={s.id}><td>{s.name} <span className="subtle">v{s.version}</span></td><td><span className="badge">{s.status}</span></td><td>{s.confidence}</td><td><code>{JSON.stringify(s.metrics)}</code></td><td>{s.calculation_ref}<div className="subtle">{s.model_version}</div></td><td><code>{shortHash(s.output_hash)}</code></td></tr>)}{state.scenarios.length===0&&<tr><td colSpan={6} className="subtle">No economic scenario exists. No return metric is inferred.</td></tr>}</tbody></table></div></section></>;
}