type LayoutOption={name:string;status:string;metrics:Record<string,any>;assumptions?:string[]};

function Sheet({title,code,children}:{title:string;code:string;children:React.ReactNode}){
 return <article className="card" style={{padding:14}}><div className="eyebrow">{code} · PRELIMINARY</div><h3 style={{margin:"7px 0 12px"}}>{title}</h3>{children}</article>;
}

const wall={fill:"none",stroke:"#101828",strokeWidth:2};
const room={fill:"#f7f8fb",stroke:"#98a2b3",strokeWidth:1};
const core={fill:"#e7edff",stroke:"#5570d9",strokeWidth:1.5};
const label={fontSize:9,fill:"#344054",textAnchor:"middle" as const};

export default function PreliminaryLayoutSet({option}:{option:LayoutOption}){
 const plot=option.metrics?.plot||{};const width=Number(plot.width_ft||40.334);const depth=Number(plot.depth_ft||51.25);const half=Number(plot.parcel_width_ft||width/2);const programme=option.metrics?.programme||{};
 return <section className="panel" style={{marginTop:18}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}><div><div className="demo">FIRST LAYOUT SET / CONCEPT</div><h2 style={{margin:"8px 0"}}>{option.name}</h2><p className="subtle" style={{maxWidth:760}}>A reviewable spatial diagram generated from the captured two-plot brief. It is a genuine first planning layout—not a construction or sanction drawing—and remains subject to survey, authority and architect verification.</p></div><span className="badge">{option.status.replaceAll("_"," ")} · NOT VERIFIED</span></div>
  <div className="note" style={{margin:"14px 0"}}><b>Captured basis:</b> assembled plot {width.toFixed(3)} ft × {depth.toFixed(2)} ft; two adjacent parcels of approximately {half.toFixed(3)} ft × {depth.toFixed(2)} ft; {programme.unit_count||"6 units"}; {programme.target_floors||"stilt plus three"}; shared stair and lift.</div>
  <div className="grid-3">
   <Sheet code="A-001" title="Assembled site / parcels"><svg viewBox="0 0 300 250" role="img" aria-label="Two adjacent assembled plots"><rect x="54" y="24" width="192" height="190" {...wall}/><line x1="150" y1="24" x2="150" y2="214" stroke="#5570d9" strokeDasharray="5 4"/><text x="102" y="112" style={label}>SV 60 / PLOT 1</text><text x="198" y="112" style={label}>SV 61 / PLOT 2</text><text x="102" y="129" style={label}>{half.toFixed(3)}&apos; × {depth.toFixed(2)}&apos;</text><text x="198" y="129" style={label}>{half.toFixed(3)}&apos; × {depth.toFixed(2)}&apos;</text><text x="150" y="238" style={label}>EAST / FRONT · {width.toFixed(3)} FT</text><text x="22" y="120" transform="rotate(-90 22 120)" style={label}>DEPTH {depth.toFixed(2)} FT</text></svg></Sheet>
   <Sheet code="A-101" title="Stilt parking + common core"><svg viewBox="0 0 300 250" role="img" aria-label="Stilt parking diagram"><rect x="38" y="22" width="224" height="194" {...wall}/>{[0,1,2].map(i=><rect key={i} x={50+i*70} y="38" width="54" height="64" {...room}/>)}{[0,1,2].map(i=><rect key={i} x={50+i*70} y="136" width="54" height="64" {...room}/>)}<rect x="126" y="96" width="48" height="48" {...core}/><text x="150" y="116" style={label}>LIFT +</text><text x="150" y="129" style={label}>STAIR</text><text x="77" y="72" style={label}>P1</text><text x="147" y="72" style={label}>P2</text><text x="217" y="72" style={label}>P3</text><text x="77" y="170" style={label}>P4</text><text x="147" y="170" style={label}>P5</text><text x="217" y="170" style={label}>P6</text><text x="150" y="238" style={label}>ENTRY / MANOEUVRING TO BE VERIFIED</text></svg></Sheet>
   <Sheet code="A-102" title="Typical residential floor"><svg viewBox="0 0 300 250" role="img" aria-label="Typical floor with two two-bedroom units"><rect x="30" y="20" width="240" height="200" {...wall}/><line x1="150" y1="20" x2="150" y2="220" stroke="#101828" strokeWidth="2"/><rect x="126" y="88" width="48" height="64" {...core}/>{[38,174].map((x,i)=><g key={i}><rect x={x} y="30" width="88" height="52" {...room}/><rect x={x} y="88" width="42" height="55" {...room}/><rect x={x+46} y="88" width="42" height="55" {...room}/><rect x={x} y="149" width="88" height="60" {...room}/><text x={x+44} y="58" style={label}>LIVING / DINING</text><text x={x+21} y="119" style={label}>BED 1</text><text x={x+67} y="119" style={label}>BATH / UTIL.</text><text x={x+44} y="181" style={label}>BED 2 + KITCHEN</text></g>)}<text x="150" y="112" style={label}>STAIR</text><text x="150" y="126" style={label}>+ LIFT</text><text x="82" y="238" style={label}>2-BED UNIT / PLOT 1</text><text x="218" y="238" style={label}>2-BED UNIT / PLOT 2</text></svg></Sheet>
   <Sheet code="A-103" title="Terrace zoning"><svg viewBox="0 0 300 250" role="img" aria-label="Terrace zoning"><rect x="38" y="24" width="224" height="190" {...wall}/><rect x="126" y="82" width="48" height="70" {...core}/><rect x="50" y="38" width="64" height="62" fill="#eaf5ea" stroke="#6a9a6a"/><rect x="186" y="38" width="64" height="62" fill="#eaf5ea" stroke="#6a9a6a"/><rect x="50" y="118" width="64" height="78" {...room}/><rect x="186" y="118" width="64" height="78" {...room}/><text x="82" y="72" style={label}>GARDEN</text><text x="218" y="72" style={label}>GARDEN</text><text x="82" y="160" style={label}>OPEN TERRACE</text><text x="218" y="160" style={label}>OPEN TERRACE</text><text x="150" y="111" style={label}>CORE</text><text x="150" y="238" style={label}>TANKS / SERVICES SUBJECT TO COORDINATION</text></svg></Sheet>
   <Sheet code="A-201" title="Concept building section"><svg viewBox="0 0 300 250" role="img" aria-label="Building section"><line x1="34" y1="220" x2="270" y2="220" stroke="#101828" strokeWidth="2"/>{[{y:176,n:"STILT / PARKING"},{y:132,n:"GROUND / 2 UNITS"},{y:88,n:"FIRST / 2 UNITS"},{y:44,n:"SECOND / 2 UNITS"}].map(f=><g key={f.y}><rect x="58" y={f.y} width="184" height="38" {...room}/><text x="150" y={f.y+23} style={label}>{f.n}</text></g>)}<rect x="58" y="18" width="184" height="20" fill="#eaf5ea" stroke="#6a9a6a"/><text x="150" y="31" style={label}>TERRACE</text><rect x="135" y="18" width="30" height="196" {...core}/><text x="150" y="236" style={label}>BASEMENT REQUIREMENT REQUIRES SITE / AUTHORITY REVIEW</text></svg></Sheet>
  </div>
  <div className="note" style={{marginTop:16}}><b>Review questions for the architect:</b> confirm road/front orientation, Vastu priorities, exact stair/lift position, parking manoeuvring, basement permissibility, setbacks, shaft locations, daylight/ventilation, unit entrances and room-area targets before schematic development.</div>
 </section>;
}
