"use client";
import {useRouter} from "next/navigation";
import {useState,useTransition} from "react";
import {createClient} from "@/lib/supabase";

type Processing={id:string;purpose_code:string;purpose_description:string;legal_basis:string;retention_days?:number|null;version:number;active:boolean;record_hash:string};
type Retention={id:string;record_class:string;retention_days:number;legal_hold_required:boolean;disposal_method:string;status:string;version:number;policy_hash:string;created_by:string};
type Dsr={id:string;request_type:string;subject_reference:string;identity_status:string;state:string;requested_at:string;completion_hash?:string|null};
type ExportRequest={id:string;project_id:string;document_id:string;purpose:string;status:string;requested_at:string;expires_at?:string|null;request_hash:string;requested_by:string};
type ProjectRow={id:string;code:string;name:string;classification:string};
export type PrivacySecurityState={processing:Processing[];consents:unknown[];retention:Retention[];requests:Dsr[];exports:ExportRequest[];projects:ProjectRow[]};
export type SecurityFinding={id:string;source:string;title:string;severity:string;affected_component:string;status:string;detected_at:string;due_at?:string|null};

const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
export default function PrivacySecurityClient({organisationId,state,findings}:{organisationId:string;state:PrivacySecurityState;findings:SecurityFinding[]}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [chain,setChain]=useState<{valid:boolean;checked_events:number;first_invalid_event_id?:string|null;chain_head?:string|null}|null>(null);const [busy,startTransition]=useTransition();
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function rpc(name:string,args:Record<string,unknown>,ok:string){const {error}=await supabase.rpc(name,args);if(error){setMessage(error.message);return;}refresh(ok);}
 async function createProcessing(fd:FormData){await rpc("create_processing_record",{target_organisation_id:organisationId,input_payload:{purpose_code:String(fd.get("purpose_code")||""),purpose_description:String(fd.get("purpose_description")||""),legal_basis:String(fd.get("legal_basis")||""),retention_days:String(fd.get("retention_days")||"")||null,data_categories:String(fd.get("data_categories")||"").split(",").map(v=>v.trim()).filter(Boolean),subject_categories:String(fd.get("subject_categories")||"").split(",").map(v=>v.trim()).filter(Boolean),recipients:String(fd.get("recipients")||"").split(",").map(v=>v.trim()).filter(Boolean)}},"Processing record version created and audited.");}
 async function createRetention(fd:FormData){await rpc("create_retention_policy",{target_organisation_id:organisationId,input_payload:{record_class:String(fd.get("record_class")||""),retention_days:String(fd.get("retention_days")||""),legal_hold_required:fd.get("legal_hold_required")==="on",disposal_method:String(fd.get("disposal_method")||"")}},"Retention policy draft created.");}
 async function approveRetention(fd:FormData){await rpc("approve_retention_policy",{target_policy_id:String(fd.get("policy_id")||""),target_reason:String(fd.get("reason")||"")},"Retention policy independently approved.");}
 async function createDsr(fd:FormData){await rpc("create_privacy_request",{target_organisation_id:organisationId,input_payload:{request_type:String(fd.get("request_type")||"access"),subject_reference:String(fd.get("subject_reference")||""),scope:String(fd.get("scope")||"").split(",").map(v=>v.trim()).filter(Boolean)}},"Privacy request created.");}
 async function verifyDsr(fd:FormData){await rpc("verify_privacy_request_identity",{target_request_id:String(fd.get("request_id")||""),target_decision:String(fd.get("decision")||"verified"),target_reason:String(fd.get("reason")||"")},"Privacy identity decision recorded.");}
 async function completeDsr(fd:FormData){await rpc("complete_privacy_request",{target_request_id:String(fd.get("request_id")||""),input_payload:{evidence_refs:String(fd.get("evidence")||"").split(",").map(v=>v.trim()).filter(Boolean),legal_hold_refs:String(fd.get("holds")||"").split(",").map(v=>v.trim()).filter(Boolean),decision_reason:String(fd.get("reason")||"")}},"Privacy request completed with evidence.");}
 async function classify(fd:FormData){await rpc("set_project_data_classification",{target_project_id:String(fd.get("project_id")||""),target_classification:String(fd.get("classification")||"internal"),target_reason:String(fd.get("reason")||"")},"Project classification updated and audited.");}
 async function decideExport(fd:FormData){await rpc("decide_restricted_document_export",{target_request_id:String(fd.get("request_id")||""),target_decision:String(fd.get("decision")||"approved"),target_reason:String(fd.get("reason")||""),target_expires_at:fd.get("expires_at")?new Date(String(fd.get("expires_at"))).toISOString():null},"Restricted export decision recorded.");}
 async function verifyChain(){const {data,error}=await supabase.rpc("verify_audit_chain",{target_organisation_id:organisationId});if(error){setMessage(error.message);return;}setChain(data as typeof chain);setMessage("Audit chain verification completed against persisted hashes.");}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Security:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Processing Records",String(state.processing.filter(r=>r.active).length)],["Active Retention",String(state.retention.filter(r=>r.status==="active").length)],["Privacy Requests",String(state.requests.filter(r=>r.state!=="completed"&&r.state!=="rejected").length)],["Restricted Exports",String(state.exports.filter(r=>r.status==="pending").length)],["Security Findings",String(findings.filter(f=>f.status!=="closed"&&f.status!=="verified").length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Audit Chain Integrity</h3><p className="subtle">Recomputes the organisation hash chain from actor, action, object, before/after state, reason, correlation ID and timestamp.</p><button className="btn" onClick={verifyChain}>Verify Audit Chain</button>{chain&&<div className="note" style={{marginTop:12}}><b>{chain.valid?"Valid":"Integrity failure"}</b><div className="subtle">Checked {chain.checked_events} events · head <code>{short(chain.chain_head)}</code>{chain.first_invalid_event_id?` · first invalid ${chain.first_invalid_event_id}`:""}</div></div>}</section>
   <section className="panel"><h3>Project Classification</h3><form action={classify} style={{display:"grid",gap:8}}><select name="project_id" required><option value="">Select project</option>{state.projects.map(p=><option value={p.id} key={p.id}>{p.code} · {p.name} · {pretty(p.classification)}</option>)}</select><select name="classification" defaultValue="internal"><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select><input name="reason" required placeholder="Classification rationale"/><button className="btn">Set Classification</button></form></section>
  </div>
  <div className="panel-grid">
   <section className="panel"><h3>Processing Register</h3><form action={createProcessing} style={{display:"grid",gap:8}}><input name="purpose_code" required placeholder="Purpose code"/><input name="purpose_description" required placeholder="Purpose description"/><input name="legal_basis" required placeholder="Legal basis"/><input name="retention_days" type="number" min="1" placeholder="Retention days"/><input name="data_categories" placeholder="Data categories, comma separated"/><input name="subject_categories" placeholder="Subject categories"/><input name="recipients" placeholder="Recipients"/><button className="btn">Create Version</button></form><div style={{marginTop:14,display:"grid",gap:8}}>{state.processing.filter(r=>r.active).map(r=><div className="note" key={r.id}><b>{r.purpose_code} · v{r.version}</b><div className="subtle">{r.purpose_description} · {r.legal_basis} · {r.retention_days||"—"} days</div><code>{short(r.record_hash)}</code></div>)}</div></section>
   <section className="panel"><h3>Retention Governance</h3><form action={createRetention} style={{display:"grid",gap:8}}><input name="record_class" required placeholder="Record class"/><input name="retention_days" type="number" min="1" required placeholder="Retention days"/><input name="disposal_method" required placeholder="Disposal method"/><label><input name="legal_hold_required" type="checkbox"/> Legal hold review required</label><button className="btn">Draft Policy</button></form><div style={{marginTop:14,display:"grid",gap:8}}>{state.retention.map(r=><div className="note" key={r.id}><b>{r.record_class} · v{r.version} · {pretty(r.status)}</b><div className="subtle">{r.retention_days} days · {r.disposal_method}</div>{r.status==="draft"&&<form action={approveRetention} style={{display:"flex",gap:6,marginTop:6}}><input type="hidden" name="policy_id" value={r.id}/><input name="reason" required placeholder="Independent approval reason"/><button className="btn ghost">Approve</button></form>}</div>)}</div></section>
  </div>
  <section className="panel"><h3>Data Subject Requests</h3><form action={createDsr} style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><select name="request_type"><option>access</option><option>correction</option><option>erasure</option><option>restriction</option><option>portability</option><option>objection</option></select><input name="subject_reference" required placeholder="Subject reference"/><input name="scope" placeholder="Scope refs, comma separated"/><button className="btn">Create Request</button></form><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Type / Subject</th><th>Identity</th><th>State</th><th>Requested</th><th>Governed Action</th></tr></thead><tbody>{state.requests.map(r=><tr key={r.id}><td><b>{pretty(r.request_type)}</b><div className="subtle">{r.subject_reference}</div></td><td>{pretty(r.identity_status)}</td><td><span className="badge">{pretty(r.state)}</span></td><td>{new Date(r.requested_at).toLocaleString("en-IN")}</td><td>{r.identity_status==="pending"?<form action={verifyDsr} style={{display:"grid",gap:5}}><input type="hidden" name="request_id" value={r.id}/><select name="decision"><option value="verified">Verify identity</option><option value="rejected">Reject identity</option></select><input name="reason" required placeholder="Evidence/reason"/><button className="btn ghost">Record Decision</button></form>:r.state==="in_progress"?<form action={completeDsr} style={{display:"grid",gap:5}}><input type="hidden" name="request_id" value={r.id}/><input name="evidence" required placeholder="Completion evidence refs"/><input name="holds" placeholder="Legal hold refs, if any"/><input name="reason" placeholder="Decision/hold reason"/><button className="btn ghost">Complete with Evidence</button></form>:<code>{short(r.completion_hash)}</code>}</td></tr>)}{state.requests.length===0&&<tr><td colSpan={5} className="subtle">No privacy requests recorded.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Restricted Export Requests</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Purpose</th><th>Document</th><th>Status</th><th>Expiry</th><th>Decision</th></tr></thead><tbody>{state.exports.map(r=><tr key={r.id}><td>{r.purpose}</td><td><code>{r.document_id.slice(0,8)}</code></td><td><span className="badge">{pretty(r.status)}</span></td><td>{r.expires_at?new Date(r.expires_at).toLocaleString("en-IN"):"—"}</td><td>{r.status==="pending"?<form action={decideExport} style={{display:"grid",gap:5}}><input type="hidden" name="request_id" value={r.id}/><select name="decision"><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="reason" required placeholder="Decision reason"/><input name="expires_at" type="datetime-local"/><button className="btn ghost">Record Decision</button></form>:<code>{short(r.request_hash)}</code>}</td></tr>)}{state.exports.length===0&&<tr><td colSpan={5} className="subtle">No restricted export requests.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Security Findings</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Source</th><th>Finding</th><th>Severity</th><th>Component</th><th>Status</th><th>Detected / Due</th></tr></thead><tbody>{findings.map(f=><tr key={f.id}><td>{f.source}</td><td><b>{f.title}</b></td><td><span className="badge">{f.severity}</span></td><td>{f.affected_component}</td><td>{pretty(f.status)}</td><td>{new Date(f.detected_at).toLocaleDateString("en-IN")}<div className="subtle">{f.due_at?`Due ${new Date(f.due_at).toLocaleDateString("en-IN")}`:""}</div></td></tr>)}{findings.length===0&&<tr><td colSpan={6} className="subtle">No security findings visible to this role.</td></tr>}</tbody></table></div></section>
 </>;
}
