"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import type {Bid,BidEvaluation,BOQLine,ProcurementWorkspaceState,ProjectRow,PurchaseOrder,TenderPackage,Vendor} from "@/components/lifecycle-runtime-types";

type ProcurementState=ProcurementWorkspaceState&{organisation_id?:string;invites?:Array<{id:string;tender_package_id:string;vendor_id:string;created_at:string;declined_at?:string|null}>};
type GRN={id:string;project_id:string;purchase_order_id:string;grn_number:string;receipt_date:string;lines:unknown[];inspection_result:string;evidence_refs:unknown[];created_at:string};
type VendorInvoiceRow={id:string;project_id:string;purchase_order_id:string;vendor_id:string;invoice_number:string;invoice_date:string;currency:string;total:number;matched_po_value:number;matched_receipt_value:number;variance:number;match_result:Record<string,unknown>;status:string;created_at:string};
const pretty=(v:string)=>v.replaceAll("_"," ");
const money=(n:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n||0));
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseJSON(raw:FormDataEntryValue|null,label:string,fallback:unknown){try{return JSON.parse(String(raw??JSON.stringify(fallback)));}catch{throw new Error(`${label} must be valid JSON.`);}}

export default function ProcurementWorkspaceClient({projects,projectId,state}:{projects:ProjectRow[];projectId:string;state:ProcurementState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const vendors=state.vendors||[];const packages=state.packages||[];const bids=state.bids||[];const evaluations=state.evaluations||[];const pos=state.purchase_orders||[];const grns=(state.goods_receipts||[]) as unknown as GRN[];const invoices=(state.vendor_invoices||[]) as unknown as VendorInvoiceRow[];const boq=state.approved_boq_lines||[];
 const vendorName=(id:string)=>vendors.find(v=>v.id===id)?.legal_name||id.slice(0,8);const packageName=(id:string)=>packages.find(p=>p.id===id)?.package_code||id.slice(0,8);const poName=(id:string)=>pos.find(p=>p.id===id)?.po_number||id.slice(0,8);
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function registerVendor(form:FormData){if(!state.organisation_id){setMessage("Project organisation could not be resolved.");return;}try{const categories=parseJSON(form.get("categories"),"Categories",[]);const {error}=await supabase.rpc("register_procurement_vendor",{target_organisation_id:state.organisation_id,input_payload:{legal_name:String(form.get("legal_name")||""),display_name:String(form.get("display_name")||"")||undefined,gstin:String(form.get("gstin")||"")||undefined,pan:String(form.get("pan")||"")||undefined,udyam_number:String(form.get("udyam_number")||"")||undefined,categories}});if(error)throw error;refresh("Vendor registered. KYC remains pending until independently reviewed.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function reviewVendor(v:Vendor,kyc:string,status:string){const reason=window.prompt(`Reason for ${kyc} / ${status}:`)||"Procurement vendor review";const {error}=await supabase.rpc("review_procurement_vendor",{target_vendor_id:v.id,target_kyc_status:kyc,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`Vendor ${v.legal_name} moved to ${kyc} / ${status}.`);}
 async function createPackage(form:FormData){try{const boqIds=form.getAll("boq_line_ids").map(String);if(boqIds.length===0)throw new Error("Select at least one approved BOQ line.");const scopeRefs=parseJSON(form.get("scope_refs"),"Scope refs",[]);const {error}=await supabase.rpc("create_tender_package",{target_project_id:projectId,input_payload:{boq_line_ids:boqIds,package_code:String(form.get("package_code")||""),title:String(form.get("title")||""),scope_refs:scopeRefs,bid_due_at:String(form.get("bid_due_at")||""),opening_at:String(form.get("opening_at")||""),opening_authority_role:String(form.get("opening_authority_role")||"procurement_manager")}});if(error)throw error;refresh("Tender package created from an approved BOQ snapshot.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function issueRFQ(form:FormData){const vendorIds=form.getAll("vendor_ids").map(String);if(vendorIds.length===0){setMessage("Select at least one verified active vendor.");return;}const {error}=await supabase.rpc("issue_tender_rfq",{target_package_id:String(form.get("package_id")||""),target_vendor_ids:vendorIds,target_reason:String(form.get("reason")||"RFQ issued from Procurement workspace")});if(error){setMessage(error.message);return;}refresh("RFQ issued to the selected qualified bidders.");}
 async function openBids(p:TenderPackage){const reason=window.prompt("Controlled bid-opening reason / meeting reference:")||"";if(!reason)return;const {error}=await supabase.rpc("open_tender_bids",{target_package_id:p.id,target_reason:reason});if(error){setMessage(error.message);return;}refresh("Sealed bids opened under configured time and authority controls.");}
 async function evaluate(form:FormData){try{const exclusions=parseJSON(form.get("exclusions_summary"),"Exclusions",[]);const evidence=parseJSON(form.get("evidence_refs"),"Evidence refs",[]);const {error}=await supabase.rpc("record_bid_evaluation",{target_bid_id:String(form.get("bid_id")||""),input_payload:{evaluation_type:String(form.get("evaluation_type")||"technical"),decision:String(form.get("decision")||"qualified"),score:String(form.get("score")||"")||undefined,normalised_total:String(form.get("normalised_total")||"")||undefined,exclusions_summary:exclusions,evidence_refs:evidence}});if(error)throw error;refresh("Bid evaluation recorded with an immutable evaluation hash.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function award(form:FormData){try{const negotiation=parseJSON(form.get("negotiation_summary"),"Negotiation summary",{});const {error}=await supabase.rpc("award_tender_package",{target_package_id:String(form.get("package_id")||""),target_bid_id:String(form.get("bid_id")||""),input_payload:{reason:String(form.get("reason")||""),negotiation_summary:negotiation}});if(error)throw error;refresh("Tender award locked to exact bid and evaluation evidence.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function createPO(form:FormData){try{const scope=parseJSON(form.get("scope_snapshot"),"Scope snapshot",{});const terms=parseJSON(form.get("terms"),"Terms",{});const delivery=parseJSON(form.get("delivery_schedule"),"Delivery schedule",[]);const {error}=await supabase.rpc("create_purchase_order_from_award",{target_package_id:String(form.get("package_id")||""),input_payload:{po_number:String(form.get("po_number")||""),total:String(form.get("total")||"")||undefined,scope_snapshot:scope,terms,delivery_schedule:delivery}});if(error)throw error;refresh("Draft PO created from the exact award-decision hash.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function transitionPO(po:PurchaseOrder,status:string){const reason=window.prompt(`Reason to ${status} PO ${po.po_number}:`)||`PO ${status}`;const {error}=await supabase.rpc("transition_purchase_order",{target_po_id:po.id,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`PO ${po.po_number} moved to ${status}.`);}
 async function amendPO(po:PurchaseOrder){const reason=window.prompt(`Reason for amendment to ${po.po_number}:`)||"";if(!reason)return;const total=window.prompt("Revised PO value:",String(po.total))||String(po.total);const variation=window.prompt("Approved variation total:",String(po.approved_variation_total||0))||String(po.approved_variation_total||0);const {error}=await supabase.rpc("amend_purchase_order",{target_po_id:po.id,input_payload:{reason,total,approved_variation_total:variation}});if(error){setMessage(error.message);return;}refresh("Versioned PO amendment created; original authority remains preserved.");}
 async function recordGRN(form:FormData){try{const lines=parseJSON(form.get("lines"),"GRN lines",[]);const evidence=parseJSON(form.get("evidence_refs"),"Evidence refs",[]);const {error}=await supabase.rpc("record_goods_receipt",{target_po_id:String(form.get("po_id")||""),input_payload:{grn_number:String(form.get("grn_number")||""),receipt_date:String(form.get("receipt_date")||""),inspection_result:String(form.get("inspection_result")||"pending"),lines,evidence_refs:evidence}});if(error)throw error;refresh("Goods receipt posted with inspection and receipt evidence.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function matchInvoice(form:FormData){try{const evidence=parseJSON(form.get("evidence_refs"),"Invoice evidence",[]);const {error}=await supabase.rpc("record_vendor_invoice_match",{target_po_id:String(form.get("po_id")||""),input_payload:{invoice_number:String(form.get("invoice_number")||""),invoice_date:String(form.get("invoice_date")||""),currency:String(form.get("currency")||"INR"),total:String(form.get("total")||""),tolerance:String(form.get("tolerance")||"0"),evidence_refs:evidence}});if(error)throw error;refresh("Vendor invoice matched against PO authority and accepted receipt value before posting.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 const bidCount=(id:string)=>Number(state.bid_counts?.find(b=>b.tender_package_id===id)?.submitted_count||0);
 const nextPO=(po:PurchaseOrder)=>po.status==="draft"?"approved":po.status==="approved"?"issued":po.status==="issued"?"delivering":po.status==="delivering"?"closed":null;
 return <>
  <section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/procurement?project=${p.id}`} className={p.id===projectId?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div></section>
  {message&&<div className="note" style={{marginTop:16}}><b>Procurement runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis" style={{marginTop:16}}>{[["Verified Vendors",String(vendors.filter(v=>v.kyc_status==="verified"&&v.status==="active").length).padStart(2,"0")],["Tender Packages",String(packages.length).padStart(2,"0")],["Visible Bids",String(bids.length).padStart(2,"0")],["Issued POs",String(pos.filter(p=>["issued","delivering","closed"].includes(p.status)).length).padStart(2,"0")],["Invoice Exceptions",String(invoices.filter(i=>i.status==="exception").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Vendor Master</h3><form action={registerVendor}><div className="field-grid"><div className="field"><label>Legal name</label><input name="legal_name" required/></div><div className="field"><label>Display name</label><input name="display_name"/></div><div className="field"><label>GSTIN</label><input name="gstin"/></div><div className="field"><label>PAN</label><input name="pan"/></div><div className="field"><label>Udyam</label><input name="udyam_number"/></div></div><div className="field"><label>Categories JSON</label><textarea name="categories" rows={2} defaultValue="[]"/></div><button className="btn">Register Vendor</button></form><div style={{marginTop:12}}>{vendors.slice(0,10).map(v=><div className="note" key={v.id} style={{marginBottom:7}}><b>{v.legal_name}</b><div className="subtle">KYC {v.kyc_status} · {v.status}</div><div style={{display:"flex",gap:5,marginTop:5,flexWrap:"wrap"}}>{v.kyc_status!=="verified"&&<button className="btn ghost" type="button" onClick={()=>reviewVendor(v,"verified","active")}>Verify KYC</button>}{v.status==="active"&&<button className="btn ghost" type="button" onClick={()=>reviewVendor(v,v.kyc_status,"suspended")}>Suspend</button>}{v.status!=="active"&&<button className="btn ghost" type="button" onClick={()=>reviewVendor(v,v.kyc_status,"active")}>Reactivate</button>}</div></div>)}</div></section>
  <section className="panel"><h3>Create Tender Package</h3><form action={createPackage}><div className="field-grid"><div className="field"><label>Package code</label><input name="package_code" required/></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Bid due</label><input name="bid_due_at" type="datetime-local" required/></div><div className="field"><label>Opening time</label><input name="opening_at" type="datetime-local" required/></div><div className="field"><label>Opening authority role</label><input name="opening_authority_role" defaultValue="procurement_manager"/></div></div><div className="field"><label>Approved BOQ lines</label><select name="boq_line_ids" multiple size={6} required>{boq.map((b:BOQLine)=><option key={b.id} value={b.id}>{b.code} · {b.description} · {b.quantity} {b.unit}</option>)}</select></div><div className="field"><label>Scope references JSON</label><textarea name="scope_refs" rows={2} defaultValue="[]"/></div><button className="btn">Create Tender</button></form></section></div>
  <section className="panel" style={{marginTop:16}}><h3>Tender Control</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Package</th><th>Status</th><th>Bid Due / Opening</th><th>Bids</th><th>Award</th><th>Action</th></tr></thead><tbody>{packages.map(p=><tr key={p.id}><td><b>{p.package_code}</b><div className="subtle">{p.title}</div></td><td><span className="badge">{pretty(p.status)}</span></td><td>{p.bid_due_at?new Date(p.bid_due_at).toLocaleString("en-IN"):"—"}<div className="subtle">Open: {p.opening_at?new Date(p.opening_at).toLocaleString("en-IN"):"—"}</div></td><td>{bidCount(p.id)}{!p.opened_at&&<div className="subtle">Sealed / not internally visible</div>}</td><td><code>{shortHash(p.award_decision_hash)}</code></td><td>{p.status==="rfq"&&!p.opened_at&&<button className="btn ghost" type="button" onClick={()=>openBids(p)}>Controlled Open</button>}</td></tr>)}{packages.length===0&&<tr><td colSpan={6} className="subtle">No tender packages yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Issue RFQ</h3><form action={issueRFQ}><div className="field"><label>Draft package</label><select name="package_id" required>{packages.filter(p=>p.status==="draft").map(p=><option key={p.id} value={p.id}>{p.package_code} · {p.title}</option>)}</select></div><div className="field"><label>Verified active vendors</label><select name="vendor_ids" multiple size={6} required>{vendors.filter(v=>v.kyc_status==="verified"&&v.status==="active").map(v=><option key={v.id} value={v.id}>{v.legal_name}</option>)}</select></div><div className="field"><label>Reason / issue record</label><input name="reason" defaultValue="Approved tender issue"/></div><button className="btn">Issue RFQ</button></form></section>
  <section className="panel"><h3>Bid Evaluation</h3><form action={evaluate}><div className="field"><label>Opened bid</label><select name="bid_id" required>{bids.map(b=><option key={b.id} value={b.id}>{packageName(b.tender_package_id)} · {vendorName(b.vendor_id)} · {money(b.total,b.currency)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Type</label><select name="evaluation_type"><option>technical</option><option>commercial</option></select></div><div className="field"><label>Decision</label><select name="decision"><option>qualified</option><option>rejected</option><option>ranked</option><option>recommended</option><option>not_recommended</option></select></div><div className="field"><label>Score</label><input name="score" type="number" step="0.01"/></div><div className="field"><label>Normalised total</label><input name="normalised_total" type="number" step="0.01"/></div></div><div className="field"><label>Exclusions JSON</label><textarea name="exclusions_summary" rows={2} defaultValue="[]"/></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={2} defaultValue="[]"/></div><button className="btn">Record Evaluation</button></form></section></div>
  <div className="panel-grid"><section className="panel"><h3>Award Tender</h3><form action={award}><div className="field"><label>Evaluation-stage package</label><select name="package_id" required>{packages.filter(p=>["evaluation","bid_received"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.package_code} · {p.title}</option>)}</select></div><div className="field"><label>Evaluated bid</label><select name="bid_id" required>{bids.filter(b=>b.status==="evaluated").map(b=><option key={b.id} value={b.id}>{packageName(b.tender_package_id)} · {vendorName(b.vendor_id)} · {money(b.total,b.currency)}</option>)}</select></div><div className="field"><label>Award reason</label><textarea name="reason" rows={2} required/></div><div className="field"><label>Negotiation summary JSON</label><textarea name="negotiation_summary" rows={3} defaultValue="{}"/></div><button className="btn">Lock Award</button></form></section>
  <section className="panel"><h3>Create PO from Award</h3><form action={createPO}><div className="field"><label>Awarded package</label><select name="package_id" required>{packages.filter(p=>p.status==="awarded").map(p=><option key={p.id} value={p.id}>{p.package_code} · {p.title}</option>)}</select></div><div className="field-grid"><div className="field"><label>PO number</label><input name="po_number" required/></div><div className="field"><label>PO total</label><input name="total" type="number" step="0.01" placeholder="Defaults to selected bid total"/></div></div><div className="field"><label>Scope snapshot JSON</label><textarea name="scope_snapshot" rows={2} defaultValue="{}"/></div><div className="field"><label>Terms JSON</label><textarea name="terms" rows={2} defaultValue="{}"/></div><div className="field"><label>Delivery schedule JSON</label><textarea name="delivery_schedule" rows={2} defaultValue="[]"/></div><button className="btn">Create Draft PO</button></form></section></div>
  <section className="panel" style={{marginTop:16}}><h3>Purchase Orders</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>PO</th><th>Vendor</th><th>Version</th><th>Value</th><th>Status</th><th>Decision Hash</th><th>Actions</th></tr></thead><tbody>{pos.map(po=>{const next=nextPO(po);return <tr key={po.id}><td>{po.po_number}</td><td>{vendorName(po.vendor_id)}</td><td>v{po.version}</td><td>{money(po.total,po.currency)}<div className="subtle">Variation {money(po.approved_variation_total||0,po.currency)}</div></td><td><span className="badge">{pretty(po.status)}</span></td><td><code>{shortHash(po.decision_hash)}</code></td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{next&&<button className="btn ghost" type="button" onClick={()=>transitionPO(po,next)}>{pretty(next)}</button>}{["approved","issued","delivering"].includes(po.status)&&<button className="btn ghost" type="button" onClick={()=>amendPO(po)}>Amend</button>}</div></td></tr>})}{pos.length===0&&<tr><td colSpan={7} className="subtle">No purchase orders yet.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid"><section className="panel"><h3>Goods Receipt</h3><form action={recordGRN}><div className="field"><label>Issued PO</label><select name="po_id" required>{pos.filter(p=>["issued","delivering","closed"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.po_number} · {vendorName(p.vendor_id)}</option>)}</select></div><div className="field-grid"><div className="field"><label>GRN number</label><input name="grn_number" required/></div><div className="field"><label>Receipt date</label><input name="receipt_date" type="date"/></div><div className="field"><label>Inspection result</label><select name="inspection_result"><option>pending</option><option>accepted</option><option>conditional</option><option>rejected</option></select></div></div><div className="field"><label>Receipt lines JSON</label><textarea name="lines" rows={4} defaultValue='[{"description":"Delivered item","quantity":0,"rate":0,"value":0}]'/></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={2} defaultValue="[]"/></div><button className="btn">Post GRN</button></form></section>
  <section className="panel"><h3>Three-way Invoice Match</h3><form action={matchInvoice}><div className="field"><label>PO</label><select name="po_id" required>{pos.filter(p=>["issued","delivering","closed"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.po_number}</option>)}</select></div><div className="field-grid"><div className="field"><label>Invoice number</label><input name="invoice_number" required/></div><div className="field"><label>Invoice date</label><input name="invoice_date" type="date"/></div><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div><div className="field"><label>Total</label><input name="total" type="number" step="0.01" required/></div><div className="field"><label>Allowed tolerance</label><input name="tolerance" type="number" step="0.01" defaultValue="0"/></div></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={2} defaultValue="[]"/></div><button className="btn">Match Before Posting</button></form></section></div>
  <div className="panel-grid"><section className="panel"><h3>Receipt Ledger</h3>{grns.slice(0,12).map(g=><div className="note" key={g.id} style={{marginBottom:7}}><b>{g.grn_number} · {poName(g.purchase_order_id)}</b><div className="subtle">{g.receipt_date} · inspection {g.inspection_result}</div></div>)}{grns.length===0&&<p className="subtle">No GRNs recorded.</p>}</section><section className="panel"><h3>Invoice Match Ledger</h3>{invoices.slice(0,12).map(i=><div className="note" key={i.id} style={{marginBottom:7}}><b>{i.invoice_number} · {money(i.total,i.currency)}</b><div className="subtle">{i.status} · variance {money(i.variance,i.currency)} · PO {poName(i.purchase_order_id)}</div></div>)}{invoices.length===0&&<p className="subtle">No vendor invoices matched.</p>}</section></div>
  <section className="panel"><h3>Evaluation Evidence</h3>{evaluations.slice(0,15).map((e:BidEvaluation)=><div className="note" key={e.id} style={{marginBottom:7}}><b>{e.evaluation_type} · {e.decision}</b><div className="subtle">Bid {e.bid_id.slice(0,8)} · score {e.score??"—"} · normalised {e.normalised_total??"—"} · hash <code>{shortHash(e.evaluation_hash)}</code></div></div>)}{evaluations.length===0&&<p className="subtle">No opened-bid evaluations yet.</p>}</section>
 </>;
}
