"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

export type ProfessionalWorkspaceState={profiles:any[];assignments:any[];conflicts:any[];performance:any[];assignment_events:any[]};
type Candidate={profile_id:string;user_id:string;display_name:string;discipline:string;years_experience:number;skills:any;typologies:any;capacity_hours_week:number;availability_status:string;score:number;allocated_percent:number;evidence:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const parseArray=(v:FormDataEntryValue|null)=>{const s=String(v||"").trim();if(!s)return [];const x=JSON.parse(s);if(!Array.isArray(x))throw new Error("Expected a JSON array");return x;};

export default function ProfessionalNetworkClient({organisationId,projectId,currentUserId,state}:{organisationId:string;projectId?:string;currentUserId:string;state:ProfessionalWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [candidates,setCandidates]=useState<Candidate[]>([]);const [searchRole,setSearchRole]=useState("lead_architect");const [searchDiscipline,setSearchDiscipline]=useState("architecture");const [busy,startTransition]=useTransition();
 const profiles=state.profiles||[];const assignments=state.assignments||[];const conflicts=state.conflicts||[];const performance=state.performance||[];
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function saveProfile(form:FormData){try{const {error}=await supabase.rpc("upsert_professional_profile",{target_organisation_id:organisationId,input_payload:{user_id:String(form.get("user_id")||"")||undefined,display_name:String(form.get("display_name")||""),discipline:String(form.get("discipline")||""),registration_summary:String(form.get("registration_summary")||""),geographies:parseArray(form.get("geographies")),typologies:parseArray(form.get("typologies")),skills:parseArray(form.get("skills")),years_experience:String(form.get("years_experience")||"0"),fee_rate:String(form.get("fee_rate")||""),fee_currency:String(form.get("fee_currency")||"INR"),capacity_hours_week:String(form.get("capacity_hours_week")||"40"),availability_status:String(form.get("availability_status")||"active")}});if(error)return setMessage(error.message);refresh("Professional profile saved with a deterministic profile hash.");}catch(e){fail(e);}}
 async function submitCredential(form:FormData){const {error}=await supabase.rpc("submit_professional_credential",{input_payload:{credential_type:String(form.get("credential_type")||""),issuing_body:String(form.get("issuing_body")||""),registration_number:String(form.get("registration_number")||""),discipline:String(form.get("discipline")||""),valid_from:String(form.get("valid_from")||""),valid_until:String(form.get("valid_until")||""),evidence_uri:String(form.get("evidence_uri")||"")}});if(error)return setMessage(error.message);refresh("Credential submitted for independent verification and audited.");}
 async function reviewCredential(id:string,decision:string){const {error}=await supabase.rpc("review_professional_credential",{target_credential_id:id,decision});if(error)return setMessage(error.message);refresh(`Credential ${decision}.`);}
 async function recommend(form:FormData){if(!projectId)return;const role=String(form.get("role")||"");const discipline=String(form.get("discipline")||"");setSearchRole(role);setSearchDiscipline(discipline);const {data,error}=await supabase.rpc("recommend_professionals",{target_project_id:projectId,target_role_code:role,target_discipline:discipline});if(error)return setMessage(error.message);setCandidates((data||[]) as Candidate[]);setMessage((data||[]).length?"Eligibility-filtered recommendation set generated. Human assignment is still required.":"No eligible professional currently satisfies credentials, discipline, conflict and capacity controls.");}
 async function assign(profileId:string){if(!projectId)return;const allocation=window.prompt("Allocation percent", "25");if(!allocation)return;const appointment=window.prompt("Appointment / authority reference (required for controlled roles)","")??"";const {error}=await supabase.rpc("assign_project_professional",{target_project_id:projectId,target_profile_id:profileId,target_role_code:searchRole,target_discipline:searchDiscipline,target_allocation_percent:Number(allocation),target_appointment_ref:appointment});if(error)return setMessage(error.message);setCandidates([]);refresh("Professional assigned from the eligible set; assignment history is immutable.");}
 async function replace(assignment:any){if(!projectId)return;const eligible=profiles.filter(p=>p.id!==assignment.professional_profile_id);const profileId=window.prompt(`Replacement profile UUID. Eligible profiles visible: ${eligible.map(p=>`${p.display_name}=${p.id}`).join(" | ")}`);if(!profileId)return;const reason=window.prompt("Replacement reason");if(!reason?.trim())return;const {error}=await supabase.rpc("replace_project_professional",{target_assignment_id:assignment.id,target_new_profile_id:profileId.trim(),target_reason:reason.trim()});if(error)return setMessage(error.message);refresh("Assignment replaced without rewriting the prior professional's history or approvals.");}
 async function declareConflict(form:FormData){if(!projectId)return;const {error}=await supabase.rpc("declare_professional_conflict",{target_profile_id:String(form.get("profile_id")||""),target_project_id:projectId,target_conflict_type:String(form.get("conflict_type")||""),target_details:String(form.get("details")||"")});if(error)return setMessage(error.message);refresh("Conflict declared; this professional is excluded from recommendation until cleared.");}
 async function clearConflict(id:string){const reason=window.prompt("Conflict clearance reason");if(!reason?.trim())return;const {error}=await supabase.rpc("clear_professional_conflict",{target_conflict_id:id,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh("Conflict cleared with auditable reason.");}
 async function recordPerformance(form:FormData){if(!projectId)return;const {error}=await supabase.rpc("record_professional_performance",{target_profile_id:String(form.get("profile_id")||""),target_project_id:projectId,input_payload:{metric_code:String(form.get("metric_code")||""),metric_value:String(form.get("metric_value")||""),unit:String(form.get("unit")||""),outcome_type:String(form.get("outcome_type")||"other"),source_ref:String(form.get("source_ref")||""),source_hash:String(form.get("source_hash")||""),notes:String(form.get("notes")||"")}});if(error)return setMessage(error.message);refresh("Performance metric recorded with source project outcome evidence.");}
 async function reviewPerformance(id:string,stateValue:string){const reason=window.prompt(`${stateValue} reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("review_professional_performance",{target_metric_id:id,target_state:stateValue,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Performance metric ${stateValue}.`);}
 const activeAssignments=assignments.filter(a=>["accepted","active"].includes(a.state));const credentialBlocks=profiles.filter(p=>(p.credentials||[]).some((c:any)=>c.verification_status!=="verified"||c.valid_until&&new Date(c.valid_until)<new Date())).length;const capacityRisks=profiles.filter(p=>Number(p.allocated_percent)>=80).length;
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Professional Network:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Profiles",String(profiles.length)],["Active Assignments",String(activeAssignments.length)],["Credential Blocks",String(credentialBlocks)],["≥80% Allocation",String(capacityRisks)],["Open Conflicts",String(conflicts.filter(c=>c.status==="open").length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Professional Profile</h3><form action={saveProfile}><div className="field-grid"><div className="field"><label>User UUID</label><input name="user_id" defaultValue={currentUserId}/></div><div className="field"><label>Display name</label><input name="display_name"/></div><div className="field"><label>Discipline</label><input name="discipline" required placeholder="architecture / structure / mep / cost"/></div><div className="field"><label>Years experience</label><input name="years_experience" type="number" min="0" step="0.5" defaultValue="0"/></div><div className="field"><label>Capacity hours/week</label><input name="capacity_hours_week" type="number" min="1" defaultValue="40"/></div><div className="field"><label>Availability</label><select name="availability_status"><option>active</option><option>limited</option><option>unavailable</option><option>suspended</option></select></div></div><div className="field"><label>Registration summary</label><input name="registration_summary"/></div><div className="field-grid"><div className="field"><label>Geographies JSON</label><textarea name="geographies" rows={2} placeholder='["Delhi NCR"]'/></div><div className="field"><label>Typologies JSON</label><textarea name="typologies" rows={2} placeholder='["hotel"]'/></div><div className="field"><label>Skills JSON</label><textarea name="skills" rows={2} placeholder='["BIM","coordination"]'/></div></div><button className="btn">Save Profile</button></form></section>
   <section className="panel"><h3>Submit My Credential</h3><form action={submitCredential}><div className="field-grid"><div className="field"><label>Credential type</label><input name="credential_type" required/></div><div className="field"><label>Issuing body</label><input name="issuing_body" required/></div><div className="field"><label>Registration number</label><input name="registration_number" required/></div><div className="field"><label>Discipline</label><input name="discipline"/></div><div className="field"><label>Valid from</label><input name="valid_from" type="date"/></div><div className="field"><label>Valid until</label><input name="valid_until" type="date"/></div></div><div className="field"><label>Evidence reference</label><input name="evidence_uri"/></div><button className="btn ghost">Submit Credential</button></form></section>
  </div>
  <section className="panel"><h3>Professional Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Professional</th><th>Discipline</th><th>Availability / Load</th><th>Experience</th><th>Credentials</th><th>Profile hash</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td><b>{p.display_name}</b><div className="subtle">{p.id.slice(0,8)}</div></td><td>{p.discipline}</td><td><span className="badge">{pretty(p.availability_status)}</span><div className="subtle">{Number(p.allocated_percent||0)}% allocated</div></td><td>{p.years_experience} years</td><td>{(p.credentials||[]).map((c:any)=><div key={c.id} style={{marginBottom:5}}>{c.credential_type} · <span className="badge">{pretty(c.verification_status)}</span>{c.verification_status==="pending"&&<span style={{marginLeft:6}}><button className="btn ghost" style={{padding:5}} onClick={()=>reviewCredential(c.id,"verified")}>Verify</button></span>}</div>)}{!(p.credentials||[]).length&&<span className="subtle">None recorded</span>}</td><td><code>{short(p.profile_hash)}</code></td></tr>)}{profiles.length===0&&<tr><td colSpan={6} className="subtle">No professional profiles have been created.</td></tr>}</tbody></table></div></section>
  {projectId&&<>
   <div className="panel-grid">
    <section className="panel"><h3>Eligibility & Recommendation</h3><form action={recommend}><div className="field-grid"><div className="field"><label>Role</label><input name="role" defaultValue="lead_architect" required/></div><div className="field"><label>Discipline</label><input name="discipline" defaultValue="architecture" required/></div></div><button className="btn">Find Eligible Professionals</button></form><div style={{marginTop:14,display:"grid",gap:8}}>{candidates.map(c=><div className="note" key={c.profile_id}><b>{c.display_name}</b> · score {c.score}<div className="subtle">{c.discipline} · {c.years_experience} yrs · {c.allocated_percent}% allocated</div><button className="btn ghost" style={{marginTop:8}} onClick={()=>assign(c.profile_id)}>Assign</button></div>)}</div></section>
    <section className="panel"><h3>Declare Conflict</h3><form action={declareConflict}><div className="field"><label>Professional</label><select name="profile_id" required>{profiles.map(p=><option key={p.id} value={p.id}>{p.display_name} · {p.discipline}</option>)}</select></div><div className="field"><label>Conflict type</label><input name="conflict_type" required/></div><div className="field"><label>Details</label><textarea name="details" rows={3} required/></div><button className="btn ghost" disabled={!profiles.length}>Declare Conflict</button></form></section>
   </div>
   <section className="panel"><h3>Project Assignments</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Role</th><th>Discipline</th><th>Professional</th><th>Allocation</th><th>State</th><th>Authority / History</th></tr></thead><tbody>{assignments.map(a=>{const p=profiles.find(x=>x.id===a.professional_profile_id);return <tr key={a.id}><td>{a.role_code}</td><td>{a.discipline}</td><td>{p?.display_name||a.user_id?.slice(0,8)||"—"}</td><td>{a.allocation_percent??"—"}%</td><td><span className="badge">{pretty(a.state)}</span></td><td><div className="subtle">{a.appointment_ref||"No appointment ref"}</div>{a.supersedes_assignment_id&&<div className="subtle">Supersedes {a.supersedes_assignment_id.slice(0,8)}</div>}{["accepted","active"].includes(a.state)&&<button className="btn ghost" style={{marginTop:6,padding:6}} onClick={()=>replace(a)}>Replace</button>}</td></tr>})}{assignments.length===0&&<tr><td colSpan={6} className="subtle">No project professional assignments exist yet.</td></tr>}</tbody></table></div></section>
   <div className="panel-grid"><section className="panel"><h3>Open Conflicts</h3>{conflicts.map(c=><div className="note" key={c.id}><b>{c.conflict_type}</b> · {c.details}<div className="subtle">{pretty(c.status)}</div>{c.status==="open"&&<button className="btn ghost" style={{marginTop:6}} onClick={()=>clearConflict(c.id)}>Clear with Reason</button>}</div>)}{conflicts.length===0&&<div className="subtle">No declared project conflicts.</div>}</section><section className="panel"><h3>Record Outcome Performance</h3><form action={recordPerformance}><div className="field"><label>Professional</label><select name="profile_id" required>{profiles.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></div><div className="field-grid"><div className="field"><label>Metric code</label><input name="metric_code" required/></div><div className="field"><label>Value</label><input name="metric_value" type="number" step="0.0001" required/></div><div className="field"><label>Unit</label><input name="unit" required/></div><div className="field"><label>Outcome type</label><select name="outcome_type"><option>first_pass_quality</option><option>correction</option><option>schedule</option><option>rfi</option><option>ncr</option><option>cost_impact</option><option>review</option><option>other</option></select></div></div><div className="field"><label>Source project record</label><input name="source_ref" required placeholder="RFI/NCR/release/task/report reference"/></div><div className="field"><label>Exact source hash</label><input name="source_hash" required/></div><button className="btn ghost" disabled={!profiles.length}>Record Performance</button></form></section></div>
   <section className="panel"><h3>Performance Scorecard Evidence</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Professional</th><th>Metric</th><th>Outcome</th><th>Value</th><th>Source</th><th>Review</th></tr></thead><tbody>{performance.map(m=>{const p=profiles.find(x=>x.id===m.profile_id);return <tr key={m.id}><td>{p?.display_name||m.profile_id.slice(0,8)}</td><td>{m.metric_code}</td><td>{pretty(m.outcome_type)}</td><td>{m.metric_value} {m.unit}</td><td>{m.source_ref}<div className="subtle"><code>{short(m.source_hash)}</code></div></td><td><span className="badge">{pretty(m.review_state)}</span>{m.review_state==="recorded"&&<div style={{marginTop:5}}><button className="btn ghost" style={{padding:5}} onClick={()=>reviewPerformance(m.id,"validated")}>Validate</button> <button className="btn ghost" style={{padding:5}} onClick={()=>reviewPerformance(m.id,"excluded")}>Exclude</button></div>}</td></tr>})}{performance.length===0&&<tr><td colSpan={6} className="subtle">No source-traceable performance metrics yet.</td></tr>}</tbody></table></div></section>
  </>}
 </>;
}
