"use client";

import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type BenchmarkCase={id:string;code:string;name:string;benchmark_model_ref:string;benchmark_model_checksum:string;measurement_rule_set_ref:string;expected_quantities:unknown[];default_tolerance:Record<string,unknown>;status:string;case_hash:string;created_by?:string|null;approved_by?:string|null;approved_at?:string|null};
type BenchmarkResult={id:string;case_id:string;engine_ref:string;engine_version:string;actual_quantities:unknown[];findings:unknown[];passed:boolean;result_hash:string;status:string;created_by?:string|null;reviewed_by?:string|null;reviewed_at?:string|null};
export type QTOBenchmarkWorkspace={cases:BenchmarkCase[];results:BenchmarkResult[]};
export const emptyQTOBenchmarkWorkspace:QTOBenchmarkWorkspace={cases:[],results:[]};
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function parseJson(raw:FormDataEntryValue|null,fallback:unknown){const s=String(raw||"").trim();if(!s)return fallback;return JSON.parse(s);}

export default function QTOBenchmarkGovernanceClient({workspace}:{workspace:QTOBenchmarkWorkspace}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function createCase(form:FormData){try{const {data,error}=await supabase.rpc("create_qto_benchmark_case",{input_payload:{code:String(form.get("code")||""),name:String(form.get("name")||""),benchmark_model_ref:String(form.get("benchmark_model_ref")||""),benchmark_model_checksum:String(form.get("benchmark_model_checksum")||""),measurement_rule_set_ref:String(form.get("measurement_rule_set_ref")||""),expected_quantities:parseJson(form.get("expected_quantities"),[]),default_tolerance:parseJson(form.get("default_tolerance"),{absolute:0,percent:0})}});if(error)return setMessage(error.message);refresh(`Benchmark case ${String(data).slice(0,8)} created. A different platform admin must approve it.`);}catch(e){fail(e);}}
 async function approveCase(id:string){const reason=window.prompt("Independent benchmark-case approval reason");if(!reason?.trim())return;const {error}=await supabase.rpc("approve_qto_benchmark_case",{target_case_id:id,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh("Golden benchmark case approved.");}
 async function recordResult(form:FormData){try{const {data,error}=await supabase.rpc("record_qto_benchmark_result",{target_case_id:String(form.get("case_id")||""),target_engine_ref:String(form.get("engine_ref")||""),target_engine_version:String(form.get("engine_version")||""),target_actual_quantities:parseJson(form.get("actual_quantities"),[])});if(error)return setMessage(error.message);refresh(`Benchmark result ${String(data).slice(0,8)} recorded. Deterministic findings decide whether independent approval is possible.`);}catch(e){fail(e);}}
 async function reviewResult(id:string,decision:string){const reason=window.prompt(`${decision} benchmark result reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("review_qto_benchmark_result",{target_result_id:id,target_decision:decision,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Benchmark result ${decision}.`);}
 return <>{message&&<div className="note" style={{marginBottom:16}}><b>QTO Benchmark:</b> {message}{busy?" Refreshing…":""}</div>}
 <div className="kpis">{[["Golden Cases",workspace.cases.length],["Approved Cases",workspace.cases.filter(c=>c.status==="approved").length],["Recorded Results",workspace.results.length],["Certified Results",workspace.results.filter(r=>r.status==="approved"&&r.passed).length]].map(([l,v])=><div className="kpi" key={String(l)}><div className="label">{l}</div><div className="value">{String(v).padStart(2,"0")}</div><div className="subtle">Global deterministic certification</div></div>)}</div>
 <div className="panel-grid" style={{marginTop:16}}><section className="panel"><h3>Create Golden Benchmark</h3><form action={createCase}><div className="field-grid"><div className="field"><label>Case code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Measurement rule-set ref</label><input name="measurement_rule_set_ref" required/></div></div><div className="field"><label>Benchmark model reference</label><input name="benchmark_model_ref" required/></div><div className="field"><label>Benchmark model SHA-256</label><input name="benchmark_model_checksum" minLength={64} maxLength={64} required/></div><div className="field"><label>Expected quantities JSON</label><textarea name="expected_quantities" rows={8} required placeholder='[{"code":"WALL-001","unit":"m2","quantity":125.4,"tolerance_percent":0.5}]'/></div><div className="field"><label>Default tolerance JSON</label><textarea name="default_tolerance" rows={3} defaultValue='{"absolute":0,"percent":0.5}'/></div><button className="btn">Create Benchmark Case</button></form></section>
 <section className="panel"><h3>Execute Benchmark Result</h3><form action={recordResult}><div className="field"><label>Approved case</label><select name="case_id" required>{workspace.cases.filter(c=>c.status==="approved").map(c=><option key={c.id} value={c.id}>{c.code} · {c.measurement_rule_set_ref}</option>)}</select></div><div className="field-grid"><div className="field"><label>QTO engine</label><input name="engine_ref" required placeholder="conceptspaces-qto"/></div><div className="field"><label>Engine version</label><input name="engine_version" required placeholder="1.0.0"/></div></div><div className="field"><label>Actual quantities JSON</label><textarea name="actual_quantities" rows={8} required placeholder='[{"code":"WALL-001","unit":"m2","quantity":125.2}]'/></div><button className="btn ghost" disabled={!workspace.cases.some(c=>c.status==="approved")}>Run Deterministic Comparison</button></form><div className="note" style={{marginTop:12}}>Only a passing result can be independently approved. Project QTO runs fail closed until an approved result exists for the exact engine/version + rule-set.</div></section></div>
 <section className="panel"><h3>Certification Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Case / Rule Set</th><th>Case State</th><th>Engine</th><th>Result</th><th>Findings</th><th>Hashes</th><th>Authority</th></tr></thead><tbody>{workspace.cases.flatMap(c=>{const rows=workspace.results.filter(r=>r.case_id===c.id);if(!rows.length)return [<tr key={c.id}><td><b>{c.code}</b><div className="subtle">{c.measurement_rule_set_ref}</div></td><td><span className="badge">{pretty(c.status)}</span></td><td>—</td><td>—</td><td>—</td><td><code>{short(c.case_hash)}</code></td><td>{c.status==="draft"?<button className="btn ghost" onClick={()=>approveCase(c.id)}>Approve Case</button>:"Approved"}</td></tr>];return rows.map(r=><tr key={r.id}><td><b>{c.code}</b><div className="subtle">{c.measurement_rule_set_ref}</div></td><td><span className="badge">{pretty(c.status)}</span></td><td>{r.engine_ref}@{r.engine_version}</td><td><span className="badge">{r.passed?"Pass":"Fail"}</span> · {pretty(r.status)}</td><td>{Array.isArray(r.findings)?r.findings.length:0}</td><td><code>{short(c.case_hash)}</code><div><code>{short(r.result_hash)}</code></div></td><td>{r.status==="recorded"?<span style={{display:"flex",gap:6}}><button className="btn ghost" disabled={!r.passed} onClick={()=>reviewResult(r.id,"approved")}>Approve</button><button className="btn ghost" onClick={()=>reviewResult(r.id,"rejected")}>Reject</button></span>:pretty(r.status)}</td></tr>);})}{!workspace.cases.length&&<tr><td colSpan={7} className="subtle">No golden QTO benchmark case exists yet.</td></tr>}</tbody></table></div></section></>;
}
