"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {RealityCapture,RealityDeviation,RealityWorkspaceState} from "@/components/lifecycle-runtime-types";

const pretty=(v:string)=>v.replaceAll("_"," ");
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseJSON(raw:FormDataEntryValue|null,label:string,fallback:unknown){try{return JSON.parse(String(raw??JSON.stringify(fallback)));}catch{throw new Error(`${label} must be valid JSON.`);}}

export default function RealityVerificationClient({projectId,state}:{projectId:string;state:RealityWorkspaceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const captures=state.captures||[];const deviations=state.deviations||[];const models=state.approved_models||[];
 const modelName=(id?:string|null)=>id?models.find(m=>m.id===id)?.model_name||id.slice(0,8):"—";
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function registerCapture(form:FormData){try{const tolerance=parseJSON(form.get("tolerance"),"Tolerance",{});const provenance=parseJSON(form.get("capture_provenance"),"Capture provenance",{});const {error}=await supabase.rpc("register_reality_capture",{target_project_id:projectId,input_payload:{capture_type:String(form.get("capture_type")||"photo"),capture_ref:String(form.get("capture_ref")||""),model_id:String(form.get("model_id")||""),coordinate_system:String(form.get("coordinate_system")||"")||undefined,tolerance,capture_provenance:provenance}});if(error)throw error;refresh("Reality capture registered against the exact approved model checksum.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function compare(form:FormData){try{const deviationsPayload=parseJSON(form.get("deviations"),"Deviations",[]);if(!Array.isArray(deviationsPayload))throw new Error("Deviations must be a JSON array.");const {error}=await supabase.rpc("record_reality_comparison",{target_capture_id:String(form.get("capture_id")||""),input_payload:{deviations:deviationsPayload,engine_ref:String(form.get("engine_ref")||"")||undefined,algorithm_version:String(form.get("algorithm_version")||"")||undefined}});if(error)throw error;refresh("Reality comparison recorded. The comparison hash was derived server-side from capture, model and deviation evidence.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function review(d:RealityDeviation,decision:string){const note=window.prompt(`${decision} note for ${d.deviation_type} deviation:`)||"";if(decision!=="review"&&!note)return;let approvedRef="";if(decision==="accepted"&&["major","critical"].includes(d.severity)){approvedRef=window.prompt("Approved deviation reference:")||"";if(!approvedRef)return;}const {error}=await supabase.rpc("review_reality_deviation",{target_deviation_id:d.id,target_decision:decision,input_payload:{review_note:note,accepted_deviation_ref:approvedRef||undefined}});if(error){setMessage(error.message);return;}refresh(decision==="ncr_raised"?"Deviation escalated into a governed coordination issue and formal NCR.":`Deviation moved to ${decision}.`);}
 return <section className="panel" style={{marginTop:16}}><div><div className="eyebrow">Reality Verification</div><h3>Exact-model capture, comparison and human disposition</h3><p className="subtle">Capture registration pins the approved model checksum. Comparison hashes are generated inside the database from the controlled evidence payload, not trusted from the browser.</p></div>
 {message&&<div className="note" style={{margin:"10px 0"}}>{message}{busy?" Refreshing…":""}</div>}
 <div className="kpis">{[["Captures",String(captures.length).padStart(2,"0")],["Review Required",String(captures.filter(c=>c.comparison_status==="review_required").length).padStart(2,"0")],["Open Deviations",String(deviations.filter(d=>["detected","review"].includes(d.status)).length).padStart(2,"0")],["Major / Critical",String(deviations.filter(d=>["major","critical"].includes(d.severity)&&!["resolved","accepted"].includes(d.status)).length).padStart(2,"0")],["Accepted Captures",String(captures.filter(c=>c.comparison_status==="accepted").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live</div></div>)}</div>
 <div className="panel-grid" style={{marginTop:16}}><form action={registerCapture}><h3>Register Capture</h3><div className="field-grid"><div className="field"><label>Capture type</label><select name="capture_type"><option value="photo">Photo</option><option value="360">360</option><option value="drone">Drone</option><option value="point_cloud">Point cloud</option><option value="lidar">LiDAR</option></select></div><div className="field"><label>Capture reference</label><input name="capture_ref" required placeholder="CDE / object storage reference"/></div><div className="field"><label>Approved model</label><select name="model_id" required>{models.map(m=><option key={m.id} value={m.id}>{m.discipline} · {m.model_name} · {m.revision??"current"}</option>)}</select></div><div className="field"><label>Coordinate system</label><input name="coordinate_system" placeholder="Optional override"/></div></div><div className="field"><label>Tolerance JSON</label><textarea name="tolerance" rows={3} defaultValue={'{"position_mm":20,"dimension_mm":10}'}/></div><div className="field"><label>Capture provenance JSON</label><textarea name="capture_provenance" rows={3} defaultValue={'{"source":"site_capture","device":"recorded"}'}/></div><button className="btn">Register Against Model</button></form>
 <form action={compare}><h3>Record Deterministic Comparison</h3><div className="field"><label>Capture</label><select name="capture_id" required>{captures.filter(c=>["queued","processing","failed"].includes(c.comparison_status)).map(c=><option key={c.id} value={c.id}>{c.capture_type} · {c.capture_ref} · {modelName(c.model_id)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Engine reference</label><input name="engine_ref" placeholder="comparison-engine"/></div><div className="field"><label>Algorithm version</label><input name="algorithm_version" placeholder="1.0.0"/></div></div><div className="field"><label>Deviations JSON</label><textarea name="deviations" rows={8} defaultValue={'[]'} placeholder='[{"deviation_type":"position","model_object_ref":"GUID","measured_value":35,"permitted_tolerance":20,"unit":"mm","severity":"major","confidence":0.94,"evidence_refs":["capture://evidence"]}]'/></div><button className="btn">Record Comparison</button></form></div>
 <section style={{marginTop:16}}><h3>Capture Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Captured</th><th>Type / Ref</th><th>Model</th><th>Status</th><th>Registration</th><th>Comparison</th></tr></thead><tbody>{captures.map((c:RealityCapture)=><tr key={c.id}><td>{new Date(c.captured_at).toLocaleString("en-IN")}</td><td><b>{c.capture_type}</b><div className="subtle">{c.capture_ref}</div></td><td>{modelName(c.model_id)}<div className="subtle"><code>{shortHash(c.model_checksum)}</code></div></td><td><span className="badge">{pretty(c.comparison_status)}</span></td><td><code>{shortHash(c.registration_hash)}</code></td><td><code>{shortHash(c.comparison_hash)}</code></td></tr>)}{captures.length===0&&<tr><td colSpan={6} className="subtle">No reality captures yet.</td></tr>}</tbody></table></div></section>
 <section style={{marginTop:16}}><h3>Deviation Review</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Deviation</th><th>Location / Object</th><th>Measured</th><th>Confidence</th><th>Status</th><th>Decision</th></tr></thead><tbody>{deviations.map((d:RealityDeviation)=><tr key={d.id}><td><b>{pretty(d.deviation_type)}</b><div className="subtle">{d.severity}</div></td><td>{d.location_ref||"—"}<div className="subtle">{d.model_object_ref||"No object ref"}</div></td><td>{d.measured_value??"—"} {d.unit||""}<div className="subtle">Tolerance {d.permitted_tolerance??"—"}</div></td><td>{d.confidence==null?"—":`${(Number(d.confidence)*100).toFixed(1)}%`}</td><td><span className="badge">{pretty(d.status)}</span></td><td>{["detected","review"].includes(d.status)&&<div style={{display:"flex",gap:5,flexWrap:"wrap"}}><button className="btn ghost" type="button" onClick={()=>review(d,"review")}>Review</button><button className="btn ghost" type="button" onClick={()=>review(d,"accepted")}>Accept</button><button className="btn ghost" type="button" onClick={()=>review(d,"ncr_raised")}>Raise NCR</button></div>}</td></tr>)}{deviations.length===0&&<tr><td colSpan={6} className="subtle">No deviations recorded.</td></tr>}</tbody></table></div></section>
 </section>;
}
