"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type Pack={id:string;code:string;version:number;title:string;authority:string;publication_status:string;jurisdiction_country:string;jurisdiction_state?:string|null;jurisdiction_city?:string|null;effective_from:string;effective_until?:string|null;source_uri?:string|null;source_hash?:string|null;content_hash?:string|null;created_by?:string|null;technical_reviewed_by?:string|null;published_by?:string|null};
type Rule={id:string;pack_id:string;rule_code:string;subject:string;source_reference:string;clause_reference?:string|null;effective_from:string;disposition:string;requires_professional_interpretation:boolean;rule_hash?:string|null};
type Impact={id:string;project_id:string;pack_id:string;status:string;reason:string;evidence_hash:string;detected_at:string};
export type RegulaGovernanceState={packs:Pack[];rules:Rule[];impacts:Impact[]};
export default function RegulaGovernanceClient({state}:{state:RegulaGovernanceState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const refresh=(m:string)=>{setMessage(m);startTransition(()=>router.refresh());};
 async function createPack(form:FormData){const payload={code:String(form.get("code")||""),title:String(form.get("title")||""),authority:String(form.get("authority")||""),jurisdiction_country:String(form.get("jurisdiction_country")||"IN"),jurisdiction_state:String(form.get("jurisdiction_state")||""),jurisdiction_city:String(form.get("jurisdiction_city")||""),effective_from:String(form.get("effective_from")||""),effective_until:String(form.get("effective_until")||""),source_uri:String(form.get("source_uri")||""),source_hash:String(form.get("source_hash")||"").toLowerCase()};const {error}=await supabase.rpc("create_regula_pack",{input_payload:payload});if(error){setMessage(error.message);return;}refresh("REGULA pack draft created with source/effective-date provenance.");}
 async function addRule(form:FormData){const packId=String(form.get("pack_id")||"");const payload={rule_code:String(form.get("rule_code")||""),subject:String(form.get("subject")||""),expression:String(form.get("expression")||""),narrative:String(form.get("narrative")||""),source_reference:String(form.get("source_reference")||""),clause_reference:String(form.get("clause_reference")||""),effective_from:String(form.get("effective_from")||""),disposition:String(form.get("disposition")||"amber"),requires_professional_interpretation:form.get("requires_professional_interpretation")==="on"};const {error}=await supabase.rpc("add_regula_rule",{target_pack_id:packId,input_payload:payload});if(error){setMessage(error.message);return;}refresh("Rule added to the draft pack with clause/source hash.");}
 async function transition(pack:Pack,status:string){const reason=window.prompt(`Reason for moving ${pack.code} v${pack.version} to ${status}?`);if(!reason)return;const {error}=await supabase.rpc("transition_regula_pack",{target_pack_id:pack.id,target_status:status,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`REGULA pack moved to ${status}.`);}
 const draftPacks=state.packs.filter(p=>p.publication_status==="draft");
 return <section className="panel" style={{marginTop:18}}><h3>REGULA Publication Governance</h3>{message&&<div className="note" role="status" aria-live="polite" style={{marginBottom:14}}>{message}{busy?" Refreshing…":""}</div>}
  <div className="panel-grid">
   <div><h3>New Source Pack</h3><form action={createPack}><div className="field-grid"><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Authority</label><input name="authority" required/></div><div className="field"><label>Country</label><input name="jurisdiction_country" defaultValue="IN" required/></div><div className="field"><label>State</label><input name="jurisdiction_state"/></div><div className="field"><label>City</label><input name="jurisdiction_city"/></div><div className="field"><label>Effective From</label><input type="date" name="effective_from" required/></div><div className="field"><label>Effective Until</label><input type="date" name="effective_until"/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Authoritative Source URI</label><input name="source_uri" required/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Source SHA-256</label><input name="source_hash" pattern="[0-9A-Fa-f]{64}" required/></div></div><button className="btn" style={{marginTop:12}}>Create Draft Pack</button></form></div>
   <div><h3>Add Rule</h3><form action={addRule}><div className="field-grid"><div className="field"><label>Draft Pack</label><select name="pack_id" required><option value="">Select</option>{draftPacks.map(p=><option key={p.id} value={p.id}>{p.code} v{p.version}</option>)}</select></div><div className="field"><label>Rule Code</label><input name="rule_code" required/></div><div className="field"><label>Subject</label><input name="subject" required/></div><div className="field"><label>Effective From</label><input type="date" name="effective_from" required/></div><div className="field"><label>Disposition</label><select name="disposition" defaultValue="amber"><option value="green">Green</option><option value="amber">Amber</option><option value="red">Red</option></select></div><div className="field"><label>Clause Reference</label><input name="clause_reference" required/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Source Reference</label><input name="source_reference" required/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Narrative</label><textarea name="narrative" rows={3} required/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Deterministic Expression (optional)</label><textarea name="expression" rows={2}/></div></div><label style={{display:"block",marginTop:10}}><input type="checkbox" name="requires_professional_interpretation"/> Requires professional interpretation</label><button className="btn" style={{marginTop:12}}>Add Rule</button></form></div>
  </div>
  <div style={{overflowX:"auto",marginTop:18}}><table className="table"><thead><tr><th>Pack</th><th>Authority / Source</th><th>State</th><th>Rules</th><th>Control</th></tr></thead><tbody>{state.packs.map(p=><tr key={p.id}><td><b>{p.code} v{p.version}</b><div className="subtle">{p.title}<br/>{p.effective_from}{p.effective_until?` → ${p.effective_until}`:" → current"}</div></td><td>{p.authority}<div className="subtle">{p.source_uri||"—"}<br/><code>{p.source_hash?.slice(0,12)}…</code></div></td><td><span className="badge">{p.publication_status.replaceAll("_"," ")}</span></td><td>{state.rules.filter(r=>r.pack_id===p.id).length}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{p.publication_status==="draft"&&<button className="btn ghost" type="button" onClick={()=>transition(p,"technical_review")}>Submit</button>}{p.publication_status==="technical_review"&&<button className="btn ghost" type="button" onClick={()=>transition(p,"legal_review")}>Technical Approve</button>}{p.publication_status==="legal_review"&&<button className="btn" type="button" onClick={()=>transition(p,"published")}>Publish</button>}{p.publication_status==="published"&&<button className="btn ghost" type="button" onClick={()=>transition(p,"retired")}>Retire</button>}</div></td></tr>)}{state.packs.length===0&&<tr><td colSpan={5} className="subtle">No REGULA packs are governed yet.</td></tr>}</tbody></table></div>
  <div className="note" style={{marginTop:14}}><b>Impact detection:</b> publishing a pack creates evidence-hashed candidate impacts for matching active projects and invalidates affected compiler outputs. {state.impacts.length} impact record(s) currently exist.</div>
 </section>;
}
