"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Applicability={id:string;pack_id:string;pack_code:string;title:string;authority?:string|null;effective_from:string;effective_until?:string|null;status:string;precedence:number;confirmed_by?:string|null;confirmed_at?:string|null};
type Run={id:string;as_of:string;engine:string;engine_version:string;status:string;rules_evaluated:number;deterministic_passes:number;deterministic_failures:number;interpretation_required:number;not_verified:number;created_at:string}|null;
type Finding={id:string;rule_code:string;subject:string;disposition:string;status:string;observed_value:unknown;required_value:unknown;explanation:string;source_reference:string;checked_at:string};
export type RegulaState={applicability:Applicability[];latest_run:Run;latest_findings:Finding[]};
export default function RegulaRuntimeClient({projectId,state}:{projectId:string;state:RegulaState}){
 const router=useRouter();const supabase=createClient();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const refresh=()=>startTransition(()=>router.refresh());
 async function resolve(){setMessage("Resolving published packs by project jurisdiction and effective date…");const {data,error}=await supabase.rpc("resolve_regula_applicability",{target_project_id:projectId,target_as_of:new Date().toISOString().slice(0,10)});if(error){setMessage(error.message);return;}setMessage(`${data||0} new candidate pack(s) proposed. A verified regulatory professional must confirm applicability.`);refresh();}
 async function decide(id:string,decision:"confirmed"|"rejected"){setMessage(`Recording ${decision} applicability decision…`);const {error}=await supabase.rpc("confirm_regula_applicability",{target_applicability_id:id,target_decision:decision});if(error){setMessage(error.message);return;}setMessage(`Applicability ${decision}.`);refresh();}
 async function run(){setMessage("Running deterministic Green-rule evaluation. Amber and Red rules remain human/authority gated…");const {data,error}=await supabase.functions.invoke("regula-evaluate",{body:{project_id:projectId,as_of:new Date().toISOString().slice(0,10)}});if(error){setMessage(error.message);return;}const result=data as {error?:string;summary?:{rules_evaluated:number;pass:number;fail:number;requires_interpretation:number;not_verified:number}};if(result.error){setMessage(result.error);return;}setMessage(`REGULA completed ${result.summary?.rules_evaluated||0} rule(s): ${result.summary?.pass||0} pass, ${result.summary?.fail||0} fail, ${result.summary?.requires_interpretation||0} interpretation, ${result.summary?.not_verified||0} not verified.`);refresh();}
 const runState=state.latest_run;return <>
 {message&&<div className="note" style={{marginBottom:16}}><b>REGULA:</b> {message}{busy?" Refreshing…":""}</div>}
 <div className="topbar" style={{marginBottom:16}}><div><div className="subtle">Only published packs can be proposed. Applicability remains a professional decision.</div></div><div style={{display:"flex",gap:10}}><button className="btn ghost" onClick={resolve}>Resolve Applicability</button><button className="btn" onClick={run}>Run Compliance</button></div></div>
 <div className="kpis">{[["Applicable Packs",String(state.applicability.filter(a=>a.status==="confirmed").length)],["Rules Evaluated",String(runState?.rules_evaluated||0)],["Pass",String(runState?.deterministic_passes||0)],["Fail",String(runState?.deterministic_failures||0)],["Human / Unknown",String((runState?.interpretation_required||0)+(runState?.not_verified||0))]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live database</div></div>)}</div>
 <section className="panel" style={{marginTop:18}}><h3>Applicability Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Pack</th><th>Authority</th><th>Effective</th><th>Status</th><th>Decision</th></tr></thead><tbody>{state.applicability.map(a=><tr key={a.id}><td><b>{a.pack_code}</b><br/><span className="subtle">{a.title}</span></td><td>{a.authority||"Not stated"}</td><td>{a.effective_from}{a.effective_until?` → ${a.effective_until}`:" → current"}</td><td><span className="badge">{a.status}</span></td><td>{a.status==="proposed"?<div style={{display:"flex",gap:8}}><button className="btn ghost" onClick={()=>decide(a.id,"confirmed")}>Confirm</button><button className="btn ghost" onClick={()=>decide(a.id,"rejected")}>Reject</button></div>:<span className="subtle">{a.confirmed_at?new Date(a.confirmed_at).toLocaleString("en-IN"):"Recorded"}</span>}</td></tr>)}{state.applicability.length===0&&<tr><td colSpan={5} className="subtle">No candidate regulatory packs have been resolved for this project yet.</td></tr>}</tbody></table></div></section>
 <section className="panel" style={{marginTop:18}}><h3>Latest Compliance Findings</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Rule</th><th>Subject</th><th>Disposition</th><th>Status</th><th>Evidence / Explanation</th></tr></thead><tbody>{state.latest_findings.map(f=><tr key={f.id}><td>{f.rule_code}</td><td>{f.subject}</td><td><span className="badge">{f.disposition}</span></td><td><span className="badge">{f.status.replaceAll("_"," ")}</span></td><td><div>{f.explanation}</div><div className="subtle">Source: {f.source_reference}</div></td></tr>)}{state.latest_findings.length===0&&<tr><td colSpan={5} className="subtle">No compliance evaluation has been executed against confirmed packs.</td></tr>}</tbody></table></div></section>
 <div className="panel-grid"><section className="panel"><h3>Disposition Contract</h3><p className="subtle"><b>Green</b> is evaluated only when a published deterministic evaluator and verified Project Truth input both exist.<br/><br/><b>Amber</b> always returns Requires Interpretation.<br/><br/><b>Red</b> remains Not Verified until authority/specialist evidence is provided.</p></section><section className="panel"><h3>No-Hallucination Regulatory Rule</h3><p className="subtle">REGULA never invents FAR, setbacks, height limits, parking ratios or statutory applicability. Missing rule logic or unverified input produces Not Verified, not a guessed answer.</p></section></div>
 </>;
}
