"use client";
import {useRouter} from "next/navigation";
import {useState,useTransition} from "react";
import {createClient} from "@/lib/supabase";

type ProjectChoice={id:string;code:string;name:string};
type Job={id:string;project_id?:string|null;job_type:string;status:string;criticality:string;autonomy_level:string;trace_id:string;engine_id?:string|null;engine_version?:string|null;input_hash?:string|null;output_hash?:string|null;retry_count:number;max_retries:number;quarantine_reason?:string|null;created_at:string;finished_at?:string|null;error?:unknown};
type Provider={provider_key:string;environment:string;status:string;latency_ms?:number|null;consecutive_failures:number;last_error_code?:string|null;checked_at:string;instance_status?:string|null;circuit_open_until?:string|null;failure_threshold?:number|null};
type Slo={id:string;service:string;metric_key:string;target_operator:"gte"|"lte";target_value:number;unit:string;window_minutes:number;status:string;version:number;slo_hash:string;created_by:string;latest_value?:number|null;latest_observed_at?:string|null;within_target?:boolean|null};
type Incident={id:string;number:string;title:string;severity:string;status:string;customer_impact:string;trace_id:string;detected_at:string;postmortem_ref?:string|null;resolution_hash?:string|null};
type Drill={id:string;service:string;backup_ref:string;environment:string;started_at:string;completed_at?:string|null;rpo_minutes_target:number;rto_minutes_target:number;achieved_rpo_minutes?:number|null;achieved_rto_minutes?:number|null;status:string;drill_hash?:string|null};
export type SreState={jobs:Job[];providers:Provider[];slos:Slo[];incidents:Incident[];drills:Drill[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
export default function ReliabilityWorkspaceClient({organisationId,projects,state}:{organisationId:string;projects:ProjectChoice[];state:SreState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 async function rpc(name:string,args:Record<string,unknown>,ok:string){const {error}=await supabase.rpc(name,args);if(error){setMessage(error.message);return;}refresh(ok);}
 async function createJob(fd:FormData){let input:Record<string,unknown>={};try{input=JSON.parse(String(fd.get("input")||"{}"));}catch{setMessage("Job input must be valid JSON.");return;}await rpc("create_compute_job",{target_organisation_id:organisationId,target_project_id:String(fd.get("project_id")||"")||null,target_job_type:String(fd.get("job_type")||""),input_payload:input,target_idempotency_key:String(fd.get("idempotency_key")||""),target_engine_id:String(fd.get("engine_id")||""),target_engine_version:String(fd.get("engine_version")||""),target_criticality:String(fd.get("criticality")||"C1"),target_autonomy_level:String(fd.get("autonomy")||"ai_draft")},"Compute job created with immutable input hash and trace ID.");}
 async function retryJob(fd:FormData){await rpc("retry_compute_job",{target_job_id:String(fd.get("job_id")),target_reason:String(fd.get("reason")||"")},"Failed job requeued with the same immutable input hash.");}
 async function quarantineJob(fd:FormData){await rpc("quarantine_compute_job",{target_job_id:String(fd.get("job_id")),target_reason:String(fd.get("reason")||"")},"Job quarantined without mutating project source-of-truth state.");}
 async function createSlo(fd:FormData){await rpc("create_service_slo",{input_payload:{service:String(fd.get("service")||""),metric_key:String(fd.get("metric_key")||""),target_operator:String(fd.get("target_operator")||"gte"),target_value:String(fd.get("target_value")||""),unit:String(fd.get("unit")||""),window_minutes:String(fd.get("window_minutes")||"")}},"SLO draft created.");}
 async function approveSlo(fd:FormData){await rpc("approve_service_slo",{target_slo_id:String(fd.get("slo_id")),target_reason:String(fd.get("reason")||"")},"SLO independently approved.");}
 async function recordTelemetry(fd:FormData){await rpc("record_service_telemetry",{input_payload:{service:String(fd.get("service")||""),metric_key:String(fd.get("metric_key")||""),metric_value:String(fd.get("metric_value")||""),unit:String(fd.get("unit")||""),source:String(fd.get("source")||""),trace_id:String(fd.get("trace_id")||"")||null}},"Telemetry sample recorded with evidence hash.");}
 async function declareIncident(fd:FormData){await rpc("declare_platform_incident",{input_payload:{severity:String(fd.get("severity")||"SEV2"),title:String(fd.get("title")||""),customer_impact:String(fd.get("customer_impact")||""),regulatory_impact:String(fd.get("regulatory_impact")||""),service_refs:String(fd.get("services")||"").split(",").map(v=>v.trim()).filter(Boolean)}},"Incident declared with trace ID.");}
 async function transitionIncident(fd:FormData){await rpc("transition_platform_incident",{target_incident_id:String(fd.get("incident_id")),target_status:String(fd.get("status")||"monitoring"),input_payload:{postmortem_ref:String(fd.get("postmortem_ref")||""),resolution_evidence_refs:String(fd.get("evidence")||"").split(",").map(v=>v.trim()).filter(Boolean)}},"Incident state advanced with governed evidence.");}
 async function startDrill(fd:FormData){await rpc("start_restore_drill",{input_payload:{service:String(fd.get("service")||""),backup_ref:String(fd.get("backup_ref")||""),environment:String(fd.get("environment")||"staging"),rpo_minutes_target:String(fd.get("rpo")||""),rto_minutes_target:String(fd.get("rto")||"")}},"Restore drill started.");}
 async function completeDrill(fd:FormData){await rpc("complete_restore_drill",{target_drill_id:String(fd.get("drill_id")),input_payload:{achieved_rpo_minutes:String(fd.get("achieved_rpo")||""),achieved_rto_minutes:String(fd.get("achieved_rto")||""),integrity_checks:String(fd.get("checks")||"").split(",").map(v=>v.trim()).filter(Boolean),evidence_refs:String(fd.get("evidence")||"").split(",").map(v=>v.trim()).filter(Boolean)}},"Restore drill completed; pass/fail computed from achieved RPO/RTO and evidence.");}
 const openIncidents=state.incidents.filter(i=>i.status!=="closed").length;const failedJobs=state.jobs.filter(j=>j.status==="failed"||j.status==="quarantined").length;const openCircuits=state.providers.filter(p=>p.circuit_open_until&&new Date(p.circuit_open_until)>new Date()).length;const failingSlos=state.slos.filter(s=>s.status==="active"&&s.within_target===false).length;
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>SRE:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Open Incidents",String(openIncidents)],["Failed / Quarantined Jobs",String(failedJobs)],["Open Provider Circuits",String(openCircuits)],["SLO Breaches",String(failingSlos)],["DR Evidence",String(state.drills.filter(d=>d.status==="pass").length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Create Compute Job</h3><form action={createJob} style={{display:"grid",gap:8}}><select name="project_id"><option value="">Organisation-level job</option>{projects.map(p=><option value={p.id} key={p.id}>{p.code} · {p.name}</option>)}</select><input name="job_type" required placeholder="Job type: render / solver / QA"/><input name="idempotency_key" required placeholder="Idempotency key"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input name="engine_id" required placeholder="Engine ID"/><input name="engine_version" required placeholder="Engine version"/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><select name="criticality" defaultValue="C1">{["C0","C1","C2","C3","C4"].map(v=><option key={v}>{v}</option>)}</select><select name="autonomy" defaultValue="ai_draft"><option>human_only</option><option>ai_advisory</option><option>ai_draft</option><option>execute_after_approval</option><option>bounded_autonomous</option></select></div><textarea name="input" defaultValue="{}" rows={5}/><button className="btn">Create Idempotent Job</button></form></section>
   <section className="panel"><h3>Provider Health & Circuit State</h3><div style={{display:"grid",gap:8}}>{state.providers.map(p=><div className="note" key={`${p.provider_key}-${p.environment}`}><b>{p.provider_key} · {p.environment}</b> <span className="badge">{pretty(p.status)}</span><div className="subtle">Latency {p.latency_ms??"—"} ms · consecutive failures {p.consecutive_failures}/{p.failure_threshold??3} · instance {pretty(p.instance_status)}</div><div className="subtle">Circuit {p.circuit_open_until&&new Date(p.circuit_open_until)>new Date()?`OPEN until ${new Date(p.circuit_open_until).toLocaleString("en-IN")}`:"closed"}{p.last_error_code?` · ${p.last_error_code}`:""}</div></div>)}{state.providers.length===0&&<div className="note">No provider health evidence has been recorded yet.</div>}</div></section>
  </div>
  <section className="panel"><h3>Compute Job Console</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Job</th><th>State</th><th>Engine</th><th>Trace</th><th>Input / Output</th><th>Retry</th><th>Recovery</th></tr></thead><tbody>{state.jobs.map(j=><tr key={j.id}><td><b>{j.job_type}</b><div className="subtle">{new Date(j.created_at).toLocaleString("en-IN")}</div></td><td><span className="badge">{pretty(j.status)}</span><div className="subtle">{j.criticality} · {pretty(j.autonomy_level)}</div></td><td>{j.engine_id||"—"}<div className="subtle">{j.engine_version||"—"}</div></td><td><code>{j.trace_id.slice(0,12)}…</code></td><td><code>{short(j.input_hash)}</code><div className="subtle">out {short(j.output_hash)}</div></td><td>{j.retry_count}/{j.max_retries}</td><td>{j.status==="failed"?<div style={{display:"grid",gap:6,minWidth:210}}><form action={retryJob} style={{display:"flex",gap:5}}><input type="hidden" name="job_id" value={j.id}/><input name="reason" required placeholder="Retry reason"/><button className="btn ghost">Retry</button></form><form action={quarantineJob} style={{display:"flex",gap:5}}><input type="hidden" name="job_id" value={j.id}/><input name="reason" required placeholder="Quarantine reason"/><button className="btn ghost">Quarantine</button></form></div>:j.status==="quarantined"?<span className="subtle">{j.quarantine_reason}</span>:"—"}</td></tr>)}{state.jobs.length===0&&<tr><td colSpan={7} className="subtle">No governed compute jobs recorded.</td></tr>}</tbody></table></div></section>
  <div className="panel-grid">
   <section className="panel"><h3>SLO Governance</h3><form action={createSlo} style={{display:"grid",gap:7}}><input name="service" required placeholder="Service"/><input name="metric_key" required placeholder="Metric key"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><select name="target_operator"><option value="gte">≥ target</option><option value="lte">≤ target</option></select><input name="target_value" type="number" step="any" required placeholder="Target"/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input name="unit" required placeholder="Unit"/><input name="window_minutes" type="number" min="1" required placeholder="Window minutes"/></div><button className="btn">Draft SLO</button></form><div style={{marginTop:12,display:"grid",gap:8}}>{state.slos.map(s=><div className="note" key={s.id}><b>{s.service} · {s.metric_key} · v{s.version}</b> <span className="badge">{pretty(s.status)}</span><div className="subtle">Target {s.target_operator==="gte"?"≥":"≤"} {s.target_value} {s.unit} / {s.window_minutes} min · latest {s.latest_value??"—"} {s.unit} · {s.within_target===true?"within target":s.within_target===false?"BREACH":"no sample"}</div>{s.status==="draft"&&<form action={approveSlo} style={{display:"flex",gap:5,marginTop:6}}><input type="hidden" name="slo_id" value={s.id}/><input name="reason" required placeholder="Independent approval reason"/><button className="btn ghost">Approve</button></form>}</div>)}</div></section>
   <section className="panel"><h3>Record Telemetry Evidence</h3><form action={recordTelemetry} style={{display:"grid",gap:8}}><input name="service" required placeholder="Service"/><input name="metric_key" required placeholder="Metric key"/><input name="metric_value" type="number" step="any" required placeholder="Value"/><input name="unit" required placeholder="Unit"/><input name="source" required placeholder="Source: Vercel / synthetic / DB"/><input name="trace_id" placeholder="Trace UUID (optional)"/><button className="btn">Record Evidence</button></form></section>
  </div>
  <section className="panel" id="incidents"><h3>Incident Command</h3><form action={declareIncident} style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><select name="severity"><option>SEV0</option><option>SEV1</option><option>SEV2</option><option>SEV3</option></select><input name="title" required placeholder="Incident title"/><input name="customer_impact" required placeholder="Customer impact"/><input name="services" placeholder="Service refs, comma separated"/><input name="regulatory_impact" placeholder="Regulatory impact"/><button className="btn">Declare Incident</button></form><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Impact</th><th>Trace</th><th>Transition</th></tr></thead><tbody>{state.incidents.map(i=><tr key={i.id}><td><b>{i.number}</b><div className="subtle">{i.title}</div></td><td><span className="badge">{i.severity}</span></td><td>{pretty(i.status)}</td><td>{i.customer_impact}</td><td><code>{i.trace_id.slice(0,12)}…</code></td><td>{i.status!=="closed"?<form action={transitionIncident} style={{display:"grid",gap:5,minWidth:220}}><input type="hidden" name="incident_id" value={i.id}/><select name="status"><option>mitigating</option><option>monitoring</option><option>resolved</option><option>postmortem</option><option>closed</option></select><input name="postmortem_ref" placeholder="Postmortem ref (required SEV0/1 close)"/><input name="evidence" placeholder="Resolution evidence refs"/><button className="btn ghost">Advance</button></form>:<code>{short(i.resolution_hash)}</code>}</td></tr>)}{state.incidents.length===0&&<tr><td colSpan={6} className="subtle">No platform incidents visible.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Backup / Restore Drills</h3><form action={startDrill} style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><input name="service" required placeholder="Service"/><input name="backup_ref" required placeholder="Backup reference"/><select name="environment"><option>staging</option><option>test</option></select><input name="rpo" type="number" min="1" required placeholder="RPO target min"/><input name="rto" type="number" min="1" required placeholder="RTO target min"/><button className="btn">Start Restore Drill</button></form><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Service</th><th>Environment</th><th>Targets</th><th>Achieved</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{state.drills.map(d=><tr key={d.id}><td><b>{d.service}</b><div className="subtle">{d.backup_ref}</div></td><td>{d.environment}</td><td>RPO {d.rpo_minutes_target}m · RTO {d.rto_minutes_target}m</td><td>{d.achieved_rpo_minutes??"—"}m / {d.achieved_rto_minutes??"—"}m</td><td><span className="badge">{pretty(d.status)}</span></td><td>{d.status==="running"?<form action={completeDrill} style={{display:"grid",gap:5,minWidth:220}}><input type="hidden" name="drill_id" value={d.id}/><input name="achieved_rpo" type="number" min="0" required placeholder="Achieved RPO"/><input name="achieved_rto" type="number" min="0" required placeholder="Achieved RTO"/><input name="checks" required placeholder="Integrity checks, comma separated"/><input name="evidence" required placeholder="Evidence refs, comma separated"/><button className="btn ghost">Complete Drill</button></form>:<code>{short(d.drill_hash)}</code>}</td></tr>)}{state.drills.length===0&&<tr><td colSpan={6} className="subtle">No restore drills recorded.</td></tr>}</tbody></table></div></section>
 </>;
}
