"use client";
import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {CommercialProposal,ScopeCatalogueItem,ScopeCommercialState,ScopeOverride,ScopeSelection} from "@/components/commercial-runtime-types";

const money=(n:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n||0));
const pretty=(v:string)=>v.replaceAll("_"," ");
const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseJSON(raw:string,label:string,fallback:unknown){try{return JSON.parse(raw||JSON.stringify(fallback));}catch{throw new Error(`${label} must be valid JSON.`);}}

type DraftScope={state:string;pricing_model:string;quoted_amount:string;notes:string};
export default function ScopeCommercialClient({organisationId,state}:{organisationId:string;state:ScopeCommercialState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const [opportunityId,setOpportunityId]=useState(state.opportunities[0]?.id||"");
 const opportunity=state.opportunities.find(o=>o.id===opportunityId);const intake=state.intake_sessions.find(s=>s.opportunity_id===opportunityId);const currentSelections=state.selections.filter(s=>s.intake_session_id===intake?.id);const currentOverrides=state.overrides.filter(o=>o.intake_session_id===intake?.id);const currentProposals=state.proposals.filter(p=>p.opportunity_id===opportunityId).sort((a,b)=>b.version-a.version);const currentProposalIds=new Set(currentProposals.map(p=>p.id));const events=state.negotiation_events.filter(e=>currentProposalIds.has(e.proposal_id));
 const initialDrafts=useMemo(()=>Object.fromEntries(state.catalogue.map(c=>{const s=currentSelections.find(x=>x.module_code.toUpperCase()===c.code.toUpperCase());return [c.code,{state:s?.state||c.default_state,pricing_model:s?.pricing_model||String(c.pricing_models?.[0]||"fixed"),quoted_amount:s?.quoted_amount==null?"":String(s.quoted_amount),notes:s?.notes||""}]})),[opportunityId,intake?.id,state.catalogue,currentSelections.length]);
 const [drafts,setDrafts]=useState<Record<string,DraftScope>>(initialDrafts);
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 function change(code:string,patch:Partial<DraftScope>){setDrafts(prev=>({...prev,[code]:{...(prev[code]||initialDrafts[code]),...patch}}));}
 const previewTotal=state.catalogue.reduce((sum,c)=>{const d=drafts[c.code]||initialDrafts[c.code];return sum+(d?.state==="included"?Number(d.quoted_amount||0):0);},0);
 async function ensureSession(){if(!opportunityId){setMessage("Create an opportunity in CRM first.");return;}const {error}=await supabase.rpc("ensure_opportunity_scope_session",{target_opportunity_id:opportunityId});if(error){setMessage(error.message);return;}refresh("Commercial scope session created with the canonical service catalogue.");}
 async function saveScope(c:ScopeCatalogueItem){if(!intake){setMessage("Create the scope session first.");return;}const d=drafts[c.code]||initialDrafts[c.code];const {error}=await supabase.rpc("set_scope_selection",{target_intake_session_id:intake.id,target_module_code:c.code,input_payload:{state:d.state,pricing_model:d.state==="excluded"?undefined:d.pricing_model,quoted_amount:d.state==="excluded"?undefined:d.quoted_amount,currency:opportunity?.currency||"INR",notes:d.notes}});if(error){setMessage(error.message);return;}refresh(`${c.code} scope saved and dependency-validated.`);}
 async function requestOverride(c:ScopeCatalogueItem,dependency:string){if(!intake)return;const reason=window.prompt(`${c.code} normally depends on ${dependency}. Give the override reason:`)||"";if(!reason)return;const evidenceRaw=window.prompt("Evidence / external-responsibility references JSON:","[]")||"";if(!evidenceRaw)return;try{const evidence=parseJSON(evidenceRaw,"Override evidence",[]);if(!Array.isArray(evidence)||evidence.length===0)throw new Error("At least one evidence reference is required.");const {error}=await supabase.rpc("request_scope_dependency_override",{target_intake_session_id:intake.id,target_module_code:c.code,target_dependency_code:dependency,target_reason:reason,target_evidence_refs:evidence});if(error)throw error;refresh(`Dependency override requested for ${c.code} → ${dependency}.`);}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function decideOverride(o:ScopeOverride,decision:string){const reason=window.prompt(`${decision} override ${o.module_code} → ${o.dependency_code}:`)||"";if(!reason)return;const {error}=await supabase.rpc("decide_scope_dependency_override",{target_override_id:o.id,target_decision:decision,target_reason:reason});if(error){setMessage(error.message);return;}refresh(`Scope dependency override ${decision}.`);}
 async function createProposal(form:FormData){if(!intake||!opportunityId){setMessage("A scope session is required.");return;}try{const notes=parseJSON(String(form.get("commercial_notes")||"[]"),"Commercial notes",[]);const {error}=await supabase.rpc("create_scope_bound_proposal",{target_opportunity_id:opportunityId,target_intake_session_id:intake.id,input_payload:{currency:String(form.get("currency")||opportunity?.currency||"INR"),tax:String(form.get("tax")||"0"),valid_until:String(form.get("valid_until")||"")||undefined,commercial_notes:notes,source_proposal_id:String(form.get("source_proposal_id")||"")||undefined}});if(error)throw error;refresh("New immutable scope-bound proposal revision created from the current selections.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function proposalAction(p:CommercialProposal,action:string){if(action==="submit"){const {error}=await supabase.rpc("submit_proposal_for_review",{target_proposal_id:p.id});if(error){setMessage(error.message);return;}refresh(`Proposal v${p.version} submitted for independent review.`);return;}if(action==="send"){const note=window.prompt("Internal review note:")||"Commercial review completed";const {error}=await supabase.rpc("approve_and_send_proposal",{target_proposal_id:p.id,review_note:note});if(error){setMessage(error.message);return;}refresh(`Proposal v${p.version} approved and sent.`);return;}const evidence=window.prompt(`Evidence reference for client ${action}:`)||"";if(!evidence)return;let counter:number|null=null;if(action==="countered"){const raw=window.prompt("Client counter amount:",String(p.total))||"";if(!raw)return;counter=Number(raw);if(!Number.isFinite(counter)||counter<0){setMessage("Counter amount is invalid.");return;}}const {error}=await supabase.rpc("record_proposal_client_decision",{target_proposal_id:p.id,decision:action,evidence_reference:evidence,client_counter_offer:counter});if(error){setMessage(error.message);return;}refresh(`Client ${action} recorded against proposal v${p.version}.`);}
 const currency=opportunity?.currency||"INR";
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Commercial runtime:</b> {message}{busy?" Refreshing…":""}</div>}
  <section className="panel"><h3>Opportunity</h3>{state.opportunities.length?<div className="field"><label>Commercial opportunity</label><select value={opportunityId} onChange={e=>{setOpportunityId(e.target.value);setMessage("");}}>{state.opportunities.map(o=><option key={o.id} value={o.id}>{o.project_name} · {pretty(o.stage)} · {o.currency}</option>)}</select></div>:<div className="note">No opportunity exists. Create a qualified opportunity in CRM before commercial scope definition.</div>}{opportunity&&!intake&&<button className="btn" type="button" onClick={ensureSession}>Start Scope Definition</button>}</section>
  {opportunity&&intake&&<>
   <div className="kpis" style={{marginTop:16}}>{[["Included",String(Object.values(drafts).filter(d=>d.state==="included").length).padStart(2,"0")],["Optional",String(Object.values(drafts).filter(d=>d.state==="optional").length).padStart(2,"0")],["Excluded",String(Object.values(drafts).filter(d=>d.state==="excluded").length).padStart(2,"0")],["Controlled Fee Preview",money(previewTotal,currency)],["Proposal Revisions",String(currentProposals.length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value" style={{fontSize:String(v).length>12?18:30}}>{v}</div><div className="subtle">Live</div></div>)}</div>
   <section className="panel" style={{marginTop:16}}><h3>Modular Scope Configurator</h3><p className="subtle">Changing a state or fee updates the controlled preview immediately. Save commits the selection through dependency validation and audit.</p><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Module</th><th>State</th><th>Pricing</th><th>Quoted Fee</th><th>Dependencies</th><th>Notes / Action</th></tr></thead><tbody>{state.catalogue.map(c=>{const d=drafts[c.code]||initialDrafts[c.code];const selection=currentSelections.find(s=>s.module_code.toUpperCase()===c.code.toUpperCase());return <tr key={c.code}><td><b>{c.code} · {c.name}</b><div className="subtle">{c.category}<br/>{c.description}</div></td><td><select value={d?.state||c.default_state} onChange={e=>change(c.code,{state:e.target.value})}><option value="included">Included</option><option value="optional">Optional</option><option value="excluded">Excluded</option></select></td><td>{d?.state!=="excluded"?<select value={d?.pricing_model||"fixed"} onChange={e=>change(c.code,{pricing_model:e.target.value})}>{(c.pricing_models||[]).map(m=><option value={m} key={m}>{pretty(m)}</option>)}</select>:"—"}</td><td>{d?.state!=="excluded"?<input type="number" min="0" step="0.01" value={d?.quoted_amount||""} onChange={e=>change(c.code,{quoted_amount:e.target.value})} placeholder="Fee"/>:"—"}<div className="subtle">Saved: {selection?.quoted_amount==null?"—":money(selection.quoted_amount,selection.currency)}</div></td><td>{(c.dependencies||[]).length?c.dependencies.map(dep=><div key={dep} style={{marginBottom:5}}><span className="badge">{dep}</span>{!currentSelections.some(s=>s.module_code.toUpperCase()===dep.toUpperCase()&&s.state==="included")&&!currentOverrides.some(o=>o.module_code.toUpperCase()===c.code.toUpperCase()&&o.dependency_code.toUpperCase()===dep.toUpperCase()&&o.status==="approved")&&<button className="btn ghost" type="button" style={{marginLeft:5,padding:"4px 7px"}} onClick={()=>requestOverride(c,dep)}>Request Override</button>}</div>):"None"}</td><td><textarea rows={2} value={d?.notes||""} onChange={e=>change(c.code,{notes:e.target.value})}/><button className="btn ghost" type="button" onClick={()=>saveScope(c)}>Save {c.code}</button></td></tr>})}</tbody></table></div></section>
   <div className="panel-grid"><section className="panel"><h3>Dependency Overrides</h3>{currentOverrides.map(o=><div className="note" key={o.id} style={{marginBottom:7}}><b>{o.module_code} → {o.dependency_code}</b><div>{o.reason}</div><div className="subtle">{o.status} · evidence {o.evidence_refs?.length||0}</div>{o.status==="requested"&&<div style={{display:"flex",gap:5,marginTop:5}}><button className="btn ghost" type="button" onClick={()=>decideOverride(o,"approved")}>Approve</button><button className="btn ghost" type="button" onClick={()=>decideOverride(o,"rejected")}>Reject</button></div>}</div>)}{currentOverrides.length===0&&<p className="subtle">No dependency overrides requested.</p>}</section>
   <section className="panel"><h3>Create Proposal Revision</h3><form action={createProposal}><div className="field-grid"><div className="field"><label>Currency</label><input name="currency" defaultValue={currency}/></div><div className="field"><label>Tax estimate</label><input name="tax" type="number" min="0" step="0.01" defaultValue="0"/></div><div className="field"><label>Valid until</label><input name="valid_until" type="date"/></div><div className="field"><label>Source proposal</label><select name="source_proposal_id"><option value="">New commercial revision</option>{currentProposals.map(p=><option key={p.id} value={p.id}>v{p.version} · {p.status}</option>)}</select></div></div><div className="field"><label>Commercial notes JSON</label><textarea name="commercial_notes" rows={3} defaultValue="[]"/></div><div className="note"><b>Current included fee:</b> {money(previewTotal,currency)}. The proposal itself is generated from saved selections, not unsaved browser values.</div><button className="btn" style={{marginTop:10}}>Create Scope-Bound Proposal</button></form></section></div>
   <section className="panel"><h3>Proposal Version Ledger</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Version</th><th>Status</th><th>Commercials</th><th>Scope Hash</th><th>Validity / Counter</th><th>Actions</th></tr></thead><tbody>{currentProposals.map(p=><tr key={p.id}><td><b>v{p.version}</b><div className="subtle">{new Date(p.created_at).toLocaleString("en-IN")}</div></td><td><span className="badge">{pretty(p.status)}</span></td><td>{money(p.total,p.currency)}<div className="subtle">Subtotal {money(p.subtotal,p.currency)} · tax {money(p.tax,p.currency)}</div></td><td><code>{shortHash(p.scope_hash)}</code>{p.accepted_scope_hash&&<div className="subtle">Accepted {shortHash(p.accepted_scope_hash)}</div>}</td><td>{p.valid_until||"No expiry"}{p.client_counter_offer!=null&&<div className="subtle">Counter {money(p.client_counter_offer,p.currency)}</div>}</td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{p.status==="draft"&&<button className="btn ghost" type="button" onClick={()=>proposalAction(p,"submit")}>Internal Review</button>}{p.status==="internal_review"&&<button className="btn ghost" type="button" onClick={()=>proposalAction(p,"send")}>Approve & Send</button>}{["sent","countered"].includes(p.status)&&<><button className="btn ghost" type="button" onClick={()=>proposalAction(p,"accepted")}>Record Accept</button><button className="btn ghost" type="button" onClick={()=>proposalAction(p,"countered")}>Record Counter</button><button className="btn ghost" type="button" onClick={()=>proposalAction(p,"rejected")}>Record Reject</button></>}</div></td></tr>)}{currentProposals.length===0&&<tr><td colSpan={6} className="subtle">No proposal revisions yet.</td></tr>}</tbody></table></div></section>
   <section className="panel"><h3>Negotiation History</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Time</th><th>Proposal</th><th>Party</th><th>Event</th><th>Amount</th><th>Note</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString("en-IN")}</td><td>v{e.version}</td><td>{e.party}</td><td><span className="badge">{pretty(e.event_type)}</span></td><td>{e.amount==null?"—":money(e.amount,e.currency||currency)}</td><td>{e.note||"—"}</td></tr>)}{events.length===0&&<tr><td colSpan={6} className="subtle">Negotiation history begins with the first proposal revision.</td></tr>}</tbody></table></div></section>
  </>}
 </>;
}
