"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

type OfflinePackage={id:string;source_hash:string;downloaded_at:string;expires_at?:string|null;status:string};
type LocalChange={local_change_id:string;entity_type:string;client_created_at:string;payload:Record<string,unknown>;package_id:string;package_hash:string;local_status:"queued"|"conflict";conflict_reason?:string};
const short=(v:string)=>`${v.slice(0,12)}…`;
function parseObject(raw:string){if(!raw.trim())return {};const value=JSON.parse(raw);if(!value||Array.isArray(value)||typeof value!=="object")throw new Error("Additional payload must be a JSON object.");return value as Record<string,unknown>;}

export default function SiteOfflineQueueClient({projectId,packages}:{projectId:string;packages:OfflinePackage[]}){
 const supabase=createClient();const storageKey=`conceptspaces:site-offline:${projectId}`;const active=packages.filter(p=>p.status==="active");
 const [online,setOnline]=useState(true);const [queue,setQueue]=useState<LocalChange[]>([]);const [message,setMessage]=useState("");const [packageId,setPackageId]=useState(active[0]?.id||"");
 const selected=useMemo(()=>packages.find(p=>p.id===packageId),[packages,packageId]);
 useEffect(()=>{try{const raw=window.localStorage.getItem(storageKey);if(raw)setQueue(JSON.parse(raw) as LocalChange[]);}catch{}const update=()=>setOnline(navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[storageKey]);
 function persist(next:LocalChange[]){setQueue(next);window.localStorage.setItem(storageKey,JSON.stringify(next));}
 function remove(id:string){persist(queue.filter(q=>q.local_change_id!==id));}
 function clearSynced(){persist(queue.filter(q=>q.local_status==="conflict"));}
 function queueRecord(form:FormData){try{if(!selected)throw new Error("Create/select an active offline package while connected before going offline.");const entity=String(form.get("entity_type")||"observation");const title=String(form.get("title")||"").trim();const description=String(form.get("description")||"").trim();const criticality=String(form.get("criticality")||"C1");const date=String(form.get("diary_date")||"");const extras=parseObject(String(form.get("extra_payload")||"{}"));let payload:Record<string,unknown>={...extras};if(entity==="site_diary")payload={diary_date:date||new Date().toISOString().slice(0,10),weather:{},manpower:[],equipment:[],progress:[],photos:[],notes:description,...extras};else if(entity==="rfi")payload={title:title||"Offline RFI",description:description||"Captured offline",priority:"medium",criticality,...extras};else payload={observation_type:"progress",title:title||"Offline observation",description:description||"Captured offline",criticality,...extras};const item:LocalChange={local_change_id:crypto.randomUUID(),entity_type:entity,client_created_at:new Date().toISOString(),payload,package_id:selected.id,package_hash:selected.source_hash,local_status:"queued"};persist([...queue,item]);setMessage(`Queued locally ${online?"before sync":"while offline"}. No server call was required.`);}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function checkFreshness(){if(!selected)return;if(!online){setMessage(`Offline. Working set remains pinned to downloaded hash ${short(selected.source_hash)}; freshness will be checked before sync.`);return;}const {data,error}=await supabase.rpc("site_offline_package_status",{target_package_id:selected.id});if(error){setMessage(error.message);return;}const d=(data||{}) as Record<string,unknown>;setMessage(d.fresh?`Package is current. Downloaded/current hash ${short(String(d.current_hash||selected.source_hash))}.`:`STALE SITE PACKAGE: downloaded ${short(String(d.downloaded_hash||selected.source_hash))}, current ${short(String(d.current_hash||"unknown"))}. Refresh the working set before acting.`);}
 async function sync(){if(!online){setMessage("Device is offline. Changes remain safely queued locally.");return;}const pending=queue.filter(q=>q.package_id===packageId);if(!pending.length){setMessage("No local changes are queued for this package.");return;}const outbound=pending.map(({local_change_id,entity_type,client_created_at,payload})=>({local_change_id,entity_type,client_created_at,payload}));const {data,error}=await supabase.rpc("sync_site_offline_changes",{target_package_id:packageId,target_changes:outbound});if(error){setMessage(error.message);return;}const result=(data||{}) as {results?:Array<{local_change_id:string;status:string;error?:string}>;downloaded_hash?:string;current_hash?:string};const rows=result.results||[];const resultMap=new Map(rows.map(r=>[r.local_change_id,r]));const next=queue.flatMap(q=>{if(q.package_id!==packageId)return [q];const r=resultMap.get(q.local_change_id);if(!r)return [q];if(r.status==="synced")return [];return [{...q,local_status:"conflict" as const,conflict_reason:r.error||"SYNC_CONFLICT"}];});persist(next);const conflicts=rows.filter(r=>r.status!=="synced").length;const synced=rows.filter(r=>r.status==="synced").length;setMessage(conflicts?`${synced} synced; ${conflicts} blocked. STALE_SITE_PACKAGE/conflict items remain on this device for explicit resolution.`:`${synced} offline change(s) synced. Server revalidated the downloaded control hash before applying each action.`);}
 return <section className="panel" style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h3>Device Offline Queue</h3><div className="subtle">Actual browser-local capture. The queue works without network and is server-revalidated against the frozen IFC/document package before sync.</div></div><span className="badge">{online?"Online":"Offline"}</span></div>{message&&<div className="note" style={{marginTop:12}}>{message}</div>}
 <div className="panel-grid" style={{marginTop:12}}><form action={queueRecord}><div className="field"><label>Downloaded control package</label><select value={packageId} onChange={e=>setPackageId(e.target.value)} required><option value="">Select package</option>{active.map(p=><option key={p.id} value={p.id}>{p.id.slice(0,8)} · {short(p.source_hash)}</option>)}</select></div><div className="field-grid"><div className="field"><label>Offline record type</label><select name="entity_type"><option value="observation">Observation</option><option value="site_diary">Site diary</option><option value="rfi">RFI</option></select></div><div className="field"><label>Criticality</label><select name="criticality"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option></select></div><div className="field"><label>Diary date</label><input name="diary_date" type="date"/></div></div><div className="field"><label>Title / subject</label><input name="title"/></div><div className="field"><label>Description / notes / question</label><textarea name="description" rows={3}/></div><div className="field"><label>Additional controlled payload JSON</label><textarea name="extra_payload" rows={4} defaultValue="{}"/></div><button className="btn" disabled={!selected}>Queue On Device</button></form>
 <div><h3>Working-set controls</h3>{selected?<div className="note"><b>Package {selected.id.slice(0,8)}</b><div className="subtle">Downloaded {new Date(selected.downloaded_at).toLocaleString("en-IN")} · hash <code>{short(selected.source_hash)}</code>{selected.expires_at?` · expires ${new Date(selected.expires_at).toLocaleString("en-IN")}`:""}</div></div>:<div className="note">Create an offline package while connected before field capture.</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><button className="btn ghost" type="button" onClick={checkFreshness} disabled={!selected}>Check Freshness</button><button className="btn" type="button" onClick={sync} disabled={!selected||!queue.some(q=>q.package_id===packageId)}>Sync Queued Changes</button><button className="btn ghost" type="button" onClick={clearSynced} disabled={!queue.length}>Keep Conflicts Only</button></div></div></div>
 <div style={{overflowX:"auto",marginTop:14}}><table className="table"><thead><tr><th>Local record</th><th>Type</th><th>Package hash</th><th>Captured</th><th>Status</th><th></th></tr></thead><tbody>{queue.map(q=><tr key={q.local_change_id}><td><code>{q.local_change_id.slice(0,8)}</code></td><td>{q.entity_type}</td><td><code>{short(q.package_hash)}</code></td><td>{new Date(q.client_created_at).toLocaleString("en-IN")}</td><td><span className="badge">{q.local_status}</span>{q.conflict_reason&&<div className="subtle">{q.conflict_reason}</div>}</td><td><button className="btn ghost" type="button" onClick={()=>remove(q.local_change_id)}>Discard Local</button></td></tr>)}{!queue.length&&<tr><td colSpan={6} className="subtle">No device-local changes queued.</td></tr>}</tbody></table></div>
 </section>;
}
