"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

export type GeometryRow={id:string;source_type:string;source_reference?:string|null;verification:string;engine_valid:boolean;content_hash:string;area:number;coordinate_system?:string|null;geometry:{result?:{perimeter?:number;centroid?:{x:number;y:number};orientation?:string;edges?:Array<{index:number;length:number;bearing:number}>}};validation_messages:string[];verified_by?:string|null;verified_at?:string|null;created_at:string};
const sample=JSON.stringify([{x:0,y:0},{x:40,y:0},{x:40,y:30},{x:0,y:30}],null,2);
export default function SiteGeometryClient({projectId,rows}:{projectId:string;rows:GeometryRow[]}){
 const router=useRouter();const supabase=createClient();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 async function evaluate(form:FormData){setMessage("Running deterministic geometry kernel…");let vertices:unknown;try{vertices=JSON.parse(String(form.get("vertices")||"[]"));}catch{setMessage("Vertices must be valid JSON.");return;}if(!Array.isArray(vertices)){setMessage("Vertices must be a JSON array.");return;}const parcel={vertices,unit:String(form.get("unit")||"m"),coordinate_system:String(form.get("coordinate_system")||"")||undefined,source_type:String(form.get("source_type")||"manual"),source_reference:String(form.get("source_reference")||"")||undefined};const {data,error}=await supabase.functions.invoke("geometry-evaluate",{body:{project_id:projectId,parcel}});if(error){setMessage(error.message);return;}const result=data as {error?:string;geometry_id?:string;result?:{valid:boolean;area:number;validation_messages:string[]}};if(result.error){setMessage(result.error);return;}setMessage(result.result?.valid?`Geometry evaluated. Area ${result.result.area.toLocaleString("en-IN")} m². Evidence ${result.geometry_id?.slice(0,8)}.`:`Geometry recorded as invalid: ${(result.result?.validation_messages||[]).join(", ")}`);startTransition(()=>router.refresh());}
 async function verify(row:GeometryRow){setMessage("Binding professional verification to exact geometry hash…");const {error}=await supabase.rpc("verify_site_geometry",{target_geometry_id:row.id,target_content_hash:row.content_hash});if(error){setMessage(error.message);return;}setMessage("Professionally verified against the immutable content hash.");startTransition(()=>router.refresh());}
 const latest=rows[0];return <>
 {message&&<div className="note" style={{marginBottom:16}}><b>Geometry:</b> {message}{busy?" Refreshing…":""}</div>}
 <div className="panel-grid"><section className="panel"><h3>Precision Geometry Kernel</h3><form action={evaluate}><div className="field-grid"><div className="field"><label>Coordinate vertices</label><textarea name="vertices" rows={10} defaultValue={sample}/></div><div><div className="field"><label>Unit</label><select name="unit"><option value="m">metres</option><option value="ft">feet</option></select></div><div className="field"><label>Source</label><select name="source_type"><option value="manual">Manual / preliminary</option><option value="survey">Survey</option><option value="cadastral">Cadastral</option><option value="dwg">DWG</option><option value="dxf">DXF</option><option value="point_cloud">Point cloud</option><option value="lidar">LiDAR</option></select></div><div className="field"><label>Coordinate system</label><input name="coordinate_system" placeholder="e.g. EPSG / local survey grid"/></div><div className="field"><label>Source reference</label><input name="source_reference" placeholder="Survey / CDE document reference"/></div></div></div><button className="btn" style={{marginTop:14}}>Evaluate & Record</button></form></section>
 <section className="panel"><h3>No-Hallucination Geometry Rule</h3><p className="subtle">The kernel accepts ordered corner coordinates. It computes area, perimeter, centroid, orientation, edge lengths and bearings and rejects self-intersecting, degenerate or zero-edge polygons.</p><div className="note"><b>Four side lengths are never treated as a unique parcel.</b> A release-capable geometry still requires verified coordinates, bearings/angles/diagonal evidence or a survey/CAD/cadastral source.</div>{latest&&<div style={{marginTop:16}}><div className="eyebrow">Latest evidence</div><div className="metric-grid"><div><b>{latest.engine_valid?"Valid":"Invalid"}</b><span>Kernel state</span></div><div><b>{Number(latest.area||0).toLocaleString("en-IN")}</b><span>Area m²</span></div><div><b>{latest.verification.replaceAll("_"," ")}</b><span>Verification</span></div></div></div>}</section></div>
 <section className="panel" style={{marginTop:18}}><h3>Immutable Geometry Evidence</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Created</th><th>Source</th><th>Area</th><th>Kernel</th><th>Verification</th><th>Hash</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString("en-IN")}</td><td>{r.source_type}<br/><span className="subtle">{r.source_reference||"No external reference"}</span></td><td>{Number(r.area||0).toLocaleString("en-IN")} m²</td><td><span className="badge">{r.engine_valid?"Valid":"Invalid"}</span>{r.validation_messages?.length>0&&<div className="subtle">{r.validation_messages.join(", ")}</div>}</td><td>{r.verification.replaceAll("_"," ")}</td><td><code>{r.content_hash?.slice(0,12)}…</code></td><td>{r.engine_valid&&r.verification==="unverified"&&<button className="btn ghost" type="button" onClick={()=>verify(r)}>Professional Verify</button>}</td></tr>)}{rows.length===0&&<tr><td colSpan={7} className="subtle">No deterministic parcel evidence has been recorded yet.</td></tr>}</tbody></table></div></section>
 </>;
}
