"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {Vendor} from "@/components/lifecycle-runtime-types";

export type ProgrammeActivity={id:string;project_id:string;wbs_code:string;title:string;state:string;planned_start?:string|null;planned_finish?:string|null;actual_start?:string|null;actual_finish?:string|null;forecast_finish?:string|null;progress_percent:number;contractor_vendor_id?:string|null;evidence_refs:unknown[];delay_reason?:string|null;recovery_plan?:string|null;lookahead_bucket?:string|null;updated_at:string};
export type ActivityDependency={id:string;project_id:string;predecessor_activity_id:string;successor_activity_id:string;relationship:string;lag_days:number;created_at:string};
export type ProgrammeBaseline={id:string;project_id:string;version:number;title:string;status:string;baseline_hash:string;baselined_at:string};
export type SiteProgrammeState={programmes:ProgrammeBaseline[];activities:ProgrammeActivity[];dependencies:ActivityDependency[]};
export const emptySiteProgrammeState:SiteProgrammeState={programmes:[],activities:[],dependencies:[]};
const pretty=(v:string)=>v.replaceAll("_"," ");const shortHash=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
function parseArray(raw:string,label:string){try{const value=JSON.parse(raw||"[]");if(!Array.isArray(value))throw new Error();return value;}catch{throw new Error(`${label} must be a JSON array.`);}}

export default function SiteProgrammeClient({projectId,state,vendors}:{projectId:string;state:SiteProgrammeState;vendors:Vendor[]}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();const activities=state.activities||[];const dependencies=state.dependencies||[];const programmes=state.programmes||[];
 const vendorName=(id?:string|null)=>id?vendors.find(v=>v.id===id)?.legal_name||id.slice(0,8):"Unassigned";const activityName=(id:string)=>activities.find(a=>a.id===id)?.wbs_code||id.slice(0,8);function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 async function createActivity(form:FormData){const {error}=await supabase.rpc("create_site_activity",{target_project_id:projectId,input_payload:{wbs_code:String(form.get("wbs_code")||""),title:String(form.get("title")||""),planned_start:String(form.get("planned_start")||"")||undefined,planned_finish:String(form.get("planned_finish")||"")||undefined,contractor_vendor_id:String(form.get("contractor_vendor_id")||"")||undefined,lookahead_bucket:String(form.get("lookahead_bucket")||"")||undefined}});if(error){setMessage(error.message);return;}refresh("Activity added to the current programme graph.");}
 async function setDependency(form:FormData){const {error}=await supabase.rpc("set_site_activity_dependency",{target_project_id:projectId,target_predecessor_id:String(form.get("predecessor")||""),target_successor_id:String(form.get("successor")||""),target_relationship:String(form.get("relationship")||"FS"),target_lag_days:Number(form.get("lag_days")||0)});if(error){setMessage(error.message);return;}refresh("Dependency recorded; cyclic programme paths are rejected server-side.");}
 async function baseline(form:FormData){const {error}=await supabase.rpc("baseline_site_programme",{target_project_id:projectId,target_title:String(form.get("title")||"")});if(error){setMessage(error.message);return;}refresh("New immutable programme baseline created; prior baseline preserved as superseded history.");}
 async function updateActivity(form:FormData){try{const evidence=parseArray(String(form.get("evidence_refs")||"[]"),"Evidence refs");const {error}=await supabase.rpc("update_site_activity",{target_activity_id:String(form.get("activity_id")||""),input_payload:{state:String(form.get("state")||""),progress_percent:String(form.get("progress_percent")||""),actual_start:String(form.get("actual_start")||"")||undefined,actual_finish:String(form.get("actual_finish")||"")||undefined,forecast_finish:String(form.get("forecast_finish")||"")||undefined,delay_reason:String(form.get("delay_reason")||"")||undefined,recovery_plan:String(form.get("recovery_plan")||"")||undefined,lookahead_bucket:String(form.get("lookahead_bucket")||"")||undefined,evidence_refs:evidence,reason:String(form.get("reason")||"")||undefined}});if(error)throw error;refresh("Activity actuals, forecast and evidence updated without rewriting the baseline snapshot.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 const weighted=activities.length?activities.reduce((s,a)=>s+Number(a.progress_percent||0),0)/activities.length:0;const baselineRow=programmes.find(p=>p.status==="baselined");
 return <section className="panel" style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="eyebrow">Programme Control</div><h3>WBS, dependencies, baseline & actuals</h3></div><div className="badge">Overall {weighted.toFixed(1)}%</div></div>{message&&<div className="note" style={{margin:"10px 0"}}>{message}{busy?" Refreshing…":""}</div>}
  <div className="panel-grid"><form action={createActivity}><h3>Create Activity</h3><div className="field-grid"><div className="field"><label>WBS code</label><input name="wbs_code" required/></div><div className="field"><label>Activity</label><input name="title" required/></div><div className="field"><label>Planned start</label><input name="planned_start" type="date"/></div><div className="field"><label>Planned finish</label><input name="planned_finish" type="date"/></div><div className="field"><label>Contractor</label><select name="contractor_vendor_id"><option value="">Unassigned</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.legal_name}</option>)}</select></div><div className="field"><label>Look-ahead bucket</label><input name="lookahead_bucket" placeholder="2-week / 4-week / recovery"/></div></div><button className="btn">Add Activity</button></form>
  <form action={setDependency}><h3>Set Dependency</h3><div className="field"><label>Predecessor</label><select name="predecessor" required>{activities.map(a=><option key={a.id} value={a.id}>{a.wbs_code} · {a.title}</option>)}</select></div><div className="field"><label>Successor</label><select name="successor" required>{activities.map(a=><option key={a.id} value={a.id}>{a.wbs_code} · {a.title}</option>)}</select></div><div className="field-grid"><div className="field"><label>Relationship</label><select name="relationship"><option>FS</option><option>SS</option><option>FF</option><option>SF</option></select></div><div className="field"><label>Lag days</label><input name="lag_days" type="number" defaultValue="0"/></div></div><button className="btn ghost">Set Dependency</button></form></div>
  <div className="panel-grid"><form action={baseline}><h3>Baseline Programme</h3><div className="field"><label>Baseline title</label><input name="title" required defaultValue={`Construction Baseline ${programmes.length+1}`}/></div><button className="btn">Freeze New Baseline</button><div className="subtle" style={{marginTop:7}}>Current: {baselineRow?`v${baselineRow.version} · ${shortHash(baselineRow.baseline_hash)}`:"No baseline yet"}</div></form>
  <form action={updateActivity}><h3>Update Actual / Forecast</h3><div className="field"><label>Activity</label><select name="activity_id" required>{activities.map(a=><option key={a.id} value={a.id}>{a.wbs_code} · {a.title}</option>)}</select></div><div className="field-grid"><div className="field"><label>State</label><select name="state"><option>not_started</option><option>in_progress</option><option>blocked</option><option>complete</option></select></div><div className="field"><label>Progress %</label><input name="progress_percent" type="number" min="0" max="100" step="0.1"/></div><div className="field"><label>Actual start</label><input name="actual_start" type="date"/></div><div className="field"><label>Actual finish</label><input name="actual_finish" type="date"/></div><div className="field"><label>Forecast finish</label><input name="forecast_finish" type="date"/></div><div className="field"><label>Look-ahead</label><input name="lookahead_bucket"/></div></div><div className="field"><label>Delay reason</label><input name="delay_reason"/></div><div className="field"><label>Recovery plan</label><textarea name="recovery_plan" rows={2}/></div><div className="field"><label>Evidence refs JSON</label><textarea name="evidence_refs" rows={2} defaultValue="[]"/></div><div className="field"><label>Update reason</label><input name="reason"/></div><button className="btn ghost">Post Update</button></form></div>
  <div style={{overflowX:"auto",marginTop:14}}><table className="table"><thead><tr><th>WBS</th><th>Activity</th><th>State</th><th>Progress</th><th>Planned</th><th>Forecast</th><th>Contractor</th><th>Evidence</th></tr></thead><tbody>{activities.map(a=><tr key={a.id}><td>{a.wbs_code}</td><td><b>{a.title}</b>{a.delay_reason&&<div className="subtle">Delay: {a.delay_reason}</div>}{a.recovery_plan&&<div className="subtle">Recovery: {a.recovery_plan}</div>}</td><td><span className="badge">{pretty(a.state)}</span></td><td>{Number(a.progress_percent).toFixed(1)}%</td><td>{a.planned_start||"—"} → {a.planned_finish||"—"}</td><td>{a.forecast_finish||"—"}</td><td>{vendorName(a.contractor_vendor_id)}</td><td>{Array.isArray(a.evidence_refs)?a.evidence_refs.length:0}</td></tr>)}{activities.length===0&&<tr><td colSpan={8} className="subtle">No WBS activities yet.</td></tr>}</tbody></table></div>
  {dependencies.length>0&&<div className="note" style={{marginTop:10}}><b>Dependency graph:</b> {dependencies.map(d=>`${activityName(d.predecessor_activity_id)} ${d.relationship}${d.lag_days?`+${d.lag_days}d`:""} → ${activityName(d.successor_activity_id)}`).join(" · ")}</div>}
 </section>;
}
