"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";

type TaxWorkspace={rules:any[];determinations:any[]};
const pretty=(v?:string|null)=>v?v.replaceAll("_"," "):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…`:"—";
const parseObject=(v:FormDataEntryValue|null)=>{const s=String(v||"").trim();if(!s)return {};const x=JSON.parse(s);if(!x||Array.isArray(x)||typeof x!=="object")throw new Error("Expected a JSON object");return x;};

export default function TaxRuleGovernanceClient({workspace}:{workspace:TaxWorkspace}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const rules=workspace.rules||[];const determinations=workspace.determinations||[];
 function refresh(t:string){setMessage(t);startTransition(()=>router.refresh());}
 function fail(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function createRule(form:FormData){try{const {error}=await supabase.rpc("create_tax_rule",{input_payload:{rule_set:String(form.get("rule_set")||""),code:String(form.get("code")||""),jurisdiction:String(form.get("jurisdiction")||"IN"),effective_from:String(form.get("effective_from")||""),effective_until:String(form.get("effective_until")||""),priority:String(form.get("priority")||"100"),source_reference:String(form.get("source_reference")||""),conditions:parseObject(form.get("conditions")),outcome:parseObject(form.get("outcome"))}});if(error)return setMessage(error.message);refresh("Tax rule drafted with an immutable rule hash. Independent publication is required.");}catch(e){fail(e);}}
 async function transition(id:string,status:string){const reason=window.prompt(`${status} reason`);if(!reason?.trim())return;const {error}=await supabase.rpc("transition_tax_rule",{target_rule_id:id,target_status:status,target_reason:reason.trim()});if(error)return setMessage(error.message);refresh(`Tax rule moved to ${pretty(status)}.`);}
 const published=rules.filter(r=>r.publication_status==="published").length;const review=rules.filter(r=>r.publication_status==="review").length;const draft=rules.filter(r=>r.publication_status==="draft").length;const sets=new Set(rules.map(r=>r.rule_set)).size;
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Tax governance:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Published",String(published)],["In Review",String(review)],["Draft",String(draft)],["Rule Sets",String(sets)],["Determinations",String(determinations.length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live governed state</div></div>)}</div>
  <div className="panel-grid" style={{marginTop:16}}>
   <section className="panel"><h3>Draft Effective-Dated Rule</h3><form action={createRule}><div className="field-grid"><div className="field"><label>Rule set</label><input name="rule_set" required/></div><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Jurisdiction</label><input name="jurisdiction" defaultValue="IN" required/></div><div className="field"><label>Priority</label><input name="priority" type="number" defaultValue="100"/></div><div className="field"><label>Effective from</label><input name="effective_from" type="date" required/></div><div className="field"><label>Effective until</label><input name="effective_until" type="date"/></div></div><div className="field"><label>Official source reference</label><input name="source_reference" required placeholder="Gazette / circular / statutory source reference"/></div><div className="field-grid"><div className="field"><label>Conditions JSON</label><textarea name="conditions" rows={6} defaultValue="{}"/></div><div className="field"><label>Outcome JSON</label><textarea name="outcome" rows={6} required defaultValue="{}"/></div></div><button className="btn">Create Draft Rule</button></form></section>
   <section className="panel"><h3>Governance Rules</h3><div className="note"><b>No hard-coded law.</b> Tax logic becomes usable only through effective-dated rule versions with source evidence. The maker cannot publish their own draft, and published content is immutable.</div><p className="subtle" style={{marginTop:12}}>When the platform cannot establish applicability from published evidence, downstream tax determination remains Needs Review / Not Verified rather than inferring law.</p></section>
  </div>
  <section className="panel"><h3>Tax Rule Register</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Rule</th><th>Jurisdiction</th><th>Effective</th><th>Status</th><th>Source</th><th>Hash</th><th>Action</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><b>{r.code}</b><div className="subtle">{r.rule_set}</div></td><td>{r.jurisdiction}</td><td>{r.effective_from}{r.effective_until?` → ${r.effective_until}`:" → open"}</td><td><span className="badge">{pretty(r.publication_status)}</span></td><td>{r.source_reference}</td><td><code>{short(r.rule_hash)}</code></td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{r.publication_status==="draft"&&<button className="btn ghost" style={{padding:6}} onClick={()=>transition(r.id,"review")}>Send to Review</button>}{r.publication_status==="review"&&<><button className="btn ghost" style={{padding:6}} onClick={()=>transition(r.id,"draft")}>Return Draft</button><button className="btn" style={{padding:6}} onClick={()=>transition(r.id,"published")}>Publish</button></>}{r.publication_status==="published"&&<button className="btn ghost" style={{padding:6}} onClick={()=>transition(r.id,"retired")}>Retire</button>}</div></td></tr>)}{rules.length===0&&<tr><td colSpan={7} className="subtle">No tax rules exist. No statutory logic will be fabricated.</td></tr>}</tbody></table></div></section>
  <section className="panel"><h3>Recent Tax Determinations</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Date</th><th>Source</th><th>Status</th><th>Rules</th><th>Explanation</th></tr></thead><tbody>{determinations.slice(0,50).map(d=><tr key={d.id}><td>{d.transaction_date}</td><td>{d.source_type}</td><td><span className="badge">{pretty(d.status)}</span></td><td><code>{JSON.stringify(d.rule_ids||[])}</code></td><td><span className="subtle">{JSON.stringify(d.explanation||[])}</span></td></tr>)}{determinations.length===0&&<tr><td colSpan={5} className="subtle">No tax determinations have been recorded.</td></tr>}</tbody></table></div></section>
 </>;
}
