"use client";

import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";

export type MessageRow={id:string;project_id?:string|null;channel:string;provider_key:string;environment:string;recipient:string;purpose:string;template_key?:string|null;subject?:string|null;status:string;attempt_count:number;provider_message_id?:string|null;last_error?:Record<string,unknown>|null;created_at:string;sent_at?:string|null;delivered_at?:string|null};
export type ProjectChoice={id:string;code:string;name:string};

function mask(value:string){if(value.includes("@")){const [a,b]=value.split("@");return `${a.slice(0,2)}***@${b}`;}const digits=value.replace(/\D/g,"");return digits.length>5?`${digits.slice(0,2)}******${digits.slice(-3)}`:value;}

export default function TransactionalMessagingClient({organisationId,projects,messages}:{organisationId:string;projects:ProjectChoice[];messages:MessageRow[]}){
  const router=useRouter();const [channel,setChannel]=useState("email");const [status,setStatus]=useState("");const [busy,startTransition]=useTransition();
  async function send(form:FormData){setStatus("Queueing governed message…");const project=String(form.get("project_id")||"");const body=String(form.get("body")||"");const params=String(form.get("params")||"");const userName=String(form.get("user_name")||"");const payload=channel==="email"?{text:body}:channel==="whatsapp"?{user_name:userName||"Concept Spaces Client",template_params:params?params.split("|").map(v=>v.trim()):[]}: {body,variables_values:params};
    const response=await fetch("/api/providers/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organisation_id:organisationId,project_id:project||null,channel,recipient:String(form.get("recipient")||""),purpose:String(form.get("purpose")||"project_notification"),template_key:String(form.get("template_key")||""),subject:String(form.get("subject")||""),payload,consent_basis:"transactional_contractual"})});const result=await response.json() as {error?:string;message_id?:string;dispatch_error?:string};if(!response.ok&&response.status!==202){setStatus(result.error||"Message failed.");return;}setStatus(result.dispatch_error?`Queued ${result.message_id?.slice(0,8)}. Dispatch worker response: ${result.dispatch_error}`:`Queued and dispatched ${result.message_id?.slice(0,8)}.`);startTransition(()=>router.refresh());}
  return <>
    {status&&<div className="note" style={{marginBottom:16}}><b>Messaging:</b> {status}{busy?" Refreshing…":""}</div>}
    <div className="panel-grid"><section className="panel"><h3>New Transactional Message</h3><form action={send}><div className="field-grid"><div className="field"><label>Channel</label><select value={channel} onChange={e=>setChannel(e.target.value)}><option value="email">Email · Resend</option><option value="whatsapp">WhatsApp · AiSensy</option><option value="sms">SMS · Fast2SMS</option></select></div><div className="field"><label>Project</label><select name="project_id"><option value="">Organisation-level</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></div><div className="field"><label>Purpose</label><select name="purpose"><option value="project_notification">Project notification</option><option value="approval_request">Approval request</option><option value="invoice_notice">Invoice notice</option><option value="contract_notice">Contract notice</option><option value="security_notice">Security notice</option><option value="otp">OTP</option><option value="system_notice">System notice</option></select></div><div className="field"><label>Recipient</label><input name="recipient" required placeholder={channel==="email"?"client@example.com":"+919999999999"}/></div>{channel==="email"&&<div className="field"><label>Subject</label><input name="subject" required placeholder="Project update"/></div>}{channel!=="email"&&<div className="field"><label>{channel==="whatsapp"?"AiSensy Campaign":"DLT Message / Template ID"}</label><input name="template_key" required/></div>}{channel==="whatsapp"&&<div className="field"><label>User Name</label><input name="user_name" placeholder="Client name"/></div>}<div className="field"><label>{channel==="email"?"Message":"Template parameters"}</label>{channel==="email"?<textarea name="body" required rows={5}/>:<input name="params" placeholder="value1|value2|value3"/>}</div>{channel==="sms"&&<div className="field"><label>Manual-route body, if applicable</label><textarea name="body" rows={3}/></div>}</div><button className="btn" style={{marginTop:14}}>Queue & Dispatch</button></form></section><section className="panel"><h3>Runtime Rules</h3><p className="subtle">Only transactional purposes are permitted here. Marketing journeys remain a separate consent-governed workflow.</p><div className="note"><b>Idempotent delivery.</b> Each dispatch receives a unique idempotency key. Provider retries cannot silently create duplicate commercial communications.</div><p className="subtle" style={{marginTop:14}}>WhatsApp uses live approved AiSensy API campaigns. Fast2SMS uses DLT configuration. Email sends carry Resend idempotency keys.</p></section></div>
    <section className="panel" style={{marginTop:18}}><h3>Live Delivery Queue</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Created</th><th>Channel</th><th>Recipient</th><th>Purpose</th><th>Provider</th><th>Status</th><th>Attempts</th></tr></thead><tbody>{messages.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString("en-IN")}</td><td>{m.channel.toUpperCase()}</td><td>{mask(m.recipient)}</td><td>{m.purpose.replaceAll("_"," ")}</td><td>{m.provider_key}</td><td><span className="badge">{m.status}</span></td><td>{m.attempt_count}</td></tr>)}{messages.length===0&&<tr><td colSpan={7} className="subtle">No transactional messages have been queued yet.</td></tr>}</tbody></table></div></section>
  </>;
}
