"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase";
import type {Bid,BOQLine,TenderPackage,Vendor} from "@/components/lifecycle-runtime-types";

type Invite={id:string;tender_package_id:string;vendor_id:string;invited_at:string;viewed_at?:string|null;declined_at?:string|null};
type InviteView={invite:Invite;package:TenderPackage;vendor_id:string};
type ScopeLine={tender_package_id:string;line:BOQLine};
type BidLine={id:string;bid_id:string;boq_line_id:string;quantity:number;rate:number;total:number;exclusions:unknown[]};
type Clarification={id:string;tender_package_id:string;vendor_id:string;question:string;response?:string|null;status:string;due_at?:string|null;created_at:string;answered_at?:string|null};
export type VendorProcurementState={vendor_accounts:Vendor[];invites:InviteView[];boq_lines:ScopeLine[];own_bids:Bid[];own_bid_lines:BidLine[];clarifications:Clarification[]};
export const emptyVendorProcurementState:VendorProcurementState={vendor_accounts:[],invites:[],boq_lines:[],own_bids:[],own_bid_lines:[],clarifications:[]};
const money=(n:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n||0));
const pretty=(v:string)=>v.replaceAll("_"," ");
function parseArray(raw:FormDataEntryValue|null,label:string){try{const value=JSON.parse(String(raw||"[]"));if(!Array.isArray(value))throw new Error();return value;}catch{throw new Error(`${label} must be a JSON array.`);}}

export default function VendorProcurementClient({state}:{state:VendorProcurementState}){
 const supabase=createClient();const router=useRouter();const [message,setMessage]=useState("");const [busy,startTransition]=useTransition();
 const accounts=state.vendor_accounts||[];const invites=state.invites||[];const scopes=state.boq_lines||[];const bids=state.own_bids||[];const clarifications=state.clarifications||[];
 const vendorName=(id:string)=>accounts.find(v=>v.id===id)?.legal_name||id.slice(0,8);
 const ownBid=(packageId:string,vendorId:string)=>bids.find(b=>b.tender_package_id===packageId&&b.vendor_id===vendorId&&b.status!=="withdrawn");
 function refresh(text:string){setMessage(text);startTransition(()=>router.refresh());}
 async function respond(invite:Invite,response:string){const {error}=await supabase.rpc("respond_tender_invite",{target_invite_id:invite.id,target_response:response});if(error){setMessage(error.message);return;}refresh(response==="acknowledge"?"Invitation acknowledged.":"Invitation declined.");}
 async function clarify(form:FormData){const {error}=await supabase.rpc("raise_tender_clarification",{target_package_id:String(form.get("package_id")||""),target_vendor_id:String(form.get("vendor_id")||""),target_question:String(form.get("question")||"")});if(error){setMessage(error.message);return;}refresh("Clarification submitted to the procurement team.");}
 async function submitBid(form:FormData){try{const packageId=String(form.get("package_id")||"");const vendorId=String(form.get("vendor_id")||"");const packageScope=scopes.filter(s=>s.tender_package_id===packageId);if(packageScope.length===0)throw new Error("No tender BOQ scope is available for this invitation.");const lines=packageScope.map(({line})=>{const rateRaw=String(form.get(`rate_${line.id}`)||"");if(rateRaw==="")throw new Error(`Enter a rate for ${line.code}.`);const qtyRaw=String(form.get(`qty_${line.id}`)||line.quantity);return {boq_line_id:line.id,quantity:Number(qtyRaw),rate:Number(rateRaw),exclusions:[]};});const technical=parseArray(form.get("technical_deviations"),"Technical deviations");const commercial=parseArray(form.get("commercial_deviations"),"Commercial deviations");const {error}=await supabase.rpc("submit_sealed_bid",{target_package_id:packageId,input_payload:{vendor_id:vendorId,currency:String(form.get("currency")||"INR"),lines,technical_deviations:technical,commercial_deviations:commercial}});if(error)throw error;refresh("Sealed bid submitted. Only your own submission remains visible in this portal.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 return <>
  {message&&<div className="note" style={{marginBottom:16}}><b>Vendor procurement:</b> {message}{busy?" Refreshing…":""}</div>}
  <div className="kpis">{[["Vendor Accounts",String(accounts.length).padStart(2,"0")],["Invitations",String(invites.length).padStart(2,"0")],["Active RFQs",String(invites.filter(i=>i.package.status==="rfq"&&!i.invite.declined_at).length).padStart(2,"0")],["Own Bids",String(bids.length).padStart(2,"0")],["Open Clarifications",String(clarifications.filter(c=>c.status==="open").length).padStart(2,"0")]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Vendor-scoped</div></div>)}</div>
  <div className="note" style={{marginTop:16}}><b>Confidentiality boundary.</b> This workspace returns only vendor identities mapped to your authenticated account, invitations issued to those vendors, the corresponding tender BOQ scope, your own bids and your own clarification threads. Competitor bids, vendor identities and evaluation data are not part of this response model.</div>
  {accounts.length===0&&<section className="panel" style={{marginTop:16}}><h3>Access pending</h3><p className="subtle">Your account is authenticated but is not mapped to an active procurement vendor. Ask the procurement team to map your user account to the approved vendor record.</p></section>}
  {invites.map(view=>{const p=view.package;const invite=view.invite;const scope=scopes.filter(s=>s.tender_package_id===p.id);const bid=ownBid(p.id,view.vendor_id);const closed=invite.declined_at||p.status!=="rfq"||(p.bid_due_at&&new Date(p.bid_due_at).getTime()<Date.now());return <section className="panel" style={{marginTop:16}} key={invite.id}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="eyebrow">{vendorName(view.vendor_id)}</div><h3>{p.package_code} · {p.title}</h3><div className="subtle">Bid due {p.bid_due_at?new Date(p.bid_due_at).toLocaleString("en-IN"):"—"} · controlled opening {p.opening_at?new Date(p.opening_at).toLocaleString("en-IN"):"—"}</div></div><div><span className="badge">{invite.declined_at?"declined":invite.viewed_at?"acknowledged":"new invitation"}</span></div></div>
   <div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:10}}>{!invite.viewed_at&&!invite.declined_at&&<button className="btn ghost" type="button" onClick={()=>respond(invite,"acknowledge")}>Acknowledge RFQ</button>}{!invite.declined_at&&!bid&&<button className="btn ghost" type="button" onClick={()=>respond(invite,"decline")}>Decline</button>}</div>
   <div style={{overflowX:"auto",marginTop:14}}><table className="table"><thead><tr><th>BOQ</th><th>Description</th><th>Quantity</th><th>Unit</th><th>Specification</th></tr></thead><tbody>{scope.map(({line})=><tr key={line.id}><td>{line.code}</td><td>{line.description}</td><td>{line.quantity}</td><td>{line.unit}</td><td>{line.rate_source?`Tender basis / ${line.revision}`:line.revision}</td></tr>)}{scope.length===0&&<tr><td colSpan={5} className="subtle">No readable BOQ scope.</td></tr>}</tbody></table></div>
   {!closed&&!bid&&scope.length>0&&<div className="panel-grid" style={{marginTop:14}}><div><h3>Sealed Commercial Submission</h3><form action={submitBid}><input type="hidden" name="package_id" value={p.id}/><input type="hidden" name="vendor_id" value={view.vendor_id}/><div className="field"><label>Currency</label><input name="currency" defaultValue="INR"/></div>{scope.map(({line})=><div className="field-grid" key={line.id}><div className="field"><label>{line.code} quantity</label><input name={`qty_${line.id}`} type="number" step="0.0001" defaultValue={line.quantity}/></div><div className="field"><label>{line.code} unit rate</label><input name={`rate_${line.id}`} type="number" min="0" step="0.01" required/></div></div>)}<div className="field"><label>Technical deviations JSON</label><textarea name="technical_deviations" rows={3} defaultValue="[]"/></div><div className="field"><label>Commercial deviations JSON</label><textarea name="commercial_deviations" rows={3} defaultValue="[]"/></div><button className="btn">Submit Sealed Bid</button></form></div><div><h3>Clarification</h3><form action={clarify}><input type="hidden" name="package_id" value={p.id}/><input type="hidden" name="vendor_id" value={view.vendor_id}/><div className="field"><label>Question</label><textarea name="question" rows={5} required/></div><button className="btn ghost">Raise Clarification</button></form></div></div>}
   {bid&&<div className="note" style={{marginTop:14}}><b>Submission received.</b> {money(bid.total,bid.currency)} · status {pretty(bid.status)} · submitted {bid.submitted_at?new Date(bid.submitted_at).toLocaleString("en-IN"):"—"}. No competitor comparison is disclosed here.</div>}
   <div style={{marginTop:14}}><h3>Your Clarifications</h3>{clarifications.filter(c=>c.tender_package_id===p.id&&c.vendor_id===view.vendor_id).map(c=><div className="note" key={c.id} style={{marginBottom:7}}><b>{c.question}</b><div className="subtle">{pretty(c.status)} · raised {new Date(c.created_at).toLocaleString("en-IN")}</div>{c.response&&<div style={{marginTop:5}}>Response: {c.response}</div>}</div>)}{clarifications.filter(c=>c.tender_package_id===p.id&&c.vendor_id===view.vendor_id).length===0&&<p className="subtle">No clarification threads.</p>}</div>
  </section>})}
 </>;
}
