import Link from "next/link";
import { requireWorkspaceUser } from "@/lib/auth";
import TransactionalMessagingClient,{type MessageRow,type ProjectChoice} from "@/components/TransactionalMessagingClient";
import CommunicationMeetingClient,{type CommunicationMeetingState} from "@/components/CommunicationMeetingClient";

export const dynamic="force-dynamic";
type Org={id:string;name:string;role_code:string};
const emptyState:CommunicationMeetingState={communications:[],meetings:[],transcripts:[],minutes:[],decisions:[],actions:[]};

export default async function CommunicationsPage({searchParams}:{searchParams:Promise<{org?:string;project?:string}>}){
  const {supabase}=await requireWorkspaceUser();const {data:orgData,error:orgError}=await supabase.rpc("list_user_organisations");if(orgError)throw new Error(orgError.message);const orgs=(orgData||[]) as Org[];const params=await searchParams;const org=orgs.find(o=>o.id===params.org)||orgs[0];let projects:ProjectChoice[]=[];let messages:MessageRow[]=[];let project:ProjectChoice|undefined;let meetingState=emptyState;
  if(org){const [{data:projectData,error:projectError},{data:messageData,error:messageError}]=await Promise.all([supabase.rpc("list_accessible_projects_for_org",{target_organisation_id:org.id}),supabase.rpc("list_provider_messages",{target_organisation_id:org.id,target_limit:100})]);if(projectError)throw new Error(projectError.message);if(messageError)throw new Error(messageError.message);projects=(projectData||[]) as ProjectChoice[];messages=(messageData||[]) as MessageRow[];project=projects.find(p=>p.id===params.project)||projects[0];if(project){const {data,error}=await supabase.rpc("list_communication_meeting_workspace",{target_project_id:project.id});if(error)throw new Error(error.message);meetingState=(data||emptyState) as CommunicationMeetingState;}}
  const queued=messages.filter(m=>m.status==="queued"||m.status==="processing").length;const sent=messages.filter(m=>["accepted","sent","delivered"].includes(m.status)).length;const failed=messages.filter(m=>m.status==="failed").length;
  return <>
    <div className="topbar"><div><div className="demo">F25 / Communication & Meeting Intelligence</div><h1>Communications</h1><div className="subtle">Policy-governed project communications, transactional delivery, source-retained meeting transcripts and human-approved minutes that create durable decisions/actions.</div></div></div>
    <section className="panel"><h3>Organisation</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{orgs.map(o=><Link key={o.id} href={`/app/communications?org=${o.id}`} className={org?.id===o.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{o.name}</Link>)}</div></section>
    <div className="kpis" style={{marginTop:16}}>{[["Provider Queue",String(queued)],["Sent / Accepted",String(sent)],["Provider Failed",String(failed)],["Projects",String(projects.length)],["Policy Drafts",String(meetingState.communications.length)]].map(([l,v])=><div className="kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div><div className="subtle">Live database</div></div>)}</div>
    {org?<><section className="panel" style={{marginTop:18}}><h3>Project Context</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/communications?org=${org.id}&project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{projects.length===0&&<div className="subtle">No accessible project exists in this organisation.</div>}</section>{project&&<CommunicationMeetingClient projectId={project.id} state={meetingState}/>}<section className="panel" style={{marginTop:18}}><h3>Transactional Delivery Layer</h3><p className="subtle">Provider dispatch remains idempotent and separate from communication approval. Sensitive/legal/critical project messages cannot enter this queue until the F25 policy gate approves them.</p><TransactionalMessagingClient organisationId={org.id} projects={projects} messages={messages}/></section></>:<div className="note" style={{marginTop:18}}>No active organisation membership is available.</div>}
  </>;
}
