import Link from "next/link";
import {requireWorkspaceUser} from "@/lib/auth";
import CompilerRuntimeClient,{type CompilerState} from "@/components/CompilerRuntimeClient";

export const dynamic="force-dynamic";
type ProjectRow={id:string;code:string;name:string;typology:string;stage:string;criticality:string;status:string};
const emptyState:CompilerState={run:null,stages:[],candidates:[],branches:[]};
export default async function DesignPage({searchParams}:{searchParams:Promise<{project?:string}>}){
 const {supabase}=await requireWorkspaceUser();const {data:projectData,error:projectError}=await supabase.rpc("list_accessible_projects");if(projectError)throw new Error(projectError.message);const projects=(projectData||[]) as ProjectRow[];const params=await searchParams;const project=projects.find(p=>p.id===params.project)||projects[0];let state=emptyState;if(project){const {data,error}=await supabase.rpc("list_project_compiler_state",{target_project_id:project.id});if(error)throw new Error(error.message);state=(data||emptyState) as CompilerState;}
 return <><div className="topbar"><div><div className="demo">Design Intelligence / Building Compiler™</div><h1>Design Intelligence</h1><div className="subtle">Freeze verified project inputs, run governed feasibility/design stages, compare deterministic candidates and let humans shortlist without overwriting approved truth.</div></div><div style={{display:"flex",gap:8}}><Link className="btn ghost" href="/app/branches">Building Git</Link><Link className="btn ghost" href="/app/change-impact">Change Impact</Link></div></div><section className="panel"><h3>Project</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{projects.map(p=><Link key={p.id} href={`/app/design?project=${p.id}`} className={project?.id===p.id?"btn":"btn ghost"} style={{padding:"8px 11px"}}>{p.code} · {p.name}</Link>)}</div>{projects.length===0&&<div className="note">No accessible project exists yet.</div>}</section>{project&&<div style={{marginTop:18}}><CompilerRuntimeClient projectId={project.id} state={state}/></div>}<div className="note"><b>No global “best” option.</b> Candidate metrics remain tied to the frozen compiler input version and deterministic stage evidence. Human shortlisting is a recorded decision; professional Architecture/Engineering release remains downstream and independent.</div></>;
}