begin;

create schema if not exists privacy;
grant usage on schema privacy to authenticated;

create table if not exists privacy.processing_records(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references core.organisations(id) on delete cascade,purpose_code text not null,purpose_description text not null,legal_basis text not null,data_categories jsonb not null default '[]'::jsonb,subject_categories jsonb not null default '[]'::jsonb,recipients jsonb not null default '[]'::jsonb,retention_days integer check(retention_days is null or retention_days>0),active boolean not null default true,version integer not null default 1 check(version>0),supersedes_id uuid references privacy.processing_records(id) on delete set null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),record_hash text not null,unique(organisation_id,purpose_code,version)
);
create table if not exists privacy.consent_records(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references core.organisations(id) on delete cascade,subject_user_id uuid references auth.users(id) on delete set null,subject_reference text not null,purpose_code text not null,legal_basis text not null,status text not null check(status in ('granted','withdrawn','not_required')),evidence_ref text not null,evidence_hash text not null,effective_at timestamptz not null default now(),withdrawn_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now()
);
create table if not exists privacy.retention_policies(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references core.organisations(id) on delete cascade,record_class text not null,retention_days integer not null check(retention_days>0),legal_hold_required boolean not null default false,disposal_method text not null,status text not null default 'draft' check(status in ('draft','active','superseded')),version integer not null default 1 check(version>0),supersedes_id uuid references privacy.retention_policies(id) on delete set null,policy_hash text not null,created_by uuid not null references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),unique(organisation_id,record_class,version)
);
create table if not exists privacy.data_subject_requests(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references core.organisations(id) on delete cascade,request_type text not null check(request_type in ('access','correction','erasure','restriction','portability','objection')),subject_user_id uuid references auth.users(id) on delete set null,subject_reference text not null,identity_status text not null default 'pending' check(identity_status in ('pending','verified','rejected')),state text not null default 'identity_pending' check(state in ('identity_pending','in_progress','completed','rejected')),scope jsonb not null default '[]'::jsonb,legal_hold_refs jsonb not null default '[]'::jsonb,requested_at timestamptz not null default now(),requested_by uuid references auth.users(id) on delete set null,verified_by uuid references auth.users(id),verified_at timestamptz,completed_by uuid references auth.users(id),completed_at timestamptz,completion_evidence_refs jsonb not null default '[]'::jsonb,completion_hash text,decision_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists privacy.project_export_requests(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references core.organisations(id) on delete cascade,project_id uuid not null references project.projects(id) on delete cascade,document_id uuid not null references cde.documents(id) on delete cascade,requested_by uuid not null references auth.users(id),purpose text not null,intended_recipient text,status text not null default 'pending' check(status in ('pending','approved','rejected','expired','used')),requested_at timestamptz not null default now(),decided_by uuid references auth.users(id),decided_at timestamptz,decision_reason text,expires_at timestamptz,used_at timestamptz,request_hash text not null,approval_hash text
);

alter table privacy.processing_records enable row level security;alter table privacy.consent_records enable row level security;alter table privacy.retention_policies enable row level security;alter table privacy.data_subject_requests enable row level security;alter table privacy.project_export_requests enable row level security;
grant select,insert,update on privacy.processing_records,privacy.consent_records,privacy.retention_policies,privacy.data_subject_requests,privacy.project_export_requests to authenticated;

do $$ declare t text; begin foreach t in array array['processing_records','consent_records','retention_policies','data_subject_requests'] loop execute format('drop policy if exists %I on privacy.%I','privacy_org_read_'||t,t);execute format('create policy %I on privacy.%I for select to authenticated using (core.is_internal_org_member(organisation_id))','privacy_org_read_'||t,t);end loop;end $$;

drop policy if exists privacy_export_read on privacy.project_export_requests;create policy privacy_export_read on privacy.project_export_requests for select to authenticated using(project.can_access_project(project_id) or requested_by=auth.uid());
drop policy if exists privacy_processing_write on privacy.processing_records;create policy privacy_processing_write on privacy.processing_records for insert to authenticated with check(core.has_org_role(organisation_id,array['super_admin','org_admin']) and created_by=auth.uid() and current_setting('conceptspaces.privacy_phase',true)='processing');
drop policy if exists privacy_consent_write on privacy.consent_records;create policy privacy_consent_write on privacy.consent_records for insert to authenticated with check(core.is_internal_org_member(organisation_id) and created_by=auth.uid() and current_setting('conceptspaces.privacy_phase',true)='consent');
drop policy if exists privacy_retention_write on privacy.retention_policies;create policy privacy_retention_write on privacy.retention_policies for insert to authenticated with check(core.has_org_role(organisation_id,array['super_admin','org_admin']) and created_by=auth.uid() and current_setting('conceptspaces.privacy_phase',true)='retention');
drop policy if exists privacy_retention_update on privacy.retention_policies;create policy privacy_retention_update on privacy.retention_policies for update to authenticated using(core.has_org_role(organisation_id,array['super_admin','org_admin'])) with check(core.has_org_role(organisation_id,array['super_admin','org_admin']) and current_setting('conceptspaces.privacy_phase',true)='retention_approve');
drop policy if exists privacy_dsr_write on privacy.data_subject_requests;create policy privacy_dsr_write on privacy.data_subject_requests for insert to authenticated with check(core.is_internal_org_member(organisation_id) and current_setting('conceptspaces.privacy_phase',true)='dsr_create');
drop policy if exists privacy_dsr_update on privacy.data_subject_requests;create policy privacy_dsr_update on privacy.data_subject_requests for update to authenticated using(core.has_org_role(organisation_id,array['super_admin','org_admin'])) with check(core.has_org_role(organisation_id,array['super_admin','org_admin']) and current_setting('conceptspaces.privacy_phase',true) in ('dsr_verify','dsr_complete','dsr_reject'));
drop policy if exists privacy_export_insert on privacy.project_export_requests;create policy privacy_export_insert on privacy.project_export_requests for insert to authenticated with check(requested_by=auth.uid() and project.can_access_project(project_id) and current_setting('conceptspaces.privacy_phase',true)='export_request');
drop policy if exists privacy_export_update on privacy.project_export_requests;create policy privacy_export_update on privacy.project_export_requests for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.privacy_phase',true) in ('export_decide','export_use'));

commit;
