begin;

create or replace function public.create_processing_record(target_organisation_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='privacy','core','audit','extensions','auth','pg_temp' as $$
declare prior privacy.processing_records%rowtype; r privacy.processing_records%rowtype; v int; h text;
begin
 if auth.uid() is null or not core.has_org_role(target_organisation_id,array['super_admin','org_admin']) then raise exception 'privacy_governance_authority_required';end if;
 if nullif(btrim(input_payload->>'purpose_code'),'') is null or nullif(btrim(input_payload->>'purpose_description'),'') is null or nullif(btrim(input_payload->>'legal_basis'),'') is null then raise exception 'processing_record_core_fields_required';end if;
 select * into prior from privacy.processing_records where organisation_id=target_organisation_id and purpose_code=lower(btrim(input_payload->>'purpose_code')) and active order by version desc limit 1 for update;v:=coalesce(prior.version,0)+1;
 h:=encode(extensions.digest(jsonb_build_object('organisation_id',target_organisation_id,'purpose_code',lower(btrim(input_payload->>'purpose_code')),'purpose_description',btrim(input_payload->>'purpose_description'),'legal_basis',btrim(input_payload->>'legal_basis'),'data_categories',coalesce(input_payload->'data_categories','[]'::jsonb),'subject_categories',coalesce(input_payload->'subject_categories','[]'::jsonb),'recipients',coalesce(input_payload->'recipients','[]'::jsonb),'retention_days',nullif(input_payload->>'retention_days','')::int,'version',v)::text,'sha256'),'hex');
 perform set_config('conceptspaces.privacy_phase','processing',true);
 if prior.id is not null then update privacy.processing_records set active=false where id=prior.id;end if;
 insert into privacy.processing_records(organisation_id,purpose_code,purpose_description,legal_basis,data_categories,subject_categories,recipients,retention_days,version,supersedes_id,created_by,record_hash)
 values(target_organisation_id,lower(btrim(input_payload->>'purpose_code')),btrim(input_payload->>'purpose_description'),btrim(input_payload->>'legal_basis'),coalesce(input_payload->'data_categories','[]'::jsonb),coalesce(input_payload->'subject_categories','[]'::jsonb),coalesce(input_payload->'recipients','[]'::jsonb),nullif(input_payload->>'retention_days','')::int,v,prior.id,auth.uid(),h) returning * into r;
 perform audit.append_event(target_organisation_id,null,'privacy.processing_record_created','processing_record',r.id,null,to_jsonb(r),h,gen_random_uuid());return r.id;
end;$$;
revoke all on function public.create_processing_record(uuid,jsonb) from public,anon;grant execute on function public.create_processing_record(uuid,jsonb) to authenticated;

create or replace function public.record_privacy_consent(target_organisation_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='privacy','core','audit','extensions','auth','pg_temp' as $$
declare r privacy.consent_records%rowtype; status_value text:=lower(btrim(input_payload->>'status')); h text;
begin
 if auth.uid() is null or not core.is_internal_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;
 if status_value not in ('granted','withdrawn','not_required') then raise exception 'consent_status_invalid';end if;
 if nullif(btrim(input_payload->>'subject_reference'),'') is null or nullif(btrim(input_payload->>'purpose_code'),'') is null or nullif(btrim(input_payload->>'legal_basis'),'') is null or nullif(btrim(input_payload->>'evidence_ref'),'') is null then raise exception 'consent_evidence_fields_required';end if;
 h:=encode(extensions.digest(jsonb_build_object('organisation_id',target_organisation_id,'subject_reference',btrim(input_payload->>'subject_reference'),'purpose_code',lower(btrim(input_payload->>'purpose_code')),'legal_basis',btrim(input_payload->>'legal_basis'),'status',status_value,'evidence_ref',btrim(input_payload->>'evidence_ref'))::text,'sha256'),'hex');
 perform set_config('conceptspaces.privacy_phase','consent',true);
 insert into privacy.consent_records(organisation_id,subject_user_id,subject_reference,purpose_code,legal_basis,status,evidence_ref,evidence_hash,effective_at,withdrawn_at,created_by)
 values(target_organisation_id,nullif(input_payload->>'subject_user_id','')::uuid,btrim(input_payload->>'subject_reference'),lower(btrim(input_payload->>'purpose_code')),btrim(input_payload->>'legal_basis'),status_value,btrim(input_payload->>'evidence_ref'),h,coalesce(nullif(input_payload->>'effective_at','')::timestamptz,now()),case when status_value='withdrawn' then now() end,auth.uid()) returning * into r;
 perform audit.append_event(target_organisation_id,null,'privacy.consent_'||status_value,'consent_record',r.id,null,to_jsonb(r),h,gen_random_uuid());return r.id;
end;$$;
revoke all on function public.record_privacy_consent(uuid,jsonb) from public,anon;grant execute on function public.record_privacy_consent(uuid,jsonb) to authenticated;

create or replace function public.create_retention_policy(target_organisation_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='privacy','core','audit','extensions','auth','pg_temp' as $$
declare prior privacy.retention_policies%rowtype; r privacy.retention_policies%rowtype; v int; h text;
begin
 if auth.uid() is null or not core.has_org_role(target_organisation_id,array['super_admin','org_admin']) then raise exception 'retention_governance_authority_required';end if;
 if nullif(btrim(input_payload->>'record_class'),'') is null or coalesce(nullif(input_payload->>'retention_days','')::int,0)<=0 or nullif(btrim(input_payload->>'disposal_method'),'') is null then raise exception 'retention_policy_fields_required';end if;
 select * into prior from privacy.retention_policies where organisation_id=target_organisation_id and record_class=lower(btrim(input_payload->>'record_class')) and status in ('draft','active') order by version desc limit 1 for update;v:=coalesce(prior.version,0)+1;
 h:=encode(extensions.digest(jsonb_build_object('organisation_id',target_organisation_id,'record_class',lower(btrim(input_payload->>'record_class')),'retention_days',(input_payload->>'retention_days')::int,'legal_hold_required',coalesce((input_payload->>'legal_hold_required')::boolean,false),'disposal_method',btrim(input_payload->>'disposal_method'),'version',v)::text,'sha256'),'hex');
 perform set_config('conceptspaces.privacy_phase','retention',true);
 insert into privacy.retention_policies(organisation_id,record_class,retention_days,legal_hold_required,disposal_method,status,version,supersedes_id,policy_hash,created_by)
 values(target_organisation_id,lower(btrim(input_payload->>'record_class')),(input_payload->>'retention_days')::int,coalesce((input_payload->>'legal_hold_required')::boolean,false),btrim(input_payload->>'disposal_method'),'draft',v,prior.id,h,auth.uid()) returning * into r;
 perform audit.append_event(target_organisation_id,null,'privacy.retention_policy_drafted','retention_policy',r.id,null,to_jsonb(r),h,gen_random_uuid());return r.id;
end;$$;
revoke all on function public.create_retention_policy(uuid,jsonb) from public,anon;grant execute on function public.create_retention_policy(uuid,jsonb) to authenticated;

create or replace function public.approve_retention_policy(target_policy_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='privacy','core','audit','auth','pg_temp' as $$
declare r privacy.retention_policies%rowtype; before_state jsonb;
begin
 select * into r from privacy.retention_policies where id=target_policy_id for update;if not found then raise exception 'retention_policy_not_found';end if;
 if auth.uid() is null or not core.has_org_role(r.organisation_id,array['super_admin','org_admin']) or r.created_by=auth.uid() then raise exception 'independent_retention_approval_required';end if;
 if r.status<>'draft' or nullif(btrim(target_reason),'') is null then raise exception 'retention_policy_not_approvable';end if;before_state:=to_jsonb(r);
 perform set_config('conceptspaces.privacy_phase','retention_approve',true);
 update privacy.retention_policies set status='superseded' where organisation_id=r.organisation_id and record_class=r.record_class and status='active';
 update privacy.retention_policies set status='active',approved_by=auth.uid(),approved_at=now() where id=r.id returning * into r;
 perform audit.append_event(r.organisation_id,null,'privacy.retention_policy_approved','retention_policy',r.id,before_state,to_jsonb(r),target_reason,gen_random_uuid());return r.status;
end;$$;
revoke all on function public.approve_retention_policy(uuid,text) from public,anon;grant execute on function public.approve_retention_policy(uuid,text) to authenticated;

create or replace function public.create_privacy_request(target_organisation_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='privacy','core','audit','auth','pg_temp' as $$
declare r privacy.data_subject_requests%rowtype; kind text:=lower(btrim(input_payload->>'request_type'));
begin
 if auth.uid() is null or not core.is_internal_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;
 if kind not in ('access','correction','erasure','restriction','portability','objection') or nullif(btrim(input_payload->>'subject_reference'),'') is null then raise exception 'privacy_request_fields_invalid';end if;
 perform set_config('conceptspaces.privacy_phase','dsr_create',true);insert into privacy.data_subject_requests(organisation_id,request_type,subject_user_id,subject_reference,scope,requested_by) values(target_organisation_id,kind,nullif(input_payload->>'subject_user_id','')::uuid,btrim(input_payload->>'subject_reference'),coalesce(input_payload->'scope','[]'::jsonb),auth.uid()) returning * into r;
 perform audit.append_event(r.organisation_id,null,'privacy.request_created','data_subject_request',r.id,null,to_jsonb(r),null,gen_random_uuid());return r.id;
end;$$;
revoke all on function public.create_privacy_request(uuid,jsonb) from public,anon;grant execute on function public.create_privacy_request(uuid,jsonb) to authenticated;

create or replace function public.verify_privacy_request_identity(target_request_id uuid,target_decision text,target_reason text)
returns text language plpgsql security invoker set search_path='privacy','core','audit','auth','pg_temp' as $$
declare r privacy.data_subject_requests%rowtype; d text:=lower(btrim(target_decision)); before_state jsonb;
begin select * into r from privacy.data_subject_requests where id=target_request_id for update;if not found then raise exception 'privacy_request_not_found';end if;if auth.uid() is null or not core.has_org_role(r.organisation_id,array['super_admin','org_admin']) then raise exception 'privacy_identity_verification_authority_required';end if;if r.identity_status<>'pending' or d not in ('verified','rejected') or nullif(btrim(target_reason),'') is null then raise exception 'privacy_identity_decision_invalid';end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.privacy_phase',case when d='verified' then 'dsr_verify' else 'dsr_reject' end,true);update privacy.data_subject_requests set identity_status=d,state=case when d='verified' then 'in_progress' else 'rejected' end,verified_by=auth.uid(),verified_at=now(),decision_reason=btrim(target_reason),updated_at=now() where id=r.id returning * into r;perform audit.append_event(r.organisation_id,null,'privacy.identity_'||d,'data_subject_request',r.id,before_state,to_jsonb(r),target_reason,gen_random_uuid());return r.state;end;$$;
revoke all on function public.verify_privacy_request_identity(uuid,text,text) from public,anon;grant execute on function public.verify_privacy_request_identity(uuid,text,text) to authenticated;

create or replace function public.complete_privacy_request(target_request_id uuid,input_payload jsonb)
returns text language plpgsql security invoker set search_path='privacy','core','audit','extensions','auth','pg_temp' as $$
declare r privacy.data_subject_requests%rowtype; before_state jsonb; evidence jsonb:=coalesce(input_payload->'evidence_refs','[]'::jsonb);holds jsonb:=coalesce(input_payload->'legal_hold_refs','[]'::jsonb);h text;
begin select * into r from privacy.data_subject_requests where id=target_request_id for update;if not found then raise exception 'privacy_request_not_found';end if;if auth.uid() is null or not core.has_org_role(r.organisation_id,array['super_admin','org_admin']) then raise exception 'privacy_completion_authority_required';end if;if r.identity_status<>'verified' or r.state<>'in_progress' or jsonb_array_length(evidence)=0 then raise exception 'privacy_verified_request_and_completion_evidence_required';end if;if r.request_type='erasure' and jsonb_array_length(holds)>0 and nullif(btrim(input_payload->>'decision_reason'),'') is null then raise exception 'retention_hold_reason_required';end if;h:=encode(extensions.digest(jsonb_build_object('request_id',r.id,'type',r.request_type,'scope',r.scope,'evidence',evidence,'legal_holds',holds,'reason',coalesce(input_payload->>'decision_reason',''))::text,'sha256'),'hex');before_state:=to_jsonb(r);perform set_config('conceptspaces.privacy_phase','dsr_complete',true);update privacy.data_subject_requests set state='completed',completed_by=auth.uid(),completed_at=now(),completion_evidence_refs=evidence,legal_hold_refs=holds,completion_hash=h,decision_reason=nullif(btrim(input_payload->>'decision_reason'),''),updated_at=now() where id=r.id returning * into r;perform audit.append_event(r.organisation_id,null,'privacy.request_completed','data_subject_request',r.id,before_state,to_jsonb(r),h,gen_random_uuid());return r.state;end;$$;
revoke all on function public.complete_privacy_request(uuid,jsonb) from public,anon;grant execute on function public.complete_privacy_request(uuid,jsonb) to authenticated;

create or replace function public.request_restricted_document_export(target_document_id uuid,target_purpose text,target_recipient text default null)
returns uuid language plpgsql security invoker set search_path='privacy','cde','project','audit','extensions','auth','pg_temp' as $$
declare d cde.documents%rowtype;p project.projects%rowtype;r privacy.project_export_requests%rowtype;h text;
begin select * into d from cde.documents where id=target_document_id;if not found then raise exception 'document_not_found';end if;select * into p from project.projects where id=d.project_id;if not found or auth.uid() is null or not project.can_access_project(p.id) then raise exception 'project_access_required';end if;if p.data_classification<>'restricted' then raise exception 'restricted_export_request_only_required_for_restricted_project';end if;if d.status not in ('approved','issued') or d.cde_state<>'published' then raise exception 'document_not_published_for_export';end if;if nullif(btrim(target_purpose),'') is null then raise exception 'export_purpose_required';end if;h:=encode(extensions.digest(jsonb_build_object('project_id',p.id,'document_id',d.id,'revision',d.revision,'purpose',btrim(target_purpose),'recipient',coalesce(target_recipient,''),'requester',auth.uid())::text,'sha256'),'hex');perform set_config('conceptspaces.privacy_phase','export_request',true);insert into privacy.project_export_requests(organisation_id,project_id,document_id,requested_by,purpose,intended_recipient,request_hash) values(p.organisation_id,p.id,d.id,auth.uid(),btrim(target_purpose),nullif(btrim(target_recipient),''),h) returning * into r;perform audit.append_event(p.organisation_id,p.id,'security.export_requested','project_export_request',r.id,null,to_jsonb(r),h,gen_random_uuid());return r.id;end;$$;
revoke all on function public.request_restricted_document_export(uuid,text,text) from public,anon;grant execute on function public.request_restricted_document_export(uuid,text,text) to authenticated;

create or replace function public.decide_restricted_document_export(target_request_id uuid,target_decision text,target_reason text,target_expires_at timestamptz default null)
returns text language plpgsql security invoker set search_path='privacy','project','audit','extensions','auth','pg_temp' as $$
declare r privacy.project_export_requests%rowtype;d text:=lower(btrim(target_decision));before_state jsonb;h text;
begin select * into r from privacy.project_export_requests where id=target_request_id for update;if not found then raise exception 'export_request_not_found';end if;if auth.uid() is null or not project.can_manage_project(r.project_id) then raise exception 'export_approval_authority_required';end if;if r.requested_by=auth.uid() then raise exception 'export_requester_cannot_approve_own_request';end if;if r.status<>'pending' or d not in ('approved','rejected') or nullif(btrim(target_reason),'') is null then raise exception 'export_decision_invalid';end if;if d='approved' and (target_expires_at is null or target_expires_at<=now()) then raise exception 'future_export_approval_expiry_required';end if;h:=encode(extensions.digest(jsonb_build_object('request_hash',r.request_hash,'decision',d,'reason',btrim(target_reason),'expires_at',target_expires_at,'approver',auth.uid())::text,'sha256'),'hex');before_state:=to_jsonb(r);perform set_config('conceptspaces.privacy_phase','export_decide',true);update privacy.project_export_requests set status=d,decided_by=auth.uid(),decided_at=now(),decision_reason=btrim(target_reason),expires_at=case when d='approved' then target_expires_at end,approval_hash=h where id=r.id returning * into r;perform audit.append_event(r.organisation_id,r.project_id,'security.export_'||d,'project_export_request',r.id,before_state,to_jsonb(r),h,gen_random_uuid());return r.status;end;$$;
revoke all on function public.decide_restricted_document_export(uuid,text,text,timestamptz) from public,anon;grant execute on function public.decide_restricted_document_export(uuid,text,text,timestamptz) to authenticated;

create or replace function public.authorize_document_download(target_document_id uuid,target_export_request_id uuid default null)
returns jsonb language plpgsql security invoker set search_path='privacy','cde','project','engagement','audit','auth','pg_temp' as $$
declare d cde.documents%rowtype;p project.projects%rowtype;internal_mode boolean;client_ok boolean:=false;allowed boolean:=false;watermark boolean:=false;export_ok boolean:=false;reason_value text;
begin select * into d from cde.documents where id=target_document_id;if not found then raise exception 'document_not_found';end if;select * into p from project.projects where id=d.project_id;if auth.uid() is null then raise exception 'authentication_required';end if;internal_mode:=project.can_access_project(p.id);client_ok:=engagement.client_can_access_project(p.id) and exists(select 1 from engagement.client_portal_access a where a.project_id=p.id and a.user_id=auth.uid() and a.status='active' and coalesce((a.permissions->>'download_documents')::boolean,false));
 if d.status not in ('approved','issued') then reason_value:='document_not_approved_or_issued';elsif client_ok and d.cde_state<>'published' then reason_value:='client_download_requires_published_document';elsif p.data_classification='public' then allowed:=internal_mode or client_ok;elsif p.data_classification='internal' then allowed:=internal_mode;if not allowed then reason_value:='internal_classification_block';end if;elsif p.data_classification='confidential' then allowed:=project.can_manage_project(p.id);watermark:=allowed;if not allowed then reason_value:='confidential_download_management_authority_required';end if;elsif p.data_classification='restricted' then if target_export_request_id is not null then export_ok:=exists(select 1 from privacy.project_export_requests r where r.id=target_export_request_id and r.document_id=d.id and r.project_id=p.id and r.requested_by=auth.uid() and r.status='approved' and r.expires_at>now());end if;allowed:=export_ok;watermark:=allowed;if not allowed then reason_value:='CLASSIFICATION_BLOCK';end if;end if;
 if allowed then perform audit.append_event(p.organisation_id,p.id,'security.download_authorized','document',d.id,null,jsonb_build_object('classification',p.data_classification,'revision',d.revision,'export_request_id',target_export_request_id,'watermark_required',watermark),null,gen_random_uuid());else perform audit.append_event(p.organisation_id,p.id,'security.download_blocked','document',d.id,null,jsonb_build_object('classification',p.data_classification,'reason',coalesce(reason_value,'permission_denied')),coalesce(reason_value,'permission_denied'),gen_random_uuid());end if;return jsonb_build_object('allowed',allowed,'classification',p.data_classification,'watermark_required',watermark,'reason',case when allowed then null else coalesce(reason_value,'permission_denied') end,'document_id',d.id,'revision',d.revision);end;$$;
revoke all on function public.authorize_document_download(uuid,uuid) from public,anon;grant execute on function public.authorize_document_download(uuid,uuid) to authenticated;

create or replace function public.verify_audit_chain(target_organisation_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='audit','core','extensions','auth','pg_temp' as $$
declare e audit.events%rowtype;expected_previous text:=null;computed text;first_bad uuid:=null;checked_count bigint:=0;
begin if auth.uid() is null or not core.is_internal_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;for e in select * from audit.events where organisation_id=target_organisation_id order by created_at,id loop checked_count:=checked_count+1;if e.previous_hash is distinct from expected_previous then first_bad:=e.id;exit;end if;computed:=encode(extensions.digest(concat_ws('|',coalesce(e.previous_hash,''),e.id::text,e.organisation_id::text,coalesce(e.project_id::text,''),coalesce(e.actor_id::text,''),e.action,e.resource_type,coalesce(e.resource_id::text,''),coalesce(e.before_state::text,''),coalesce(e.after_state::text,''),coalesce(e.reason,''),e.correlation_id::text,e.created_at::text),'sha256'),'hex');if computed<>e.event_hash then first_bad:=e.id;exit;end if;expected_previous:=e.event_hash;end loop;return jsonb_build_object('valid',first_bad is null,'checked_events',checked_count,'first_invalid_event_id',first_bad,'chain_head',expected_previous);end;$$;
revoke all on function public.verify_audit_chain(uuid) from public,anon;grant execute on function public.verify_audit_chain(uuid) to authenticated;

create or replace function public.list_privacy_security_workspace(target_organisation_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='privacy','project','core','auth','pg_temp' as $$
begin if auth.uid() is null or not core.is_internal_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;return jsonb_build_object('processing',coalesce((select jsonb_agg(to_jsonb(r) order by r.purpose_code,r.version desc) from privacy.processing_records r where r.organisation_id=target_organisation_id),'[]'::jsonb),'consents',coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from privacy.consent_records r where r.organisation_id=target_organisation_id),'[]'::jsonb),'retention',coalesce((select jsonb_agg(to_jsonb(r) order by r.record_class,r.version desc) from privacy.retention_policies r where r.organisation_id=target_organisation_id),'[]'::jsonb),'requests',coalesce((select jsonb_agg(to_jsonb(r) order by r.requested_at desc) from privacy.data_subject_requests r where r.organisation_id=target_organisation_id),'[]'::jsonb),'exports',coalesce((select jsonb_agg(to_jsonb(r) order by r.requested_at desc) from privacy.project_export_requests r where r.organisation_id=target_organisation_id and project.can_access_project(r.project_id)),'[]'::jsonb),'projects',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'code',p.code::text,'name',p.name,'classification',p.data_classification) order by p.name) from project.projects p where p.organisation_id=target_organisation_id and project.can_access_project(p.id)),'[]'::jsonb));end;$$;
revoke all on function public.list_privacy_security_workspace(uuid) from public,anon;grant execute on function public.list_privacy_security_workspace(uuid) to authenticated;

commit;
