begin;

alter table integration.instances
 add column if not exists failure_threshold integer not null default 3 check(failure_threshold between 1 and 20),
 add column if not exists circuit_open_until timestamptz;

create or replace function public.record_provider_health(target_organisation_id uuid,target_provider_key text,target_environment text,target_status text,target_latency_ms integer,target_error_code text)
returns void language plpgsql security definer set search_path='public','integration','pg_temp' as $$
declare previous_failures int:=0;next_failures int:=0;threshold_value int:=3;open_until timestamptz;
begin
 if target_status not in ('healthy','degraded','down') then raise exception 'provider_health_status_invalid';end if;
 select consecutive_failures into previous_failures from public.provider_health_checks where organisation_id=target_organisation_id and provider_key=target_provider_key and environment=target_environment order by checked_at desc limit 1;previous_failures:=coalesce(previous_failures,0);
 next_failures:=case when target_status in ('degraded','down') then previous_failures+1 else 0 end;
 select failure_threshold into threshold_value from integration.instances where organisation_id=target_organisation_id and provider_key=target_provider_key and environment=target_environment limit 1;threshold_value:=coalesce(threshold_value,3);
 open_until:=case when next_failures>=threshold_value then now()+interval '5 minutes' else null end;
 insert into public.provider_health_checks(organisation_id,provider_key,environment,status,latency_ms,consecutive_failures,last_error_code,checked_at) values(target_organisation_id,target_provider_key,target_environment,target_status,target_latency_ms,next_failures,target_error_code,now());
 update integration.instances set last_health_check_at=now(),last_health_status=target_status,status=case when target_status='healthy' and status in ('configured','degraded') then 'verified' when target_status in ('degraded','down') then 'degraded' else status end,verified_at=case when target_status='healthy' then coalesce(verified_at,now()) else verified_at end,circuit_open_until=open_until,updated_at=now() where organisation_id=target_organisation_id and provider_key=target_provider_key and environment=target_environment and enabled=true;
end;$$;
revoke all on function public.record_provider_health(uuid,text,text,text,integer,text) from public,anon,authenticated;grant execute on function public.record_provider_health(uuid,text,text,text,integer,text) to service_role;

create or replace function public.create_service_slo(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='operations','core','audit','extensions','auth','pg_temp' as $$
declare prior operations.service_slos%rowtype;r operations.service_slos%rowtype;v int;h text;org_id uuid;op text:=lower(btrim(input_payload->>'target_operator'));
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'service'),'') is null or nullif(btrim(input_payload->>'metric_key'),'') is null or op not in ('gte','lte') or nullif(input_payload->>'target_value','') is null or nullif(btrim(input_payload->>'unit'),'') is null or coalesce(nullif(input_payload->>'window_minutes','')::int,0)<=0 then raise exception 'slo_fields_invalid';end if;select * into prior from operations.service_slos where service=btrim(input_payload->>'service') and metric_key=btrim(input_payload->>'metric_key') and status in ('draft','active') order by version desc limit 1 for update;v:=coalesce(prior.version,0)+1;h:=encode(extensions.digest(jsonb_build_object('service',btrim(input_payload->>'service'),'metric_key',btrim(input_payload->>'metric_key'),'operator',op,'target',(input_payload->>'target_value')::numeric,'unit',btrim(input_payload->>'unit'),'window',(input_payload->>'window_minutes')::int,'version',v)::text,'sha256'),'hex');perform set_config('conceptspaces.sre_phase','slo_create',true);insert into operations.service_slos(service,metric_key,target_operator,target_value,unit,window_minutes,status,version,supersedes_id,created_by,slo_hash) values(btrim(input_payload->>'service'),btrim(input_payload->>'metric_key'),op,(input_payload->>'target_value')::numeric,btrim(input_payload->>'unit'),(input_payload->>'window_minutes')::int,'draft',v,prior.id,auth.uid(),h) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'slo.drafted','service_slo',r.id,null,to_jsonb(r),h,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.create_service_slo(jsonb) from public,anon;grant execute on function public.create_service_slo(jsonb) to authenticated;

create or replace function public.approve_service_slo(target_slo_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='operations','core','audit','auth','pg_temp' as $$
declare r operations.service_slos%rowtype;before_state jsonb;org_id uuid;
begin select * into r from operations.service_slos where id=target_slo_id for update;if not found then raise exception 'slo_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or r.created_by=auth.uid() then raise exception 'independent_slo_approval_required';end if;if r.status<>'draft' or nullif(btrim(target_reason),'') is null then raise exception 'slo_not_approvable';end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.sre_phase','slo_approve',true);update operations.service_slos set status='superseded' where service=r.service and metric_key=r.metric_key and status='active';update operations.service_slos set status='active',approved_by=auth.uid(),approved_at=now() where id=r.id returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'slo.approved','service_slo',r.id,before_state,to_jsonb(r),target_reason,gen_random_uuid());end if;return r.status;end;$$;
revoke all on function public.approve_service_slo(uuid,text) from public,anon;grant execute on function public.approve_service_slo(uuid,text) to authenticated;

create or replace function public.record_service_telemetry(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='operations','core','audit','extensions','auth','pg_temp' as $$
declare r operations.service_telemetry%rowtype;h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'service'),'') is null or nullif(btrim(input_payload->>'metric_key'),'') is null or nullif(input_payload->>'metric_value','') is null or nullif(btrim(input_payload->>'unit'),'') is null or nullif(btrim(input_payload->>'source'),'') is null then raise exception 'telemetry_fields_invalid';end if;h:=encode(extensions.digest(jsonb_build_object('service',btrim(input_payload->>'service'),'metric_key',btrim(input_payload->>'metric_key'),'value',(input_payload->>'metric_value')::numeric,'unit',btrim(input_payload->>'unit'),'source',btrim(input_payload->>'source'),'trace_id',nullif(input_payload->>'trace_id','')::uuid,'observed_at',coalesce(nullif(input_payload->>'observed_at','')::timestamptz,now()))::text,'sha256'),'hex');perform set_config('conceptspaces.sre_phase','telemetry',true);insert into operations.service_telemetry(service,metric_key,metric_value,unit,source,trace_id,observed_at,evidence_hash,created_by) values(btrim(input_payload->>'service'),btrim(input_payload->>'metric_key'),(input_payload->>'metric_value')::numeric,btrim(input_payload->>'unit'),btrim(input_payload->>'source'),nullif(input_payload->>'trace_id','')::uuid,coalesce(nullif(input_payload->>'observed_at','')::timestamptz,now()),h,auth.uid()) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'slo.telemetry_recorded','service_telemetry',r.id,null,jsonb_build_object('service',r.service,'metric_key',r.metric_key,'metric_value',r.metric_value,'unit',r.unit,'trace_id',r.trace_id),h,coalesce(r.trace_id,gen_random_uuid()));end if;return r.id;end;$$;
revoke all on function public.record_service_telemetry(jsonb) from public,anon;grant execute on function public.record_service_telemetry(jsonb) to authenticated;

create or replace function public.list_sre_workspace(target_organisation_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='workflow','operations','public','core','project','integration','auth','pg_temp' as $$
begin if auth.uid() is null or not core.is_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;return jsonb_build_object(
'jobs',coalesce((select jsonb_agg(to_jsonb(j) order by j.created_at desc) from workflow.jobs j where j.organisation_id=target_organisation_id and (j.project_id is null or project.can_access_project(j.project_id))),'[]'::jsonb),
'providers',coalesce((select jsonb_agg(jsonb_build_object('provider_key',h.provider_key,'environment',h.environment,'status',h.status,'latency_ms',h.latency_ms,'consecutive_failures',h.consecutive_failures,'last_error_code',h.last_error_code,'checked_at',h.checked_at,'instance_status',i.status,'circuit_open_until',i.circuit_open_until,'failure_threshold',i.failure_threshold) order by h.provider_key) from (select distinct on (provider_key,environment) * from public.provider_health_checks where organisation_id=target_organisation_id or organisation_id is null order by provider_key,environment,checked_at desc) h left join integration.instances i on i.organisation_id=target_organisation_id and i.provider_key=h.provider_key and i.environment=h.environment),'[]'::jsonb),
'slos',case when core.is_platform_admin() then coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'service',s.service,'metric_key',s.metric_key,'target_operator',s.target_operator,'target_value',s.target_value,'unit',s.unit,'window_minutes',s.window_minutes,'status',s.status,'version',s.version,'slo_hash',s.slo_hash,'created_by',s.created_by,'latest_value',(select t.metric_value from operations.service_telemetry t where t.service=s.service and t.metric_key=s.metric_key order by t.observed_at desc limit 1),'latest_observed_at',(select t.observed_at from operations.service_telemetry t where t.service=s.service and t.metric_key=s.metric_key order by t.observed_at desc limit 1),'within_target',(select case when s.target_operator='gte' then t.metric_value>=s.target_value else t.metric_value<=s.target_value end from operations.service_telemetry t where t.service=s.service and t.metric_key=s.metric_key order by t.observed_at desc limit 1)) order by s.service,s.metric_key,s.version desc) from operations.service_slos s),'[]'::jsonb) else '[]'::jsonb end,
'incidents',case when core.is_platform_admin() then coalesce((select jsonb_agg(to_jsonb(i) order by i.detected_at desc) from public.incidents i),'[]'::jsonb) else '[]'::jsonb end,
'drills',case when core.is_platform_admin() then coalesce((select jsonb_agg(to_jsonb(d) order by d.started_at desc) from public.backup_restore_drills d),'[]'::jsonb) else '[]'::jsonb end);end;$$;
revoke all on function public.list_sre_workspace(uuid) from public,anon;grant execute on function public.list_sre_workspace(uuid) to authenticated;

commit;
