begin;

alter table public.api_credentials
 add column if not exists project_restrictions jsonb not null default '[]'::jsonb,
 add column if not exists rate_limit_per_minute integer not null default 60 check(rate_limit_per_minute between 1 and 100000),
 add column if not exists rotated_from_id uuid references public.api_credentials(id) on delete set null,
 add column if not exists credential_hash text;

grant insert,update on public.api_credentials to authenticated;
drop policy if exists api_credentials_governed_insert on public.api_credentials;
create policy api_credentials_governed_insert on public.api_credentials for insert to authenticated with check((core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) and created_by=auth.uid() and current_setting('conceptspaces.integration_phase',true) in ('api_issue','api_rotate'));
drop policy if exists api_credentials_governed_update on public.api_credentials;
create policy api_credentials_governed_update on public.api_credentials for update to authenticated using(core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) with check((core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) and current_setting('conceptspaces.integration_phase',true) in ('api_revoke','api_rotate','api_used'));

create or replace function public.issue_api_credential(target_organisation_id uuid,input_payload jsonb)
returns jsonb language plpgsql security invoker set search_path='public','core','audit','extensions','auth','pg_temp' as $$
declare raw_secret text;prefix text;secret_digest text;r public.api_credentials%rowtype;scopes jsonb:=coalesce(input_payload->'scopes','[]'::jsonb);projects jsonb:=coalesce(input_payload->'project_restrictions','[]'::jsonb);h text;
begin
 if auth.uid() is null or not (core.is_platform_admin() or core.has_org_role(target_organisation_id,array['super_admin','org_admin'])) then raise exception 'api_credential_authority_required';end if;
 if nullif(btrim(input_payload->>'name'),'') is null or jsonb_array_length(scopes)=0 then raise exception 'api_credential_name_and_scope_required';end if;
 if exists(select 1 from jsonb_array_elements_text(scopes) s where s='*' or s='admin:*') then raise exception 'api_blanket_scope_forbidden';end if;
 if nullif(input_payload->>'expires_at','')::timestamptz is not null and (input_payload->>'expires_at')::timestamptz<=now() then raise exception 'api_credential_future_expiry_required';end if;
 raw_secret:='cs_'||encode(extensions.gen_random_bytes(32),'hex');prefix:=left(raw_secret,12);secret_digest:=encode(extensions.digest(raw_secret,'sha256'),'hex');
 h:=encode(extensions.digest(jsonb_build_object('organisation_id',target_organisation_id,'name',btrim(input_payload->>'name'),'key_prefix',prefix,'scopes',scopes,'project_restrictions',projects,'expires_at',nullif(input_payload->>'expires_at','')::timestamptz,'rate_limit',coalesce(nullif(input_payload->>'rate_limit_per_minute','')::int,60))::text,'sha256'),'hex');
 perform set_config('conceptspaces.integration_phase','api_issue',true);
 insert into public.api_credentials(organisation_id,name,key_prefix,secret_hash,scopes,allowed_ip_cidrs,expires_at,created_by,project_restrictions,rate_limit_per_minute,credential_hash)
 values(target_organisation_id,btrim(input_payload->>'name'),prefix,secret_digest,scopes,coalesce(input_payload->'allowed_ip_cidrs','[]'::jsonb),nullif(input_payload->>'expires_at','')::timestamptz,auth.uid(),projects,coalesce(nullif(input_payload->>'rate_limit_per_minute','')::int,60),h) returning * into r;
 perform audit.append_event(target_organisation_id,null,'api.credential_issued','api_credential',r.id,null,jsonb_build_object('name',r.name,'key_prefix',r.key_prefix,'scopes',r.scopes,'project_restrictions',r.project_restrictions,'expires_at',r.expires_at,'rate_limit_per_minute',r.rate_limit_per_minute),h,gen_random_uuid());
 return jsonb_build_object('credential_id',r.id,'key_prefix',prefix,'secret',raw_secret,'shown_once',true,'expires_at',r.expires_at,'scopes',r.scopes);
end;$$;
revoke all on function public.issue_api_credential(uuid,jsonb) from public,anon;grant execute on function public.issue_api_credential(uuid,jsonb) to authenticated;

create or replace function public.revoke_api_credential(target_credential_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='public','core','audit','auth','pg_temp' as $$
declare r public.api_credentials%rowtype;before_state jsonb;
begin select * into r from public.api_credentials where id=target_credential_id for update;if not found then raise exception 'api_credential_not_found';end if;if auth.uid() is null or not (core.is_platform_admin() or core.has_org_role(r.organisation_id,array['super_admin','org_admin'])) then raise exception 'api_credential_authority_required';end if;if r.revoked_at is not null then return 'revoked';end if;if nullif(btrim(target_reason),'') is null then raise exception 'api_revocation_reason_required';end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.integration_phase','api_revoke',true);update public.api_credentials set revoked_at=now() where id=r.id returning * into r;perform audit.append_event(r.organisation_id,null,'api.credential_revoked','api_credential',r.id,before_state,jsonb_build_object('revoked_at',r.revoked_at,'key_prefix',r.key_prefix),target_reason,gen_random_uuid());return 'revoked';end;$$;
revoke all on function public.revoke_api_credential(uuid,text) from public,anon;grant execute on function public.revoke_api_credential(uuid,text) to authenticated;

create or replace function public.rotate_api_credential(target_credential_id uuid,target_reason text)
returns jsonb language plpgsql security invoker set search_path='public','core','audit','extensions','auth','pg_temp' as $$
declare old public.api_credentials%rowtype;r public.api_credentials%rowtype;raw_secret text;prefix text;secret_digest text;h text;
begin select * into old from public.api_credentials where id=target_credential_id for update;if not found then raise exception 'api_credential_not_found';end if;if auth.uid() is null or not (core.is_platform_admin() or core.has_org_role(old.organisation_id,array['super_admin','org_admin'])) then raise exception 'api_credential_authority_required';end if;if old.revoked_at is not null or nullif(btrim(target_reason),'') is null then raise exception 'api_credential_not_rotatable';end if;raw_secret:='cs_'||encode(extensions.gen_random_bytes(32),'hex');prefix:=left(raw_secret,12);secret_digest:=encode(extensions.digest(raw_secret,'sha256'),'hex');h:=encode(extensions.digest(jsonb_build_object('organisation_id',old.organisation_id,'name',old.name,'key_prefix',prefix,'scopes',old.scopes,'project_restrictions',old.project_restrictions,'expires_at',old.expires_at,'rate_limit',old.rate_limit_per_minute,'rotated_from',old.id)::text,'sha256'),'hex');perform set_config('conceptspaces.integration_phase','api_rotate',true);update public.api_credentials set revoked_at=now() where id=old.id;insert into public.api_credentials(organisation_id,name,key_prefix,secret_hash,scopes,allowed_ip_cidrs,expires_at,created_by,project_restrictions,rate_limit_per_minute,rotated_from_id,credential_hash) values(old.organisation_id,old.name,prefix,secret_digest,old.scopes,old.allowed_ip_cidrs,old.expires_at,auth.uid(),old.project_restrictions,old.rate_limit_per_minute,old.id,h) returning * into r;perform audit.append_event(old.organisation_id,null,'api.credential_rotated','api_credential',r.id,jsonb_build_object('old_id',old.id,'old_prefix',old.key_prefix),jsonb_build_object('new_id',r.id,'new_prefix',r.key_prefix,'scopes',r.scopes),target_reason,gen_random_uuid());return jsonb_build_object('credential_id',r.id,'key_prefix',prefix,'secret',raw_secret,'shown_once',true,'rotated_from_id',old.id);end;$$;
revoke all on function public.rotate_api_credential(uuid,text) from public,anon;grant execute on function public.rotate_api_credential(uuid,text) to authenticated;

create or replace function integration.validate_api_credential(target_secret text,target_scope text,target_project_id uuid default null)
returns jsonb language plpgsql security definer set search_path='public','integration','extensions','pg_temp' as $$
declare r public.api_credentials%rowtype;digest_value text;
begin if nullif(target_secret,'') is null or nullif(target_scope,'') is null then return jsonb_build_object('valid',false,'reason','credential_missing');end if;digest_value:=encode(extensions.digest(target_secret,'sha256'),'hex');select * into r from public.api_credentials where key_prefix=left(target_secret,12) and secret_hash=digest_value limit 1;if not found then return jsonb_build_object('valid',false,'reason','credential_invalid');end if;if r.revoked_at is not null then return jsonb_build_object('valid',false,'reason','credential_revoked');end if;if r.expires_at is not null and r.expires_at<=now() then return jsonb_build_object('valid',false,'reason','credential_expired');end if;if not (r.scopes ? target_scope) then return jsonb_build_object('valid',false,'reason','API_SCOPE_DENIED');end if;if target_project_id is not null and jsonb_array_length(r.project_restrictions)>0 and not (r.project_restrictions ? target_project_id::text) then return jsonb_build_object('valid',false,'reason','project_scope_denied');end if;update public.api_credentials set last_used_at=now() where id=r.id;return jsonb_build_object('valid',true,'credential_id',r.id,'organisation_id',r.organisation_id,'rate_limit_per_minute',r.rate_limit_per_minute);end;$$;
revoke all on function integration.validate_api_credential(text,text,uuid) from public,anon,authenticated;grant execute on function integration.validate_api_credential(text,text,uuid) to service_role;

create table if not exists integration.data_contracts(
 id uuid primary key default gen_random_uuid(),contract_key text not null unique,producer text not null,description text not null,status text not null default 'active' check(status in ('active','deprecated')),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists integration.data_contract_versions(
 id uuid primary key default gen_random_uuid(),contract_id uuid not null references integration.data_contracts(id) on delete cascade,major_version integer not null check(major_version>0),minor_version integer not null check(minor_version>=0),schema_definition jsonb not null,compatibility_mode text not null default 'backward' check(compatibility_mode in ('backward','none')),breaking_change boolean not null default false,status text not null default 'draft' check(status in ('draft','published','deprecated')),predecessor_id uuid references integration.data_contract_versions(id) on delete set null,schema_hash text not null,created_by uuid not null references auth.users(id),published_by uuid references auth.users(id),published_at timestamptz,deprecation_at timestamptz,created_at timestamptz not null default now(),unique(contract_id,major_version,minor_version));
alter table integration.data_contracts enable row level security;alter table integration.data_contract_versions enable row level security;
grant select,insert,update on integration.data_contracts,integration.data_contract_versions to authenticated;
drop policy if exists data_contracts_read on integration.data_contracts;create policy data_contracts_read on integration.data_contracts for select to authenticated using(core.is_platform_admin());
drop policy if exists data_contract_versions_read on integration.data_contract_versions;create policy data_contract_versions_read on integration.data_contract_versions for select to authenticated using(core.is_platform_admin());
drop policy if exists data_contracts_insert on integration.data_contracts;create policy data_contracts_insert on integration.data_contracts for insert to authenticated with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.integration_phase',true)='contract_create');
drop policy if exists data_contract_versions_insert on integration.data_contract_versions;create policy data_contract_versions_insert on integration.data_contract_versions for insert to authenticated with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.integration_phase',true)='contract_version');
drop policy if exists data_contract_versions_update on integration.data_contract_versions;create policy data_contract_versions_update on integration.data_contract_versions for update to authenticated using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.integration_phase',true) in ('contract_publish','contract_deprecate'));

create or replace function integration.is_breaking_schema(old_schema jsonb,new_schema jsonb)
returns boolean language sql stable security definer set search_path='pg_temp' as $$
 select exists(select 1 from jsonb_each(coalesce(old_schema->'properties','{}'::jsonb)) o where not (coalesce(new_schema->'properties','{}'::jsonb) ? o.key) or coalesce(new_schema->'properties'->o.key->>'type','')<>coalesce(o.value->>'type','')) or exists(select 1 from jsonb_array_elements_text(coalesce(new_schema->'required','[]'::jsonb)) n where not exists(select 1 from jsonb_array_elements_text(coalesce(old_schema->'required','[]'::jsonb)) o where o=n));
$$;
revoke all on function integration.is_breaking_schema(jsonb,jsonb) from public,anon,authenticated;

create or replace function public.create_data_contract_version(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='integration','core','audit','extensions','auth','pg_temp' as $$
declare c integration.data_contracts%rowtype;prev integration.data_contract_versions%rowtype;r integration.data_contract_versions%rowtype;maj int:=coalesce(nullif(input_payload->>'major_version','')::int,1);minv int:=coalesce(nullif(input_payload->>'minor_version','')::int,0);schema_value jsonb:=coalesce(input_payload->'schema_definition','{}'::jsonb);breaking boolean:=false;h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'contract_key'),'') is null or nullif(btrim(input_payload->>'producer'),'') is null or nullif(btrim(input_payload->>'description'),'') is null or schema_value='{}'::jsonb then raise exception 'data_contract_fields_invalid';end if;select * into c from integration.data_contracts where contract_key=btrim(input_payload->>'contract_key') for update;if not found then perform set_config('conceptspaces.integration_phase','contract_create',true);insert into integration.data_contracts(contract_key,producer,description,created_by) values(btrim(input_payload->>'contract_key'),btrim(input_payload->>'producer'),btrim(input_payload->>'description'),auth.uid()) returning * into c;end if;select * into prev from integration.data_contract_versions where contract_id=c.id and status='published' order by major_version desc,minor_version desc limit 1;if prev.id is not null then breaking:=integration.is_breaking_schema(prev.schema_definition,schema_value);end if;h:=encode(extensions.digest(jsonb_build_object('contract_id',c.id,'major',maj,'minor',minv,'schema',schema_value,'compatibility_mode',coalesce(input_payload->>'compatibility_mode','backward'),'breaking',breaking,'predecessor',prev.id)::text,'sha256'),'hex');perform set_config('conceptspaces.integration_phase','contract_version',true);insert into integration.data_contract_versions(contract_id,major_version,minor_version,schema_definition,compatibility_mode,breaking_change,status,predecessor_id,schema_hash,created_by) values(c.id,maj,minv,schema_value,coalesce(nullif(btrim(input_payload->>'compatibility_mode'),''),'backward'),breaking,'draft',prev.id,h,auth.uid()) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'schema.version_drafted','data_contract_version',r.id,null,jsonb_build_object('contract_key',c.contract_key,'major',maj,'minor',minv,'breaking',breaking,'schema_hash',h),h,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.create_data_contract_version(jsonb) from public,anon;grant execute on function public.create_data_contract_version(jsonb) to authenticated;

create or replace function public.publish_data_contract_version(target_version_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='integration','core','audit','auth','pg_temp' as $$
declare r integration.data_contract_versions%rowtype;prev integration.data_contract_versions%rowtype;c integration.data_contracts%rowtype;before_state jsonb;org_id uuid;
begin select * into r from integration.data_contract_versions where id=target_version_id for update;if not found then raise exception 'data_contract_version_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or r.created_by=auth.uid() then raise exception 'independent_schema_publish_authority_required';end if;if r.status<>'draft' or nullif(btrim(target_reason),'') is null then raise exception 'schema_version_not_publishable';end if;select * into c from integration.data_contracts where id=r.contract_id;select * into prev from integration.data_contract_versions where contract_id=r.contract_id and status='published' order by major_version desc,minor_version desc limit 1;if prev.id is not null then if r.breaking_change and r.major_version<=prev.major_version then raise exception 'SCHEMA_INCOMPATIBLE:breaking_change_requires_major_version';end if;if not r.breaking_change and r.major_version<prev.major_version then raise exception 'schema_version_regression';end if;if r.major_version=prev.major_version and r.minor_version<=prev.minor_version then raise exception 'schema_minor_version_must_increase';end if;end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.integration_phase','contract_publish',true);update integration.data_contract_versions set status='published',published_by=auth.uid(),published_at=now() where id=r.id returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,case when r.breaking_change then 'schema.breaking_change_published' else 'schema.version_published' end,'data_contract_version',r.id,before_state,jsonb_build_object('contract_key',c.contract_key,'major',r.major_version,'minor',r.minor_version,'breaking',r.breaking_change,'schema_hash',r.schema_hash),target_reason,gen_random_uuid());end if;return r.status;end;$$;
revoke all on function public.publish_data_contract_version(uuid,text) from public,anon;grant execute on function public.publish_data_contract_version(uuid,text) to authenticated;

alter table public.event_subscriptions add column if not exists secret_ref text, add column if not exists filter jsonb not null default '{}'::jsonb, add column if not exists created_by uuid references auth.users(id), add column if not exists subscription_hash text;
grant insert,update on public.event_subscriptions,public.event_definitions to authenticated;
drop policy if exists event_subscription_insert on public.event_subscriptions;create policy event_subscription_insert on public.event_subscriptions for insert to authenticated with check((core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) and created_by=auth.uid() and current_setting('conceptspaces.integration_phase',true)='subscription_create');
drop policy if exists event_subscription_update on public.event_subscriptions;create policy event_subscription_update on public.event_subscriptions for update to authenticated using(core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) with check((core.is_platform_admin() or core.has_org_role(organisation_id,array['super_admin','org_admin'])) and current_setting('conceptspaces.integration_phase',true)='subscription_toggle');
drop policy if exists event_definition_insert on public.event_definitions;create policy event_definition_insert on public.event_definitions for insert to authenticated with check(core.is_platform_admin() and current_setting('conceptspaces.integration_phase',true)='event_register');

create or replace function public.create_event_subscription(target_organisation_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='public','core','audit','extensions','auth','pg_temp' as $$
declare r public.event_subscriptions%rowtype;h text;
begin if auth.uid() is null or not (core.is_platform_admin() or core.has_org_role(target_organisation_id,array['super_admin','org_admin'])) then raise exception 'integration_subscription_authority_required';end if;if nullif(btrim(input_payload->>'subscriber_key'),'') is null or nullif(btrim(input_payload->>'event_pattern'),'') is null or nullif(btrim(input_payload->>'endpoint_ref'),'') is null or nullif(btrim(input_payload->>'secret_ref'),'') is null then raise exception 'subscription_fields_required';end if;h:=encode(extensions.digest(jsonb_build_object('organisation_id',target_organisation_id,'subscriber_key',btrim(input_payload->>'subscriber_key'),'event_pattern',btrim(input_payload->>'event_pattern'),'endpoint_ref',btrim(input_payload->>'endpoint_ref'),'secret_ref',btrim(input_payload->>'secret_ref'),'filter',coalesce(input_payload->'filter','{}'::jsonb),'allowed_criticalities',coalesce(input_payload->'allowed_criticalities','["C0","C1","C2"]'::jsonb))::text,'sha256'),'hex');perform set_config('conceptspaces.integration_phase','subscription_create',true);insert into public.event_subscriptions(organisation_id,subscriber_key,event_pattern,endpoint_ref,enabled,max_attempts,backoff_seconds,allowed_criticalities,secret_ref,filter,created_by,subscription_hash) values(target_organisation_id,btrim(input_payload->>'subscriber_key'),btrim(input_payload->>'event_pattern'),btrim(input_payload->>'endpoint_ref'),true,coalesce(nullif(input_payload->>'max_attempts','')::int,8),coalesce(input_payload->'backoff_seconds','[30,120,300,900,3600]'::jsonb),coalesce(input_payload->'allowed_criticalities','["C0","C1","C2"]'::jsonb),btrim(input_payload->>'secret_ref'),coalesce(input_payload->'filter','{}'::jsonb),auth.uid(),h) returning * into r;perform audit.append_event(target_organisation_id,null,'integration.subscription_created','event_subscription',r.id,null,jsonb_build_object('subscriber_key',r.subscriber_key,'event_pattern',r.event_pattern,'endpoint_ref',r.endpoint_ref,'enabled',r.enabled,'subscription_hash',h),h,gen_random_uuid());return r.id;end;$$;
revoke all on function public.create_event_subscription(uuid,jsonb) from public,anon;grant execute on function public.create_event_subscription(uuid,jsonb) to authenticated;

create or replace function public.set_event_subscription_enabled(target_subscription_id uuid,target_enabled boolean,target_reason text)
returns boolean language plpgsql security invoker set search_path='public','core','audit','auth','pg_temp' as $$
declare r public.event_subscriptions%rowtype;before_state jsonb;
begin select * into r from public.event_subscriptions where id=target_subscription_id for update;if not found then raise exception 'subscription_not_found';end if;if auth.uid() is null or not (core.is_platform_admin() or core.has_org_role(r.organisation_id,array['super_admin','org_admin'])) or nullif(btrim(target_reason),'') is null then raise exception 'subscription_toggle_authority_and_reason_required';end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.integration_phase','subscription_toggle',true);update public.event_subscriptions set enabled=target_enabled,updated_at=now() where id=r.id returning * into r;perform audit.append_event(r.organisation_id,null,case when target_enabled then 'integration.subscription_enabled' else 'integration.subscription_paused' end,'event_subscription',r.id,before_state,jsonb_build_object('enabled',r.enabled,'subscriber_key',r.subscriber_key,'event_pattern',r.event_pattern),target_reason,gen_random_uuid());return r.enabled;end;$$;
revoke all on function public.set_event_subscription_enabled(uuid,boolean,text) from public,anon;grant execute on function public.set_event_subscription_enabled(uuid,boolean,text) to authenticated;

create or replace function public.register_event_definition(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='public','core','audit','auth','pg_temp' as $$
declare r public.event_definitions%rowtype;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'event_type'),'') is null or nullif(btrim(input_payload->>'owner_domain'),'') is null or nullif(btrim(input_payload->>'description'),'') is null then raise exception 'event_definition_fields_required';end if;perform set_config('conceptspaces.integration_phase','event_register',true);insert into public.event_definitions(event_type,latest_version,owner_domain,description,pii_classification,default_criticality,retention_days,replayable,enabled) values(btrim(input_payload->>'event_type'),coalesce(nullif(input_payload->>'latest_version','')::int,1),btrim(input_payload->>'owner_domain'),btrim(input_payload->>'description'),coalesce(nullif(btrim(input_payload->>'pii_classification'),''),'none'),coalesce(nullif(btrim(input_payload->>'default_criticality'),''),'C1'),coalesce(nullif(input_payload->>'retention_days','')::int,2555),coalesce((input_payload->>'replayable')::boolean,true),true) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'integration.event_registered','event_definition',r.id,null,to_jsonb(r),null,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.register_event_definition(jsonb) from public,anon;grant execute on function public.register_event_definition(jsonb) to authenticated;

create or replace function public.list_api_integration_workspace(target_organisation_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='public','integration','core','auth','pg_temp' as $$
begin if auth.uid() is null or not core.is_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;return jsonb_build_object(
'credentials',case when core.is_platform_admin() or core.has_org_role(target_organisation_id,array['super_admin','org_admin']) then coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'name',a.name,'key_prefix',a.key_prefix,'scopes',a.scopes,'project_restrictions',a.project_restrictions,'allowed_ip_cidrs',a.allowed_ip_cidrs,'expires_at',a.expires_at,'revoked_at',a.revoked_at,'created_at',a.created_at,'last_used_at',a.last_used_at,'rate_limit_per_minute',a.rate_limit_per_minute,'rotated_from_id',a.rotated_from_id) order by a.created_at desc) from public.api_credentials a where a.organisation_id=target_organisation_id),'[]'::jsonb) else '[]'::jsonb end,
'instances',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'provider_key',i.provider_key,'environment',i.environment,'status',i.status,'enabled',i.enabled,'verified_at',i.verified_at,'last_health_check_at',i.last_health_check_at,'last_health_status',i.last_health_status,'circuit_open_until',i.circuit_open_until,'failure_threshold',i.failure_threshold) order by i.provider_key,i.environment) from integration.instances i where i.organisation_id=target_organisation_id),'[]'::jsonb),
'subscriptions',case when core.is_platform_admin() or core.has_org_role(target_organisation_id,array['super_admin','org_admin']) then coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'subscriber_key',s.subscriber_key,'event_pattern',s.event_pattern,'endpoint_ref',s.endpoint_ref,'enabled',s.enabled,'max_attempts',s.max_attempts,'allowed_criticalities',s.allowed_criticalities,'filter',s.filter,'subscription_hash',s.subscription_hash,'created_at',s.created_at) order by s.created_at desc) from public.event_subscriptions s where s.organisation_id=target_organisation_id),'[]'::jsonb) else '[]'::jsonb end,
'deliveries',case when core.is_platform_admin() then coalesce((select jsonb_agg(to_jsonb(d) order by d.created_at desc) from public.event_deliveries d join public.event_subscriptions s on s.id=d.subscription_id where s.organisation_id=target_organisation_id limit 100),'[]'::jsonb) else '[]'::jsonb end,
'webhooks',case when core.is_platform_admin() then coalesce((select jsonb_agg(to_jsonb(w) order by w.received_at desc) from integration.webhook_events w where w.organisation_id=target_organisation_id limit 100),'[]'::jsonb) else '[]'::jsonb end,
'event_definitions',case when core.is_platform_admin() then coalesce((select jsonb_agg(to_jsonb(e) order by e.event_type) from public.event_definitions e),'[]'::jsonb) else '[]'::jsonb end,
'data_contracts',case when core.is_platform_admin() then coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'contract_key',c.contract_key,'producer',c.producer,'description',c.description,'status',c.status,'versions',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'major_version',v.major_version,'minor_version',v.minor_version,'compatibility_mode',v.compatibility_mode,'breaking_change',v.breaking_change,'status',v.status,'schema_hash',v.schema_hash,'created_by',v.created_by,'published_at',v.published_at) order by v.major_version desc,v.minor_version desc) from integration.data_contract_versions v where v.contract_id=c.id),'[]'::jsonb)) order by c.contract_key) from integration.data_contracts c),'[]'::jsonb) else '[]'::jsonb end);
end;$$;
revoke all on function public.list_api_integration_workspace(uuid) from public,anon;grant execute on function public.list_api_integration_workspace(uuid) to authenticated;

commit;
