begin;

-- Effective-dated tax governance
alter table finance.tax_rules
 add column if not exists created_by uuid references auth.users(id) on delete set null,
 add column if not exists updated_at timestamptz not null default now(),
 add column if not exists rule_hash text,
 add column if not exists supersedes_id uuid references finance.tax_rules(id) on delete set null;

grant insert,update on finance.tax_rules to authenticated;
drop policy if exists tax_rules_governed_insert on finance.tax_rules;
create policy tax_rules_governed_insert on finance.tax_rules for insert to authenticated
with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.tax_phase',true)='draft');
drop policy if exists tax_rules_governed_update on finance.tax_rules;
create policy tax_rules_governed_update on finance.tax_rules for update to authenticated
using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.tax_phase',true) in ('review','publish','retire'));

create or replace function finance.guard_published_tax_rule()
returns trigger language plpgsql security definer set search_path='finance','pg_temp' as $$
begin
 if old.publication_status='published' and current_setting('conceptspaces.tax_phase',true)<>'retire' then raise exception 'PUBLISHED_TAX_RULE_IMMUTABLE';end if;
 if old.publication_status='published' and (new.rule_set is distinct from old.rule_set or new.code is distinct from old.code or new.jurisdiction is distinct from old.jurisdiction or new.effective_from is distinct from old.effective_from or new.effective_until is distinct from old.effective_until or new.priority is distinct from old.priority or new.conditions is distinct from old.conditions or new.outcome is distinct from old.outcome or new.source_reference is distinct from old.source_reference or new.rule_hash is distinct from old.rule_hash) then raise exception 'PUBLISHED_TAX_RULE_CONTENT_IMMUTABLE';end if;
 return new;
end;$$;
revoke all on function finance.guard_published_tax_rule() from public,anon,authenticated;
drop trigger if exists trg_guard_published_tax_rule on finance.tax_rules;
create trigger trg_guard_published_tax_rule before update on finance.tax_rules for each row execute function finance.guard_published_tax_rule();

create or replace function public.create_tax_rule(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='finance','core','audit','extensions','auth','pg_temp' as $$
declare r finance.tax_rules%rowtype;prior finance.tax_rules%rowtype;h text;ef date:=nullif(input_payload->>'effective_from','')::date;eu date:=nullif(input_payload->>'effective_until','')::date;
begin
 if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;
 if nullif(btrim(input_payload->>'rule_set'),'') is null or nullif(btrim(input_payload->>'code'),'') is null or ef is null or nullif(btrim(input_payload->>'source_reference'),'') is null then raise exception 'tax_rule_core_fields_required';end if;
 if eu is not null and eu<ef then raise exception 'tax_rule_effective_range_invalid';end if;
 if coalesce(input_payload->'outcome','{}'::jsonb)='{}'::jsonb then raise exception 'tax_rule_outcome_required';end if;
 select * into prior from finance.tax_rules where rule_set=btrim(input_payload->>'rule_set') and code::text=btrim(input_payload->>'code') and publication_status='published' order by effective_from desc limit 1;
 h:=encode(extensions.digest(jsonb_build_object('rule_set',btrim(input_payload->>'rule_set'),'code',btrim(input_payload->>'code'),'jurisdiction',coalesce(nullif(btrim(input_payload->>'jurisdiction'),''),'IN'),'effective_from',ef,'effective_until',eu,'priority',coalesce(nullif(input_payload->>'priority','')::int,100),'conditions',coalesce(input_payload->'conditions','{}'::jsonb),'outcome',input_payload->'outcome','source_reference',btrim(input_payload->>'source_reference'),'supersedes_id',prior.id)::text,'sha256'),'hex');
 perform set_config('conceptspaces.tax_phase','draft',true);
 insert into finance.tax_rules(rule_set,code,jurisdiction,effective_from,effective_until,priority,conditions,outcome,source_reference,publication_status,created_by,rule_hash,supersedes_id)
 values(btrim(input_payload->>'rule_set'),btrim(input_payload->>'code'),coalesce(nullif(btrim(input_payload->>'jurisdiction'),''),'IN'),ef,eu,coalesce(nullif(input_payload->>'priority','')::int,100),coalesce(input_payload->'conditions','{}'::jsonb),input_payload->'outcome',btrim(input_payload->>'source_reference'),'draft',auth.uid(),h,prior.id) returning * into r;
 perform audit.append_event((select organisation_id from core.memberships where user_id=auth.uid() and status='active' limit 1),null,'tax.rule_drafted','tax_rule',r.id,null,to_jsonb(r),h,gen_random_uuid());return r.id;
end;$$;
revoke all on function public.create_tax_rule(jsonb) from public,anon;grant execute on function public.create_tax_rule(jsonb) to authenticated;

create or replace function public.transition_tax_rule(target_rule_id uuid,target_status text,target_reason text)
returns text language plpgsql security invoker set search_path='finance','core','audit','auth','pg_temp' as $$
declare r finance.tax_rules%rowtype;s text:=lower(btrim(target_status));before_state jsonb;org_id uuid;
begin
 select * into r from finance.tax_rules where id=target_rule_id for update;if not found then raise exception 'tax_rule_not_found';end if;
 if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;
 if nullif(btrim(target_reason),'') is null then raise exception 'tax_rule_transition_reason_required';end if;
 if (r.publication_status='draft' and s<>'review') or (r.publication_status='review' and s not in ('draft','published')) or (r.publication_status='published' and s<>'retired') then raise exception 'tax_rule_transition_invalid';end if;
 if s='published' and r.created_by=auth.uid() then raise exception 'maker_cannot_publish_own_tax_rule';end if;
 if s='published' and (nullif(btrim(r.source_reference),'') is null or r.outcome='{}'::jsonb or r.rule_hash is null) then raise exception 'tax_rule_publication_evidence_incomplete';end if;
 before_state:=to_jsonb(r);perform set_config('conceptspaces.tax_phase',case s when 'review' then 'review' when 'published' then 'publish' when 'retired' then 'retire' else 'review' end,true);
 update finance.tax_rules set publication_status=s,approved_by=case when s='published' then auth.uid() else approved_by end,approved_at=case when s='published' then now() else approved_at end,updated_at=now() where id=r.id returning * into r;
 if s='published' and r.supersedes_id is not null then perform set_config('conceptspaces.tax_phase','retire',true);update finance.tax_rules set publication_status='retired',effective_until=coalesce(effective_until,r.effective_from-1),updated_at=now() where id=r.supersedes_id and publication_status='published';end if;
 select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'tax.rule_'||s,'tax_rule',r.id,before_state,to_jsonb(r),target_reason,gen_random_uuid());end if;return r.publication_status;
end;$$;
revoke all on function public.transition_tax_rule(uuid,text,text) from public,anon;grant execute on function public.transition_tax_rule(uuid,text,text) to authenticated;

create or replace function public.list_tax_rule_workspace()
returns jsonb language plpgsql stable security invoker set search_path='finance','core','auth','pg_temp' as $$
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;return jsonb_build_object('rules',coalesce((select jsonb_agg(to_jsonb(r) order by r.rule_set,r.code,r.effective_from desc) from finance.tax_rules r),'[]'::jsonb),'determinations',coalesce((select jsonb_agg(to_jsonb(d) order by d.determined_at desc) from finance.tax_determinations d where core.is_internal_org_member(d.organisation_id) limit 100),'[]'::jsonb));end;$$;
revoke all on function public.list_tax_rule_workspace() from public,anon;grant execute on function public.list_tax_rule_workspace() to authenticated;

-- AI governance: keep definitions/history, never seed invented agents/models.
alter table ai.agent_definitions add column if not exists created_by uuid references auth.users(id) on delete set null, add column if not exists updated_by uuid references auth.users(id) on delete set null, add column if not exists updated_at timestamptz not null default now(), add column if not exists definition_hash text;
alter table ai.model_profiles add column if not exists created_by uuid references auth.users(id) on delete set null, add column if not exists approved_by uuid references auth.users(id) on delete set null, add column if not exists approved_at timestamptz, add column if not exists profile_hash text;
alter table ai.prompt_versions add column if not exists prompt_hash text;
grant insert,update on ai.agent_definitions,ai.model_profiles,ai.prompt_versions,ai.evaluation_cases,ai.evaluation_results to authenticated;

drop policy if exists ai_agent_insert on ai.agent_definitions;create policy ai_agent_insert on ai.agent_definitions for insert to authenticated with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.ai_phase',true)='agent_create');
drop policy if exists ai_agent_update on ai.agent_definitions;create policy ai_agent_update on ai.agent_definitions for update to authenticated using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.ai_phase',true)='agent_state');
drop policy if exists ai_model_insert on ai.model_profiles;create policy ai_model_insert on ai.model_profiles for insert to authenticated with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.ai_phase',true)='model_create');
drop policy if exists ai_model_update on ai.model_profiles;create policy ai_model_update on ai.model_profiles for update to authenticated using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.ai_phase',true)='model_state');
drop policy if exists ai_prompt_insert on ai.prompt_versions;create policy ai_prompt_insert on ai.prompt_versions for insert to authenticated with check(core.is_platform_admin() and created_by=auth.uid() and current_setting('conceptspaces.ai_phase',true)='prompt_create');
drop policy if exists ai_prompt_update on ai.prompt_versions;create policy ai_prompt_update on ai.prompt_versions for update to authenticated using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.ai_phase',true)='prompt_state');
drop policy if exists ai_eval_case_insert on ai.evaluation_cases;create policy ai_eval_case_insert on ai.evaluation_cases for insert to authenticated with check(core.is_platform_admin() and current_setting('conceptspaces.ai_phase',true)='eval_case');
drop policy if exists ai_eval_result_insert on ai.evaluation_results;create policy ai_eval_result_insert on ai.evaluation_results for insert to authenticated with check(core.is_platform_admin() and current_setting('conceptspaces.ai_phase',true)='eval_result');

create or replace function public.create_ai_agent(input_payload jsonb)
returns text language plpgsql security invoker set search_path='ai','core','audit','extensions','auth','pg_temp' as $$
declare r ai.agent_definitions%rowtype;crit text:=upper(btrim(input_payload->>'max_criticality'));aut text:=lower(btrim(input_payload->>'allowed_autonomy'));h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'code'),'') is null or nullif(btrim(input_payload->>'name'),'') is null or nullif(btrim(input_payload->>'purpose'),'') is null or crit not in ('C0','C1','C2','C3','C4') or aut not in ('human_only','ai_advisory','ai_draft','execute_after_approval','bounded_autonomous') then raise exception 'ai_agent_fields_invalid';end if;if crit in ('C3','C4') and aut='bounded_autonomous' then raise exception 'C3_C4_AUTONOMY_FORBIDDEN';end if;h:=encode(extensions.digest(jsonb_build_object('code',btrim(input_payload->>'code'),'name',btrim(input_payload->>'name'),'purpose',btrim(input_payload->>'purpose'),'max_criticality',crit,'allowed_autonomy',aut,'allowed_tools',coalesce(input_payload->'allowed_tools','[]'::jsonb),'prohibited_actions',coalesce(input_payload->'prohibited_actions','[]'::jsonb),'no_hallucination_zones',coalesce(input_payload->'no_hallucination_zones','[]'::jsonb),'requires_grounding',coalesce((input_payload->>'requires_grounding')::boolean,true),'requires_human_approval_for',coalesce(input_payload->'requires_human_approval_for','[]'::jsonb))::text,'sha256'),'hex');perform set_config('conceptspaces.ai_phase','agent_create',true);insert into ai.agent_definitions(code,name,purpose,max_criticality,allowed_autonomy,allowed_tools,prohibited_actions,no_hallucination_zones,requires_grounding,requires_human_approval_for,enabled,created_by,updated_by,definition_hash) values(btrim(input_payload->>'code'),btrim(input_payload->>'name'),btrim(input_payload->>'purpose'),crit,aut,coalesce(input_payload->'allowed_tools','[]'::jsonb),coalesce(input_payload->'prohibited_actions','[]'::jsonb),coalesce(input_payload->'no_hallucination_zones','[]'::jsonb),coalesce((input_payload->>'requires_grounding')::boolean,true),coalesce(input_payload->'requires_human_approval_for','[]'::jsonb),false,auth.uid(),auth.uid(),h) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.agent_created','ai_agent',null,null,jsonb_build_object('code',r.code::text,'definition_hash',h,'enabled',false),h,gen_random_uuid());end if;return r.code::text;end;$$;
revoke all on function public.create_ai_agent(jsonb) from public,anon;grant execute on function public.create_ai_agent(jsonb) to authenticated;

create or replace function public.create_ai_model_profile(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='ai','core','audit','extensions','auth','pg_temp' as $$
declare r ai.model_profiles%rowtype;crit text:=upper(btrim(input_payload->>'max_criticality'));h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'provider'),'') is null or nullif(btrim(input_payload->>'model'),'') is null or nullif(btrim(input_payload->>'purpose'),'') is null or crit not in ('C0','C1','C2','C3','C4') then raise exception 'ai_model_fields_invalid';end if;if nullif(btrim(input_payload->>'secret_ref'),'') is null then raise exception 'ai_model_secret_reference_required';end if;h:=encode(extensions.digest(jsonb_build_object('provider',btrim(input_payload->>'provider'),'model',btrim(input_payload->>'model'),'purpose',btrim(input_payload->>'purpose'),'max_criticality',crit,'structured',coalesce((input_payload->>'supports_structured_output')::boolean,false),'vision',coalesce((input_payload->>'supports_vision')::boolean,false),'tools',coalesce((input_payload->>'supports_tool_use')::boolean,false),'residency',input_payload->>'data_residency','evaluation_threshold',nullif(input_payload->>'evaluation_threshold','')::numeric,'secret_ref',btrim(input_payload->>'secret_ref'))::text,'sha256'),'hex');perform set_config('conceptspaces.ai_phase','model_create',true);insert into ai.model_profiles(provider,model,purpose,enabled,max_criticality,supports_structured_output,supports_vision,supports_tool_use,data_residency,cost_policy,latency_target_ms,evaluation_threshold,secret_ref,created_by,profile_hash) values(btrim(input_payload->>'provider'),btrim(input_payload->>'model'),btrim(input_payload->>'purpose'),false,crit,coalesce((input_payload->>'supports_structured_output')::boolean,false),coalesce((input_payload->>'supports_vision')::boolean,false),coalesce((input_payload->>'supports_tool_use')::boolean,false),nullif(btrim(input_payload->>'data_residency'),''),coalesce(input_payload->'cost_policy','{}'::jsonb),nullif(input_payload->>'latency_target_ms','')::int,nullif(input_payload->>'evaluation_threshold','')::numeric,btrim(input_payload->>'secret_ref'),auth.uid(),h) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.model_profile_created','ai_model_profile',r.id,null,jsonb_build_object('provider',r.provider,'model',r.model,'profile_hash',h,'enabled',false),h,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.create_ai_model_profile(jsonb) from public,anon;grant execute on function public.create_ai_model_profile(jsonb) to authenticated;

create or replace function public.create_ai_prompt_version(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='ai','core','audit','extensions','auth','pg_temp' as $$
declare r ai.prompt_versions%rowtype;v int;h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'agent_code'),'') is null or nullif(btrim(input_payload->>'template'),'') is null then raise exception 'ai_prompt_fields_invalid';end if;if not exists(select 1 from ai.agent_definitions a where a.code::text=btrim(input_payload->>'agent_code')) then raise exception 'ai_agent_not_found';end if;select coalesce(max(version),0)+1 into v from ai.prompt_versions where agent_code::text=btrim(input_payload->>'agent_code');h:=encode(extensions.digest(jsonb_build_object('agent_code',btrim(input_payload->>'agent_code'),'version',v,'template',input_payload->>'template','output_schema_ref',input_payload->>'output_schema_ref','system_policy_ref',input_payload->>'system_policy_ref')::text,'sha256'),'hex');perform set_config('conceptspaces.ai_phase','prompt_create',true);insert into ai.prompt_versions(agent_code,version,template,output_schema_ref,system_policy_ref,status,created_by,prompt_hash) values(btrim(input_payload->>'agent_code'),v,input_payload->>'template',nullif(btrim(input_payload->>'output_schema_ref'),''),nullif(btrim(input_payload->>'system_policy_ref'),''),'draft',auth.uid(),h) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.prompt_drafted','ai_prompt_version',r.id,null,jsonb_build_object('agent_code',r.agent_code::text,'version',r.version,'prompt_hash',h),h,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.create_ai_prompt_version(jsonb) from public,anon;grant execute on function public.create_ai_prompt_version(jsonb) to authenticated;

create or replace function public.create_ai_evaluation_case(input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='ai','core','audit','auth','pg_temp' as $$
declare r ai.evaluation_cases%rowtype;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(input_payload->>'suite_code'),'') is null or nullif(btrim(input_payload->>'name'),'') is null or upper(btrim(input_payload->>'criticality')) not in ('C0','C1','C2','C3','C4') then raise exception 'evaluation_case_fields_invalid';end if;perform set_config('conceptspaces.ai_phase','eval_case',true);insert into ai.evaluation_cases(suite_code,name,input,expected_assertions,criticality,active) values(btrim(input_payload->>'suite_code'),btrim(input_payload->>'name'),coalesce(input_payload->'input','{}'::jsonb),coalesce(input_payload->'expected_assertions','[]'::jsonb),upper(btrim(input_payload->>'criticality')),true) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.evaluation_case_created','ai_evaluation_case',r.id,null,to_jsonb(r),null,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.create_ai_evaluation_case(jsonb) from public,anon;grant execute on function public.create_ai_evaluation_case(jsonb) to authenticated;

create or replace function public.record_ai_evaluation_result(target_case_id uuid,target_model_profile_id uuid,target_prompt_version_id uuid,target_score numeric,target_passed boolean,target_findings jsonb default '[]'::jsonb)
returns uuid language plpgsql security invoker set search_path='ai','core','audit','auth','pg_temp' as $$
declare r ai.evaluation_results%rowtype;org_id uuid;c ai.evaluation_cases%rowtype;p ai.prompt_versions%rowtype;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if target_score<0 or target_score>1 then raise exception 'evaluation_score_out_of_range';end if;select * into c from ai.evaluation_cases where id=target_case_id and active;if not found then raise exception 'active_evaluation_case_required';end if;select * into p from ai.prompt_versions where id=target_prompt_version_id;if not found or p.agent_code::text<>c.suite_code::text then raise exception 'evaluation_case_prompt_suite_mismatch';end if;if not exists(select 1 from ai.model_profiles m where m.id=target_model_profile_id) then raise exception 'model_profile_not_found';end if;perform set_config('conceptspaces.ai_phase','eval_result',true);insert into ai.evaluation_results(case_id,model_profile_id,prompt_version_id,score,passed,findings) values(target_case_id,target_model_profile_id,target_prompt_version_id,target_score,target_passed,coalesce(target_findings,'[]'::jsonb)) returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.evaluation_recorded','ai_evaluation_result',r.id,null,to_jsonb(r),null,gen_random_uuid());end if;return r.id;end;$$;
revoke all on function public.record_ai_evaluation_result(uuid,uuid,uuid,numeric,boolean,jsonb) from public,anon;grant execute on function public.record_ai_evaluation_result(uuid,uuid,uuid,numeric,boolean,jsonb) to authenticated;

create or replace function public.activate_ai_prompt_version(target_prompt_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='ai','core','audit','auth','pg_temp' as $$
declare r ai.prompt_versions%rowtype;before_state jsonb;org_id uuid;case_count int;pass_count int;
begin select * into r from ai.prompt_versions where id=target_prompt_id for update;if not found then raise exception 'prompt_version_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or r.created_by=auth.uid() then raise exception 'independent_prompt_activation_required';end if;if r.status not in ('draft','review') or nullif(btrim(target_reason),'') is null then raise exception 'prompt_not_activatable';end if;select count(*) into case_count from ai.evaluation_cases c where c.active and c.suite_code::text=r.agent_code::text;select count(distinct er.case_id) into pass_count from ai.evaluation_results er join ai.evaluation_cases c on c.id=er.case_id where c.active and c.suite_code::text=r.agent_code::text and er.prompt_version_id=r.id and er.passed;if case_count=0 or pass_count<case_count then raise exception 'AI_EVALUATION_GATE_FAILED';end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.ai_phase','prompt_state',true);update ai.prompt_versions set status='retired' where agent_code=r.agent_code and status='active';update ai.prompt_versions set status='active',approved_by=auth.uid(),approved_at=now() where id=r.id returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.prompt_activated','ai_prompt_version',r.id,before_state,jsonb_build_object('agent_code',r.agent_code::text,'version',r.version,'prompt_hash',r.prompt_hash,'status',r.status),target_reason,gen_random_uuid());end if;return r.status;end;$$;
revoke all on function public.activate_ai_prompt_version(uuid,text) from public,anon;grant execute on function public.activate_ai_prompt_version(uuid,text) to authenticated;

create or replace function public.set_ai_model_enabled(target_model_id uuid,target_enabled boolean,target_reason text)
returns boolean language plpgsql security invoker set search_path='ai','core','audit','auth','pg_temp' as $$
declare r ai.model_profiles%rowtype;before_state jsonb;threshold numeric;org_id uuid;
begin select * into r from ai.model_profiles where id=target_model_id for update;if not found then raise exception 'model_profile_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or nullif(btrim(target_reason),'') is null then raise exception 'model_state_authority_and_reason_required';end if;if target_enabled then threshold:=coalesce(r.evaluation_threshold,0);if not exists(select 1 from ai.evaluation_results e where e.model_profile_id=r.id and e.passed and e.score>=threshold) then raise exception 'AI_MODEL_EVALUATION_GATE_FAILED';end if;end if;before_state:=to_jsonb(r);perform set_config('conceptspaces.ai_phase','model_state',true);update ai.model_profiles set enabled=target_enabled,approved_by=case when target_enabled then auth.uid() else approved_by end,approved_at=case when target_enabled then now() else approved_at end,updated_at=now() where id=r.id returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,case when target_enabled then 'ai.model_enabled' else 'ai.model_disabled' end,'ai_model_profile',r.id,before_state,jsonb_build_object('enabled',r.enabled,'profile_hash',r.profile_hash),target_reason,gen_random_uuid());end if;return r.enabled;end;$$;
revoke all on function public.set_ai_model_enabled(uuid,boolean,text) from public,anon;grant execute on function public.set_ai_model_enabled(uuid,boolean,text) to authenticated;

create or replace function public.set_ai_agent_state(target_agent_code text,target_enabled boolean,target_autonomy text,target_reason text)
returns jsonb language plpgsql security invoker set search_path='ai','core','audit','extensions','auth','pg_temp' as $$
declare r ai.agent_definitions%rowtype;before_state jsonb;aut text:=lower(btrim(target_autonomy));h text;org_id uuid;
begin select * into r from ai.agent_definitions where code::text=btrim(target_agent_code) for update;if not found then raise exception 'ai_agent_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or nullif(btrim(target_reason),'') is null then raise exception 'ai_agent_state_authority_and_reason_required';end if;if aut not in ('human_only','ai_advisory','ai_draft','execute_after_approval','bounded_autonomous') then raise exception 'ai_agent_autonomy_invalid';end if;if r.max_criticality in ('C3','C4') and aut='bounded_autonomous' then raise exception 'C3_C4_AUTONOMY_FORBIDDEN';end if;if target_enabled and r.max_criticality in ('C3','C4') and not r.requires_grounding then raise exception 'C3_C4_GROUNDING_REQUIRED';end if;if target_enabled and not exists(select 1 from ai.prompt_versions p where p.agent_code=r.code and p.status='active') then raise exception 'ACTIVE_EVALUATED_PROMPT_REQUIRED';end if;if target_enabled and not exists(select 1 from ai.model_profiles m where m.enabled and substring(m.max_criticality from 2)::int>=substring(r.max_criticality from 2)::int) then raise exception 'ELIGIBLE_ENABLED_MODEL_REQUIRED';end if;before_state:=to_jsonb(r);h:=encode(extensions.digest(jsonb_build_object('prior_hash',r.definition_hash,'code',r.code::text,'enabled',target_enabled,'autonomy',aut,'max_criticality',r.max_criticality,'requires_grounding',r.requires_grounding)::text,'sha256'),'hex');perform set_config('conceptspaces.ai_phase','agent_state',true);update ai.agent_definitions set enabled=target_enabled,allowed_autonomy=aut,updated_by=auth.uid(),updated_at=now(),definition_hash=h where code=r.code returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,'ai.agent_state_changed','ai_agent',null,before_state,jsonb_build_object('code',r.code::text,'enabled',r.enabled,'autonomy',r.allowed_autonomy,'definition_hash',h),target_reason,gen_random_uuid());end if;return jsonb_build_object('code',r.code::text,'enabled',r.enabled,'allowed_autonomy',r.allowed_autonomy,'definition_hash',h);end;$$;
revoke all on function public.set_ai_agent_state(text,boolean,text,text) from public,anon;grant execute on function public.set_ai_agent_state(text,boolean,text,text) to authenticated;

create or replace function public.list_ai_control_workspace()
returns jsonb language plpgsql stable security invoker set search_path='ai','core','auth','pg_temp' as $$
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;return jsonb_build_object('agents',coalesce((select jsonb_agg(to_jsonb(a) order by a.code) from ai.agent_definitions a),'[]'::jsonb),'models',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'provider',m.provider,'model',m.model,'purpose',m.purpose,'enabled',m.enabled,'max_criticality',m.max_criticality,'supports_structured_output',m.supports_structured_output,'supports_vision',m.supports_vision,'supports_tool_use',m.supports_tool_use,'data_residency',m.data_residency,'latency_target_ms',m.latency_target_ms,'evaluation_threshold',m.evaluation_threshold,'created_at',m.created_at,'profile_hash',m.profile_hash) order by m.provider,m.model) from ai.model_profiles m),'[]'::jsonb),'prompts',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'agent_code',p.agent_code::text,'version',p.version,'status',p.status,'output_schema_ref',p.output_schema_ref,'system_policy_ref',p.system_policy_ref,'created_by',p.created_by,'approved_by',p.approved_by,'created_at',p.created_at,'approved_at',p.approved_at,'prompt_hash',p.prompt_hash) order by p.agent_code,p.version desc) from ai.prompt_versions p),'[]'::jsonb),'evaluation_cases',coalesce((select jsonb_agg(to_jsonb(c) order by c.suite_code,c.name) from ai.evaluation_cases c),'[]'::jsonb),'evaluation_results',coalesce((select jsonb_agg(to_jsonb(r) order by r.run_at desc) from ai.evaluation_results r limit 200),'[]'::jsonb),'learning_candidates',coalesce((select jsonb_agg(to_jsonb(l) order by l.updated_at desc) from ai.learning_candidates l limit 100),'[]'::jsonb));end;$$;
revoke all on function public.list_ai_control_workspace() from public,anon;grant execute on function public.list_ai_control_workspace() to authenticated;

-- Command Centre: derived every call from source domains, never stores dashboard facts.
create or replace function public.list_command_centre_workspace(target_organisation_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='project','coordination','governance','operations','core','auth','pg_temp' as $$
begin
 if auth.uid() is null or not core.is_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;
 return jsonb_build_object(
 'projects',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'code',p.code::text,'name',p.name,'typology',p.typology,'stage',p.stage,'criticality',p.criticality,'status',p.status,'truth_issues',(select count(*) from project.truth_records t where t.project_id=p.id and t.status not in ('verified','superseded') and t.criticality in ('C2','C3','C4')),'pending_approvals',(select count(*) from coordination.approval_requests a where a.project_id=p.id and a.decision='pending'),'blocked_releases',(select count(*) from governance.release_safety_cases r where r.project_id=p.id and r.state='blocked'),'critical_risks',(select count(*) from operations.risks x where x.project_id=p.id and x.status<>'closed' and x.inherent_level in ('high','critical'))) order by p.updated_at desc) from project.projects p where p.organisation_id=target_organisation_id and project.can_access_project(p.id)),'[]'::jsonb),
 'summary',jsonb_build_object('active_projects',(select count(*) from project.projects p where p.organisation_id=target_organisation_id and p.status not in ('closed','archived') and project.can_access_project(p.id)),'truth_issues',(select count(*) from project.truth_records t join project.projects p on p.id=t.project_id where p.organisation_id=target_organisation_id and project.can_access_project(p.id) and t.status not in ('verified','superseded') and t.criticality in ('C2','C3','C4')),'pending_decisions',(select count(*) from coordination.approval_requests a join project.projects p on p.id=a.project_id where p.organisation_id=target_organisation_id and project.can_access_project(p.id) and a.decision='pending'),'blocked_release_gates',(select count(*) from governance.release_safety_cases r join project.projects p on p.id=r.project_id where p.organisation_id=target_organisation_id and project.can_access_project(p.id) and r.state='blocked'),'critical_exceptions',(select count(*) from operations.risks x join project.projects p on p.id=x.project_id where p.organisation_id=target_organisation_id and project.can_access_project(p.id) and x.status<>'closed' and x.inherent_level='critical')),
 'recent_decisions',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'project_id',a.project_id,'resource_type',a.resource_type,'criticality',a.criticality,'decision',a.decision,'requested_at',a.requested_at,'requested_resource_hash',a.requested_resource_hash) order by a.requested_at desc) from coordination.approval_requests a join project.projects p on p.id=a.project_id where p.organisation_id=target_organisation_id and project.can_access_project(p.id) limit 20),'[]'::jsonb)
 );
end;$$;
revoke all on function public.list_command_centre_workspace(uuid) from public,anon;grant execute on function public.list_command_centre_workspace(uuid) to authenticated;

commit;
