begin;

create or replace function public.propose_mep_route(target_project_id uuid,input_payload jsonb)
returns jsonb language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare s engineering.mep_systems%rowtype;m cde.models%rowtype;calc engineering.calculation_runs%rowtype;r engineering.mep_routes%rowtype;blocked jsonb:=coalesce(input_payload->'blocked_zone_intersections','[]'::jsonb);fails jsonb:=coalesce(input_payload->'constraint_failures','[]'::jsonb);reasons jsonb:='[]'::jsonb;route_ref text:=nullif(btrim(input_payload->>'route_geometry_ref'),'');calc_id uuid:=nullif(input_payload->>'calculation_run_id','')::uuid;h text;st text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if jsonb_typeof(blocked)<>'array' or jsonb_typeof(fails)<>'array' then raise exception 'mep_route_constraints_must_be_arrays';end if;
 select * into s from engineering.mep_systems where id=nullif(input_payload->>'system_id','')::uuid and project_id=target_project_id;if not found then raise exception 'mep_system_required';end if;
 select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;
 if calc_id is not null then select * into calc from engineering.calculation_runs where id=calc_id and project_id=target_project_id and status='completed';if not found or lower(calc.discipline) not in (s.discipline,'mep','mepf','multidiscipline') then raise exception 'matching_route_calculation_required';end if;end if;
 if nullif(btrim(input_payload->>'route_code'),'') is null then raise exception 'route_code_required';end if;
 if jsonb_array_length(blocked)>0 then reasons:=reasons||jsonb_build_array(jsonb_build_object('code','BLOCKED_ZONE_INTERSECTION','details',blocked));end if;if jsonb_array_length(fails)>0 then reasons:=reasons||jsonb_build_array(jsonb_build_object('code','ROUTING_CONSTRAINT_FAILED','details',fails));end if;
 st:=case when jsonb_array_length(reasons)>0 then 'infeasible' else 'feasible' end;if st='feasible' and route_ref is null then raise exception 'feasible_route_geometry_reference_required';end if;if st='infeasible' then route_ref:=null;end if;
 h:=encode(extensions.digest(jsonb_build_object('system_id',s.id,'source_model_hash',m.checksum,'route_code',btrim(input_payload->>'route_code'),'route_geometry_ref',route_ref,'blocked_zone_intersections',blocked,'constraint_failures',fails,'infeasible_reasons',reasons,'calculation_run_id',calc_id,'calculation_output_hash',calc.output_hash)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','route',true);
 insert into engineering.mep_routes(project_id,system_id,source_model_id,source_model_hash,calculation_run_id,route_code,route_geometry_ref,blocked_zone_intersections,constraint_failures,infeasible_reasons,status,route_hash,created_by) values(target_project_id,s.id,m.id,m.checksum,calc_id,btrim(input_payload->>'route_code'),route_ref,blocked,fails,reasons,st,h,auth.uid()) returning * into r;
 perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.route.'||st,'mep_route',r.id,null,to_jsonb(r),h,gen_random_uuid());return jsonb_build_object('route_id',r.id,'status',r.status,'route_geometry_ref',r.route_geometry_ref,'infeasible_reasons',r.infeasible_reasons,'route_hash',r.route_hash);
end;$$;

create or replace function public.register_mep_equipment(target_project_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare s engineering.mep_systems%rowtype;m cde.models%rowtype;r engineering.calculation_runs%rowtype;e engineering.mep_equipment%rowtype;req numeric:=nullif(input_payload->>'required_capacity','')::numeric;sel numeric:=nullif(input_payload->>'selected_capacity','')::numeric;tol numeric:=coalesce(nullif(input_payload->>'tolerance_percent','')::numeric,0);rec text;h text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if req is null or req<=0 or sel is null or sel<=0 or tol<0 or tol>100 or nullif(btrim(input_payload->>'capacity_unit'),'') is null or nullif(btrim(input_payload->>'model_object_ref'),'') is null or nullif(btrim(input_payload->>'equipment_code'),'') is null then raise exception 'equipment_model_calculation_capacity_required';end if;
 select * into s from engineering.mep_systems where id=nullif(input_payload->>'system_id','')::uuid and project_id=target_project_id;if not found then raise exception 'mep_system_required';end if;select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;select * into r from engineering.calculation_runs where id=nullif(input_payload->>'calculation_run_id','')::uuid and project_id=target_project_id and status='completed';if not found or lower(r.discipline) not in (s.discipline,'mep','mepf','multidiscipline') then raise exception 'completed_matching_mep_calculation_required';end if;
 if r.result_summary ? 'required_capacity' and abs(coalesce((r.result_summary->>'required_capacity')::numeric,req)-req)>greatest(abs(req)*0.001,0.0001) then raise exception 'equipment_required_capacity_must_match_calculation_result';end if;rec:=case when sel >= req*(1-(tol/100.0)) then 'reconciled' else 'capacity_shortfall' end;
 h:=encode(extensions.digest(jsonb_build_object('system_id',s.id,'source_model_hash',m.checksum,'model_object_ref',btrim(input_payload->>'model_object_ref'),'calculation_run_id',r.id,'calculation_input_hash',r.input_hash,'calculation_output_hash',r.output_hash,'required_capacity',req,'selected_capacity',sel,'capacity_unit',btrim(input_payload->>'capacity_unit'),'tolerance_percent',tol,'schedule_data',coalesce(input_payload->'schedule_data','{}'::jsonb),'reconciliation_status',rec)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','equipment',true);
 insert into engineering.mep_equipment(project_id,system_id,source_model_id,source_model_hash,model_object_ref,calculation_run_id,equipment_code,required_capacity,selected_capacity,capacity_unit,tolerance_percent,schedule_data,reconciliation_status,reconciliation_hash,status,created_by) values(target_project_id,s.id,m.id,m.checksum,btrim(input_payload->>'model_object_ref'),r.id,btrim(input_payload->>'equipment_code'),req,sel,btrim(input_payload->>'capacity_unit'),tol,coalesce(input_payload->'schedule_data','{}'::jsonb),rec,h,'proposed',auth.uid()) returning * into e;perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.equipment.'||rec,'mep_equipment',e.id,null,to_jsonb(e),h,gen_random_uuid());return e.id;
end;$$;

create or replace function public.create_mep_package(target_project_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare m cde.models%rowtype;p engineering.mep_packages%rowtype;v int;disc text:=lower(btrim(input_payload->>'discipline'));crit text:=upper(coalesce(nullif(btrim(input_payload->>'criticality'),''),'C2'));systems jsonb:=coalesce(input_payload->'system_ids','[]'::jsonb);loads jsonb:=coalesce(input_payload->'load_record_ids','[]'::jsonb);routes jsonb:=coalesce(input_payload->'route_ids','[]'::jsonb);equipment jsonb:=coalesce(input_payload->'equipment_ids','[]'::jsonb);h text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if disc not in ('mechanical','electrical','plumbing','fire','elv','bms','vertical_transport') or crit not in ('C0','C1','C2','C3','C4') then raise exception 'mep_package_discipline_criticality_invalid';end if;
 select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;
 if jsonb_typeof(systems)<>'array' or jsonb_typeof(loads)<>'array' or jsonb_typeof(routes)<>'array' or jsonb_typeof(equipment)<>'array' then raise exception 'mep_package_refs_must_be_arrays';end if;
 if jsonb_array_length(systems)=0 or jsonb_array_length(loads)=0 or jsonb_array_length(routes)=0 or jsonb_array_length(equipment)=0 then raise exception 'mep_package_system_load_route_equipment_required';end if;
 if exists(select 1 from jsonb_array_elements_text(systems) x where not exists(select 1 from engineering.mep_systems s where s.id=x.value::uuid and s.project_id=target_project_id and s.discipline=disc)) then raise exception 'mep_package_system_scope_invalid';end if;
 if exists(select 1 from jsonb_array_elements_text(loads) x where not exists(select 1 from engineering.mep_load_records l join engineering.mep_systems s on s.id=l.system_id where l.id=x.value::uuid and l.project_id=target_project_id and l.source_model_id=m.id and l.source_model_hash=m.checksum and l.status='current' and s.discipline=disc)) then raise exception 'mep_package_load_scope_invalid';end if;
 if exists(select 1 from jsonb_array_elements_text(routes) x where not exists(select 1 from engineering.mep_routes r join engineering.mep_systems s on s.id=r.system_id where r.id=x.value::uuid and r.project_id=target_project_id and r.source_model_id=m.id and r.source_model_hash=m.checksum and r.status in ('feasible','approved') and s.discipline=disc)) then raise exception 'mep_package_route_scope_invalid';end if;
 if exists(select 1 from jsonb_array_elements_text(equipment) x where not exists(select 1 from engineering.mep_equipment e join engineering.mep_systems s on s.id=e.system_id where e.id=x.value::uuid and e.project_id=target_project_id and e.source_model_id=m.id and e.source_model_hash=m.checksum and e.status='approved' and e.reconciliation_status='reconciled' and s.discipline=disc)) then raise exception 'mep_package_equipment_scope_invalid';end if;
 select coalesce(max(version),0)+1 into v from engineering.mep_packages where project_id=target_project_id and discipline=disc;h:=encode(extensions.digest(jsonb_build_object('project_id',target_project_id,'discipline',disc,'version',v,'source_model_id',m.id,'source_model_hash',m.checksum,'systems',systems,'loads',loads,'routes',routes,'equipment',equipment,'drawings',coalesce(input_payload->'drawing_refs','[]'::jsonb),'criticality',crit)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','package',true);
 insert into engineering.mep_packages(project_id,discipline,version,source_model_id,source_model_hash,system_ids,load_record_ids,route_ids,equipment_ids,drawing_refs,criticality,status,package_hash,created_by) values(target_project_id,disc,v,m.id,m.checksum,systems,loads,routes,equipment,coalesce(input_payload->'drawing_refs','[]'::jsonb),crit,'draft',h,auth.uid()) returning * into p;perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.package.created','mep_package',p.id,null,to_jsonb(p),h,gen_random_uuid());return p.id;
end;$$;

create or replace function engineering.invalidate_mep_on_model_revision()
returns trigger language plpgsql security definer set search_path='engineering','cde','project','audit','extensions','pg_temp' as $$
declare old_model cde.models%rowtype;loads jsonb;routes jsonb;equipment jsonb;packages jsonb;h text;
begin
 if new.status not in ('approved','issued') or new.supersedes_model_id is null then return new;end if;select * into old_model from cde.models where id=new.supersedes_model_id;if not found then return new;end if;
 select coalesce(jsonb_agg(id),'[]'::jsonb) into loads from engineering.mep_load_records where source_model_id=old_model.id and status='current';select coalesce(jsonb_agg(id),'[]'::jsonb) into routes from engineering.mep_routes where source_model_id=old_model.id and status<>'stale';select coalesce(jsonb_agg(id),'[]'::jsonb) into equipment from engineering.mep_equipment where source_model_id=old_model.id and status<>'stale';select coalesce(jsonb_agg(id),'[]'::jsonb) into packages from engineering.mep_packages where source_model_id=old_model.id;
 if jsonb_array_length(loads)+jsonb_array_length(routes)+jsonb_array_length(equipment)+jsonb_array_length(packages)=0 then return new;end if;
 h:=encode(extensions.digest(jsonb_build_object('prior_model_id',old_model.id,'prior_model_hash',old_model.checksum,'new_model_id',new.id,'new_model_hash',new.checksum,'loads',loads,'routes',routes,'equipment',equipment,'packages',packages)::text,'sha256'),'hex');
 update engineering.mep_load_records set status='stale',invalidated_at=now() where source_model_id=old_model.id and status='current';update engineering.mep_routes set status='stale',updated_at=now() where source_model_id=old_model.id and status<>'stale';update engineering.mep_equipment set status='stale',reconciliation_status='stale',updated_at=now() where source_model_id=old_model.id and status<>'stale';update engineering.mep_packages set status='stale',updated_at=now() where source_model_id=old_model.id and status not in ('issued','stale');
 insert into engineering.mep_invalidations(project_id,prior_model_id,new_model_id,prior_model_hash,new_model_hash,affected_load_ids,affected_route_ids,affected_equipment_ids,affected_package_ids,invalidation_hash) values(new.project_id,old_model.id,new.id,old_model.checksum,new.checksum,loads,routes,equipment,packages,h) on conflict(prior_model_id,new_model_id) do nothing;
 perform audit.append_event((select organisation_id from project.projects where id=new.project_id),new.project_id,'mep.model_revision_invalidated','model',new.id,to_jsonb(old_model),jsonb_build_object('new_model_id',new.id,'new_model_hash',new.checksum,'affected_loads',jsonb_array_length(loads),'affected_routes',jsonb_array_length(routes),'affected_equipment',jsonb_array_length(equipment),'affected_packages',jsonb_array_length(packages),'issued_packages_preserved',true),h,gen_random_uuid());return new;
end;$$;
revoke all on function engineering.invalidate_mep_on_model_revision() from public,anon,authenticated;

commit;