begin;

create table if not exists engineering.mep_load_records(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,system_id uuid not null references engineering.mep_systems(id) on delete cascade,calculation_run_id uuid not null references engineering.calculation_runs(id) on delete restrict,source_model_id uuid not null references cde.models(id) on delete restrict,source_model_hash text not null,status text not null check(status in ('current','stale')) default 'current',load_hash text not null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),invalidated_at timestamptz,unique(system_id,calculation_run_id,source_model_id)
);
create table if not exists engineering.mep_routes(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,system_id uuid not null references engineering.mep_systems(id) on delete cascade,source_model_id uuid not null references cde.models(id) on delete restrict,source_model_hash text not null,calculation_run_id uuid references engineering.calculation_runs(id) on delete restrict,route_code text not null,route_geometry_ref text,blocked_zone_intersections jsonb not null default '[]'::jsonb,constraint_failures jsonb not null default '[]'::jsonb,infeasible_reasons jsonb not null default '[]'::jsonb,status text not null check(status in ('feasible','infeasible','approved','stale')),route_hash text not null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,route_code)
);
create table if not exists engineering.mep_equipment(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,system_id uuid not null references engineering.mep_systems(id) on delete cascade,source_model_id uuid not null references cde.models(id) on delete restrict,source_model_hash text not null,model_object_ref text not null,calculation_run_id uuid not null references engineering.calculation_runs(id) on delete restrict,equipment_code text not null,required_capacity numeric not null,selected_capacity numeric not null,capacity_unit text not null,tolerance_percent numeric not null default 0 check(tolerance_percent>=0 and tolerance_percent<=100),schedule_data jsonb not null default '{}'::jsonb,reconciliation_status text not null check(reconciliation_status in ('reconciled','capacity_shortfall','stale')),reconciliation_hash text not null,status text not null check(status in ('proposed','approved','stale')) default 'proposed',created_by uuid references auth.users(id) on delete set null,approved_by uuid references auth.users(id) on delete set null,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,equipment_code)
);
create table if not exists engineering.mep_packages(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,discipline text not null check(discipline in ('mechanical','electrical','plumbing','fire','elv','bms','vertical_transport')),version int not null,source_model_id uuid not null references cde.models(id) on delete restrict,source_model_hash text not null,system_ids jsonb not null default '[]'::jsonb,load_record_ids jsonb not null default '[]'::jsonb,route_ids jsonb not null default '[]'::jsonb,equipment_ids jsonb not null default '[]'::jsonb,drawing_refs jsonb not null default '[]'::jsonb,criticality text not null check(criticality in ('C0','C1','C2','C3','C4')),status text not null check(status in ('draft','for_review','approved','issued','stale')) default 'draft',package_hash text not null,approval_credential_id uuid references core.professional_credentials(id) on delete restrict,approved_by uuid references auth.users(id) on delete set null,approved_at timestamptz,issued_by uuid references auth.users(id) on delete set null,issued_at timestamptz,issue_hash text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,discipline,version)
);
create table if not exists engineering.mep_invalidations(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,prior_model_id uuid not null references cde.models(id) on delete restrict,new_model_id uuid not null references cde.models(id) on delete restrict,prior_model_hash text not null,new_model_hash text not null,affected_load_ids jsonb not null default '[]'::jsonb,affected_route_ids jsonb not null default '[]'::jsonb,affected_equipment_ids jsonb not null default '[]'::jsonb,affected_package_ids jsonb not null default '[]'::jsonb,invalidation_hash text not null,detected_at timestamptz not null default now(),unique(prior_model_id,new_model_id)
);

alter table engineering.mep_load_records enable row level security;alter table engineering.mep_routes enable row level security;alter table engineering.mep_equipment enable row level security;alter table engineering.mep_packages enable row level security;alter table engineering.mep_invalidations enable row level security;
grant select,insert,update on engineering.mep_load_records,engineering.mep_routes,engineering.mep_equipment,engineering.mep_packages to authenticated;grant select on engineering.mep_invalidations to authenticated;
create policy mep_load_read on engineering.mep_load_records for select to authenticated using(project.can_access_project(project_id));
create policy mep_load_insert on engineering.mep_load_records for insert to authenticated with check(project.can_manage_project(project_id) and created_by=auth.uid() and current_setting('conceptspaces.mep_phase',true)='load');
create policy mep_load_update on engineering.mep_load_records for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.mep_phase',true)='invalidate');
create policy mep_route_read on engineering.mep_routes for select to authenticated using(project.can_access_project(project_id));
create policy mep_route_insert on engineering.mep_routes for insert to authenticated with check(project.can_manage_project(project_id) and created_by=auth.uid() and current_setting('conceptspaces.mep_phase',true)='route');
create policy mep_route_update on engineering.mep_routes for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.mep_phase',true) in ('route_approve','invalidate'));
create policy mep_equipment_read on engineering.mep_equipment for select to authenticated using(project.can_access_project(project_id));
create policy mep_equipment_insert on engineering.mep_equipment for insert to authenticated with check(project.can_manage_project(project_id) and created_by=auth.uid() and current_setting('conceptspaces.mep_phase',true)='equipment');
create policy mep_equipment_update on engineering.mep_equipment for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.mep_phase',true) in ('equipment_approve','invalidate'));
create policy mep_package_read on engineering.mep_packages for select to authenticated using(project.can_access_project(project_id));
create policy mep_package_insert on engineering.mep_packages for insert to authenticated with check(project.can_manage_project(project_id) and created_by=auth.uid() and current_setting('conceptspaces.mep_phase',true)='package');
create policy mep_package_update on engineering.mep_packages for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.mep_phase',true) in ('package_transition','invalidate'));
create policy mep_invalidation_read on engineering.mep_invalidations for select to authenticated using(project.can_access_project(project_id));

create or replace function public.record_mep_load(target_project_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare s engineering.mep_systems%rowtype;r engineering.calculation_runs%rowtype;m cde.models%rowtype;x engineering.mep_load_records%rowtype;h text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;
 select * into s from engineering.mep_systems where id=nullif(input_payload->>'system_id','')::uuid and project_id=target_project_id;if not found then raise exception 'mep_system_required';end if;
 select * into r from engineering.calculation_runs where id=nullif(input_payload->>'calculation_run_id','')::uuid and project_id=target_project_id and status='completed';if not found or lower(r.discipline) not in (s.discipline,'mep','mepf','multidiscipline') then raise exception 'completed_matching_mep_calculation_required';end if;
 select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;
 h:=encode(extensions.digest(jsonb_build_object('system_id',s.id,'calculation_run_id',r.id,'input_hash',r.input_hash,'output_hash',r.output_hash,'source_model_id',m.id,'source_model_hash',m.checksum)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','load',true);
 insert into engineering.mep_load_records(project_id,system_id,calculation_run_id,source_model_id,source_model_hash,status,load_hash,created_by) values(target_project_id,s.id,r.id,m.id,m.checksum,'current',h,auth.uid()) returning * into x;
 perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.load_recorded','mep_load',x.id,null,to_jsonb(x),h,gen_random_uuid());return x.id;
end;$$;
revoke all on function public.record_mep_load(uuid,jsonb) from public,anon;grant execute on function public.record_mep_load(uuid,jsonb) to authenticated;

create or replace function public.propose_mep_route(target_project_id uuid,input_payload jsonb)
returns jsonb language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare s engineering.mep_systems%rowtype;m cde.models%rowtype;r engineering.mep_routes%rowtype;blocked jsonb:=coalesce(input_payload->'blocked_zone_intersections','[]'::jsonb);fails jsonb:=coalesce(input_payload->'constraint_failures','[]'::jsonb);reasons jsonb:='[]'::jsonb;route_ref text:=nullif(btrim(input_payload->>'route_geometry_ref'),'');h text;st text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if jsonb_typeof(blocked)<>'array' or jsonb_typeof(fails)<>'array' then raise exception 'mep_route_constraints_must_be_arrays';end if;
 select * into s from engineering.mep_systems where id=nullif(input_payload->>'system_id','')::uuid and project_id=target_project_id;if not found then raise exception 'mep_system_required';end if;
 select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;
 if nullif(btrim(input_payload->>'route_code'),'') is null then raise exception 'route_code_required';end if;
 if jsonb_array_length(blocked)>0 then reasons:=reasons||jsonb_build_array(jsonb_build_object('code','BLOCKED_ZONE_INTERSECTION','details',blocked));end if;if jsonb_array_length(fails)>0 then reasons:=reasons||jsonb_build_array(jsonb_build_object('code','ROUTING_CONSTRAINT_FAILED','details',fails));end if;
 st:=case when jsonb_array_length(reasons)>0 then 'infeasible' else 'feasible' end;if st='feasible' and route_ref is null then raise exception 'feasible_route_geometry_reference_required';end if;if st='infeasible' then route_ref:=null;end if;
 h:=encode(extensions.digest(jsonb_build_object('system_id',s.id,'source_model_hash',m.checksum,'route_code',btrim(input_payload->>'route_code'),'route_geometry_ref',route_ref,'blocked_zone_intersections',blocked,'constraint_failures',fails,'infeasible_reasons',reasons,'calculation_run_id',nullif(input_payload->>'calculation_run_id','')::uuid)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','route',true);
 insert into engineering.mep_routes(project_id,system_id,source_model_id,source_model_hash,calculation_run_id,route_code,route_geometry_ref,blocked_zone_intersections,constraint_failures,infeasible_reasons,status,route_hash,created_by) values(target_project_id,s.id,m.id,m.checksum,nullif(input_payload->>'calculation_run_id','')::uuid,btrim(input_payload->>'route_code'),route_ref,blocked,fails,reasons,st,h,auth.uid()) returning * into r;
 perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.route.'||st,'mep_route',r.id,null,to_jsonb(r),h,gen_random_uuid());return jsonb_build_object('route_id',r.id,'status',r.status,'route_geometry_ref',r.route_geometry_ref,'infeasible_reasons',r.infeasible_reasons,'route_hash',r.route_hash);
end;$$;
revoke all on function public.propose_mep_route(uuid,jsonb) from public,anon;grant execute on function public.propose_mep_route(uuid,jsonb) to authenticated;

create or replace function public.register_mep_equipment(target_project_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare s engineering.mep_systems%rowtype;m cde.models%rowtype;r engineering.calculation_runs%rowtype;e engineering.mep_equipment%rowtype;req numeric:=nullif(input_payload->>'required_capacity','')::numeric;sel numeric:=nullif(input_payload->>'selected_capacity','')::numeric;tol numeric:=coalesce(nullif(input_payload->>'tolerance_percent','')::numeric,0);rec text;h text;
begin
 if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if req is null or req<=0 or sel is null or sel<=0 or nullif(btrim(input_payload->>'capacity_unit'),'') is null or nullif(btrim(input_payload->>'model_object_ref'),'') is null or nullif(btrim(input_payload->>'equipment_code'),'') is null then raise exception 'equipment_model_calculation_capacity_required';end if;
 select * into s from engineering.mep_systems where id=nullif(input_payload->>'system_id','')::uuid and project_id=target_project_id;if not found then raise exception 'mep_system_required';end if;select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;select * into r from engineering.calculation_runs where id=nullif(input_payload->>'calculation_run_id','')::uuid and project_id=target_project_id and status='completed';if not found then raise exception 'completed_calculation_required';end if;
 if r.result_summary ? 'required_capacity' and abs(coalesce((r.result_summary->>'required_capacity')::numeric,req)-req)>greatest(abs(req)*0.001,0.0001) then raise exception 'equipment_required_capacity_must_match_calculation_result';end if;rec:=case when sel >= req*(1-(tol/100.0)) then 'reconciled' else 'capacity_shortfall' end;
 h:=encode(extensions.digest(jsonb_build_object('system_id',s.id,'source_model_hash',m.checksum,'model_object_ref',btrim(input_payload->>'model_object_ref'),'calculation_run_id',r.id,'calculation_output_hash',r.output_hash,'required_capacity',req,'selected_capacity',sel,'capacity_unit',btrim(input_payload->>'capacity_unit'),'tolerance_percent',tol,'schedule_data',coalesce(input_payload->'schedule_data','{}'::jsonb),'reconciliation_status',rec)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','equipment',true);
 insert into engineering.mep_equipment(project_id,system_id,source_model_id,source_model_hash,model_object_ref,calculation_run_id,equipment_code,required_capacity,selected_capacity,capacity_unit,tolerance_percent,schedule_data,reconciliation_status,reconciliation_hash,status,created_by) values(target_project_id,s.id,m.id,m.checksum,btrim(input_payload->>'model_object_ref'),r.id,btrim(input_payload->>'equipment_code'),req,sel,btrim(input_payload->>'capacity_unit'),tol,coalesce(input_payload->'schedule_data','{}'::jsonb),rec,h,'proposed',auth.uid()) returning * into e;perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.equipment.'||rec,'mep_equipment',e.id,null,to_jsonb(e),h,gen_random_uuid());return e.id;
end;$$;
revoke all on function public.register_mep_equipment(uuid,jsonb) from public,anon;grant execute on function public.register_mep_equipment(uuid,jsonb) to authenticated;

create or replace function public.approve_mep_equipment(target_equipment_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='engineering','project','audit','auth','pg_temp' as $$
declare e engineering.mep_equipment%rowtype;before_state jsonb;
begin select * into e from engineering.mep_equipment where id=target_equipment_id for update;if not found or auth.uid() is null or not project.can_manage_project(e.project_id) then raise exception 'mep_equipment_authority_required';end if;if e.status<>'proposed' or e.reconciliation_status<>'reconciled' then raise exception 'equipment_must_reconcile_before_approval';end if;if e.created_by=auth.uid() then raise exception 'equipment_independent_approval_required';end if;if nullif(btrim(target_reason),'') is null then raise exception 'equipment_approval_reason_required';end if;before_state:=to_jsonb(e);perform set_config('conceptspaces.mep_phase','equipment_approve',true);update engineering.mep_equipment set status='approved',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=e.id returning * into e;perform audit.append_event((select organisation_id from project.projects where id=e.project_id),e.project_id,'mep.equipment.approved','mep_equipment',e.id,before_state,to_jsonb(e),target_reason,gen_random_uuid());return e.status;end;$$;
revoke all on function public.approve_mep_equipment(uuid,text) from public,anon;grant execute on function public.approve_mep_equipment(uuid,text) to authenticated;

create or replace function public.create_mep_package(target_project_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='engineering','cde','project','audit','extensions','auth','pg_temp' as $$
declare m cde.models%rowtype;p engineering.mep_packages%rowtype;v int;disc text:=lower(btrim(input_payload->>'discipline'));crit text:=upper(coalesce(nullif(btrim(input_payload->>'criticality'),''),'C2'));h text;
begin if auth.uid() is null or not project.can_manage_project(target_project_id) then raise exception 'mep_manage_authority_required';end if;if disc not in ('mechanical','electrical','plumbing','fire','elv','bms','vertical_transport') or crit not in ('C0','C1','C2','C3','C4') then raise exception 'mep_package_discipline_criticality_invalid';end if;select * into m from cde.models where id=nullif(input_payload->>'source_model_id','')::uuid and project_id=target_project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;if jsonb_typeof(coalesce(input_payload->'system_ids','[]'::jsonb))<>'array' or jsonb_typeof(coalesce(input_payload->'load_record_ids','[]'::jsonb))<>'array' or jsonb_typeof(coalesce(input_payload->'route_ids','[]'::jsonb))<>'array' or jsonb_typeof(coalesce(input_payload->'equipment_ids','[]'::jsonb))<>'array' then raise exception 'mep_package_refs_must_be_arrays';end if;select coalesce(max(version),0)+1 into v from engineering.mep_packages where project_id=target_project_id and discipline=disc;h:=encode(extensions.digest(jsonb_build_object('project_id',target_project_id,'discipline',disc,'version',v,'source_model_id',m.id,'source_model_hash',m.checksum,'systems',coalesce(input_payload->'system_ids','[]'::jsonb),'loads',coalesce(input_payload->'load_record_ids','[]'::jsonb),'routes',coalesce(input_payload->'route_ids','[]'::jsonb),'equipment',coalesce(input_payload->'equipment_ids','[]'::jsonb),'drawings',coalesce(input_payload->'drawing_refs','[]'::jsonb),'criticality',crit)::text,'sha256'),'hex');perform set_config('conceptspaces.mep_phase','package',true);insert into engineering.mep_packages(project_id,discipline,version,source_model_id,source_model_hash,system_ids,load_record_ids,route_ids,equipment_ids,drawing_refs,criticality,status,package_hash,created_by) values(target_project_id,disc,v,m.id,m.checksum,coalesce(input_payload->'system_ids','[]'::jsonb),coalesce(input_payload->'load_record_ids','[]'::jsonb),coalesce(input_payload->'route_ids','[]'::jsonb),coalesce(input_payload->'equipment_ids','[]'::jsonb),coalesce(input_payload->'drawing_refs','[]'::jsonb),crit,'draft',h,auth.uid()) returning * into p;perform audit.append_event((select organisation_id from project.projects where id=target_project_id),target_project_id,'mep.package.created','mep_package',p.id,null,to_jsonb(p),h,gen_random_uuid());return p.id;end;$$;
revoke all on function public.create_mep_package(uuid,jsonb) from public,anon;grant execute on function public.create_mep_package(uuid,jsonb) to authenticated;

create or replace function public.transition_mep_package(target_package_id uuid,target_status text,target_credential_id uuid,target_reason text)
returns text language plpgsql security invoker set search_path='engineering','cde','project','governance','audit','extensions','auth','pg_temp' as $$
declare p engineering.mep_packages%rowtype;value text:=lower(btrim(target_status));before_state jsonb;id_text text;r engineering.calculation_runs%rowtype;credential_ok boolean;final_hash text;
begin select * into p from engineering.mep_packages where id=target_package_id for update;if not found or auth.uid() is null or not project.can_manage_project(p.project_id) then raise exception 'mep_package_authority_required';end if;if nullif(btrim(target_reason),'') is null then raise exception 'mep_package_transition_reason_required';end if;if not ((p.status='draft' and value='for_review') or (p.status='for_review' and value='approved') or (p.status='approved' and value='issued')) then raise exception 'mep_package_transition_invalid';end if;if exists(select 1 from cde.models m where m.id=p.source_model_id and (m.status not in ('approved','issued') or m.checksum is distinct from p.source_model_hash)) then raise exception 'MEP_SOURCE_MODEL_STALE';end if;
 if value in ('for_review','approved','issued') then
   if exists(select 1 from jsonb_array_elements_text(p.load_record_ids) x join engineering.mep_load_records l on l.id=x.value::uuid where l.project_id=p.project_id and (l.status<>'current' or l.source_model_hash is distinct from p.source_model_hash)) then raise exception 'MEP_LOAD_STALE';end if;
   if exists(select 1 from jsonb_array_elements_text(p.route_ids) x join engineering.mep_routes r on r.id=x.value::uuid where r.project_id=p.project_id and (r.status in ('infeasible','stale') or r.source_model_hash is distinct from p.source_model_hash)) then raise exception 'ROUTE_INFEASIBLE';end if;
   if exists(select 1 from jsonb_array_elements_text(p.equipment_ids) x join engineering.mep_equipment e on e.id=x.value::uuid where e.project_id=p.project_id and (e.status<>'approved' or e.reconciliation_status<>'reconciled' or e.source_model_hash is distinct from p.source_model_hash)) then raise exception 'EQUIPMENT_SCHEDULE_RECONCILIATION_FAIL';end if;
   for id_text in select jsonb_array_elements_text(p.load_record_ids) loop select cr.* into r from engineering.mep_load_records l join engineering.calculation_runs cr on cr.id=l.calculation_run_id where l.id=id_text::uuid;if r.id is null or r.status<>'completed' or r.output_hash is null then raise exception 'MEP_CALCULATION_NOT_RELEASE_READY';end if;if p.criticality in ('C3','C4') and not exists(select 1 from engineering.professional_reviews pr where pr.resource_type='calculation' and pr.resource_id=r.id and pr.resource_hash=r.output_hash and pr.decision in ('accepted','accepted_with_comments') and governance.credential_is_current_for_release(pr.credential_id,pr.reviewer_user_id,p.discipline)) then raise exception 'MEP_PROFESSIONAL_CALCULATION_REVIEW_REQUIRED';end if;end loop;
 end if;
 if value='approved' then if p.created_by=auth.uid() then raise exception 'mep_package_maker_cannot_approve';end if;credential_ok:=target_credential_id is not null and governance.credential_is_current_for_release(target_credential_id,auth.uid(),p.discipline);if p.criticality in ('C3','C4') and not credential_ok then raise exception 'MEP_RELEASE_CREDENTIAL_REQUIRED';end if;if p.criticality='C4' and p.discipline in ('fire','electrical') and not credential_ok then raise exception 'C4_DESIGNATED_PROFESSIONAL_REQUIRED';end if;end if;
 before_state:=to_jsonb(p);final_hash:=case when value='issued' then encode(extensions.digest(jsonb_build_object('package_hash',p.package_hash,'approved_by',p.approved_by,'approval_credential_id',p.approval_credential_id)::text,'sha256'),'hex') else p.issue_hash end;perform set_config('conceptspaces.mep_phase','package_transition',true);update engineering.mep_packages set status=value,approval_credential_id=case when value='approved' then target_credential_id else approval_credential_id end,approved_by=case when value='approved' then auth.uid() else approved_by end,approved_at=case when value='approved' then now() else approved_at end,issued_by=case when value='issued' then auth.uid() else issued_by end,issued_at=case when value='issued' then now() else issued_at end,issue_hash=final_hash,updated_at=now() where id=p.id returning * into p;perform audit.append_event((select organisation_id from project.projects where id=p.project_id),p.project_id,'mep.package.'||value,'mep_package',p.id,before_state,to_jsonb(p),target_reason,gen_random_uuid());return p.status;end;$$;
revoke all on function public.transition_mep_package(uuid,text,uuid,text) from public,anon;grant execute on function public.transition_mep_package(uuid,text,uuid,text) to authenticated;

create or replace function engineering.invalidate_mep_on_model_revision()
returns trigger language plpgsql security definer set search_path='engineering','cde','project','audit','extensions','pg_temp' as $$
declare old_model cde.models%rowtype;loads jsonb;routes jsonb;equipment jsonb;packages jsonb;h text;
begin if new.status not in ('approved','issued') or new.supersedes_model_id is null then return new;end if;select * into old_model from cde.models where id=new.supersedes_model_id;if not found then return new;end if;select coalesce(jsonb_agg(id),'[]'::jsonb) into loads from engineering.mep_load_records where source_model_id=old_model.id and status='current';select coalesce(jsonb_agg(id),'[]'::jsonb) into routes from engineering.mep_routes where source_model_id=old_model.id and status<>'stale';select coalesce(jsonb_agg(id),'[]'::jsonb) into equipment from engineering.mep_equipment where source_model_id=old_model.id and status<>'stale';select coalesce(jsonb_agg(id),'[]'::jsonb) into packages from engineering.mep_packages where source_model_id=old_model.id and status<>'stale';if jsonb_array_length(loads)+jsonb_array_length(routes)+jsonb_array_length(equipment)+jsonb_array_length(packages)=0 then return new;end if;h:=encode(extensions.digest(jsonb_build_object('prior_model_id',old_model.id,'prior_model_hash',old_model.checksum,'new_model_id',new.id,'new_model_hash',new.checksum,'loads',loads,'routes',routes,'equipment',equipment,'packages',packages)::text,'sha256'),'hex');update engineering.mep_load_records set status='stale',invalidated_at=now() where source_model_id=old_model.id and status='current';update engineering.mep_routes set status='stale',updated_at=now() where source_model_id=old_model.id and status<>'stale';update engineering.mep_equipment set status='stale',reconciliation_status='stale',updated_at=now() where source_model_id=old_model.id and status<>'stale';update engineering.mep_packages set status='stale',updated_at=now() where source_model_id=old_model.id and status<>'stale';insert into engineering.mep_invalidations(project_id,prior_model_id,new_model_id,prior_model_hash,new_model_hash,affected_load_ids,affected_route_ids,affected_equipment_ids,affected_package_ids,invalidation_hash) values(new.project_id,old_model.id,new.id,old_model.checksum,new.checksum,loads,routes,equipment,packages,h) on conflict(prior_model_id,new_model_id) do nothing;perform audit.append_event((select organisation_id from project.projects where id=new.project_id),new.project_id,'mep.model_revision_invalidated','model',new.id,to_jsonb(old_model),jsonb_build_object('new_model_id',new.id,'new_model_hash',new.checksum,'affected_loads',jsonb_array_length(loads),'affected_routes',jsonb_array_length(routes),'affected_equipment',jsonb_array_length(equipment),'affected_packages',jsonb_array_length(packages)),h,gen_random_uuid());return new;end;$$;
revoke all on function engineering.invalidate_mep_on_model_revision() from public,anon,authenticated;drop trigger if exists cde_model_revision_invalidates_mep on cde.models;create trigger cde_model_revision_invalidates_mep after update of status on cde.models for each row execute function engineering.invalidate_mep_on_model_revision();

create or replace function public.list_mep_workspace(target_project_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='engineering','cde','project','auth','pg_temp' as $$
begin if auth.uid() is null or not project.can_access_project(target_project_id) then raise exception 'project_access_required';end if;return jsonb_build_object('systems',coalesce((select jsonb_agg(to_jsonb(s) order by s.system_code) from engineering.mep_systems s where s.project_id=target_project_id),'[]'::jsonb),'models',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'name',m.model_name,'discipline',m.discipline,'revision',m.revision,'checksum',m.checksum,'status',m.status) order by m.model_name,m.revision) from cde.models m where m.project_id=target_project_id and m.status in ('approved','issued')),'[]'::jsonb),'loads',coalesce((select jsonb_agg(to_jsonb(l) order by l.created_at desc) from engineering.mep_load_records l where l.project_id=target_project_id),'[]'::jsonb),'routes',coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from engineering.mep_routes r where r.project_id=target_project_id),'[]'::jsonb),'equipment',coalesce((select jsonb_agg(to_jsonb(e) order by e.created_at desc) from engineering.mep_equipment e where e.project_id=target_project_id),'[]'::jsonb),'packages',coalesce((select jsonb_agg(to_jsonb(p) order by p.discipline,p.version desc) from engineering.mep_packages p where p.project_id=target_project_id),'[]'::jsonb),'invalidations',coalesce((select jsonb_agg(to_jsonb(i) order by i.detected_at desc) from engineering.mep_invalidations i where i.project_id=target_project_id),'[]'::jsonb),'calculations',coalesce((select jsonb_agg(to_jsonb(c) order by c.created_at desc) from engineering.calculation_runs c where c.project_id=target_project_id and lower(c.discipline) in ('mechanical','electrical','plumbing','fire','elv','bms','vertical_transport','mep','mepf')),'[]'::jsonb));end;$$;
revoke all on function public.list_mep_workspace(uuid) from public,anon;grant execute on function public.list_mep_workspace(uuid) to authenticated;

commit;