begin;

alter table cde.documents add column if not exists source_model_id uuid references cde.models(id) on delete restrict;
alter table cde.documents add column if not exists source_model_hash text;
alter table cde.documents add column if not exists source_model_revision text;
alter table cde.documents add column if not exists issued_version_id uuid references cde.file_versions(id) on delete restrict;

create or replace function cde.guard_published_document_content()
returns trigger language plpgsql security definer set search_path='cde','pg_temp' as $$
begin
 if (old.cde_state in ('published','archived') or old.status in ('issued','superseded','withdrawn')) and
    (new.project_id is distinct from old.project_id or new.document_number is distinct from old.document_number or new.title is distinct from old.title or new.discipline is distinct from old.discipline or new.document_type is distinct from old.document_type or new.revision is distinct from old.revision or new.current_version_id is distinct from old.current_version_id or new.source_model_id is distinct from old.source_model_id or new.source_model_hash is distinct from old.source_model_hash or new.source_model_revision is distinct from old.source_model_revision or new.issued_version_id is distinct from old.issued_version_id) then
   raise exception 'PUBLISHED_DOCUMENT_CONTENT_IMMUTABLE';
 end if;
 return new;
end;$$;
revoke all on function cde.guard_published_document_content() from public,anon,authenticated;
drop trigger if exists cde_published_document_content_immutable on cde.documents;
create trigger cde_published_document_content_immutable before update on cde.documents for each row execute function cde.guard_published_document_content();

create table if not exists cde.model_validation_findings(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,validation_run_id uuid not null references cde.model_validation_runs(id) on delete cascade,model_id uuid not null references cde.models(id) on delete cascade,finding_code text not null,severity text not null,object_ref text,property_ref text,expected_value jsonb,observed_value jsonb,message text not null,coordination_issue_id uuid references coordination.issues(id) on delete set null,finding_hash text not null,created_at timestamptz not null default now()
);
alter table cde.model_validation_findings enable row level security;grant select on cde.model_validation_findings to authenticated;
create policy cde_validation_findings_read on cde.model_validation_findings for select to authenticated using(project.can_access_project(project_id));

create table if not exists cde.cad_jobs(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references project.projects(id) on delete cascade,target_document_id uuid not null references cde.documents(id) on delete restrict,source_model_id uuid not null references cde.models(id) on delete restrict,source_model_hash text not null,adapter_key text not null,adapter_version text not null,output_format text not null,input_hash text not null,status text not null check(status in ('queued','running','succeeded','failed','quarantined')) default 'queued',output_object_key text,output_checksum text,output_file_version_id uuid references cde.file_versions(id) on delete restrict,error_code text,error_detail jsonb not null default '{}'::jsonb,requested_by uuid references auth.users(id) on delete set null,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),unique(project_id,target_document_id,input_hash,adapter_key,adapter_version,output_format)
);
alter table cde.cad_jobs enable row level security;grant select,insert,update on cde.cad_jobs to authenticated;
create policy cad_jobs_read on cde.cad_jobs for select to authenticated using(project.can_access_project(project_id));
create policy cad_jobs_insert on cde.cad_jobs for insert to authenticated with check(project.can_manage_project(project_id) and requested_by=auth.uid() and current_setting('conceptspaces.cad_phase',true)='queue');
create policy cad_jobs_update on cde.cad_jobs for update to authenticated using(project.can_manage_project(project_id)) with check(project.can_manage_project(project_id) and current_setting('conceptspaces.cad_phase',true) in ('start','complete','fail','quarantine'));

create or replace function public.record_cde_model_validation(target_model_id uuid,input_payload jsonb)
returns uuid language plpgsql security invoker set search_path='public','cde','project','coordination','audit','extensions','auth','pg_temp' as $$
declare m cde.models%rowtype;v cde.model_validation_runs%rowtype;org_id uuid;validation_type_value text;result_hash_value text;finding jsonb;issue_id uuid;fh text;code text;severity text;obj_ref text;prop_ref text;msg text;
begin
 select * into m from cde.models where id=target_model_id for update;if not found or auth.uid() is null or not project.can_manage_project(m.project_id) then raise exception 'model_manage_authority_required';end if;if m.status in ('issued','superseded','withdrawn') then raise exception 'immutable_model_revision';end if;
 validation_type_value:=lower(coalesce(nullif(btrim(input_payload->>'validation_type'),''),'ifc'));if validation_type_value not in ('ifc','ids','geometry','semantic','round_trip') then raise exception 'unsupported_validation_type';end if;result_hash_value:=lower(coalesce(input_payload->>'result_hash',''));if result_hash_value !~ '^[0-9a-f]{64}$' then raise exception 'validation_result_hash_required';end if;if jsonb_typeof(coalesce(input_payload->'findings','[]'::jsonb))<>'array' then raise exception 'validation_findings_must_be_array';end if;
 perform set_config('conceptspaces.model_phase','validate',true);insert into cde.model_validation_runs(project_id,model_id,validation_type,adapter_key,adapter_version,passed,result_hash,findings,evidence_refs,created_by) values(m.project_id,m.id,validation_type_value,nullif(btrim(input_payload->>'adapter_key'),''),nullif(btrim(input_payload->>'adapter_version'),''),coalesce((input_payload->>'passed')::boolean,false),result_hash_value,coalesce(input_payload->'findings','[]'::jsonb),coalesce(input_payload->'evidence_refs','[]'::jsonb),auth.uid()) returning * into v;update cde.models set validation_summary=jsonb_build_object('validation_run_id',v.id,'type',v.validation_type,'passed',v.passed,'findings',v.findings,'validated_at',v.created_at),validation_hash=v.result_hash,updated_at=now() where id=m.id returning * into m;
 for finding in select value from jsonb_array_elements(coalesce(v.findings,'[]'::jsonb)) loop
   if jsonb_typeof(finding)<>'object' then raise exception 'validation_finding_object_required';end if;code:=coalesce(nullif(btrim(finding->>'code'),''),'VALIDATION_FINDING');severity:=lower(coalesce(nullif(btrim(finding->>'severity'),''),'medium'));obj_ref:=nullif(btrim(finding->>'object_ref'),'');prop_ref:=nullif(btrim(finding->>'property_ref'),'');msg:=coalesce(nullif(btrim(finding->>'message'),''),code);
   if validation_type_value='ids' and not v.passed and (obj_ref is null or prop_ref is null) then raise exception 'IDS_FINDING_OBJECT_PROPERTY_REQUIRED';end if;
   fh:=encode(extensions.digest(jsonb_build_object('validation_run_id',v.id,'model_hash',m.checksum,'code',code,'severity',severity,'object_ref',obj_ref,'property_ref',prop_ref,'expected',finding->'expected','observed',finding->'observed','message',msg)::text,'sha256'),'hex');
   issue_id:=null;if not v.passed then issue_id:=public.create_coordination_issue(jsonb_build_object('project_id',m.project_id,'issue_type','coordination','title',upper(validation_type_value)||' · '||code||' · '||coalesce(obj_ref,'model'),'description',msg||case when prop_ref is not null then ' | property: '||prop_ref else '' end,'priority',case when severity in ('critical','major','high') then 'high' else 'medium' end,'criticality',case when severity='critical' then 'C4' when severity in ('major','high') then 'C3' else 'C2' end,'location_ref',obj_ref));perform set_config('conceptspaces.coordination_phase','raise',true);insert into coordination.issue_links(issue_id,resource_type,resource_id,relationship) values(issue_id,'model',m.id,'validation_object_property_failure') on conflict do nothing;end if;
   insert into cde.model_validation_findings(project_id,validation_run_id,model_id,finding_code,severity,object_ref,property_ref,expected_value,observed_value,message,coordination_issue_id,finding_hash) values(m.project_id,v.id,m.id,code,severity,obj_ref,prop_ref,finding->'expected',finding->'observed',msg,issue_id,fh);
 end loop;
 select organisation_id into org_id from project.projects where id=m.project_id;perform audit.append_event(org_id,m.project_id,'cde.model.validation_recorded','model_validation',v.id,null,jsonb_build_object('validation',to_jsonb(v),'normalised_findings',(select count(*) from cde.model_validation_findings f where f.validation_run_id=v.id)),v.result_hash,gen_random_uuid());return v.id;
end;$$;
revoke all on function public.record_cde_model_validation(uuid,jsonb) from public,anon;grant execute on function public.record_cde_model_validation(uuid,jsonb) to authenticated;

create or replace function public.queue_cad_job(target_document_id uuid,target_source_model_id uuid,target_adapter_key text,target_adapter_version text,target_output_format text,target_reason text)
returns uuid language plpgsql security invoker set search_path='cde','project','audit','extensions','auth','pg_temp' as $$
declare d cde.documents%rowtype;m cde.models%rowtype;j cde.cad_jobs%rowtype;h text;
begin select * into d from cde.documents where id=target_document_id;if not found or auth.uid() is null or not project.can_manage_project(d.project_id) then raise exception 'document_manage_authority_required';end if;if d.cde_state<>'work_in_progress' or d.status<>'draft' then raise exception 'draft_wip_target_document_required';end if;select * into m from cde.models where id=target_source_model_id and project_id=d.project_id and status in ('approved','issued');if not found then raise exception 'approved_source_model_required';end if;if nullif(btrim(target_adapter_key),'') is null or nullif(btrim(target_adapter_version),'') is null or nullif(btrim(target_output_format),'') is null or nullif(btrim(target_reason),'') is null then raise exception 'cad_adapter_version_format_reason_required';end if;h:=encode(extensions.digest(jsonb_build_object('document_id',d.id,'document_revision',d.revision,'source_model_id',m.id,'source_model_hash',m.checksum,'source_model_revision',m.revision,'adapter_key',btrim(target_adapter_key),'adapter_version',btrim(target_adapter_version),'output_format',lower(btrim(target_output_format)))::text,'sha256'),'hex');perform set_config('conceptspaces.cad_phase','queue',true);insert into cde.cad_jobs(project_id,target_document_id,source_model_id,source_model_hash,adapter_key,adapter_version,output_format,input_hash,status,requested_by) values(d.project_id,d.id,m.id,m.checksum,btrim(target_adapter_key),btrim(target_adapter_version),lower(btrim(target_output_format)),h,'queued',auth.uid()) returning * into j;perform audit.append_event((select organisation_id from project.projects where id=d.project_id),d.project_id,'cde.cad_job.queued','cad_job',j.id,null,to_jsonb(j),target_reason,gen_random_uuid());return j.id;end;$$;
revoke all on function public.queue_cad_job(uuid,uuid,text,text,text,text) from public,anon;grant execute on function public.queue_cad_job(uuid,uuid,text,text,text,text) to authenticated;

create or replace function public.start_cad_job(target_job_id uuid)
returns text language plpgsql security invoker set search_path='cde','project','auth','pg_temp' as $$
declare j cde.cad_jobs%rowtype;begin select * into j from cde.cad_jobs where id=target_job_id for update;if not found or auth.uid() is null or not project.can_manage_project(j.project_id) then raise exception 'cad_job_authority_required';end if;if j.status<>'queued' then raise exception 'cad_job_not_queued';end if;perform set_config('conceptspaces.cad_phase','start',true);update cde.cad_jobs set status='running',started_at=now() where id=j.id returning * into j;return j.status;end;$$;
revoke all on function public.start_cad_job(uuid) from public,anon;grant execute on function public.start_cad_job(uuid) to authenticated;

create or replace function public.finish_cad_job(target_job_id uuid,target_succeeded boolean,target_output_object_key text,target_output_mime_type text,target_output_size_bytes bigint,target_output_checksum text,target_error_code text,target_error_detail jsonb)
returns jsonb language plpgsql security invoker set search_path='public','cde','project','audit','auth','pg_temp' as $$
declare j cde.cad_jobs%rowtype;d cde.documents%rowtype;m cde.models%rowtype;fv jsonb;version_id uuid;
begin select * into j from cde.cad_jobs where id=target_job_id for update;if not found or auth.uid() is null or not project.can_manage_project(j.project_id) then raise exception 'cad_job_authority_required';end if;if j.status not in ('queued','running') then raise exception 'cad_job_not_finishable';end if;select * into d from cde.documents where id=j.target_document_id for update;select * into m from cde.models where id=j.source_model_id;
 if not target_succeeded then perform set_config('conceptspaces.cad_phase','fail',true);update cde.cad_jobs set status='failed',error_code=coalesce(nullif(btrim(target_error_code),''),'CAD_ADAPTER_FAILED'),error_detail=coalesce(target_error_detail,'{}'::jsonb),completed_at=now() where id=j.id returning * into j;perform audit.append_event((select organisation_id from project.projects where id=j.project_id),j.project_id,'cde.cad_job.failed','cad_job',j.id,null,to_jsonb(j),j.error_code,gen_random_uuid());return jsonb_build_object('status','failed','document_mutated',false,'document_id',d.id,'document_current_version_id',d.current_version_id);end if;
 if d.status<>'draft' or d.cde_state<>'work_in_progress' then raise exception 'cad_target_document_changed_during_job';end if;if m.status not in ('approved','issued') or m.checksum is distinct from j.source_model_hash then raise exception 'CAD_SOURCE_REVISION_STALE';end if;if target_output_checksum !~ '^[0-9a-fA-F]{64}$' or target_output_size_bytes<0 or nullif(btrim(target_output_object_key),'') is null then raise exception 'cad_output_evidence_required';end if;
 fv:=public.register_cde_file_version(d.id,target_output_object_key,target_output_mime_type,target_output_size_bytes,lower(target_output_checksum));version_id:=(fv->>'version_id')::uuid;update cde.documents set source_model_id=m.id,source_model_hash=m.checksum,source_model_revision=m.revision,updated_at=now() where id=d.id;perform set_config('conceptspaces.cad_phase','complete',true);update cde.cad_jobs set status='succeeded',output_object_key=target_output_object_key,output_checksum=lower(target_output_checksum),output_file_version_id=version_id,completed_at=now() where id=j.id returning * into j;perform audit.append_event((select organisation_id from project.projects where id=j.project_id),j.project_id,'cde.cad_job.succeeded','cad_job',j.id,null,to_jsonb(j),j.output_checksum,gen_random_uuid());return jsonb_build_object('status','succeeded','document_id',d.id,'file_version_id',version_id,'source_model_id',m.id,'source_model_revision',m.revision,'source_model_hash',m.checksum,'output_checksum',j.output_checksum);
end;$$;
revoke all on function public.finish_cad_job(uuid,boolean,text,text,bigint,text,text,jsonb) from public,anon;grant execute on function public.finish_cad_job(uuid,boolean,text,text,bigint,text,text,jsonb) to authenticated;

create or replace function public.transition_cde_document(target_document_id uuid,target_status text,target_cde_state text,evidence_note text default null)
returns void language plpgsql security invoker set search_path='cde','project','coordination','audit','public','auth','pg_temp' as $$
declare d cde.documents%rowtype;v cde.file_versions%rowtype;a coordination.approval_requests%rowtype;m cde.models%rowtype;before_state jsonb;org_id uuid;status_value text:=lower(btrim(target_status));state_value text:=lower(btrim(target_cde_state));
begin select * into d from cde.documents where id=target_document_id for update;if not found then raise exception 'document_not_found';end if;if not project.can_manage_project(d.project_id) then raise exception 'project_manage_authority_required';end if;if d.current_version_id is null then raise exception 'document_version_required';end if;select * into v from cde.file_versions where id=d.current_version_id;if status_value not in ('draft','for_review','for_approval','approved','issued','superseded','withdrawn') then raise exception 'unsupported_document_status';end if;if state_value not in ('work_in_progress','shared','published','archived') then raise exception 'unsupported_cde_state';end if;if d.cde_state='archived' or d.status in ('issued','superseded','withdrawn') then raise exception 'terminal_document_state';end if;
 if state_value='published' or status_value in ('approved','issued') then select * into a from coordination.approval_requests where project_id=d.project_id and resource_type='document' and resource_id=d.id and decision in ('approved','approved_with_comments') and decision_evidence_hash=v.checksum order by decided_at desc limit 1;if not found or a.decided_by is null then raise exception 'matching_approved_resource_hash_required';end if;end if;
 if status_value='issued' and state_value<>'published' then raise exception 'issued_document_must_be_published';end if;
 if (state_value='published' or status_value='issued') and lower(d.document_type) in ('drawing','shop_drawing','cad_drawing') then select * into m from cde.models where id=d.source_model_id and project_id=d.project_id;if not found or m.status not in ('approved','issued') or m.checksum is distinct from d.source_model_hash or m.revision is distinct from d.source_model_revision then raise exception 'SOURCE_MODEL_REVISION_NOT_APPROVED';end if;end if;
 before_state:=to_jsonb(d);update cde.documents set status=status_value,cde_state=state_value,checked_by=case when status_value in ('for_approval','approved','issued') then coalesce(checked_by,auth.uid()) else checked_by end,approved_by=case when status_value in ('approved','issued') then a.decided_by else approved_by end,issued_version_id=case when status_value='issued' then current_version_id else issued_version_id end,updated_at=now() where id=d.id returning * into d;select organisation_id into org_id from project.projects where id=d.project_id;perform audit.append_event(org_id,d.project_id,'cde.document.transition','document',d.id,before_state,to_jsonb(d),evidence_note,gen_random_uuid());end;$$;
revoke all on function public.transition_cde_document(uuid,text,text,text) from public,anon;grant execute on function public.transition_cde_document(uuid,text,text,text) to authenticated;

create or replace function public.list_cde_production_workspace(target_project_id uuid)
returns jsonb language plpgsql stable security invoker set search_path='cde','project','auth','pg_temp' as $$
begin if auth.uid() is null or not project.can_access_project(target_project_id) then raise exception 'project_access_required';end if;return jsonb_build_object('documents',coalesce((select jsonb_agg(to_jsonb(d) order by d.document_number,d.revision) from cde.documents d where d.project_id=target_project_id),'[]'::jsonb),'file_versions',coalesce((select jsonb_agg(to_jsonb(v) order by v.created_at desc) from cde.file_versions v join cde.documents d on d.id=v.document_id where d.project_id=target_project_id),'[]'::jsonb),'cad_jobs',coalesce((select jsonb_agg(to_jsonb(j) order by j.created_at desc) from cde.cad_jobs j where j.project_id=target_project_id),'[]'::jsonb),'validation_findings',coalesce((select jsonb_agg(to_jsonb(f) order by f.created_at desc) from cde.model_validation_findings f where f.project_id=target_project_id),'[]'::jsonb));end;$$;
revoke all on function public.list_cde_production_workspace(uuid) from public,anon;grant execute on function public.list_cde_production_workspace(uuid) to authenticated;

commit;