begin;

alter table governance.release_safety_cases add column if not exists evidence_manifest jsonb not null default '[]'::jsonb;
alter table governance.release_safety_cases add column if not exists evidence_bundle_hash text;
alter table governance.release_evidence drop constraint if exists release_evidence_evidence_type_check;
alter table governance.release_evidence add constraint release_evidence_evidence_type_check check(evidence_type in ('truth_snapshot','regulatory_check','engineering_check','coordination_check','professional_approval','client_approval','document_hash','qa_check'));
create unique index if not exists release_case_gate_content_uidx on governance.release_safety_cases(gate_id,content_hash) where gate_id is not null and content_hash is not null;

create or replace function public.capture_release_qa_check(target_safety_case_id uuid,target_reason text)
returns uuid language plpgsql security invoker set search_path='public','governance','project','extensions','auth','pg_temp' as $$
declare s governance.release_safety_cases%rowtype;snapshot jsonb;open_critical int;snapshot_hash text;new_id uuid;
begin
 select * into s from governance.release_safety_cases where id=target_safety_case_id;if not found then raise exception 'release_safety_case_not_found';end if;if auth.uid() is null or not project.can_manage_project(s.project_id) then raise exception 'project_manage_authority_required';end if;if nullif(btrim(target_reason),'') is null then raise exception 'qa_snapshot_reason_required';end if;
 select coalesce(jsonb_agg(jsonb_build_object('finding_id',f.id,'rule_code',f.rule_code,'discipline',f.discipline,'severity',f.severity,'criticality',f.criticality,'status',f.status,'object_refs',f.object_refs,'source_ref',f.source_ref,'waiver_ref',f.waiver_ref,'waiver',case when f.waiver_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then (select jsonb_build_object('id',e.id,'status',e.status,'criticality',e.criticality,'accepted_by',e.accepted_by,'rationale',e.rationale,'resolved_at',e.resolved_at) from governance.exceptions e where e.id=f.waiver_ref::uuid and e.project_id=s.project_id) else null end) order by f.created_at,f.id),'[]'::jsonb) into snapshot from public.design_lint_findings f where f.project_id=s.project_id;
 select count(*) into open_critical from public.design_lint_findings f where f.project_id=s.project_id and f.severity='critical' and f.status='open' and not (f.waiver_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and exists(select 1 from governance.exceptions e where e.id=f.waiver_ref::uuid and e.project_id=s.project_id and e.status='accepted' and e.accepted_by is not null and nullif(btrim(e.rationale),'') is not null));
 snapshot_hash:=encode(extensions.digest(jsonb_build_object('project_id',s.project_id,'package_content_hash',s.content_hash,'findings',snapshot,'open_unwaived_critical',open_critical)::text,'sha256'),'hex');perform set_config('conceptspaces.release_capture','qa_check',true);
 new_id:=public.add_release_evidence(s.id,'qa_check','design_lint_findings:'||s.project_id::text,snapshot_hash,open_critical=0,jsonb_build_object('check_version','design-linter-governed-v1','findings',snapshot,'open_unwaived_critical',open_critical,'snapshot_hash',snapshot_hash),target_reason);return new_id;
end;$$;
revoke all on function public.capture_release_qa_check(uuid,text) from public,anon;grant execute on function public.capture_release_qa_check(uuid,text) to authenticated;

create or replace function governance.release_evidence_is_current(target_evidence_id uuid)
returns boolean language plpgsql stable security invoker set search_path='governance','project','regula','engineering','core','auth','public','pg_temp' as $$
declare e governance.release_evidence%rowtype;s governance.release_safety_cases%rowtype;g governance.release_gates%rowtype;ref_uuid uuid;
begin
 if auth.uid() is null then return false;end if;select * into e from governance.release_evidence where id=target_evidence_id;if not found or not e.passed or e.safety_case_id is null then return false;end if;select * into s from governance.release_safety_cases where id=e.safety_case_id;if not found or s.content_hash is null or e.package_content_hash is distinct from s.content_hash then return false;end if;select * into g from governance.release_gates where id=s.gate_id;if not found or g.project_id<>s.project_id or e.project_id<>s.project_id or e.gate_id<>g.id then return false;end if;
 if e.evidence_type='document_hash' then return e.evidence_hash=s.content_hash;
 elsif e.evidence_type='client_approval' then return e.evidence_hash=s.content_hash and nullif(btrim(e.reference),'') is not null;
 elsif e.evidence_type='truth_snapshot' then if nullif(btrim(e.evidence_hash),'') is null then return false;end if;if exists(select 1 from project.truth_records t where t.project_id=s.project_id and t.updated_at>e.produced_at) then return false;end if;return not exists(select 1 from project.truth_records t where t.project_id=s.project_id and engineering.criticality_rank(t.criticality)>=3 and (t.status<>'verified' or (t.valid_until is not null and t.valid_until<now())));
 elsif e.evidence_type='coordination_check' then if nullif(btrim(e.evidence_hash),'') is null then return false;end if;if exists(select 1 from engineering.coordination_matrix c where c.project_id=s.project_id and c.updated_at>e.produced_at) then return false;end if;return not exists(select 1 from engineering.coordination_matrix c where c.project_id=s.project_id and c.state in ('open','coordinating'));
 elsif e.evidence_type='qa_check' then if nullif(btrim(e.evidence_hash),'') is null then return false;end if;if exists(select 1 from public.design_lint_findings f where f.project_id=s.project_id and f.updated_at>e.produced_at) then return false;end if;return not exists(select 1 from public.design_lint_findings f where f.project_id=s.project_id and f.severity='critical' and f.status='open' and not (f.waiver_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and exists(select 1 from governance.exceptions ex where ex.id=f.waiver_ref::uuid and ex.project_id=s.project_id and ex.status='accepted' and ex.accepted_by is not null and nullif(btrim(ex.rationale),'') is not null)));
 elsif e.evidence_type='regulatory_check' then if e.reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return false;end if;ref_uuid:=e.reference::uuid;return exists(select 1 from regula.evaluation_runs r where r.id=ref_uuid and r.project_id=s.project_id and r.status='completed' and r.result_hash=e.evidence_hash and r.deterministic_failures=0 and r.interpretation_required=0 and r.not_verified=0 and r.id=(select r2.id from regula.evaluation_runs r2 where r2.project_id=s.project_id and r2.status='completed' order by coalesce(r2.completed_at,r2.created_at) desc,r2.created_at desc limit 1));
 elsif e.evidence_type='engineering_check' then if e.reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return false;end if;ref_uuid:=e.reference::uuid;return exists(select 1 from engineering.calculation_runs r join engineering.engines en on en.id=r.engine_id where r.id=ref_uuid and r.project_id=s.project_id and r.status='completed' and r.output_hash=e.evidence_hash and r.engine_version=en.version and en.enabled and en.certification_status in ('conditionally_approved','approved') and engineering.criticality_rank((select p.criticality from project.projects p where p.id=s.project_id))<=engineering.criticality_rank(en.maximum_criticality) and exists(select 1 from engineering.professional_reviews pr where pr.resource_type='calculation' and pr.resource_id=r.id and pr.resource_hash=r.output_hash and pr.decision in ('accepted','accepted_with_comments') and governance.credential_is_current_for_release(pr.credential_id,pr.reviewer_user_id,r.discipline)));
 elsif e.evidence_type='professional_approval' then if e.reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return false;end if;ref_uuid:=e.reference::uuid;return exists(select 1 from governance.release_package_reviews pr where pr.id=ref_uuid and pr.safety_case_id=s.id and pr.project_id=s.project_id and pr.content_hash=s.content_hash and pr.decision in ('accepted','accepted_with_comments') and governance.credential_is_current_for_release(pr.credential_id,pr.reviewer_user_id,g.discipline) and (engineering.criticality_rank(g.criticality)<3 or s.created_by is null or pr.reviewer_user_id<>s.created_by));end if;return false;
end;$$;

create or replace function public.evaluate_release_safety_case(target_safety_case_id uuid)
returns jsonb language plpgsql security invoker set search_path='public','governance','project','engineering','audit','extensions','auth','pg_temp' as $$
declare s governance.release_safety_cases%rowtype;g governance.release_gates%rowtype;project_org_id uuid;missing_count int:=0;stale_or_failed_count int:=0;critical_exception_count int:=0;qa_missing int:=0;qa_stale int:=0;next_state text;check_payload jsonb;manifest jsonb;bundle_hash text;
begin
 select * into s from governance.release_safety_cases where id=target_safety_case_id for update;if not found then raise exception 'release_safety_case_not_found';end if;select * into g from governance.release_gates where id=s.gate_id for update;if not found then raise exception 'release_gate_not_found';end if;if auth.uid() is null or not project.can_manage_project(s.project_id) then raise exception 'project_manage_authority_required';end if;if s.state='issued' then return jsonb_build_object('state','issued','release_state','released','immutable',true,'evidence_bundle_hash',s.evidence_bundle_hash);end if;
 select count(*) into missing_count from jsonb_array_elements_text(g.required_evidence_types) req(value) where req.value<>'qa_check' and not exists(select 1 from governance.release_evidence e where e.safety_case_id=s.id and e.package_content_hash=s.content_hash and e.evidence_type=req.value);
 select count(*) into stale_or_failed_count from jsonb_array_elements_text(g.required_evidence_types) req(value) join lateral(select e.id from governance.release_evidence e where e.safety_case_id=s.id and e.package_content_hash=s.content_hash and e.evidence_type=req.value order by e.produced_at desc,e.id desc limit 1) latest on true where req.value<>'qa_check' and not governance.release_evidence_is_current(latest.id);
 select case when exists(select 1 from governance.release_evidence e where e.safety_case_id=s.id and e.package_content_hash=s.content_hash and e.evidence_type='qa_check') then 0 else 1 end into qa_missing;select case when qa_missing=1 then 0 when exists(select 1 from lateral(select e.id from governance.release_evidence e where e.safety_case_id=s.id and e.package_content_hash=s.content_hash and e.evidence_type='qa_check' order by e.produced_at desc,e.id desc limit 1) q where not governance.release_evidence_is_current(q.id)) then 1 else 0 end into qa_stale;
 select count(*) into critical_exception_count from governance.exceptions ex where ex.project_id=s.project_id and ex.criticality in ('C3','C4') and ex.status='open' and ((ex.safety_case_id=s.id) or (ex.safety_case_id is null and ex.gate_id=g.id) or (ex.safety_case_id is null and ex.gate_id is null));
 select coalesce(jsonb_agg(jsonb_build_object('evidence_type',x.evidence_type,'reference',x.reference,'evidence_hash',x.evidence_hash,'passed',x.passed,'payload',x.payload,'produced_at',x.produced_at) order by x.evidence_type,x.produced_at),'[]'::jsonb) into manifest from (select distinct on(e.evidence_type) e.* from governance.release_evidence e where e.safety_case_id=s.id and e.package_content_hash=s.content_hash order by e.evidence_type,e.produced_at desc,e.id desc)x;
 bundle_hash:=encode(extensions.digest(jsonb_build_object('project_id',s.project_id,'gate_id',g.id,'package_content_hash',s.content_hash,'manifest',manifest)::text,'sha256'),'hex');next_state:=case when missing_count=0 and stale_or_failed_count=0 and qa_missing=0 and qa_stale=0 and critical_exception_count=0 then 'ready_for_review' else 'blocked' end;if s.state='approved' and next_state='ready_for_review' then next_state:='approved';end if;
 check_payload:=jsonb_build_object('evaluated_at',now(),'package_content_hash',s.content_hash,'required_evidence_types',g.required_evidence_types,'qa_check_mandatory',true,'missing_required_evidence',missing_count,'stale_or_failed_required_evidence',stale_or_failed_count,'qa_missing',qa_missing,'qa_stale_or_failed',qa_stale,'unresolved_C3_C4_exceptions',critical_exception_count,'zero_critical_escape',critical_exception_count=0 and qa_stale=0,'evidence_bundle_hash',bundle_hash,'ready',next_state in ('ready_for_review','approved'));
 select organisation_id into project_org_id from project.projects where id=s.project_id;perform set_config('conceptspaces.release_phase','evaluate',true);update governance.release_safety_cases set state=next_state,unresolved_critical_defects=critical_exception_count+qa_stale,checks=jsonb_build_array(check_payload),evidence_manifest=manifest,evidence_bundle_hash=bundle_hash,last_evaluated_at=now(),approved_by=case when next_state='blocked' then null else approved_by end,approved_at=case when next_state='blocked' then null else approved_at end,updated_at=now() where id=s.id;update governance.release_gates set state=case when next_state='approved' then 'approved' when next_state='ready_for_review' then 'ready_for_review' else 'blocked' end,unresolved_critical_defects=critical_exception_count+qa_stale,approved_by=case when next_state='blocked' then null else approved_by end,approved_at=case when next_state='blocked' then null else approved_at end,updated_at=now() where id=g.id;perform audit.append_event(project_org_id,s.project_id,'release.safety_case_evaluated','release_safety_case',s.id,to_jsonb(s),check_payload,'Fresh release evidence and QA evaluation',null);return check_payload||jsonb_build_object('state',next_state);
end;$$;
revoke all on function public.evaluate_release_safety_case(uuid) from public,anon;grant execute on function public.evaluate_release_safety_case(uuid) to authenticated;

create or replace function public.create_release_safety_case(target_gate_id uuid,target_package_type text,target_package_reference text,target_content_hash text,target_client_approval_ref text,target_reason text)
returns uuid language plpgsql security invoker set search_path='public','governance','project','audit','auth','pg_temp' as $$
declare g governance.release_gates%rowtype;s governance.release_safety_cases%rowtype;project_org_id uuid;
begin select * into g from governance.release_gates where id=target_gate_id;if not found then raise exception 'release_gate_not_found';end if;if auth.uid() is null or not project.can_manage_project(g.project_id) then raise exception 'project_manage_authority_required';end if;if nullif(btrim(target_package_type),'') is null or nullif(btrim(target_package_reference),'') is null or target_content_hash !~ '^[0-9a-fA-F]{64}$' then raise exception 'package_identity_and_sha256_required';end if;if nullif(btrim(target_reason),'') is null then raise exception 'safety_case_reason_required';end if;select * into s from governance.release_safety_cases where gate_id=g.id and content_hash=lower(target_content_hash) limit 1;if found then return s.id;end if;select organisation_id into project_org_id from project.projects where id=g.project_id;perform set_config('conceptspaces.release_phase','create_case',true);insert into governance.release_safety_cases(project_id,gate_id,package_type,package_reference,content_hash,state,unresolved_critical_defects,checks,professional_approvals,client_approval_ref,created_by) values(g.project_id,g.id,btrim(target_package_type),btrim(target_package_reference),lower(target_content_hash),'draft',0,'[]'::jsonb,'[]'::jsonb,nullif(btrim(target_client_approval_ref),''),auth.uid()) returning * into s;insert into governance.release_evidence(project_id,gate_id,safety_case_id,package_content_hash,evidence_type,reference,evidence_hash,passed,payload,produced_by) values(g.project_id,g.id,s.id,s.content_hash,'document_hash',s.package_reference,s.content_hash,true,jsonb_build_object('package_type',s.package_type,'package_reference',s.package_reference),auth.uid());update governance.release_gates set state='not_ready',unresolved_critical_defects=0,approved_by=null,approved_at=null,released_at=null,updated_at=now() where id=g.id;perform audit.append_event(project_org_id,g.project_id,'release.safety_case_created','release_safety_case',s.id,null,to_jsonb(s),btrim(target_reason),null);return s.id;end;$$;
revoke all on function public.create_release_safety_case(uuid,text,text,text,text,text) from public,anon;grant execute on function public.create_release_safety_case(uuid,text,text,text,text,text) to authenticated;

create or replace function public.issue_release_safety_case(target_safety_case_id uuid,target_reason text)
returns void language plpgsql security invoker set search_path='public','governance','project','audit','auth','pg_temp' as $$
declare s governance.release_safety_cases%rowtype;g governance.release_gates%rowtype;project_org_id uuid;evaluation jsonb;
begin if nullif(btrim(target_reason),'') is null then raise exception 'issue_reason_required';end if;select * into s from governance.release_safety_cases where id=target_safety_case_id;if not found then raise exception 'release_safety_case_not_found';end if;if auth.uid() is null or not project.can_manage_project(s.project_id) then raise exception 'project_manage_authority_required';end if;if s.state='issued' then return;end if;if s.state<>'approved' then raise exception 'safety_case_must_be_approved_before_issue';end if;evaluation:=public.evaluate_release_safety_case(target_safety_case_id);select * into s from governance.release_safety_cases where id=target_safety_case_id for update;select * into g from governance.release_gates where id=s.gate_id for update;if s.state<>'approved' or coalesce((s.checks->0->>'ready')::boolean,false)=false then raise exception 'fresh_release_evaluation_failed';end if;if s.unresolved_critical_defects<>0 or g.unresolved_critical_defects<>0 or s.evidence_bundle_hash is null then raise exception 'zero_critical_escape_and_evidence_bundle_required';end if;select organisation_id into project_org_id from project.projects where id=s.project_id;perform set_config('conceptspaces.release_phase','issue',true);update governance.release_safety_cases set state='issued',issued_by=auth.uid(),issued_at=now(),updated_at=now() where id=s.id;update governance.release_gates set state='released',released_at=now(),updated_at=now() where id=g.id;perform audit.append_event(project_org_id,s.project_id,'release.package_issued','release_safety_case',s.id,to_jsonb(s),jsonb_build_object('state','issued','content_hash',s.content_hash,'evidence_bundle_hash',s.evidence_bundle_hash,'gate_id',g.id,'issued_by',auth.uid()),btrim(target_reason),null);end;$$;
revoke all on function public.issue_release_safety_case(uuid,text) from public,anon;grant execute on function public.issue_release_safety_case(uuid,text) to authenticated;

commit;