begin;

alter table ai.evaluation_cases add column if not exists regression_tolerance numeric not null default 0 check(regression_tolerance>=0 and regression_tolerance<=1);
alter table ai.agent_runs add column if not exists output_status text check(output_status in ('verified','not_verified','draft','blocked'));
alter table ai.agent_runs add column if not exists output_hash text;
alter table ai.agent_runs add column if not exists grounding_status text check(grounding_status in ('grounded','missing','not_required'));
alter table ai.agent_runs add column if not exists completion_payload jsonb not null default '{}'::jsonb;
alter table ai.learning_candidates add column if not exists privacy_reviewed_by uuid references auth.users(id) on delete set null;
alter table ai.learning_candidates add column if not exists privacy_reviewed_at timestamptz;
alter table ai.learning_candidates add column if not exists expert_reviewed_by uuid references auth.users(id) on delete set null;
alter table ai.learning_candidates add column if not exists expert_reviewed_at timestamptz;
alter table ai.learning_candidates add column if not exists promotion_scope text check(promotion_scope in ('project','organisation','global'));
alter table ai.learning_candidates add column if not exists promoted_at timestamptz;
alter table ai.learning_candidates add column if not exists candidate_hash text;

grant insert,update on ai.agent_runs,ai.learning_candidates to authenticated;
create policy ai_agent_runs_governed_insert on ai.agent_runs for insert to authenticated with check(current_setting('conceptspaces.ai_runtime_phase',true)='start' and ((project_id is not null and project.can_access_project(project_id)) or (project_id is null and core.is_internal_org_member(organisation_id))));
create policy ai_agent_runs_governed_update on ai.agent_runs for update to authenticated using((project_id is not null and project.can_access_project(project_id)) or (project_id is null and core.is_internal_org_member(organisation_id))) with check(current_setting('conceptspaces.ai_runtime_phase',true)='complete');
create policy ai_learning_governed_insert on ai.learning_candidates for insert to authenticated with check(core.is_platform_admin() and current_setting('conceptspaces.ai_learning_phase',true)='propose');
create policy ai_learning_governed_update on ai.learning_candidates for update to authenticated using(core.is_platform_admin()) with check(core.is_platform_admin() and current_setting('conceptspaces.ai_learning_phase',true)='transition');

create or replace function public.set_ai_model_enabled(target_model_id uuid,target_enabled boolean,target_reason text)
returns boolean language plpgsql security invoker set search_path='ai','core','engineering','audit','auth','pg_temp' as $$
declare r ai.model_profiles%rowtype;before_state jsonb;threshold numeric;org_id uuid;c ai.evaluation_cases%rowtype;latest ai.evaluation_results%rowtype;baseline numeric;
begin
 select * into r from ai.model_profiles where id=target_model_id for update;if not found then raise exception 'model_profile_not_found';end if;if auth.uid() is null or not core.is_platform_admin() or nullif(btrim(target_reason),'') is null then raise exception 'model_state_authority_and_reason_required';end if;
 if target_enabled then
   threshold:=coalesce(r.evaluation_threshold,0);
   for c in select * from ai.evaluation_cases ec where ec.active and engineering.criticality_rank(ec.criticality)<=engineering.criticality_rank(r.max_criticality) loop
     select * into latest from ai.evaluation_results e where e.case_id=c.id and e.model_profile_id=r.id order by e.run_at desc,e.id desc limit 1;
     if not found or not latest.passed or latest.score<threshold then raise exception 'AI_MODEL_EVALUATION_GATE_FAILED:%',c.name;end if;
     select max(z.score) into baseline from (select distinct on(e.model_profile_id) e.model_profile_id,e.score from ai.evaluation_results e join ai.model_profiles m on m.id=e.model_profile_id where e.case_id=c.id and m.enabled and m.id<>r.id order by e.model_profile_id,e.run_at desc,e.id desc) z;
     if baseline is not null and latest.score+c.regression_tolerance<baseline then raise exception 'AI_MODEL_BENCHMARK_REGRESSION:%',c.name;end if;
   end loop;
   if not exists(select 1 from ai.evaluation_cases ec where ec.active and engineering.criticality_rank(ec.criticality)<=engineering.criticality_rank(r.max_criticality)) then raise exception 'ACTIVE_APPLICABLE_BENCHMARK_REQUIRED';end if;
 end if;
 before_state:=to_jsonb(r);perform set_config('conceptspaces.ai_phase','model_state',true);update ai.model_profiles set enabled=target_enabled,approved_by=case when target_enabled then auth.uid() else approved_by end,approved_at=case when target_enabled then now() else approved_at end,updated_at=now() where id=r.id returning * into r;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,null,case when target_enabled then 'ai.model_enabled' else 'ai.model_disabled' end,'ai_model_profile',r.id,before_state,jsonb_build_object('enabled',r.enabled,'profile_hash',r.profile_hash,'all_applicable_benchmarks_passed',target_enabled),target_reason,gen_random_uuid());end if;return r.enabled;
end;$$;
revoke all on function public.set_ai_model_enabled(uuid,boolean,text) from public,anon;grant execute on function public.set_ai_model_enabled(uuid,boolean,text) to authenticated;

create or replace function public.start_ai_agent_run(target_organisation_id uuid,target_project_id uuid,target_agent_code text,target_model_profile_id uuid,target_criticality text,target_input_ref text,target_evidence_refs jsonb default '[]'::jsonb)
returns uuid language plpgsql security invoker set search_path='ai','core','project','engineering','audit','auth','pg_temp' as $$
declare a ai.agent_definitions%rowtype;m ai.model_profiles%rowtype;p ai.prompt_versions%rowtype;r ai.agent_runs%rowtype;crit text:=upper(btrim(target_criticality));org_id uuid;
begin
 if auth.uid() is null then raise exception 'authentication_required';end if;if crit not in ('C0','C1','C2','C3','C4') then raise exception 'AI_CRITICALITY_INVALID';end if;if jsonb_typeof(coalesce(target_evidence_refs,'[]'::jsonb))<>'array' then raise exception 'AI_EVIDENCE_REFS_MUST_BE_ARRAY';end if;
 if target_project_id is not null then select organisation_id into org_id from project.projects where id=target_project_id;if org_id is null or org_id<>target_organisation_id or not project.can_access_project(target_project_id) then raise exception 'project_access_required';end if;elsif not core.is_internal_org_member(target_organisation_id) then raise exception 'organisation_access_required';end if;
 select * into a from ai.agent_definitions where code::text=btrim(target_agent_code) and enabled;if not found then raise exception 'AI_AGENT_NOT_ENABLED';end if;select * into m from ai.model_profiles where id=target_model_profile_id and enabled;if not found then raise exception 'AI_MODEL_NOT_APPROVED';end if;
 if engineering.criticality_rank(crit)>engineering.criticality_rank(a.max_criticality) then raise exception 'AI_AGENT_CRITICALITY_POLICY_BLOCK';end if;if engineering.criticality_rank(crit)>engineering.criticality_rank(m.max_criticality) then raise exception 'AI_MODEL_CRITICALITY_POLICY_BLOCK';end if;if crit in ('C3','C4') and a.allowed_autonomy='bounded_autonomous' then raise exception 'AI_CRITICALITY_POLICY_BLOCK';end if;
 select * into p from ai.prompt_versions where agent_code=a.code and status='active' order by version desc limit 1;if not found then raise exception 'ACTIVE_EVALUATED_PROMPT_REQUIRED';end if;
 if a.requires_grounding and jsonb_array_length(coalesce(target_evidence_refs,'[]'::jsonb))=0 then raise exception 'GROUNDING_REQUIRED';end if;
 perform set_config('conceptspaces.ai_runtime_phase','start',true);insert into ai.agent_runs(organisation_id,project_id,agent_code,model_profile_id,prompt_version_id,status,criticality,input_ref,evidence_refs,started_at) values(target_organisation_id,target_project_id,a.code,m.id,p.id,'running',crit,nullif(btrim(target_input_ref),''),coalesce(target_evidence_refs,'[]'::jsonb),now()) returning * into r;perform audit.append_event(target_organisation_id,target_project_id,'ai.run_started','ai_agent_run',r.id,null,jsonb_build_object('agent_code',a.code::text,'model_profile_id',m.id,'model',m.provider||'/'||m.model,'model_max_criticality',m.max_criticality,'prompt_version_id',p.id,'prompt_version',p.version,'criticality',crit,'evidence_refs',r.evidence_refs),null,r.correlation_id);return r.id;
end;$$;
revoke all on function public.start_ai_agent_run(uuid,uuid,text,uuid,text,text,jsonb) from public,anon;grant execute on function public.start_ai_agent_run(uuid,uuid,text,uuid,text,text,jsonb) to authenticated;

create or replace function public.complete_ai_agent_run(target_run_id uuid,target_succeeded boolean,target_output_ref text,target_output_payload jsonb,target_authoritative boolean,target_output_hash text default null)
returns jsonb language plpgsql security invoker set search_path='ai','core','project','audit','auth','pg_temp' as $$
declare r ai.agent_runs%rowtype;a ai.agent_definitions%rowtype;grounded boolean;status_value text;output_status_value text;output_ref_value text;hash_value text;
begin
 select * into r from ai.agent_runs where id=target_run_id for update;if not found or auth.uid() is null then raise exception 'ai_run_not_found';end if;if not ((r.project_id is not null and project.can_access_project(r.project_id)) or (r.project_id is null and core.is_internal_org_member(r.organisation_id))) then raise exception 'ai_run_access_required';end if;if r.status not in ('queued','running','awaiting_approval') then raise exception 'ai_run_not_completable';end if;select * into a from ai.agent_definitions where code=r.agent_code;grounded:=jsonb_array_length(coalesce(r.evidence_refs,'[]'::jsonb))>0;
 if not target_succeeded then status_value:='failed';output_status_value:='blocked';output_ref_value:=null;hash_value:=null;
 elsif (target_authoritative or a.requires_grounding) and not grounded then status_value:='succeeded';output_status_value:='not_verified';output_ref_value:='not_verified:grounding_source_unavailable';hash_value:=null;
 else status_value:='succeeded';output_status_value:=case when target_authoritative then 'verified' else 'draft' end;output_ref_value:=nullif(btrim(target_output_ref),'');if target_output_hash is not null and target_output_hash !~ '^[0-9a-fA-F]{64}$' then raise exception 'AI_OUTPUT_HASH_INVALID';end if;hash_value:=lower(target_output_hash);end if;
 perform set_config('conceptspaces.ai_runtime_phase','complete',true);update ai.agent_runs set status=status_value,output_ref=output_ref_value,output_status=output_status_value,output_hash=hash_value,grounding_status=case when grounded then 'grounded' when a.requires_grounding or target_authoritative then 'missing' else 'not_required' end,completion_payload=coalesce(target_output_payload,'{}'::jsonb),finished_at=now() where id=r.id returning * into r;perform audit.append_event(r.organisation_id,r.project_id,case when output_status_value='not_verified' then 'ai.run_not_verified' when status_value='failed' then 'ai.run_failed' else 'ai.run_completed' end,'ai_agent_run',r.id,null,jsonb_build_object('status',r.status,'output_status',r.output_status,'output_ref',r.output_ref,'output_hash',r.output_hash,'grounding_status',r.grounding_status,'evidence_refs',r.evidence_refs),null,r.correlation_id);return jsonb_build_object('run_id',r.id,'status',r.status,'output_status',r.output_status,'output_ref',r.output_ref,'grounding_status',r.grounding_status,'evidence_refs',r.evidence_refs);
end;$$;
revoke all on function public.complete_ai_agent_run(uuid,boolean,text,jsonb,boolean,text) from public,anon;grant execute on function public.complete_ai_agent_run(uuid,boolean,text,jsonb,boolean,text) to authenticated;

create or replace function public.propose_ai_learning_candidate(target_source_project_id uuid,target_source_type text,target_source_ref text,target_evidence_quality text)
returns uuid language plpgsql security invoker set search_path='ai','project','core','audit','extensions','auth','pg_temp' as $$
declare c ai.learning_candidates%rowtype;q text:=lower(btrim(target_evidence_quality));h text;org_id uuid;
begin if auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if target_source_project_id is not null and not project.can_access_project(target_source_project_id) then raise exception 'project_access_required';end if;if nullif(btrim(target_source_type),'') is null or nullif(btrim(target_source_ref),'') is null or q not in ('low','medium','high') then raise exception 'learning_source_and_quality_required';end if;h:=encode(extensions.digest(jsonb_build_object('source_project_id',target_source_project_id,'source_type',btrim(target_source_type),'source_ref',btrim(target_source_ref),'evidence_quality',q)::text,'sha256'),'hex');perform set_config('conceptspaces.ai_learning_phase','propose',true);insert into ai.learning_candidates(source_project_id,source_type,source_ref,stage,privacy_state,evidence_quality,candidate_hash) values(target_source_project_id,btrim(target_source_type),btrim(target_source_ref),'observation','pending',q,h) returning * into c;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,target_source_project_id,'ai.learning_candidate_proposed','ai_learning_candidate',c.id,null,to_jsonb(c),h,gen_random_uuid());end if;return c.id;end;$$;
revoke all on function public.propose_ai_learning_candidate(uuid,text,text,text) from public,anon;grant execute on function public.propose_ai_learning_candidate(uuid,text,text,text) to authenticated;

create or replace function public.transition_ai_learning_candidate(target_candidate_id uuid,target_stage text,input_payload jsonb,target_reason text)
returns text language plpgsql security invoker set search_path='ai','core','audit','auth','pg_temp' as $$
declare c ai.learning_candidates%rowtype;s text:=lower(btrim(target_stage));experts jsonb:=coalesce(input_payload->'expert_reviewers',c.expert_reviewers);scope_value text:=lower(coalesce(nullif(btrim(input_payload->>'promotion_scope'),''),c.promotion_scope,'organisation'));benchmark numeric:=coalesce(nullif(input_payload->>'benchmark_delta','')::numeric,c.benchmark_delta);rollback text:=coalesce(nullif(btrim(input_payload->>'rollback_ref'),''),c.rollback_ref);privacy_decision text:=lower(coalesce(nullif(btrim(input_payload->>'privacy_state'),''),c.privacy_state));before_state jsonb;org_id uuid;
begin
 select * into c from ai.learning_candidates where id=target_candidate_id for update;if not found or auth.uid() is null or not core.is_platform_admin() then raise exception 'platform_admin_required';end if;if nullif(btrim(target_reason),'') is null then raise exception 'learning_transition_reason_required';end if;experts:=coalesce(input_payload->'expert_reviewers',c.expert_reviewers,'[]'::jsonb);scope_value:=lower(coalesce(nullif(btrim(input_payload->>'promotion_scope'),''),c.promotion_scope,'organisation'));benchmark:=coalesce(nullif(input_payload->>'benchmark_delta','')::numeric,c.benchmark_delta);rollback:=coalesce(nullif(btrim(input_payload->>'rollback_ref'),''),c.rollback_ref);privacy_decision:=lower(coalesce(nullif(btrim(input_payload->>'privacy_state'),''),c.privacy_state));if jsonb_typeof(experts)<>'array' then raise exception 'expert_reviewers_must_be_array';end if;if scope_value not in ('project','organisation','global') then raise exception 'learning_promotion_scope_invalid';end if;
 if s='privacy_review' then if c.stage not in ('observation','evidence') or privacy_decision not in ('approved','rejected') then raise exception 'learning_privacy_review_invalid';end if;
 elsif s='expert_review' then if c.stage<>'privacy_review' or c.privacy_state<>'approved' or jsonb_array_length(experts)=0 then raise exception 'LEARNING_PRIVACY_EXPERT_GATE_FAILED';end if;
 elsif s='benchmark' then if c.stage<>'expert_review' or c.privacy_state<>'approved' or jsonb_array_length(experts)=0 or benchmark is null then raise exception 'LEARNING_BENCHMARK_GATE_FAILED';end if;
 elsif s='shadow' then if c.stage<>'benchmark' or benchmark<0 then raise exception 'LEARNING_BENCHMARK_REGRESSION';end if;
 elsif s='controlled_production' then if c.stage<>'shadow' or c.privacy_state<>'approved' or jsonb_array_length(experts)=0 or benchmark is null or benchmark<0 or rollback is null then raise exception 'LEARNING_PROMOTION_GATES_FAILED';end if;if scope_value='global' and (c.privacy_state<>'approved' or jsonb_array_length(experts)=0) then raise exception 'GLOBAL_LEARNING_PRIVACY_EXPERT_REVIEW_REQUIRED';end if;
 elsif s='retired' then null;
 else raise exception 'learning_stage_transition_invalid';end if;
 before_state:=to_jsonb(c);perform set_config('conceptspaces.ai_learning_phase','transition',true);update ai.learning_candidates set stage=s,privacy_state=case when s='privacy_review' then privacy_decision else privacy_state end,privacy_reviewed_by=case when s='privacy_review' then auth.uid() else privacy_reviewed_by end,privacy_reviewed_at=case when s='privacy_review' then now() else privacy_reviewed_at end,expert_reviewers=experts,expert_reviewed_by=case when s='expert_review' then auth.uid() else expert_reviewed_by end,expert_reviewed_at=case when s='expert_review' then now() else expert_reviewed_at end,benchmark_delta=benchmark,rollback_ref=rollback,promotion_scope=case when s in ('shadow','controlled_production') then scope_value else promotion_scope end,promoted_at=case when s='controlled_production' then now() else promoted_at end,updated_at=now() where id=c.id returning * into c;select organisation_id into org_id from core.memberships where user_id=auth.uid() and status='active' limit 1;if org_id is not null then perform audit.append_event(org_id,c.source_project_id,'ai.learning_candidate_'||s,'ai_learning_candidate',c.id,before_state,to_jsonb(c),target_reason,gen_random_uuid());end if;return c.stage;
end;$$;
revoke all on function public.transition_ai_learning_candidate(uuid,text,jsonb,text) from public,anon;grant execute on function public.transition_ai_learning_candidate(uuid,text,jsonb,text) to authenticated;

commit;