import {revalidatePath} from "next/cache";
import {requireWorkspaceUser} from "@/lib/auth";

export const dynamic="force-dynamic";
async function createContent(formData:FormData){"use server";const {supabase,user,memberships}=await requireWorkspaceUser();const org=memberships.find(m=>m.status==="active")?.organisation_id;if(!org)throw new Error("Active organisation required.");const payload={organisation_id:org,content_key:String(formData.get("content_key")||"").trim(),content_type:String(formData.get("content_type")||"help_article"),locale:String(formData.get("locale")||"en-IN"),title:String(formData.get("title")||"").trim(),slug:String(formData.get("slug")||"").trim()||null,status:"draft",owner_user_id:user.id};const {data,error}=await supabase.from("content_entries").insert(payload).select("id").single();if(error)throw new Error(error.message);const {error:versionError}=await supabase.from("content_versions").insert({content_entry_id:data.id,version:1,body:{content:String(formData.get("body")||"")},change_reason:"Initial governed draft",created_by:user.id});if(versionError)throw new Error(versionError.message);revalidatePath("/app/admin/cms");}
export default async function CmsAdmin(){const {supabase,memberships}=await requireWorkspaceUser();const org=memberships.find(m=>m.status==="active")?.organisation_id;const {data,error}=await supabase.from("content_entries").select("*").eq("organisation_id",org||"").order("updated_at",{ascending:false});if(error)throw new Error(error.message);const entries=data||[];return <>
 <div className="topbar"><div><div className="demo">Super Admin / Live CMS</div><h1>Content Governance</h1><div className="subtle">Locale-specific, versioned content with explicit publication state.</div></div></div>
 <div className="panel-grid"><section className="panel"><h3>Create Governed Draft</h3><form action={createContent}><div className="field-grid"><div className="field"><label>Content key</label><input name="content_key" required placeholder="help.project-intake"/></div><div className="field"><label>Title</label><input name="title" required/></div><div className="field"><label>Type</label><select name="content_type"><option>help_article</option><option>knowledge_article</option><option>public_page</option><option>legal_notice</option><option>email_template</option><option>seo_landing</option></select></div><div className="field"><label>Locale</label><input name="locale" defaultValue="en-IN" required/></div><div className="field"><label>Slug</label><input name="slug"/></div></div><div className="field"><label>Initial body</label><textarea name="body" rows={6} required/></div><button className="btn">Create Draft</button></form></section><section className="panel"><h3>Publication Register</h3><table className="table"><thead><tr><th>Content</th><th>Locale</th><th>Version</th><th>State</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td><b>{e.title}</b><div className="subtle">{e.content_key}</div></td><td>{e.locale}</td><td>{e.current_version}</td><td><span className="badge">{e.status}</span></td></tr>)}{!entries.length&&<tr><td colSpan={4} className="subtle">No governed content entries yet.</td></tr>}</tbody></table></section></div>
 </>}
